### ISSUE TITLE
zsh: permission denied: npm

### ISSUE THREAD

**Issue by tyduptyler13** [joyent/node#13861]
After installing the latest build of nodejs, npm no longer works due to what appears to be a permission issue. zsh seems to know the file exists on the path but doesn't know where it is and refuses to execute it. For example:

```
tyler@MasterMyUPlay ~ % where npm
npm not found
tyler@MasterMyUPlay ~ % ll
zsh: command not found: ll
tyler@MasterMyUPlay ~ % npm
zsh: permission denied: npm
```

This shows that is knows the difference between a command that doesn't exist and one that does. However it doesn't want to show where npm is and refuses to execute it.

I did a [recursive list](https://gist.github.com/tyduptyler13/288d781b0ae78b8d0243) of all of the permissions in the /usr/local/lib/node_modules directory. Hopefully that will help.

I have already tried deleting and re-installing the relevant directories but it results in the exact same permissions.

**Comment by tyduptyler13** [comment]
I should also mention that this only seems to be on my ubuntu server. It worked fine on my other machines. Any suggestions would be appreciated.

**Comment by othiym23** [comment]
@tyduptyler13: I'm not sure how this happened, but I at least know what the problem is:

```
./npm/bin:
...
-rwx-----T 1 root root  340 Jun 18  2014 npm
-rwx-----T 1 root root 1887 Mar 24 15:44 npm-cli.js
```

Somehow, npm and `npm-cli.js` have become executable solely by root. In addition, that `T` is problematic:

> If the sticky-bit is set on a file or directory without the execution bit set for the others category (non-user-owner and non-group-owner), it is indicated with a capital T

How did you install Node.js / npm? Something in the process stomped on the permissions in `/usr/local/lib/node_modules` in the process of installing everything.

You can work around this by running `sudo chmod 0755 /usr/local/lib/node_modules/bin/{npm,npm-cli.js} /usr/local/lib/node_modules/bin/node-gyp-bin/node-gyp`, but I actually think you should figure out what happened during the install process and reinstall. I would not trust that installation of Node / npm.

**Comment by othiym23** [comment]
(The sticky bit, whether it's `t` or `T`, on files is problematic because it doesn't actually _mean_anything (it only applies to directories on Linux), and implies that the installer got badly confused at some point when moving files into place.)

**Comment by tyduptyler13** [comment]
Hmm ok. I'll try to clean it all out and do everything fresh. I'll let you know if I figure out what happened to it.

**Comment by tyduptyler13** [comment]
Unsure exactly how this happened but my permissions in my git directory also have that T bit set. Resetting everything to default.

**Comment by tyduptyler13** [comment]
For anyone who has this issue in the future (seems unlikely, but) to restore your file permissions you will need to run the following on your directory to completely fix it.

```
find -type f -exec chmod 644 {} \;
find -type d -exec chmod 755 {} \;
git diff -p -R \
    | grep -E "^(diff|(old|new) mode)"  \
    | git apply
```

This removes the T bits on all of the files by setting them to a generic default (its still missing executable bits) but then the `git diff -p -R...` restores the original permissions of the git repo.

Building and installing should now work correctly.
