### ISSUE TITLE
Slow Debugging

### ISSUE THREAD

**Issue by Uter1007** [joyent/node#13979]
Hi,

I am using the mean.js Framework and when I am trying to debug via node-inspector or Webstorm (--debug-brk=62066 --nolazy server.js) the startup of this process will take 1-2min. Are there any options to speed it up ? In the io.js Forum there is a similar thread, so I inspect it could be related: https://github.com/iojs/io.js/issues/877. 

Cheers,
Uter

**Comment by misterdjules** [comment]
Closing as a duplicate of #9125, thank you for reporting this issue :+1:

**Comment by Uter1007** [comment]
oops sorry for the duplicate :(
