### ISSUE TITLE
child_process spawn

### ISSUE THREAD

**Issue by gobwas** [joyent/node#14133]
Hello!

How can I be noticed about successful spawning with `child_process.spawn()` ?

Example:

```js

var spawn = require("child_process").spawn,
      commandBad, commandGood;

commandBad = spawn('bad_command');
commandBad.on('error', function(err) { console.log("Got error, OK"); });

commandGood = spawn("whoami");
commandGood.on('???', function() { console.log("Spawn successed!"); }); // how can i do this?

```

Thanks!

**Comment by CGavrila** [comment]
Is this what you are looking for?

```
commandGood.on('close', function (exitCode) {
  if (code !== 0) {
    console.log('ps process exited with code ' + code);
  } else {
    console.log('Process was successful');
  }
});
```

**Comment by gobwas** [comment]
Hi, @CGavrila, no )

Im looking to some event, when I can decide to `commandGood.stdin.write(...)`.

**Comment by CGavrila** [comment]
@gobwas: there may not be a way of doing this, as far as I know. You will get an error though if the spawn is not successful, so you could use that in order to stop the `stdin.write`.

**Comment by dayuoba** [comment]
no error,means it is running,and if you want to handle the process forked,
```
fooYouSpawned.stdout.on('data', function(data) {});
```
may be helpful.other events like `exit`,`error`.Just deal with the life cycle of porcess
But i think it is not a node issue.

**Comment by gobwas** [comment]
@dayuoba `data` event will be fired just if there is some data to out by spawned process =)

May be, yes, and this is not a node issue. But by the way, it could be useful thing.
