### ISSUE TITLE
Write regression test for smalloc regression

### ISSUE THREAD

**Issue by trevnorris** [joyent/node#14165]
The regression was introduced by https://github.com/joyent/node/commit/6462519d3cb7c34671dddb3cedd8441699574f35 and has been fixed by a35ba2f67df, but no test was added with the fix to prevent further regression(s).

The issue was that `poolOffset` was always adjusted, even if the pool wasn't used. Because of this it was possible to create an edge case where `poolOffset + this.length > poolSize` in `Buffer()`. This would cause the `sliceOnto()` to abort because it would attempt to read beyond memory boundaries.

Ref: https://github.com/joyent/node/issues/9180

/cc @misterdjules

**Comment by misterdjules** [comment]
Just for the record, there are instructions to reproduce the issue (and see how this PR fixes it) here: https://github.com/iojs/io.js/issues/661#issuecomment-74519950.

**Comment by misterdjules** [comment]
@trevnorris Was this issue created to add a test for a35ba2f67dfcdf21b87f4326c6d67150f40224b6? I can't remember. Anyway, I think we should definitely try to come up with a regression test for it, so reopening and removing from the 0.12.2 milestone, as it doesn't have to be done before the v0.12.2 release.

**Comment by trevnorris** [comment]
@misterdjules In the meeting you mentioned a ticket should be created so we have something to look at for the release or some such. Can't exactly remember. I agree we should come up with a minimal test case. I was able to reproduce when I found the bug, but only by using the dependencies. I'll revisit how to make a minimal test case for this.

**Comment by misterdjules** [comment]
@trevnorris Thanks!

**Comment by misterdjules** [comment]
@trevnorris Changing this issue's title to "write test for smalloc regression", as we were already tracking this problem with this issue: https://github.com/joyent/node/issues/9180, and that makes things clearer in my opinion.

**Comment by misterdjules** [comment]
@trevnorris Also updated the issue's description to make it clearer what introduced the regression, how it was fixed, and that we need to write a test to prevent further regression(s).

**Comment by trevnorris** [comment]
smalloc has been removed in io.js. don't think there's a need for it anymore.
