### ISSUE TITLE
Compressed packages

### ISSUE THREAD

**Issue by piranna** [joyent/node#14169]
Allow to ```require()``` compressed packages as dependencies inside ```ǹode_modules``` folder, the same way Python does. The idea is to use less disk space and make transfer of projects faster, since it will only move one file instead of a set of them. Also it would allow to checksum them, obviously in this case the comprossed package would not have inside its dependencies except if sringwash or bundleDependencies are being used, but the Node.js packages resolution algorythm (search for a ```node_modules``` in the current folder and all its parents until ```/```) would be capable to solve this.

To do so, the only change would be that when a compressed (.zip?) file is found inside the ```node_modules``` folder, expand it dynamically and process the ```package.json``` file the same way it would do with folders.

**Comment by bmeck** [comment]
I defer my comments to the IO.js issue

**Comment by jasnell** [comment]
Closing. This is actually a duplicate and there is conversation happening over in io.js
