### ISSUE TITLE
Network Diagnostic Module

### ISSUE THREAD

**Issue by natewatson999** [joyent/node#14166]
Periodically, networks fail. Sometimes a required port is blocked, sometimes a cable breaks, sometimes a router fails, and other things can go wrong. These can interfere with a Node server's ability to do its job correctly, even if code is theoretically perfect. When these issues are discovered, the  developer or administrator need to perform manual tests and checks to find the issue. This can be a slow process. I propose that an automated tool be written as a Node module to diagnose network problems.

Google provides a tool that does this job: https://chrome.google.com/webstore/detail/chrome-connectivity-diagn/eemlkeanncmjljgehlbplemhmdmalhdc But this is designed for consumer use, not to be triggered and used by code, nor is it made for server diagnostics. I propose that a Node server counterpart be written.

**Comment by misterdjules** [comment]
Thank you for taking the time to file this issue!

This type of functionality doesn't need to be implemented in Node.js' core. Instead, it should be implemented as a non-core module. I encourage you to do some research on npm and ask around in [Node.js' Google group](https://groups.google.com/forum/#!forum/nodejs) to know if such module already exists.

**Comment by natewatson999** [comment]
I looked for such a module, and it doesn't exist. I've decided to write one.

**Comment by natewatson999** [comment]
https://www.npmjs.com/package/network-diagnostics
Here's a minimum viable module.
