### ISSUE TITLE
RangeError: Invalid string length --- it should be saying Out Of Memory

### ISSUE THREAD

**Issue by scottstensland** [joyent/node#14170]
Please update ERROR message when attempting to call

    JSON.stringify(monsterously_HUGE_object)

Today then it runs out of RAM above gives this message 

RangeError: Invalid string length

when it clearly should indicate the system is out of RAM.
Searching this error message I see nodejs does recognize
an Out Of Memory condition yet it continues to give a less helpful error message

https://github.com/joyent/node/search?utf8=%E2%9C%93&q=RangeError%3A+Invalid+string+length

**Comment by Fishrock123** [comment]
That's an issue from v8 (the javascript engine) not node. (`JSON.*` is implemented in v8)

**Comment by misterdjules** [comment]
It would help to know how `monsterously_HUGE_object` is created, as if it's created in some way that requires allocating too much memory before any string operation can be done, it will fail with an "Out of memory" error.

Otherwise, operating on a string that is too large should throw the "Invalid string length" error, so I don't see anything that would be unexpected.

As @Fishrock123 mentioned, these errors are thrown from V8, so if you still think that these error messages are not correct, I encourage you to file an issue in V8's issues tracker.

Closing for now, but please let us know if you have any question.

**Comment by cauerego** [comment]
While I do get it this is the wrong place to ask about this issue, this is also the first hit on google, so...

Any links to where we could look for a solution to the actual problem? [I still think I need to stringify a huge object (to enable people to save and share their Mariox's advancements)](http://talk.cregox.com/t/thanks-to-mari-o-time-to-focus-on-ai/7653/12), certainly over 5mb ( I'll lz compress it later, if this matters to you ;P ).

**Comment by apple-hacker** [comment]
I have a problem about this,please help me!

**Comment by laokey** [comment]
I have a problem about this,please help me!too

**Comment by sign0** [comment]
me too ! :-1: (ubuntu 14.04, nodejs 5.10.1)

**Comment by johnbrandle** [comment]
this should work for most JSON.

example call: JSONStringifyHUGEObject({});

function JSONStringifyHUGEObject(object, uniqueKeyPrefix)
{
	var uniqueKeyPrefix = uniqueKeyPrefix || '$$$:';
	var uniqueKeyCounter = 0;

	var result = stringify(object);

	if (result !== -1) return result;
	
	return stringifyHUGEObject(object);
	
	function stringifyHUGEObject(object)
	{
		if (!object || typeof object !== 'object' || typeof object.valueOf() !== 'object') return String(object);
		
		var keyValuePairs = {};
		
		for (var property in object)
		{
			var value = object[property];
			
			if (!value || typeof value !== 'object' || typeof value.valueOf() !== 'object') continue;
			
			var key = uniqueKeyPrefix + uniqueKeyCounter++;
			object[property] = key;
			keyValuePairs[key] = {property:property, object:value};
		}
		
		var result = stringify(object);
		if (result === -1) throw new Error('huge object cannot be stringified.');
		
		for (var key in keyValuePairs)
		{
			var value = keyValuePairs[key];
			
			var innerResult = stringify(value.object);
			if (innerResult === -1) innerResult = stringifyHUGEObject(value.object);
			
			object[value.property] = value.object;
			result = result.replace(key, innerResult);
		}
		
		return result;
	}
	
	function stringify(object)
	{
		try
		{
			return JSON.stringify(object);
		}
		catch(error) {}
		
		return -1;
  }
}

**Comment by SashaDesigN** [comment]
Have to this problem now with json files) try use on ubuntu:

cat file1.json file2.json > res.json

**Comment by jcollum** [comment]
same here, csv-stringify library but this is the first google hit; I'm csv-ing a record from a very very wide table in SQL

**Comment by lianyi** [comment]
same issue at node v6.2.2  on CentOS 7

**Comment by krazyjakee** [comment]
Same here 7.9.0 - Webpack cannot build

**Comment by PassTheMayo** [comment]
Same issue here. Ubuntu 16.04, Node v8.1.4

**Comment by LKJonDoe** [comment]
is there any fix ?

**Comment by majuss** [comment]
same issue…

**Comment by sandeeptharayilGit** [comment]
facing same issue `RangeError: Invalid string length`

**Comment by gibfahn** [comment]
This repo is an archive, if you're still seeing this please open an issue at [nodejs/node](https://github.com/nodejs/node) (if there isn't one there already).
