### ISSUE TITLE
HTTPS securing passphrase for the .pfx file

### ISSUE THREAD

**Issue by joyson-17** [joyent/node#14179]
I am implementing a node backend server for a mobile application. The mobile app connects to the server using an HTTPS link. I have created a .pfx file for this link. The issue is that in the options I have to provide the passphrase in clear. This passphrase can be read by anyone who has access to the server. Is there anyway to secure this passphrase.

Regards,
Joyson.

**Comment by misterdjules** [comment]
Thank you for taking the time to file this issue. It doesn't highlight a problem with Node.js' core itself though, so I would encourage you to post in the [Node.js Google group](https://groups.google.com/forum/#!forum/nodejs), which is better suited for this type of questions.
