### ISSUE TITLE
Binding http server to file descriptor fails to read

### ISSUE THREAD

**Issue by terinjokes** [joyent/node#14183]
I'm attempting to use node.js as a systemd service using "socket activation", where systemd binds to the TCP port and passes a file descriptor to the running service, starting with file descriptor 3.

According to 0.10 and 0.12 documentation, passing this file descriptor to http.Server.listen should work (https://nodejs.org/api/http.html#http_server_listen_handle_callback). The 'listening' event successfully fires, but no connections ever make it to 'request'.

I've setup a test repository to help reproduce this issue: https://github.com/terinjokes/nodejs-systemd-issue

This test repository does work in io.js, so i suspect there's a fix that could be backported, but I was unable to find one in particular.

**Comment by misterdjules** [comment]
Thank you very much for the detailed description and for the reproduction code!

**Comment by misterdjules** [comment]
Fixed in libuv by libuv/libuv#134, which is included in [the upgrade to libuv 1.4.2 in Node.js' v0.12 branch](https://github.com/joyent/node/pull/9179). This will be available in the node v0.12.2 release that is planned to be released tomorrow (Tuesday).

As a result, closing and moving to the 0.12.2 milestone.

Let me know if you have any question, thanks!

**Comment by misterdjules** [comment]
Also just for future reference, this is the same issue as https://github.com/joyent/node/issues/8988.

**Comment by terinjokes** [comment]
@misterdjules I can reproduce in 0.10, any recourse recommendations to get this working? Suppose i could ship a native component that calls `uv__nonblock(fd, 1)` myself, but would be awesome if there was something simpler.

**Comment by piranna** [comment]
@terinjokes, where's the actual GitHub of your module? Also, does it works with fd[0](stdin)?
