### ISSUE TITLE
npm Illegal instruction on Raspberry Pi B+

### ISSUE THREAD

**Issue by nathanjohnson320** [joyent/node#14186]
Compiled node v0.12.1 on my Raspberry Pi B+ and can run node commands (node -v, cli) but whenever I do an npm command (npm install, npm -v) it says "Illegal Instruction" and exits.

**Comment by CGavrila** [comment]
NPM is a separate project, and this might have something to do with it rather than Node. Maybe it's worth raising an issue with them? (https://github.com/npm/npm)[https://github.com/npm/npm]

**Comment by nathanjohnson320** [comment]
After I applied the patch mentioned in io.js the issue is fixed
https://github.com/joyent/node/pull/14193

**Comment by misterdjules** [comment]
@nathanjohnson320 Thanks for the heads up!
