### ISSUE TITLE
Error while installing new npm package in node web application

### ISSUE THREAD

**Issue by BijurajE** [joyent/node#14213]
Registry url: https://registry.npmjs.org/
Current Time: 31-03-2015 14:47:34
Last Refreshed: 31-03-2015 14:46:13
Number of Results: 144832
====Executing command 'npm install express --save '====

npm WARN package.json NodejsWebApp1@0.1.0 No repository field.
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "E:\\NodeJs\\\\node.exe" "E:\\NodeJs\\node_modules\\npm\\bin\\npm-cli.js" "install" "express" "--save"
npm ERR! node v0.12.1
npm ERR! npm  v2.5.1
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect
npm ERR! network connect ETIMEDOUT
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Please include the following file with any support request:
npm ERR!     E:\Bijuraj\GamiService\NodejsWebApp1\NodejsWebApp1\npm-debug.log

====npm command completed with exit code 1====

Please give a solution to the above issue.

**Comment by KenanY** [comment]
@BijurajE This appears to be an issue with your internet connection rather than an issue with Node.js core or `npm`. Are you behind a proxy by any chance?

**Comment by misterdjules** [comment]
Closing as it doesn't seem to be an issue with Node.js itself. If after reporting the problem with npm (at http://github.com/npm/npm/) that turns out to be a bug with node, please let us know. Thank you!

**Comment by BijurajE** [comment]
Can you please help to setup node project in visual studio. What are the steps need to follow to work on the same.
Thanks

**Comment by misterdjules** [comment]
@BijurajE This issues tracker is used to manage bugs and contributions to Node.js' core, so I invite you to post this question either in [the Node.js Google group](https://groups.google.com/forum/#!forum/nodejs), or in StackOverflow. Thank you!

**Comment by BijurajE** [comment]
I have installed NodeJs in C drice (C:\NodeJs) and i have crated a Nodejs web application in my E drive. in the code i have written var express = require("express"); here i am getting the following error,
module.js:338
    throw err;
          ^
Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (E:\Bijuraj\GamiService\NodejsWebApp1\NodejsWebApp1\..........
rver.js:17:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

Can you please help what all steps i need to follow to make my code work?
Thanks!!!
