### ISSUE TITLE
Cant update npm version EACCES --> npm update -g

### ISSUE THREAD

**Issue by rslid** [joyent/node#14212]
Hi,

Im trying to update my npm version but Im stuck, I tried every possible solution on the Internet - changing persmissions, complete uninstall and install but still nothing works. Any advice ?

platon@platon-VirtualBox:~$ npm update -g
npm WARN optional dep failed, continuing readable-stream@1.1.13
npm ERR! Error: EACCES, mkdir '/home/platon/.node/lib/node_modules/npm/node_modules/init-package-json/node_modules/semver'
npm ERR!  { [Error: EACCES, mkdir '/home/platon/.node/lib/node_modules/npm/node_modules/init-package-json/node_modules/semver']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/home/platon/.node/lib/node_modules/npm/node_modules/init-package-json/node_modules/semver',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/home/platon/.node/lib/node_modules/npm/node_modules/init-package-json/node_modules/semver',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23',
npm ERR!      '/usr/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53',
npm ERR!      'Object.oncomplete (fs.js:108:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 3.16.0-33-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "update" "-g"
npm ERR! cwd /home/platon
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! path /home/platon/.node/lib/node_modules/npm/node_modules/init-package-json/node_modules/semver
npm ERR! fstream_path /home/platon/.node/lib/node_modules/npm/node_modules/init-package-json/node_modules/semver
npm ERR! fstream_type Directory
npm ERR! fstream_class DirWriter
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, mkdir '/home/platon/.node/lib/node_modules/npm/node_modules/init-package-json/node_modules/semver'
npm ERR! fstream_stack /usr/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23
npm ERR! fstream_stack /usr/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53
npm ERR! fstream_stack Object.oncomplete (fs.js:108:15)
npm ERR! error rolling back Error: EACCES, unlink '/home/platon/.node/lib/node_modules/npm/node_modules/dezalgo/node_modules/asap'
npm ERR! error rolling back  { [Error: EACCES, unlink '/home/platon/.node/lib/node_modules/npm/node_modules/dezalgo/node_modules/asap']
npm ERR! error rolling back   errno: 3,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   path: '/home/platon/.node/lib/node_modules/npm/node_modules/dezalgo/node_modules/asap' }
npm ERR! Error: EACCES, mkdir '/home/platon/.node/lib/node_modules/npm/node_modules/node-gyp/node_modules/tar'
npm ERR!  { [Error: EACCES, mkdir '/home/platon/.node/lib/node_modules/npm/node_modules/node-gyp/node_modules/tar']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/home/platon/.node/lib/node_modules/npm/node_modules/node-gyp/node_modules/tar',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/home/platon/.node/lib/node_modules/npm/node_modules/node-gyp/node_modules/tar',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23',
npm ERR!      '/usr/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53',
npm ERR!      'Object.oncomplete (fs.js:108:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 3.16.0-33-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "update" "-g"
npm ERR! cwd /home/platon
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! path /home/platon/.node/lib/node_modules/npm/node_modules/node-gyp/node_modules/tar
npm ERR! fstream_path /home/platon/.node/lib/node_modules/npm/node_modules/node-gyp/node_modules/tar
npm ERR! fstream_type Directory
npm ERR! fstream_class DirWriter
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, mkdir '/home/platon/.node/lib/node_modules/npm/node_modules/node-gyp/node_modules/tar'
npm ERR! fstream_stack /usr/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23
npm ERR! fstream_stack /usr/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53
npm ERR! fstream_stack Object.oncomplete (fs.js:108:15)
npm ERR! Error: EACCES, mkdir '/home/platon/.node/lib/node_modules/npm/node_modules/node-gyp/node_modules/request'
npm ERR!  { [Error: EACCES, mkdir '/home/platon/.node/lib/node_modules/npm/node_modules/node-gyp/node_modules/request']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/home/platon/.node/lib/node_modules/npm/node_modules/node-gyp/node_modules/request',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/home/platon/.node/lib/node_modules/npm/node_modules/node-gyp/node_modules/request',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23',
npm ERR!      '/usr/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53',
npm ERR!      'Object.oncomplete (fs.js:108:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 3.16.0-33-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "update" "-g"
npm ERR! cwd /home/platon
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! path /home/platon/.node/lib/node_modules/npm/node_modules/node-gyp/node_modules/request
npm ERR! fstream_path /home/platon/.node/lib/node_modules/npm/node_modules/node-gyp/node_modules/request
npm ERR! fstream_type Directory
npm ERR! fstream_class DirWriter
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, mkdir '/home/platon/.node/lib/node_modules/npm/node_modules/node-gyp/node_modules/request'
npm ERR! fstream_stack /usr/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23
npm ERR! fstream_stack /usr/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53
npm ERR! fstream_stack Object.oncomplete (fs.js:108:15)
npm ERR! error rolling back Error: EACCES, unlink '/home/platon/.node/lib/node_modules/npm/node_modules/tar'
npm ERR! error rolling back  { [Error: EACCES, unlink '/home/platon/.node/lib/node_modules/npm/node_modules/tar']
npm ERR! error rolling back   errno: 3,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   path: '/home/platon/.node/lib/node_modules/npm/node_modules/tar' }
npm ERR! error rolling back Error: EACCES, unlink '/home/platon/.node/lib/node_modules/npm/node_modules/columnify/node_modules/strip-ansi/node_modules/ansi-regex'
npm ERR! error rolling back  { [Error: EACCES, unlink '/home/platon/.node/lib/node_modules/npm/node_modules/columnify/node_modules/strip-ansi/node_modules/ansi-regex']
npm ERR! error rolling back   errno: 3,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   path: '/home/platon/.node/lib/node_modules/npm/node_modules/columnify/node_modules/strip-ansi/node_modules/ansi-regex' }
npm ERR! Error: EACCES, mkdir '/home/platon/.node/lib/node_modules/npm/node_modules/normalize-package-data/node_modules'
npm ERR!  { [Error: EACCES, mkdir '/home/platon/.node/lib/node_modules/npm/node_modules/normalize-package-data/node_modules']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/home/platon/.node/lib/node_modules/npm/node_modules/normalize-package-data/node_modules',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/home/platon/.node/lib/node_modules/npm/node_modules/normalize-package-data/node_modules/semver',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/lib/node_modules/npm/node_modules/fstream/lib/writer.js:171:23',
npm ERR!      '/usr/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53',
npm ERR!      'Object.oncomplete (fs.js:108:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 3.16.0-33-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "update" "-g"
npm ERR! cwd /home/platon
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! path /home/platon/.node/lib/node_modules/npm/node_modules/normalize-package-data/node_modules
npm ERR! fstream_path /home/platon/.node/lib/node_modules/npm/node_modules/normalize-package-data/node_modules/semver
npm ERR! fstream_type Directory
npm ERR! fstream_class DirWriter
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, mkdir '/home/platon/.node/lib/node_modules/npm/node_modules/normalize-package-data/node_modules'
npm ERR! fstream_stack /usr/lib/node_modules/npm/node_modules/fstream/lib/writer.js:171:23
npm ERR! fstream_stack /usr/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53
npm ERR! fstream_stack Object.oncomplete (fs.js:108:15)
npm ERR! Error: EACCES, mkdir '/home/platon/.node/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/request'
npm ERR!  { [Error: EACCES, mkdir '/home/platon/.node/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/request']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/home/platon/.node/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/request',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/home/platon/.node/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/request',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23',
npm ERR!      '/usr/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53',
npm ERR!      'Object.oncomplete (fs.js:108:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 3.16.0-33-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "update" "-g"
npm ERR! cwd /home/platon
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! path /home/platon/.node/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/request
npm ERR! fstream_path /home/platon/.node/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/request
npm ERR! fstream_type Directory
npm ERR! fstream_class DirWriter
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, mkdir '/home/platon/.node/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/request'
npm ERR! fstream_stack /usr/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23
npm ERR! fstream_stack /usr/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53
npm ERR! fstream_stack Object.oncomplete (fs.js:108:15)
npm ERR! error rolling back Error: EACCES, unlink '/home/platon/.node/lib/node_modules/npm/node_modules/request'
npm ERR! error rolling back  { [Error: EACCES, unlink '/home/platon/.node/lib/node_modules/npm/node_modules/request']
npm ERR! error rolling back   errno: 3,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   path: '/home/platon/.node/lib/node_modules/npm/node_modules/request' }
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/platon/npm-debug.log
npm ERR! not ok code 0

**Comment by dayuoba** [comment]
as far as i know,`npm update` means update the `node_modules` not itself
and it is not a node issue

**Comment by misterdjules** [comment]
Closing as, like @dayuoba mentioned, it doesn't seem to be an issue with Node.js itself. If after reporting the problem with npm (at http://github.com/npm/npm/) that turns out to be a bug with node, please let us know. Thank you!

**Comment by rslid** [comment]
I will try over there, sorry for misunderstanding.

Thanks
