### ISSUE TITLE
want documentation of internal javascript interfaces

### ISSUE THREAD

**Issue by ry** [joyent/node#1431]
process.binding('tcp_wrap').TCP
process.binding('pipe_wrap').Pipe
process.binding('process_wrap').Process
process.binding('timer_wrap').Timer

**Comment by jasnell** [comment]
Would likely still be a good idea but... no action since 2011? Really? Ah well... closing. Someone can revisit this later if they'd like

**Comment by dshaw** [comment]
@jasnell Likely to be an outcome of the API Compatibility WG effort @trevnorris is heading up.
