### ISSUE TITLE
x64 iisnode installer looks for x86 install of x64 node install

### ISSUE THREAD

**Issue by alan933** [joyent/node#14353]
I am trying to install iisnode-full-iis7-v0.1.14-x64.msi but it is looking for node.exe in c:\ProgramFiles(x86)\nodejs.

Why isn't it looking in c:\program files\ where node-v-0.12.1-64.msi it installed it?

There seems to be a mismatch between x86 and x64 installers.

**Comment by rramachand21** [comment]
any reason for not installing the latest version  of iisnode ?

**Comment by misterdjules** [comment]
It seems that this issue should be created at https://github.com/tjanczuk/iisnode. Closing this, but feel free to let us know if it turns out it's a problem with Node.js itself. Thank you!
