### ISSUE TITLE
how to compile nodejs with linking to shared v8/libuv/...

### ISSUE THREAD

**Issue by ddnionio** [joyent/node#14418]
In normal cases, the libraries in deps are static linked with nodejs. I want nodejs to shared link them.
I tryed ./configure --shared-libuv, but it needs that I already have libuv.so in my computer. 

Is there a method that it will compile the dynamic libraries and let nodejs link to them. (for example, it compule the libuv.so first by the source in deps/uv, then let nodejs link the .so)

**Comment by jbergstroem** [comment]
If you want to use shared libraries, installing them (including making sure you're using the right version) is up to you. That can either happen through your preferred package manager/os or manually.

Installing libuv is relatively trivial; check https://github.com/libuv/libuv#build-instructions

**Comment by ddnionio** [comment]
thanks, but the libuv link that you put doesn't tell how to build a dynamic library. Do you know how to build a dynamic/shared libuv.so?

**Comment by jbergstroem** [comment]
@ddnionio Have a look at [the libuv build instructions](https://github.com/libuv/libuv#build-instructions).

**Comment by ddnionio** [comment]
@jbergstroem Thanks. I used the gyp method before, and it only build the libuv.a. Now I choose the autogen method and it build both .a and .so

**Comment by misterdjules** [comment]
@ddnionio Could you please describe in more details why you'd like to be able to build a Node.js binary that uses the exact same libuv as the one bundled in `deps/libuv` but linked as a dynamic shared library? 

If this is a valid use case then maybe we should provide an easier way to do that.

**Comment by jbergstroem** [comment]
@misterdjules it's already as easy as I imagine it can get: `--shared-libuv`.

**Comment by misterdjules** [comment]
@jbergstroem Unless I'm missing something, without having built libuv as a dynamic shared library beforehand and without passing `--shared-libuv-includes --shared-libuv-libpath` to `configure`, it doesn't work as expected.

These prerequisites are not necessarily difficult to complete, but they're not very user friendly either.

**Comment by jbergstroem** [comment]
@misterdjules if a system already have an installed libuv or zlib or openssl which matches the versions nodejs expects, I wouldn't call it non-user friendly. As for having to install them, that's not really the scope of nodejs concern imo.

**Comment by misterdjules** [comment]
@jbergstroem What i'm trying to figure out is: is there some valid use case where one would want to link Node.js with a dynamic shared libuv that corresponds to the exact libuv version in `deps/uv` _without installing it beforehand_?

If @ddnionio asked the question, it is possible that it's a valid use case for some users, and that currently it's not user friendly enough. In this case we should find a way to make the user experience better. That could be done by improving the existing documentation or by improving the build system, and I believe @ddnionio's feedback would be helpful and worth considering.

**Comment by jbergstroem** [comment]
@misterdjules Gotcha. Lets see what @ddnionio says.

**Comment by ddnionio** [comment]
@jbergstroem @misterdjules Maybe it is not a common use case. In my case, I want to know the pure image size of nodejs without any other third party libraries, so I want to build these libs in deps/ as xxx.so and ./configire --shared-xxx.

**Comment by misterdjules** [comment]
@ddnionio Thank you for providing us with more context. Indeed, it doesn't seem like a use case that we would need to make easier. However, it seems the documentation could be improved on that topic. Does the wiki sound like the right place for you? Where did you look when trying to find more information about how to link node with dynamic shared libraries?

Thanks!

**Comment by ddnionio** [comment]
@misterdjules I dont find infomation about shared build in wiki page. I learned by reading the configure source code and asking in this post.

**Comment by misterdjules** [comment]
@ddnionio Right, there's no documentation in the Wiki about that currently, I'm trying to figure out what would be the best place for such a documentation. If you didn't look at the Wiki when looking for that info, then maybe the Wiki is not the best place.

**Comment by jasnell** [comment]
Closing this issue here. further discussion on this should be deferred to the nodejs/build WG
