### ISSUE TITLE
Zlib creating invalid gzip file when streaming (Node 0.11 and 0.12)

### ISSUE THREAD

**Issue by twappworld** [joyent/node#14479]
I reduced it to: 
```javascript
var fs = require('fs');
var output = fs.createWriteStream('test.gz');
var zlib = require('zlib');
var compress = zlib.createGzip();
var myStream = compress.pipe(output);

myStream.write('Hello, World!');
myStream.end();
```
The file test.gz is created, but is not a valid .gz file - Is it a known problem? Wrong usage?

Thanks,
Adam

**Comment by KenanY** [comment]
``` js
var fs = require('fs');
var output = fs.createWriteStream('test.gz');
var zlib = require('zlib');
var compress = zlib.createGzip();

compress.pipe(output);

compress.write('Hello, World!');
compress.end();
```

```
$ gzip -d < test.gz 
Hello, World!
```

**Comment by twappworld** [comment]
Better yet, you could do:

$ cat test.gz
Hello, World!

It leaves the file uncompressed, even for multi-megabyte streams...

**Comment by KenanY** [comment]
@twappworld With your code, yeah, since you aren't actually passing anything through the gzip stream. Your code is writing to the `output` stream. My code properly writes to the gzip stream, so you have to use `gzip -d`, you cannot simply `cat` a compressed file:

```
$ cat test.gz
HÍÉÉ×Ï/ÊIQÐÃJì
```

**Comment by twappworld** [comment]
You're right, thanks! My misunderstanding...

**Comment by misterdjules** [comment]
Closing @twappworld's repro as described in the original comment does not seem to highlight any issue, and @KenanY (thank you :+1:) showed some code to do what was actually intended.

@twappworld Please let us know if you think this issue should be reopened.

Thank you!
