### ISSUE TITLE
After-write event

### ISSUE THREAD

**Issue by rentalhost** [joyent/node#14476]
Will be great if `stream.Writable` have an event triggered after an `write()` call. It can help check the cursor position on console. Example:

```javascript
process.stdout.on("write", function(ev) {
    // ev.length = 5
    // ev.content = "Hello"
});

process.stdout.write("Hello");
```

**Comment by socketpair** [comment]
Seems this issue can be closed, since event is already exists.

```
function mywrite(str) {
   process.stdout.write(str, function(err) {
      if (err!==undefined)
        return;
      ev = {
         length: str.length,
         content: str
      };
   });
}
```

**Comment by rentalhost** [comment]
In this aspect it works, but imagine that I need control everything that is
writed on stdout, even from third party modules. It is possible only for my
own code. :( It will help you control cursor line and position, for
instance.
Em 10/04/2015 18:21, "Коренберг Марк" <notifications@github.com> escreveu:

**Comment by socketpair** [comment]
I don't ever know why you try to do that, but if you want control cursor, you should look to  PTY code. More over, anot PROCESS (!) may write to same output, so you cannot control cursor in a safe way either. It is _NOT_ safe! Next. Utf-8 and unicode...someone writes sequences of bytes that may offset your cursor to undefined position. Next, control sequences of terminal....

Just stop control cursor in that way :)

Maybe you should use `readline` module(s) for your case.

**Comment by rentalhost** [comment]
I really think that it is complicated.

**Comment by socketpair** [comment]
so, please close issue :) make life of maintainers a bit easier. Thanks for asking.
