### ISSUE TITLE
improved http.ServerResponse API

### ISSUE THREAD

**Issue by mikeal** [joyent/node#1448]
We have a long thread about this here:
```
http://groups.google.com/group/nodejs-dev/browse_thread/thread/f9ddf97342f3d5ff#
```
The gist of it is:

Right now we kind of have two totally separate APIs for dealing with setting the status code and headers and sending them. 

One is to do 
```
response.statusCode = 200 
response.setHeader('content-type', 'text/plain') 
response.end('hello world') || fs.createReadStream('hello.txt').pipe(response) 
```
The other is: 
```
response.writeHead(200, headers) 
response.end('hello world') || fs.createReadStream('hello.txt').pipe(response) 
```
In the first example we don't actually send the statusCode and headers until the first response.write() call. 

In the second example, which is the older API, we send them immediately. 

`writeHead()` also supports a 2d array of headers, which bails out of the other API entirely causing some inconsistency problems. 

Here is my proposal for a new API. 
```
http.ServerResponse :: 

.statusCode // integer 
.headers // 2d array 
.setHeader(key, value) 
.getHeader(key) 
.setHeaders(object) 
.headersSent // boolean
.sendHeaders() // sends StatusCode and headers 
.writeHead(status, headers) // reverse compat, sets StatusCode, calls setHeaders and sendHeaders(). 
```
This way, `writeHead` just becomes a shorthand and maintains the same API it does now, but it's no longer inconsistent with the rest of the API. 

This is also better support for 2d arrays as headers. You can set .headers to whatever you want because it's what `getHeader`/`setHeader` actually operate on and use. You can also just modify it in place if that's simpler. And now when you do use 2d arrays you don't bail out of the normal API flow. 

We can also replace the instance method of `setHeader`/`setHeaders`/`writeHead`/`sendHeaders` after `sendHeaders` is called to a method that throws.

**Comment by jasnell** [comment]
@joyent/node-coreteam @isaacs ... what do we want to do with this one?

**Comment by Fishrock123** [comment]
I was under the impression http was to be heavily refactored / re-written at some point when there is time. This sorta thing may fit into that, and although it's not very incremental, it will probably be necessary at some point.

**Comment by jasnell** [comment]
Agreed. I'm leaning towards closing this for now then revisiting once we actually get around to that refactoring

**Comment by jasnell** [comment]
Labeling as a feature-request for later triaging.

**Comment by jasnell** [comment]
Going to close this one as not-actionable here. Will label it as deferred to the converged repo, however.
