### ISSUE TITLE
Not documented stream.unshift(): is not allowed after 'end' event.

### ISSUE THREAD

**Issue by socketpair** [joyent/node#14596]
1. Not documented: stream.unshift(): is not allowed after 'end' event
2. Not documented: stream.read() will NOT raise error when called after 'end' event

Such strange behaviour should be documented (and maybe fixed :)

**Comment by jasnell** [comment]
The documentation on this can certainly be improved. @socketpair ... are you interested in putting together a quick PR?

**Comment by socketpair** [comment]
Now, my english is bad + I do not know if that behaviour is intended (i.e. bug or not)

**Comment by jasnell** [comment]
I'll get a PR in for this shortly

**Comment by jasnell** [comment]
PR opened. Will land shortly once it's reviewed.
