### ISSUE TITLE
Not documented: stream.readable() is fired once when read is impossible

### ISSUE THREAD

**Issue by socketpair** [joyent/node#14597]
Not documented: stream.readable() is fired once when read is impossible. I think, that just before 'end' event.

Current documentation says: ``When a chunk of data can be read from the stream``. But in that case, chunk _CAN_NOT_ be read (``stream.read()`` will return ``null``).

**Comment by jasnell** [comment]
It's a bit confusing but it's not a bug. `readable` tells you that data can be read, it does not tell you if there is actually data that will be read. Your code has to be prepared to get a `null` back when calling `read`. The example https://nodejs.org/api/stream.html#stream_readable_read_size illustrates such handling.

**Comment by socketpair** [comment]
Please reopen. I understand that this is not a bug, but as I think, this non-trivial thing should be documented. For example, is it guaranteed that `readable` will be fired BEFORE `end` ? moreover, is it guaranteed that `readable` will fire if connection aborted on remote side?

**Comment by jasnell** [comment]
OK. Care to help out with a PR? :)

**Comment by jasnell** [comment]
I've got a PR open to clarify this. Will land shortly once reviewed.
