### ISSUE TITLE
readline module throwing error v0.10.33

### ISSUE THREAD

**Issue by chacliff** [joyent/node#14593]
I have a handler running the node readline module to read lines from a csv file combine them with the  file header and saves them to a mongodb using mongoose. This worked fine as a standalone app on my windows 7 64 bit machine running v0.12.0. I loaded The application onto a red hat server for production use and used yum install nodejs. The version that is considered "stable" to run on red hat is v0.10.33. When calling the web-service and sending over the csv file and passing it into the stream for readline to read it it was reporting an error from isTty is not defined. i set terminal to false and that error went away, but a new error came to light. This error was that the readline.js write was undefined. My IT is taking a snapshot of the server but i'm wondering if there was a fix done between the versions that possibly upgrading to the new version manually would change. 
I will post my code for readline below. and return with the exact error as soon as they get the server back up for me. 
    

    function doWork(usedb, db, buffer){
	var objArray = []; 
	var header; 
	var isFirst = true; 
	var stream = streamifier.createReadStream(buffer); 
	var rl = readline.createInterface({
		input: stream
	});
	rl.on('line', function (line) {
		var icd10Obj = {};
		var data = [];
		var obj = {};
	   
		if (isFirst) {
			header = line.split(',');
			for(var i in header){ //foreach
				header[i] = toTitleCase(header[i]); //make camelCase
				header[i] = header[i].replace("-",""); //remove dashes
				header[i] = header[i].replace(/ /g, ""); //remove spaces
			};
			console.log(header); 
			isFirst = false;
		} else {
			data = line.split(',');
			obj = _.object(header, data);
			if(db === ICD9to10 || usedb ===ICD10to9){
				if(obj['Code'].length > 3){
					obj.Code = obj['Code'].splice(3, 0, ".");
				}
				if(obj['Map'].length > 3){
					obj.Map = obj['Map'].splice(3, 0, ".");
				}
			}
			objArray.push(obj);
		}
	});
	rl.on('close', function() {
		var chunk = []
		for( doc in objArray){
			chunk.push(objArray[doc]); 
			if(chunk.length == 1000){ 
				db.collection.insert(chunk, function(err, result) {
					if(err) {
						console.log("Error: " + JSON.stringify(err)); 
						reply({ 'ok': false, 'err': err });					
					}
				});
				chunk.length = 0; 
			}
		}
		if( chunk.length > 0){
			db.collection.insert(chunk, function(err, result) {
					if(err) {
						console.log("Error: " + JSON.stringify(err)); 
						reply({ 'ok': false, 'err': err });					
					}
				});
		}
		objArray.length = 0;
		
	}); 
}

**Comment by chacliff** [comment]
The exact error is as below
    

    readline.js:303
    var string = this._decoder.write(b);
                             ^
   
     TypeError: Cannot call method 'write' of undefined
      at Interface._normalWrite (readline.js:303:30)
      at ondata (readline.js:91:10)
    at emit (events.js:95:17)
    at null.<anonymous> (_stream_readable.js:764:14)
    at emit (events.js:92:17)
    at emitDataEvents (_stream_readable.js:789:10)
    at Readable.on (_stream_readable.js:710:5)
    at new Interface (readline.js:107:11)
    at Object.exports.createInterface (readline.js:39:10)
    at doWork (/app/ICDWebAPI/controller/diagnosisCodes.js:279:20)

I am going to install the newest version of node manually now from v0.10.33 to the current v0.12.2 I will notify if this solves the problem with the error.

**Comment by misterdjules** [comment]
I think this has been fixed by https://github.com/joyent/node/commit/862cc28183b03f0e1a67b052b5c8250a3e2e8995.

Note that this commit has landed only in the v0.12 branch, so node v0.10.x still has the same limitation. However the v0.10 documentation [states that the `output` property for the options object is "Required"](https://nodejs.org/dist/v0.10.38/docs/api/readline.html#readline_readline_createinterface_options), so in v0.10.x this works as expected, although it may have been useful to throw an exception if `output == null` to avoid confusion.

Closing as this works as expected and node v0.10.x is now in maintenance mode, but please feel free to comment further if you have any question.

**Comment by chacliff** [comment]
so the problem here is there is no output stream is what your saying? so either give it an output stream or upgrade to version v0.12.x

**Comment by misterdjules** [comment]
@chacliff Correct.
