### ISSUE TITLE
UDP socket sendMulti() and "multiMessages" event features

### ISSUE THREAD

**Issue by guymguym** [joyent/node#14591]
Hi

This is following recvmmsg and sendmmsg from linux that batch the handling of multiple datagrams in a single user call. For windows I saw [Windows Registered I/O API (RIO)](http://stackoverflow.com/questions/20119419/how-can-i-reduce-system-call-overhead-when-sending-a-large-number-of-udp-packets).

It would be great if node can provide a similar interface, since in many cases with UDP the small MTU of WAN networks requires splitting to multiple tiny send calls, which add a lot of cpu overhead.

I'm not sure in which layer there is more overhead - system calls, or v8 buffer preparations and garbage collection, but it just seems like a natural performance addon to node's udp.

Thanks!

**Comment by misterdjules** [comment]
That seems like an interesting topic for discussion, however I think it would get more traction with actual data from benchmarks. You might also want to start the discussion in [libuv](https://github.com/libuv/libuv), where it seems @bnoordhuis [had experimented with recvmmsg in the past and had mixed results, albeit in another context](https://github.com/joyent/libuv/issues/414#issuecomment-14023456). The link point to joyent/libuv, but please note that the libuv project moved to libuv/libuv.

**Comment by jasnell** [comment]
@misterdjules @guymguym ... any further thoughts on this? is there reason to keep this open?

**Comment by guymguym** [comment]
not for now. i guess it will only be relevant after libuv will support

**Comment by jasnell** [comment]
Ok, going to close the issue for now then.
