### ISSUE TITLE
critical error. TypeError: Object #<Object> has no method 'access'

### ISSUE THREAD

**Issue by mike-aungsan** [joyent/node#14821]
node
> var fs = require('fs');
undefined
> fs.access('servers.js', function(err, stats) { console.log(err); console.log(s
tats); })
TypeError: Object #<Object> has no method 'access'
    at repl:1:5
    at REPLServer.self.eval (repl.js:110:21)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
    at Interface._line (readline.js:531:8)
    at Interface._ttyWrite (readline.js:760:14)
    at ReadStream.onkeypress (readline.js:99:10)
    at ReadStream.emit (events.js:98:17)
    at emitKey (readline.js:1095:12)
> fs
{ Stats: [Function],
  exists: [Function],
  existsSync: [Function],
  readFile: [Function],
  readFileSync: [Function],
  close: [Function],
  closeSync: [Function],
  open: [Function],
  openSync: [Function],
  read: [Function],
  readSync: [Function],
  write: [Function],
  writeSync: [Function],
  rename: [Function],
  renameSync: [Function],
  truncate: [Function],
  truncateSync: [Function],
  ftruncate: [Function],
  ftruncateSync: [Function],
  rmdir: [Function],
  rmdirSync: [Function],
  fdatasync: [Function],
  fdatasyncSync: [Function],
  fsync: [Function],
  fsyncSync: [Function],
  mkdir: [Function],
  mkdirSync: [Function],
  readdir: [Function],
  readdirSync: [Function],
  fstat: [Function],
  lstat: [Function],
  stat: [Function],
  fstatSync: [Function],
  lstatSync: [Function],
  statSync: [Function],
  readlink: [Function],
  readlinkSync: [Function],
  symlink: [Function],
  symlinkSync: [Function],
  .....

**Comment by cjihrig** [comment]
What version of node are you running?

```
$ node
> process.version
'v0.12.2'
> fs.access;
[Function]
> fs.accessSync;
[Function]
```

**Comment by mike-aungsan** [comment]
My mistakes. Suppose to be v0.12.* but someone put v0.10.* in one of the box stupidly.
