### ISSUE TITLE
Why a handler function need refer to EventEmitter's context?

### ISSUE THREAD

**Issue by abruzzihraig** [joyent/node#14852]
Hi guys, I am studying some code in EventEmitter, and I am confused in why a handler function need refer to EventEmitter's context like below:

https://github.com/joyent/node/blob/master/lib/events.js#L106
https://github.com/joyent/node/blob/master/lib/events.js#L120

I don't know why not use `apply(null, args)` or `call(null, arguments)` here, could anyone explain it? 
Thanks!

**Comment by OrangeDog** [comment]
One of many examples I could think of:

    function fooHandler() {
        console.log(this.informations);
    }
    bars.forEach(function(bar) {
        bar.on('foo', fooHandler);
    }

Anyway, this isn't a bug. IRC or mailing list is where you want to go.
