### ISSUE TITLE
Node v0.12.2 bundles broken npm v 2.7.4

### ISSUE THREAD

**Issue by tsvendsen** [joyent/node#14882]
The npm v 2.7.4 seems like it has some problems when searching for dependencies and the registry url have a path. The search only uses hostname/-/all instead of entire registry url property. 
e.g http://hostname/nexus/content/groups/npm-all/ will result in a get to http://hostname/-/all when building index. 

npm install -g npm@latest states that 2.7.6 is the latest, but it does not update the npm which is bundled. (see other bugs on node not using the one in AppData)

However the 2.7.6 version seems to have fixed this, so providing a build of the node installer with npm version 2.7.6 would fix the problem.

As a workaround I updated npm in the node directory by going to node installation folder running npm install npm@latest

npm registry being set to http://hostname/nexus/content/groups/npm-all
npm debug log shows this:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'search',
1 verbose cli   'karma',
1 verbose cli   '--registry=http://hostname/nexus/content/groups/npm-all' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 silly mapToRegistry name -/all
6 silly mapToRegistry using default registry
7 silly mapToRegistry registry http://hostname/nexus/content/groups/npm-all
8 silly mapToRegistry uri http://hostname/nexus/content/groups/npm-all/-/all
9 info updateIndex C:\Users\txs\AppData\Roaming\npm-cache\hostname\nexus\content\groups\npm-all\-\all\.cache.json
10 warn Building the local index for the first time, please be patient
11 verbose request uri http://hostname/-/all
12 verbose request always-auth set; sending authorization
13 info attempt registry request try #1 at 08:34:32
14 verbose request id b168123c9cb10851
15 http request GET http://hostname/-/all
16 http 404 http://hostname/-/all

**Comment by outofcoffee** [comment]
I am also seeing this with npm 2.7.4.

**Comment by misterdjules** [comment]
Fixed by 8fc40af034f5b526f0d7e421401786e11a2c50cf.
