### ISSUE TITLE
Feature request: fs.(read|write)stream.tell()

### ISSUE THREAD

**Issue by AvianFlu** [joyent/node#1527]
Readable and/or writable file streams should have an equivalent method to `ftell()`.  From its man page:

      The ftell() function obtains the current value of the file position indicator for the stream pointed to by stream.

The primary use case I see for this is in the making of progress bars for file transfers.  

/cc @SubStack

**Comment by jasnell** [comment]
@joyent/node-coreteam @isaacs ... what do we want to do with this one? I agree that something like this would be useful at times but doesn't do us much good leaving this open for so long without action? Recommend closing it again. If we want to add this a new issue can be opened or someone can submit a PR adding.

**Comment by jasnell** [comment]
Going to close this one for lack of activity. If this is still something someone wants, then a new issue can be opened in nodejs/io.js or nodejs/node
