### ISSUE TITLE
setTimeout can’t work well after the process is blocked

### ISSUE THREAD

**Issue by ilc-opensource** [joyent/node#15447]
node.js version: 4d9c81b7e2522c5d5d9d35058cbb0bce1228d360 (latest version), v0.10.33, node-v0.12.2
Platform: Ubuntu 14.04.1 LTS
Architecture: x86_64

    var block = require('bindings')('hello'); // c++ addon
    var a = function() {
      var timer = (new Date()).getTime();
      console.log('before block:'+timer);
    
      block.hello(); // will be block at some time
    
      timer = (new Date()).getTime();
      console.log('after block:'+timer);
    
      setTimeout(a, 5000);
    };
    a();

In the above script, function a will be executed very 5000 milliseconds if the block.hello is not blocked; But if the block.hello is blocked in c++ code, the time point which function a will be executed again is much larger than 5000 milliseconds after block.hello is unblocked. The following is the output of the above script:
1   before block:1429079335210
2   after block:1429079335210
3   before block:1429079340215
4   after block:1429079366741
5   before block:1429079398298
6   after block:1429079398299
7   before block:1429079403304
8   after block:1429079403304
Time interval between line2 and line 3 is 5005; 
**Time interval between line4 and line 5 is 31557;**
Time interval between line6 and line 7 is 5005;

block.hello is blocked and unblocked between line 3 and line 4.

## How to reproduce the issue?
1.	Download the tar file and decompress; https://www.dropbox.com/s/1y299n1y1uy69ij/node_js_debug.tar?dl=0
2.	cd node_js_debug;
3.	sh build.sh;
4.	node a.js;
5.	In another terminal, ./setFrontEndApp 123456; after a while, ./setFrontEndApp 0

## How to fix?
I find we should recalculate now each time when processing the pending time events.

diff --git a/lib/timers.js b/lib/timers.js
index 68f87d7..c6af7f9 100644
--- a/lib/timers.js
+++ b/lib/timers.js
@@ -80,11 +80,10 @@ function listOnTimeout() {

       debug('timeout callback %d', msecs);
    
    -  var now = Timer.now();
    -  debug('now: %s', now);
    -
       var diff, first, threw;
       while (first = L.peek(list)) {
    +    var now = Timer.now();
    +    debug('now: %s', now);
         diff = now - first._idleStart;
         if (diff < msecs) {
           list.start(msecs - diff, 0);

**Comment by obastemur** [comment]
@ilc-opensource It looks like a very good catch. After inspecting your scenario, I saw some other possible issues this patch might take care of. 

Wondering how this patch will affect some existing applications. I'm going to further investigate on this.

**Comment by obastemur** [comment]
After spending some time on this issue, I didn't see any side effect because of the suggested fix. It's possible to implement a version of this suggested fix that doesn't call Timer.now on each loop. However, Timer.now call costs almost nothing comparing to look&feel and complexity of alternative implementation.

**Comment by ilc-opensource** [comment]
Is it possible to put this patch to node.js repository? Then my partners and I don't need to patch node.js in our project.

**Comment by misterdjules** [comment]
This is also the same issue as #9333.

**Comment by misterdjules** [comment]
Created a PR that fixes the issue: #17203. Thank you very much @ilc-opensource and @obastemur!

**Comment by misterdjules** [comment]
Fixed by https://github.com/joyent/node/commit/d38e865fce93c00cb128034202fb1e26987efdbc, which will be available in the upcoming v0.10.39 and v0.12.5 releases.
