### ISSUE TITLE
__dirname is not accurate when file location is unknown

### ISSUE THREAD

**Issue by bahamas10** [joyent/node#15444]
given `foo.js`

``` js
console.log(__dirname);
```

calling it directly yields the right result

```
$ node foo.js
/home/dave
```

but, when node cannot determine the path, it gives a strange result

```
$ cat foo.js | node
.
```

In this specific case, it is right, but if i go to a different directory it fails

```
$ cd /tmp
$ cat ~/foo.js | node
.
```

I propose that `__dirname` should be `undefined` in the case where it cannot be determined.

I have a full write up about this here: http://daveeddy.com/2015/04/13/dirname-case-study-for-bash-and-node/

**Comment by odeke-em** [comment]
Hello @bahamas10, this caught my interest.
Am curious, would you mind trying this out to see if it cuts the deal and the cases mentioned for you?

In your shell
```shell
$ cat << ! > foo.js
> var path = require('path');
> var dirname = path.dirname(__filename);
> var resolvedDirname = path.resolve(dirname, '.');
>
> console.log(resolvedDirname);
> !
```
Thank you.

**Comment by isaacs** [comment]
-1

I'd be ok in principle with it returning `process.cwd()`.  However, since this interface has been so stable for so long, I'd be apprehensive about changing it.

**Comment by bahamas10** [comment]
https://nodejs.org/docs/latest/api/globals.html#globals_dirname

> The name of the directory that the currently executing script resides in.

In the case that the script is passed over `stdin`, having it set to `process.cwd()` or `'.'` is misleading and potentially incorrect.  I know that this has been the behavior for a while, but I would consider it undocumented and subject to change.

**Comment by jasnell** [comment]
Agree with @isaacs ...
