### ISSUE TITLE
install usb

### ISSUE THREAD

**Issue by FlorianCcj** [joyent/node#16015]
I tried to install the usb module, but I don't succed.
When I launch "npm install usb"  here it is the return

        C:\Users\Florian>npm install usb
        npm WARN optional dep failed, continuing usb-shyp-darwin-x64@1.0.6

        > usb@1.0.5 install C:\Users\Florian\node_modules\usb
        > node shyp-blacklist.js win32-x64 win32-ia32 darwin-x64 || node-gyp rebuild

        usb@1.0.5 node_modules\usb
        ├── bindings-shyp@0.2.3
        ├── nan@1.7.0
        ├── usb-shyp-win32-x64@1.0.5
        └── usb-shyp-win32-ia32@1.0.5

        C:\Users\Florian>

and when I try to use the module, it doesn't work.
I am with node V0.12.2 and npm 2.7.4

**Comment by KenanY** [comment]
@FlorianCcj Installation looks successful. Your issue might be better suited for the mailing list or StackOverflow. This issue tracker is for _bugs_ in Node.js core.

**Comment by FlorianCcj** [comment]
ok thanks
