### ISSUE TITLE
Inconsistency in request and response headers

### ISSUE THREAD

**Issue by kuebk** [joyent/node#1604]
There is an inconsistency in parsing headers between request and response.

If in request I put 2 headers with same name but with different value node request objects returns them as one header with both values separed by comas, shouldn't I get an array of values?

Code examples:

    var http = require('http');

    http.createServer(function(request, response){
        console.log('Request header:', request.headers["x-test-header"]);

        response.setHeader("X-Test-Header", [123, 456]);
        console.log('Response header:', response.getHeader("X-Test-Header"));
        response.writeHead(200);
        response.end('OK');
    }).listen(8080);

Request:
```curl -v -H X-Test-Header:123 -H X-Test-Header:456 http://localhost:8080```

Result:
```Request header: 123, 456
Response header: [ 123, 456 ]```

**Comment by jasnell** [comment]
Comma separated is correct behavior. Node does not currently attempt to do parsing out of header values automatically (it's a non-trivial concern really).
