### ISSUE TITLE
Node.js does not search for modules when installed globally using npm

### ISSUE THREAD

**Issue by khagesh** [joyent/node#16526]
Hello, I installed node on ubuntu 14.04 using NVM. Node runs successfully and works fine.
The problem i am facing is as below.
I installed `http-server` module using `npm install -g http-server` and it installed successfully. Now, when i try to run it using node it throws error 
```
khagesh@khagesh-VirtualBox:~$ node http-server
module.js:338
    throw err;
          ^
Error: Cannot find module '/home/khagesh/http-server'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by cjihrig** [comment]
According to the docs for `http-server`, after installing with `-g`, you should run `http-server`, not `node http-server`.
