### ISSUE TITLE
process.stdin.read() prevents process from exiting if no data is received

### ISSUE THREAD

**Issue by gfxmonk** [joyent/node#17204]
Simple repro:

    console.log(process.stdin.read());

Program prints `null`, but then never exits. If you type a line (then press return), it will exit.

For a more realistic case, [here's a small gist](https://gist.github.com/gfxmonk/e4259969cd5692a32a9f) that will try consuming a stream, but bail out if it doesn't reach the end in 100ms. Sample output:

	$ node test.js fs
	reading from /dev/zero
	calling read()
	waiting for 'readable' event ...
	stream is readable!
	calling read()
	saw chunk of 65536b
	[ repeated many times ]
	waiting for 'readable' event ...
	cancel...
	removing listener
	[ process terminates ]

	$ node test.js stdin
	reading from stdin
	calling read()
	waiting for 'readable' event ...
	cancel...
	removing listener
	[ process never terminates ]

My real use case is an SSH session, where I'd like to forward my local `stdin` to the remote process' `stdin`. But once the remote command exits, I can stop forwarding `stdin` (because clearly the remote command doesn't need any input). This bug prevents my process from ever terminating.

I've tested in nodejs 0.10 and 0.12, the behaviour is the same on both.

**Comment by gfxmonk** [comment]
I forgot to mention - this is all on Linux.

**Comment by gfxmonk** [comment]
Update: I've found that explicitly calling `process.stdin.pause()` when you're no longer interested in receiving input will cause the process to exit appropriately. Since the docs state that `pause()` switches a stream out of flowing mode (which stdin should _not_ be in anyway), I'm treating this as an accidental workaround rather than a logical solution.

**Comment by jasnell** [comment]
The docs could likely be improved around this but it's working as expected. Closing the issue but we can revisit

**Comment by gritzko** [comment]
At the moment, I experience similar issues.
I do `process.stdin.on('data', ...);`  then `process.stdin.pause()` and it never terminates.
After reading the docs, I still have no idea what to do.

**Comment by gritzko** [comment]
OK, I was running it inside `tap` the test runner.
Apparently, things get messed up then.
