### ISSUE TITLE
http.ServerResponse#writeFile

### ISSUE THREAD

**Issue by networkimprov** [joyent/node#1802]
Provide a writeFile(filename, callback) method of http.ServerResponse (and/or net.Socket) which uses sendfile or splice internally. Would run in the thread pool to avoid blocking.

This was discussed last year and Ry concluded it should wait for the writev patch...

https://groups.google.com/group/nodejs-dev/browse_thread/thread/1461c9ea5e90fc4e/d62fc949de7af66e

Edit: should take a 'noCache' argument, which if true calls posix_fadvise() after each sendfile() call:

      posix_fadvise(fd, 0, 0, POSIX_FADV_DONTNEED);

**Comment by jasnell** [comment]
@joyent/node-coreteam what do we want to do with this one? I agree it will be useful but it's been sitting here forever with no action. Recommend closing. If someone wants this still we can wait for a PR that actually does it.

**Comment by jasnell** [comment]
Not something that will land in v0.10 or v0.12. Marking as deferred and closing. If this is still something someone wants, then an issue should be opened in nodejs/io.js or nodejs/node
