### ISSUE TITLE
expose process.argv string parser

### ISSUE THREAD

**Issue by maboiteaspam** [joyent/node#18207]
Hi,

I m looking for a way to re use internal NodeJs process.argv parser.

I have to transform command lines such ```echo "hello, whatever" --some f``` to pass them to ```child_process.spawn(str, args)```.

Found it would be clean and safer to re use Node Parser.

But i could not find how to do. I guess it is not part of public api.

I also tried various npm module, all those i found relies on your parser.

So far i came out with something like this.
```
      // - command line parser. Could not find how to re use node parser.
      cmdStr = cmdStr.match(/^([^ ]+)(.+)/);
      var prgm = cmdStr[1];
      cmdStr = _s.trim(cmdStr[2]);
      var args = [];
      var isquote=false;
      cmdStr.split(" ").forEach(function (part){
        if(part.match(/^['"]/)){
          args.push(part);
          isquote = true;
        }else if(part.match(/['"]$/) && !part.match(/\\['"]$/) ){
          args[args.length-1] += ''+part+' ';
          isquote = false;
        }else{

          if(isquote){
            args[args.length-1] += ''+part+' ';
          } else{
            args.push(part);
          }
        }
      });
      args.forEach(function(arg,i){
        var m = arg.match(/^\s*["'](.+)["']\s*$/);
        if( m ){
          args[i] = m[1]
        }
      });
      args[args.length-1] = _s.trim(args[args.length-1]);
      // - command line parser. Could not find how to re use node parser.
```

I m not able to handle that C code you use to produce that amazing language. So, here i am.

Any suggestions about that small issue are highly welcome.

Thanks !

**Comment by misterdjules** [comment]
This issues tracker is used to track bugs and feature requests for Node.js. I'm closing this issue for now, as this question seems to be too general.

May I invite you to ask it on the [Node.js Google group](https://groups.google.com/forum/#!forum/nodejs) first and then let us know if there are missing features or existing bugs that prevent you from using Node.js as you'd like to?
