### ISSUE TITLE
Any way to work around windows-1256 encoding?

### ISSUE THREAD

**Issue by anas-abusall** [joyent/node#18985]
Hi everyone,
I have a problem to get a string encoded with windows-1256, and i've spent many hours searching for a solution.
Any one can help me?

**Comment by llafuente** [comment]
with that brief description: use https://github.com/bnoordhuis/node-iconv

**Comment by anas-abusall** [comment]
I have problem while  installing iconv:
https://github.com/bnoordhuis/node-iconv/issues/114

**Comment by cjihrig** [comment]
You should add your error logs to the node-iconv issue. I'm going to close this for now, we can revisit if the iconv path doesn't lead anywhere.

**Comment by anas-abusall** [comment]
hmm
it's strange to close this, as you are willing to say "iconv your only solution and let them to help you there"
anyway , thanks :)
