### ISSUE TITLE
I've specified CA cert however authorizationError returns CERT_UNTRUSTED

### ISSUE THREAD

**Issue by efkan** [joyent/node#19147]
I guess I've tried all ways however I couldn't get rid of the problem.
I have got a trial SSL certificate from Comodo. It works on my web page without problem.
When I try to make a request to my API server **as a client** using Comodo SSL, `connection.authorized` value returns as false and `authorizationError` is `CERT_UNTRUSTED` at every single time. 

I've read [tlsSocket.authorized][2] and [event 'SecureConnection'][3] explanations.
>socket.authorized is a boolean value which indicates if the client has verified by one of the supplied certificate authorities for the server. If socket.authorized is false, then socket.authorizationError is set to describe how authorization failed.

Although CA certificate's been specified the below code `authorizationError` returns as CERT_UNTRUSTED.

I'd like to know what can I do?

My question on [stackoverflow][1] regarding the issue

	var https = require('https');
	var fs = require('fs');

	var options = {
		key: fs.readFileSync('key.pem'),
		cert: fs.readFileSync('cert.pem'),
		ca: fs.readFileSync('ca.pem'),

		rejectUnauthorized: false,

		hostname: 'api.mydomain.com',
		port: 443,
		path: '/',
		method: 'GET',
	};

	var req = https.request(options, function(res) {

		console.log("res.connection.authorized: ", res.connection.authorized);

		if(!res.connection.authorized) {
		  	console.log('Authorization error: ' + res.connection.authorizationError);  
		}

		console.log("headers: ", res.headers);

	})

	req.end();

[1]: http://stackoverflow.com/q/29801300/3765109
[2]: https://nodejs.org/api/tls.html#tls_tlssocket_authorized
[3]: https://nodejs.org/api/tls.html#tls_event_secureconnection

**Comment by misterdjules** [comment]
@efkan What version of node are you using? What is the URL of your API (I'd like to take a look at the certificate)?

**Comment by efkan** [comment]
@misterdjules first of all thank you.

My `node --version` is `v0.10.34` and my test API address is `islem.markalarim.club/test` on port `443`
(https://islem.markalarim.club/test)


Some findings of mine;
- [Symantec SSL Certificate Checker][1] results are good. <br>
- However [SSL Checker][2] of SSL Shopper page gives a warning as `You may need to install an Intermediate/chain certificate to link it to a trusted root certificate.`
- I've donwloaded another second CA bundle file from http://curl.haxx.se/ca/cacert.pem and I changed my code as `ca: [ fs.readFileSync('ca.pem'), fs.readFileSync('cacert.pem')]`. Still I get `CERT_UNTRUSTED` error.


[1]: https://ssltools.websecurity.symantec.com/checker/views/certCheck.jsp
[2]: https://www.sslshopper.com/ssl-checker.html#hostname=islem.markalarim.club
