### ISSUE TITLE
Cannot Use Node Debugger On A Difference Port Than 5858

### ISSUE THREAD

**Issue by jennaliu** [joyent/node#19149]
I am trying to start node debugger on a different port than the default 5858 (because I am trying to debug two scripts at the same time). I followed the advanced usage described in https://nodejs.org/api/debugger.html . These are the steps that I took:
1. run 'node --debug=9000 server.js'
2. run in anther window 'node debug localhost:9000'
The second command gives me an error:

< Debugger listening on port 5858
connecting to port 9000... ok
< module.js:338
<     throw err;
<           ^
< Error: Cannot find module '/home/ubuntu/app/localhost:9000'
<     at Function.Module._resolveFilename (module.js:336:15)
<     at Function.Module._load (module.js:278:25)
<     at Module.runMain [as _onTimeout] (module.js:501:10)
<     at Timer.listOnTimeout (timers.js:110:15)
debug> 

The debug is still trying to connect to port 5858 and thinks localhost:9000 is a script. Is there a way to use a different port with node's internal debugger?

**Comment by misterdjules** [comment]
@jennaliu I believe this is fixed by f0ef597e094f2519486e080897956389584876e4, which will be available in the upcoming v0.12.3 version. Thank you @JacksonTian! :+1:

If I'm missing something, please let us know and I'll reopen this issue. Thank you!
