### ISSUE TITLE
When running node on windows with php's proc_open() it crashes with Unknown system errno 10106

### ISSUE THREAD

**Issue by Shyru** [joyent/node#1943]
We have a small wrapper script (written in php) that starts node with a given javascript file.
To read and write to nodes stdin/stdout we use proc_open() of php. When doing this, node crashes with this exception:

```
node.
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: listen Unknown system errno 10106
    at errnoException (net.)
    at Array.<anonymous> (net.)
    at EventEmitter._tickCallback (node.)
```
Our node server uses faye () to listen on port 8000 for incoming requests.
Fore reference this is the script we are trying to execute:

```javascript
console.log("startup");
var http = require('http'),
    faye = require('faye');
	

var bayeux = new faye.NodeAdapter({mount: '/faye', timeout: 45});

bayeux.listen(8000);
console.log("running");
```
Note: I dont get the output 'startup' or 'running' from inside php.

__Important:__ When running node from commandline with this script, everything works perfectly! Its just that starting it from php with proc_open() makes it go crazy!
Any idea what could be the cause of this?

Edit: I forgot to say this is using current node 0.5.10, but the error existed already in previous node versions, but the crashes where all different, but it never worked. :-)

**Comment by jasnell** [comment]
Closing this for now as there does not appear to be anything to do at this point. Can reopen later if new information is received.
