### ISSUE TITLE
npm-gyp rebuild fails with access denied

### ISSUE THREAD

**Issue by aarthipa** [joyent/node#19483]
Hi,
I am using windows 7 64 bit. When I install ldapauth, node-gyp rebuild fails with the following error. I followed the links below to install the binaries, still not change in the error message.
https://github.com/TooTallNate/node-gyp#installation
https://github.com/TooTallNate/node-gyp/wiki/Visual-Studio-2010-Setup
I also set the follwowing - node-gyp build --msvs_version=2010

![depen](https://cloud.githubusercontent.com/assets/11402289/7295398/12c0ec10-e9d3-11e4-93fd-ff8e86222e59.png)

and here are the installed dependencies
![windoes_dependencies](https://cloud.githubusercontent.com/assets/11402289/7295463/d2d6ceca-e9d3-11e4-92aa-b481195ebb20.png)

Please help. I've been struggling with this for a while now..
Aarthi

**Comment by aredridel** [comment]
Looks like you're building a module in `c:\program files\`. This requires admin privilege on most windows machines. Move your project out of there and see if that helps.

**Comment by misterdjules** [comment]
@aarthipa Other suggestions:

1. It seems you're using node v0.8.25, have you tried using a newer version?
2. Do you have Python installed?
3. https://github.com/joyent/node/issues/4047 looks similar to this issue, could you please try some of the suggestions that have been posted there:
  * [Setting the `PYTHON` environment variable to python's full path](https://github.com/joyent/node/issues/4047#issuecomment-36245850).
  * [Passing the --msvs_version option to npm](https://github.com/joyent/node/issues/4047#issuecomment-36712471).

**Comment by aarthipa** [comment]
@misterdjules  Thanks.I have a python for 64 bit installed and the path is set to the .exe file (full path). I also set the msvs version to 2010
Following your advice, I updated node to v0.12.2.  The access denied message is gone although I got newer error as the following

C:\Programs\nodejsCloudant\node_modules\ldapauth\node_modules\bcrypt>if not defi
ned npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node
-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)

gyp ERR! configure error
gyp ERR! stack Error: spawn C:\Python27 ENOENT
gyp ERR! stack     at exports._errnoException (util.js:746:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1053
:32)
gyp ERR! stack     at child_process.js:1144:20
gyp ERR! stack     at process._tickCallback (node.js:355:11)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Programs\nodejsCloudant\node_modules\ldapauth\node_modules\bcryp
t
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
-

**Comment by aarthipa** [comment]
@aredridel - My project is under c:/Programs which is a directory I created.

**Comment by misterdjules** [comment]
@aarthipa This looks like an issue with setting up Python so that node-gyp can use it, similar to https://github.com/TooTallNate/node-gyp/issues/277. I would suggest reading that issue and trying what other users recommend.

I don't think it's a problem with Node.js itself, so I'll close this issue. If it turns out to be a bug in node, please let us know and I'll reopen.
