### ISSUE TITLE
Change the way 'npm install' and 'require' work a little bit

### ISSUE THREAD

**Issue by hawkerboy7** [joyent/node#19795]
Hi, I am quite new to Node.js and I don't understand why node modules are not installed in  `path/to/nodejs/node_modules/[module-1@version]` by default instead of `./node_modules`. I described the situation down below.

`cd ~/projects/project-1`
If you `npm install [module-1]` it's placed in `~/projects/project-1/node_modules/[module-1]` for example version `1.0.1`

`cd ~/projects/project-2`
`npm install [module-1]` it's placed in `~/projects/project-2/node_modules/[module-1]` version `1.0.1`

So if I install `module-1` in `project-2` the exact same files are downloaded and placed into `project-2`.
This is not very space and bandwidth efficient I think?

Why not change this behavior into the following?
`cd ~/projects/project-1`
`npm install [module-1]` it's __now__ placed in `path/to/nodejs/node_modules/[module-1@1.0.1]`
So the folder name is now the name of the module __AND__ the required version.

This means `require` needs an extra functionality.
`cd ~/projects/project-3/[this project is empty]`
Here index.js get the following code
```javascript
var module_1 = require('module-1');
```
To keep it backwards compatible make it do the following:
1. check the folder `./node_modules` for the `module-1`. If found: use it. If not: step 2.
2. check the package.json for the version of `module-1` that you need. If found: step 3. If not: step 4.
3. check the folder `/path/to/nodejs/node_modules/[module-1@version]`. If found: use it. If not: step 4.
4. check if `module-1` is globally installed. If found: use it. If not: step 5.
5. Error module not found!

_Here I assume_ `require` _checks if you have a module globally installed if it isn't found locally. I am not sure if this is the actual behavior of_ `require` _though, but it seemed logical to me._
This way many projects can share the exact same module instead of having it on your computer numerable times!!
Would this work?

**Comment by KenanY** [comment]
> bandwidth efficient

`npm` utilizes a cache so the second run would use almost no bandwidth.

Also the module system is [locked](https://nodejs.org/api/modules.html#modules_modules) so this is never going to happen.

**Comment by hawkerboy7** [comment]
Ahh all right, so not so much bandwidth efficient.. but space efficiency and the overall idea?

**Comment by cjihrig** [comment]
Having the same module installed multiple times is actually a strength of npm, as it helps prevent dependency conflicts. If you want to save space, you can dedupe, or globally install your modules. As @KenanY pointed out, the module system is locked, so this is unlikely to change.

**Comment by hawkerboy7** [comment]
Well that conflict can be resolved by having the version number added to the folder then right?
To bad :)
