### ISSUE TITLE
Portable Version of NodeJS

### ISSUE THREAD

**Issue by jonorozcoc** [joyent/node#19956]
NodeJS is a very complete framework and tool for developers, but need much config (I'm noob :) ) is more useful an portable version of this.

**Comment by frankcash** [comment]
Maybe try using it within docker? https://registry.hub.docker.com/_/node/

**Comment by jonorozcoc** [comment]
Yes, i tried, but Docker an installation, i need a single standalone file with all contents of NodeJS,

**Comment by jonorozcoc** [comment]
i tried, changing the enviroment variables and the npm config

**Comment by jonorozcoc** [comment]
but not worked for me.

**Comment by misterdjules** [comment]
This issues tracker is used to track bugs and feature requests for Node.js. I'm closing this issue for now, as this question seems to be too general.

May I invite you to ask it on the [Node.js Google group](https://groups.google.com/forum/#!forum/nodejs) first and then let us know if there are missing features or existing bugs that prevent you from using Node.js as you'd like to?
