### ISSUE TITLE
fs.watch fails to detect changes to file replaced by rename event

### ISSUE THREAD

**Issue by TrevorBurnham** [joyent/node#2062]
If I `fs.watch` a file and then save a change to it using the [Coda](http://www.panic.com/coda/) text editor, it first detect a `'rename'` event, then no further events. Coda appears to be very unusual in this respect; I haven't seen this behavior with any other Mac text editor. Maybe this is a fundamental problem with file change event notifications under Darwin; I'm not sure.

**Comment by jasnell** [comment]
Closing. Issue appears to have been resolved. No information as to why it was reopened. Can reopen if new information is received.
