### ISSUE TITLE
child_process.spawn behaves badly when large stdout is not read

### ISSUE THREAD

**Issue by juliemr** [joyent/node#23949]
I have a reproducible example at https://github.com/juliemr/bigbuffer

I am starting a simple http server in a child process. This server also produces a large amount of logging to stdout. When the parent node process reads stdout, the server works as expected. If stdout is set to 'pipe' but not read, the server will hang (precisely, navigating to `localhost:9005` in the example just spins forever).

I see this behavior in both node 0.10 and 0.12.

Possibly related: #7967, #6764

**Comment by cjihrig** [comment]
The explanation on #6764 seems to accurately describe what you're seeing.

**Comment by juliemr** [comment]
I understand why the child process would be prevented from closing, but I'm not sure I understand why it doesn't complete HTTP requests.

**Comment by cjihrig** [comment]
My guess is your logging code is blocking because there is no more room in the pipe. Since that is blocked, the code that serves the HTTP requests does not get to execute.

**Comment by juliemr** [comment]
Ah yes, that makes sense. Thanks.

So is this annoying to run into but WAI?

**Comment by cjihrig** [comment]
IMO, yes.
