### ISSUE TITLE
fs.watch losing track of file after change event

### ISSUE THREAD

**Issue by TrevorBurnham** [joyent/node#2405]
This only seems to happen with the TextMate 2 alpha under OS X: If you use it to save a file that you've `fs.watch`-ed, you get a `change`, and then no further events of any kind are detected. Tested under Node 0.6.6.

Could you take a look at this, @bnoordhuis? Any idea how TM2 could cause `fs.watch` to lose track of a file without emitting a `rename` event? The directory containing the file doesn't emit any events, either.

**Comment by jasnell** [comment]
Need a test case to reproduce. Closing. Can reopen if necessary.

**Comment by pravdomil** [comment]
![gif](https://cloud.githubusercontent.com/assets/2387356/21320686/34777636-c612-11e6-8014-4896cbf64134.gif)
