### ISSUE TITLE
OS X .pkg installer might not need root

### ISSUE THREAD

**Issue by cowboy** [joyent/node#2427]
When installing via OS X .pkg installer, is there any way to remove root auth or only require root auth if the installer actually needs it? On OS X 10.7, I can `touch /usr/local/bin/foo` without `sudo`, so the `node-v0.6.6.pkg` installer shouldn't need root either, right?

(I'm trying to automate installation)

```sh
$ installer -pkg /tmp/node-v0.6.6.pkg -target /
installer: Must be run as root to install this package.

$ sudo installer -pkg /tmp/node-v0.6.6.pkg -target /
Password:
installer: Package name is Node
installer: Upgrading at base path /
installer: The upgrade was successful.
```

**Comment by schwiet** [comment]
just ran into the 24561 issue. I noticed it when I couldn't npm install -g. chown fixed the issue, but still not sure what caused it.

**Comment by jasnell** [comment]
Closing this here. Would defer to nodejs/build WG.

**Comment by misterdjules** [comment]
Added more details about this issue in https://github.com/nodejs/build/issues/226.
