### ISSUE TITLE
x64 Windows installer installs to incorrect path

### ISSUE THREAD

**Issue by sbmelvin** [joyent/node#25087]
I just downloaded the x64 Windows installation MSI and it wants to install to C:\Program Files (x86)\nodejs  instead of C:\Program Files\nodejs

Is this correct? I thought the default path for 64-bit installers was C:\Program Files\ ?

**Comment by sbmelvin** [comment]
I uninstalled my previous x86 nodejs installation. Now when I run the x64 installer it uses c:\program files\.

**Comment by misterdjules** [comment]
@joyent/node-coreteam Is it the desired behavior that an install of the 64 bits version when a 32 bits is already installed is considered as an upgrade, and thus the target directory is the same as the upgraded version (`C:\Program Files (x86)\` in this case)?

**Comment by misterdjules** [comment]
Adding the confirmed-bug label, even though it's not clear it's a bug.

**Comment by sbmelvin** [comment]
It is unexpected behavior for a 64bit installer to place an application in C:\Program Files (x86)\. If a 64 bit version of node cannot coexist with a 32 bit version of node on the same machine, I think the correct action would be for the installer to ask the user if they wish to uninstall the existing node installation prior to installing the 64 bit version. Otherwise, I think that installing the 64 bit version to C:\Program Files\ (and upgrading any existing 64 bit install) would be the expected behavior.

**Comment by misterdjules** [comment]
@sbmelvin That sounds reasonable to me, thank you :+1: @orangemocha I'm not familiar with how Windows users deploy node on Windows, any thoughts?

**Comment by joaocgreis** [comment]
Fixed by 14db629497d0eb97a5f0fbb70cf3e534e460deec, but this will only work on fresh installs starting from the next release. Thank you!

**Comment by sbmelvin** [comment]
:+1:
