### ISSUE TITLE
v0.12.0 - OSX - File reads and memory safety

### ISSUE THREAD

**Issue by stennettm** [joyent/node#25105]
When providing a buffer larger than the file being read, or the number of bytes being read, an `fs.read` operation fills the buffer with data from memory, potentially exposing memory to an attacker. I imagine these are the bytes in memory immediately following the read data.

I've seen this on 0.12.0 on OSX with both synchronous and asynchronous operations, I have not yet tested other platforms or versions.

Working example:
https://github.com/stennettm/node-memorysafety/blob/master/app.js

**Comment by stennettm** [comment]
This behaviour is also seen on the following:
0.10.33 - OSX
0.10.36 - CentOS

**Comment by jasnell** [comment]
@joyent/node-tsc ... thoughts?

**Comment by indutny** [comment]
Are you sure that it is `fs.read()` that fills the buffer, and not just initial contents of it? What if you will call `buf.fill(0)` before doing `fs.read(..., buf, ....)` ?

**Comment by stennettm** [comment]
That does seem to be the case @indutny, my mistake.
