### ISSUE TITLE
node.js problems on Mac: EACCESS errors

### ISSUE THREAD

**Issue by VanKurt** [joyent/node#25103]
I have freshly installed node.js with the official installer on my Mac (OSX10.10.3).
When trying to add a package, e.g. via "nom install -g cordova ionic" I get a bunch of EACCESS errors (see below).

Shouldn't this work right out of the box?

npm WARN engine cordova-js@3.9.0: wanted: {"node":"~0.10.x"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine npm@1.3.4: wanted: {"node":">=0.6","npm":"1"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN installMany normalize-package-data was bundled with npm@1.3.4, but bundled package wasn't found in unpacked tree
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "cordova" "ionic"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! path ../lib/node_modules/ionic/bin/ionic
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, symlink '../lib/node_modules/ionic/bin/ionic'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, symlink '../lib/node_modules/ionic/bin/ionic']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '../lib/node_modules/ionic/bin/ionic' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/borisbrock/npm-debug.log

**Comment by hertzg** [comment]
`EACCES, symlink '../lib/node_modules/ionic/bin/ionic'`
you need access to ../lib folder for which you dont have permission use `sudo npm install -g whatever_package`

**Comment by VanKurt** [comment]
Do I really need superuser rights to install npm packages?
That doesn't sound right...

Shouldn't node.js/npm use folders that are accessible with basic user rights?

**Comment by hertzg** [comment]
You are trying to install a pacakge globally (the `-g` flag) and it probably wants to link an executable  to your `PATH` directory and your current user does not have permission to it.

**Comment by cjihrig** [comment]
You should avoid using `sudo` to install modules if possible. Here is a tutorial that might help - https://medium.com/@adambretz/su-dont-npm-install-295376e2e5f8

**Comment by Hardik21** [comment]
a
