### ISSUE TITLE
v8: don't busy loop in cpu profiler thread - backport

### ISSUE THREAD

**Issue by tunniclm** [joyent/node#25137]
As described in issue #9439, the profiler consumes 100% of a core on 0.12 when enabled via the CpuProfiler API. This was already improved in 0.10 but the fix did not carry forward correctly to 0.12 due to changes in V8.

I submitted a pull request in #9439 for a fix, but a change has now landed in V8 master for this issue and should probably be backported instead.

The V8 change is https://codereview.chromium.org/1118533003, worked under issue  https://code.google.com/p/v8/issues/detail?id=3967.

**Comment by misterdjules** [comment]
@tunniclm Thank you! Could you please create a PR against the v0.12 branch that backports this change? There are instructions on how to do so in the [wiki](https://github.com/joyent/node/wiki/V8-upgrade-process#how-to-land-a-patch-from-upstream-v8). If they're incomplete, please feel free to suggest improvements.

Adding this to the 0.12.3 milestone, and closing #9439 in favor of this one.

**Comment by tunniclm** [comment]
Note that this backport does not address the problem on Windows, where the coarse scheduler granularity makes it more difficult to make the trade-off between CPU usage and precision.

I would like to investigate some alternatives on Windows (eg: using Sleep(0), SwitchToThread(), or a more significant change involving locking)--it is unclear to me what potential scheduling delays would be introduced by each of these approaches, however.

**Comment by misterdjules** [comment]
@tunniclm Thank you for backporting the change from upstream. What do you mean by:
> Note that this backport does not address the problem on Windows

? Do you mean that on Windows, the profiler still consumes 100%, or that it doesn't but the precision is not as good as before?

**Comment by tunniclm** [comment]
@misterdjules : Yes, on Windows the code busy loops and consumes a core.

**Comment by misterdjules** [comment]
Fixed by https://github.com/joyent/node/commit/80cdae855fe349f0cf3b5c646060e4799107392f, thank you @tunniclm :+1:
