### ISSUE TITLE
 throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by rbbauto** [joyent/node#25265]
no stack trace only this:
events.js:72
        throw er; // Unhandled 'error' event
              ^
server.js 
////////////////////////////////////////////////////////////////////////////////////////////////////////////////
var dgram	=		require("dgram");
var server	=	dgram.createSocket("udp4");
var funcion	=	require("./funciones.js");
var enviar	=	require("./sendUdp.js");

server.on("error", function (err) {
  console.log("server error: " + err.stack);
  server.close();
});

server.on("message", function (msg, rinfo) {

	enviar.sendUdp(rinfo.address,rinfo.port,msg);
	
});

server.on("listening", function () {
  var address = server.address();
  console.log("Servidor Iniciado " +
      address.address + ":" + address.port);
});

server.bind(4096);
////////////////////////////////////////////////////////////////////////////////////////////////////////////////
sendUdp.js 
////////////////////////////////////////////////////////////////////////////////////////////////////////////////
function sendUdp(host,port,trama){
	var dgram 		= 	require('dgram');
	var funcion		= 	require("./funciones.js");
	var BaseDeDatos	= 	require("./mysql.js");
	var HOST 		= 	host;
	var PORT 		= 	4096; // Salida del Server
	

	var tramaAComparar	=	trama.toString().split('*');
	if(funcion.calcChecksum(tramaAComparar[0]) == funcion.buscarChecksum(trama)  ){
	
	var client		= dgram.createSocket('udp4');
		client.bind(PORT);
		
		var msj = '>ACK;' + funcion.ParsearSentencia(trama)[0] +';' 
		+ funcion.ParsearSentencia(trama)[1] + ';';
		var msj_mas_checksum = msj + funcion.calcChecksum(msj) +"<";
		
		var message	= new Buffer(msj_mas_checksum.toString());
		console.log("Servidor Responde: " + msj_mas_checksum);
	
		
		client.send(message, 0, message.length, port, HOST, function(err, bytes) {
		if (err) { throw err;
    }
		client.close();
		delete client.bind;
		console.log('UDP message sent to ' + HOST +':'+ port);
		BaseDeDatos.grabar(funcion.ParsearSentencia(trama.toString()));
		
				}); 
	

		}
	else{
		console.log(trama);
		var tramaAComparar	=	trama.toString().split('*');
		console.log("Error en Checksum Recibido!! " + 
		funcion.calcChecksum(tramaAComparar[0]) + " " +
		funcion.buscarChecksum(trama));
		
		
	}
	
	

}; 
exports.sendUdp = sendUdp; 
////////////////////////////////////////////////////////////////////////////////////////////////////////////////
other files no relevant.
use node v0.10.37

received y send around 180 times then show this:
events.js:72
        throw er; // Unhandled 'error' event
please any help are welcome

**Comment by dnakamura** [comment]
what platform is this on?

**Comment by rbbauto** [comment]
fool on my, windows 7 32b

**Comment by rbbauto** [comment]
funciones.js

function calcChecksum(cmd)
{ 
try{
  /* Calcular la suma de comprobación por XOR
   todos los valores de caracteres en la cadena cmd   */ 
   
  var checksum = 0;
  for(var i = 0; i < cmd.length; i++) {
    checksum = checksum ^ cmd.toString().charCodeAt(i);
  }

  // Convertirlo a hexadecimal 
  var tmp, hexsum = Number(checksum).toString(16).toUpperCase();
  if (hexsum.length < 2) {
    hexsum = ("00" + hexsum).slice(-2);
  }
  return tmp = "*" + hexsum;
}catch(err){
	console.log("Error En Function calcChecksum: " + err);
}
}

function buscarChecksum(chk){
	try{
	var 	 posicion =  chk.toString().indexOf("*");
	return   chk.toString().substring(posicion, posicion + 3);	
	}catch(err){
		console.log("Error en Funcion buscarChecksum: " + err);
	}
} 

function ParsearSentencia(trama){
	try{
	var arrays	=	trama.toString().split(';');	
	var fecha	=	20 + trama.toString().substring(8, 10) + "-" + trama.toString().substring(6,8) + "-" +trama.toString().substring(4,6);
	var hora	=	trama.toString().substring(10,12) + ":" + trama.toString().substring(12,14) + ":" + trama.toString().substring(14,16);
	var latitud	=	trama.toString().substring(16,19) + "." + trama.toString().substring(19,24);
	var longitud =  trama.toString().substring(24,28) + "." + trama.toString().substring(28,33);
	var velocidad = trama.toString().substring(33,36);
	var direccion = trama.toString().substring(36,39);
	var posicion =	trama.toString().substring(39,40);
	var edadDato =	trama.toString().substring(40,42);
	var entradas =	trama.toString().substring(42,44);
	var nroEvento = trama.toString().substring(44,46);
	var prescionHorizontal = trama.toString().substring(46,48);
	var dato	=	trama.toString();
	var res	=		[ fecha, hora, latitud, longitud, velocidad, direccion, posicion, edadDato, entradas, nroEvento, prescionHorizontal, dato];
	var resultado = [arrays[1], arrays[2]].concat(res);

	return resultado;
	}catch(err){
		console.log("Error en Function ParsearSentencia: " + err);
	}
}
exports.calcChecksum = calcChecksum;
exports.buscarChecksum = buscarChecksum;
exports.ParsearSentencia = ParsearSentencia;

**Comment by rbbauto** [comment]
mysql.js

function grabar (trama){
	
	var mysql      = require('mysql');
	var connection = mysql.createConnection({
	host     : 'localhost',
	user     : 'gps',
	password : '14781478',
	database : 'gps'
	});
 
	connection.connect();
	var post  = {id: '', id_equipo: trama[0].substring(3,7) ,fecha_hora: trama[2] + " " + trama[3], fecha_equipo: trama[2], hora_equipo:trama[3] , latitud: trama[4], longitud: trama[5], velocidad: trama[6], direccion: trama[7], entradas: trama[10], trama: trama[13] };
	var query = connection.query('INSERT INTO datogps SET ?', post, function(err, result) {
	if(err){console.log("Mysql Error: " + err);}
	
	});
 
 
	connection.end();
 
}
exports.grabar = grabar;

**Comment by rbbauto** [comment]
try cath  is useless

**Comment by rbbauto** [comment]
win 7 32bits

El 15/05/2015 a las 15:03, dnakamura escibió:

**Comment by dnakamura** [comment]
Interestingly I cant reproduce this on 0.10.37, only 0.13.0-pre, which does print out a stack trace
```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: bind EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at dgram.js:224:28
    at dns.js:85:18
    at process._tickCallback (node.js:355:11)
```
Your problems are occuring in sendUDP.js
```
client.bind(PORT);
```
This throws an error since the server is already bound to port 4096.
This is how it should be implemented.
sendUDP.js:
```
function sendUdp(sock, host,port,trama){
	var funcion = require("./funciones.js");
	var BaseDeDatos = require("./mysql.js");
	var HOST = host;


	var tramaAComparar  =   trama.toString().split('*');
	if(funcion.calcChecksum(tramaAComparar[0]) == funcion.buscarChecksum(trama)  ){
		var msj = '>ACK;' + funcion.ParsearSentencia(trama)[0] +';' 
		+ funcion.ParsearSentencia(trama)[1] + ';';
		var msj_mas_checksum = msj + funcion.calcChecksum(msj) +"<";

		var message = new Buffer(msj_mas_checksum.toString());
		console.log("Servidor Responde: " + msj_mas_checksum);


		sock.send(message, 0, message.length, port, HOST, function(err, bytes) {
			if (err) { throw err;}
			console.log('UDP message sent to ' + HOST +':'+ port);
			BaseDeDatos.grabar(funcion.ParsearSentencia(trama.toString()));
		}); 
	} else {
		console.log(trama);
		var tramaAComparar  =   trama.toString().split('*');
		console.log("Error en Checksum Recibido!! " + 
		funcion.calcChecksum(tramaAComparar[0]) + " " +
		funcion.buscarChecksum(trama));
	}

};
exports.sendUdp = sendUdp; 
```

server.js
```
var dgram = require("dgram");
var server = dgram.createSocket("udp4");
var funcion = require("./funciones.js");
var enviar = require("./sendUdp.js");

server.on("error", function (err) {
console.log("server error: " + err.stack);
server.close();
});

server.on("message", function (msg, rinfo) {

enviar.sendUdp(this, rinfo.address,rinfo.port,msg);

});

server.on("listening", function () {
var address = server.address();
console.log("Servidor Iniciado " +
address.address + ":" + address.port);
});

server.bind(4096);
```

Also, on the client side you don't need to call ```bind()```. As soon as you send data it will automatically bind to an available port.

**Comment by rbbauto** [comment]
ok now im testing you modified. and will let you know as if I work.
P.D: sorry...... my inglish suck

**Comment by rbbauto** [comment]
changes made in server.js & sendUdp.js  not solve the problem.
still show the same:
events.js:72
throw er; // Unhandled 'error' event

and server crash!

**Comment by rbbauto** [comment]
receives y send around 200 times

**Comment by rbbauto** [comment]
>RGP081212110417-3464940-058510600000000029F2501;ID=A001;#0002;*57<
this is what server receives

**Comment by rbbauto** [comment]
make a test whit this same code in other computer whit windows 8 and work fine. then im re install win 7 in the first computer and repeat the test. I'll let you know as I was

**Comment by rbbauto** [comment]
ok. re-install win 7 32bit in 32bit CPU and problem persist
 work fine in : win 7 64bits, win 8, win xp serv.pack2.
but i decide for install Ubuntu. thanks dnakamura for your answer
