### ISSUE TITLE
Cannot set ciphers for TLS client

### ISSUE THREAD

**Issue by iamthechad** [joyent/node#25270]
Setting ciphers for TLS client connections does not seem to work. See the below code.

    var tls = require('tls'),
        net = require('net');

    var options = {
        isServer: false
    };

    var context = tls.createSecureContext({ciphers: 'THIS_IS_NOT_A_CIPHER'});
    var tcpSocket = new net.Socket();
    tcpSocket.connect(443, "www.google.com");
    options.secureContext = context;
    options.socket = tcpSocket;
    var socket = tls.connect(options, function() {
        console.log(socket.getPeerCertificate());
        socket.end();
    });
    socket.setEncoding('utf8');
    socket.on('error', function(error) {
        console.log(error);
    });

This code prints out the peer certificate information for Google instead of raising an error, since `THIS_IS_NOT_A_CIPHER` is clearly not a valid cipher.

Even when I use valid ciphers, I get the same results. If I inspect the SSL handshake using Wireshark, I can see that the Client Hello is providing ~60 ciphers instead of just the one I specified.

I see the expected result in Wireshark if I use openssl directly:

`openssl s_client -cipher AES128-SHA -connect www.google.com:443 -no_ssl2 -no_ssl3`

Given that there is no error for an invalid cipher and the wrong value being used in the SSL handshake for a valid cipher, I would guess there's some issue in either parsing or setting the user-specified `ciphers`.

**Comment by iamthechad** [comment]
After digging through the source code, I've found that I can specify `ciphers` directly when calling `tls.connect()`. This option isn't documented, which is why I went through the whole route of creating a `SecureContext` then a `net.Socket`. If I specify `ciphers` directly into `tls.connect()`, I get the expected behavior.

**Comment by jasnell** [comment]
@iamthechad ... just for reference, which node.js version?

**Comment by iamthechad** [comment]
@jasnell D'oh! This is on 0.12.x, which seems to have had a pretty major reworking of the TLS API.

**Comment by dnakamura** [comment]
As far as I can tell, setting SecureContext is not supported.  It won't throw any errors, but its ignored all the same.

**Comment by iamthechad** [comment]
Setting `secureContext` doesn't work, but setting `ciphers` does. The docs for `tls.connect()` should be updated to reflect this. Can we reuse this issue for that change, or should I open a new one?

**Comment by iamthechad** [comment]
This was fixed via #25325
