### ISSUE TITLE
Documentation error for TLS.connect()

### ISSUE THREAD

**Issue by iamthechad** [joyent/node#25271]
While working on code that let to issue #25270, I found that the docs for `tls.connect()` are incorrect.

It's not specified in the docs, but `secureContext` can be specified on the `options` object.

**Comment by dnakamura** [comment]
Setting secureContext is not supported, see comments on #25270

**Comment by iamthechad** [comment]
Setting `secureContext` is not supported, but setting `ciphers` is. The ability to specify `ciphers` in the `options` object is also missing from the docs. Can we repurpose this issue to address that, or should I open a new one?

**Comment by mhdawson** [comment]
I think its ok to re-purpose this one.

**Comment by iamthechad** [comment]
Fixed via #25325
