### ISSUE TITLE
Upgrade npm to 2.9.1

### ISSUE THREAD

**Issue by misterdjules** [joyent/node#25287]
As discussed with @othiym23 on IRC. This is npm's latest stable release, so if we can get it reasonably soon, we should probably include it in v0.12.3.

@othiym23 I'm creating this issue for tracking, not to add any pressure to your already busy schedule :)

**Comment by trevnorris** [comment]
Sounds good to me.

**Comment by cjihrig** [comment]
+1 from me.

**Comment by misterdjules** [comment]
Fixed by 03cfbd65fb650e2fc8139bd96dc05dbd01f1a2d6.
