### ISSUE TITLE
test-npm does not run properly in 0.12.X stream

### ISSUE THREAD

**Issue by mhdawson** [joyent/node#25290]
Looks like a change in npm 2.8.4 which modified how the test-all target runs has broken test-npm in 0.12.X.

When I checkout, run make node and then make test-npm it fails complaining that npm is not found.  I can see that in npm 2.7.4 (which is in master)  test-all is as follows:

    "test-all": "node ./test/run.js && tap test/tap/*.js",

In 2.8.4 which is in v0.12 it is 

    test-all": "npm run test-legacy && npm test",

which explains why we'd see the npm not found were as we have not seen it previously

Changing test-npm with this patch allows us to run again (although there are still failures in individual tests):

<PRE>
diff --git a/Makefile b/Makefile
index 1629d14..f9c8322 100644
--- a/Makefile
+++ b/Makefile
@@ -158,7 +158,8 @@ test-npm: node
        cd deps/npm ; npm_config_cache="$(shell pwd)/npm-cache" \
             npm_config_prefix="$(shell pwd)/npm-prefix" \
             npm_config_tmp="$(shell pwd)/npm-tmp" \
-            PATH="../../:${PATH}" node cli.js run-script test-all && \
+            PATH="../../:${PATH}" node cli.js run-script test-legacy && \
+            PATH="../../:${PATH}" node cli.js run-script test && \
             PATH="../../:${PATH}" node cli.js prune --prod && \
             cd ../.. && \
             rm -rf npm-cache npm-tmp npm-prefix
</PRE>

**Comment by mhdawson** [comment]
I should possibly be 

<PRE>
diff --git a/Makefile b/Makefile
index 1629d14..f9c8322 100644
--- a/Makefile
+++ b/Makefile
@@ -158,7 +158,8 @@ test-npm: node
        cd deps/npm ; npm_config_cache="$(shell pwd)/npm-cache" \
             npm_config_prefix="$(shell pwd)/npm-prefix" \
             npm_config_tmp="$(shell pwd)/npm-tmp" \
-            PATH="../../:${PATH}" node cli.js run-script test-all && \
+            PATH="../../:${PATH}" node cli.js run-script test-legacy && \
+            PATH="../../:${PATH}" node cli.js run-script tap && \
             PATH="../../:${PATH}" node cli.js prune --prod && \
             cd ../.. && \
             rm -rf npm-cache npm-tmp npm-prefix
</PRE>

to be more consistent with the new test-all. The test and tap targets are the exact same:
<PRE>
"scripts": {
"test-legacy": "node ./test/run.js",
"test": "tap --timeout 120 test/tap/*.js",
"tap": "tap --timeout 120 test/tap/*.js",
"test-all": "node ./test/run.js && tap test/tap/*.js",
"prepublish": "node bin/npm-cli.js prune --prefix=. --no-global && rimraf test/*/*/node_modules && make -j8 doc",
"dumpconf": "env | grep npm | sort | uniq"
},
</PRE>

**Comment by mhdawson** [comment]
Created pull request https://github.com/joyent/node/pull/25294

**Comment by misterdjules** [comment]
Fixed by https://github.com/joyent/node/commit/dbda13abb6e3ed8990ee1a479c421cffb437c8a9, which was included in v0.12.7, so moved to that milestone too.
