### ISSUE TITLE
writable.uncork() does not provide callback

### ISSUE THREAD

**Issue by socketpair** [joyent/node#25292]
`writeable.write()` provides callback, notifying completition of write request (either with error or without). `writable.uncork()`  actually starts writing, but don't provide such callback. I think this is API bug, but can be fixed without breaking current applications (except custom streams....)

**Comment by trevnorris** [comment]
`.uncork()` happens immediately. The callback for the final `.write()` will alert you to when the final write is complete. Can you give an example to what implementation you had in mind?

**Comment by jasnell** [comment]
not particularly convinced we should do this, especially as @trevnorris points out, the callback on `write` still works.

**Comment by socketpair** [comment]
OK, I thought that `write()` callback will fire when data was pushed to the kernel. I thought that `cork()` and `uncork()` is just wrappers over `setsockopt(..., SOL_TCP, TCP_CORK, ...);`.

Now, I understand. It will be nice if you add to documentation that "Callback of last `write()` will fire after calling `uncork()` when data will be sent to network. Call to cork() is never block, and just allows nodejs to continue writing."

**Comment by trevnorris** [comment]
`.uncork()` will immediately flush the queued data to the kernel to be written. A callback passed to `.write()` isn't called until the data has been confirmed to be sent, not just when it's been passed to the kernel.

**Comment by socketpair** [comment]
Hmmm, how you detect that data really sent? we cannot check anything after write() syscall...

**Comment by trevnorris** [comment]
Depending on the reason, it would probably create an `'error'` event on the connection. But the way to tell the data was sent is no different then if you had just done `.write()`.

**Comment by jasnell** [comment]
Assuming this can be closed. Can re-open if necessary
