### ISSUE TITLE
JSON.stringify/parse of Buffers behavior change?

### ISSUE THREAD

**Issue by KaptainKrayola** [joyent/node#25323]
Pre 0.12.2 if you JSON.stringify on a buffer it would give you back an array.  You could then JSON.parse on the array and get back the original Buffer.  It seems now that if you stringify a buffer you get back an object with "type" and "data" keys.  

Is this by design and if so why?  This breaks a bunch of code from other versions expecting to simply get back the original buffer when you JSON.parse it.

**Comment by cjihrig** [comment]
`JSON.parse()` never returned an actual `Buffer` instance. 2cae44f16934836f0a66b2ea930a0604f505e571 added the ability to restore a `Buffer` using `JSON.stringify()` and `JSON.parse()`. For example:

```
$ ./node -v
v0.12.3-pre
$ ./node 
> var b = new Buffer('foo');
undefined
> b;
<Buffer 66 6f 6f>
> var b2 = new Buffer(JSON.parse(JSON.stringify(b)));
undefined
> b2;
<Buffer 66 6f 6f>
```

**Comment by KaptainKrayola** [comment]
You're right, you didn't get back an actually buffer, my fault.  I may not have expressed myself very well in my initial post so i'll try again.

Before 0.12.2 i could take a JSON.stringify and get back - [116,101,115,116,32,116,101,120,116]

Now at 0.12.2 I get back -  {"type":"Buffer","data":[116,101,115,116,32,116,101,120,116]}

So when I do a JSON.parse instead of getting back  (which is how it used to work) -
 [116,101,115,116,32,116,101,120,116]

I get back - 
{ type: 'Buffer',
  data: [ 116, 101, 115, 116, 32, 116, 101, 120, 116 ] }

So anything I have that was relying on it coming back from the JSON.parse as just the array is broken.

I hope this illustrates my problem a little better than my first post.

**Comment by KaptainKrayola** [comment]
I see what you're saying now.  the issue I'm seeing must either be elsewhere or some kind of bug.  Thanks for the clarification.
