### ISSUE TITLE
Recursive child_process.spawn argument split on Windows

### ISSUE THREAD

**Issue by andraaspar** [joyent/node#25339]
# Steps

On Windows 7, 64-bit, Node v0.12.3.

Given this in `test.js`:
```js
var child_process = require('child_process');

process.argv.slice(2).forEach(function(cmd, i) {
	console.log('Executing argument ' + i + ': ' + cmd);
	child_process.spawn('cmd', ['/c', cmd], {stdio: 'inherit'});
});
```
And invoking it like this (Bash style escapes):
```bat
node test.js "node test.js \"echo foo\""
```
or like this (Windows style escapes):
```bat
node test.js "node test.js ""echo foo"""
```
# Output
```bat
Executing argument 0: node test.js "echo foo"
Executing argument 0: "echo
Executing argument 1: foo"
'\"echo' is not recognized as an internal or external command,
operable program or batch file.
'foo\"' is not recognized as an internal or external command,
operable program or batch file.
```
The `"echo foo"` argument was split, the double quotes around it kept.

# Expected output
```bat
Executing argument 0: node test.js "echo foo"
Executing argument 0: echo foo
foo
```

**Comment by piscisaureus** [comment]
On windows - unlike linux - a program receives a *command line* and not an *argument list*.
The possibility to pass an array of arguments lies in the fact that libuv internally converts that to a command line, which (under normal circumstances) is turned back into an argument list by the child process it self (the msvcrt runtime typically takes care of that before invoking `main`).

cmd.exe however uses special rules (see `cmd /?` for more information about that) that are unlike any other program. Hence, relying on the default behavior isn't appropriate as soon as cmd.exe enters the mix. 

For this purpose, node supports a `windowsVerbatimArguments` option that lets you take care of the quoting/escaping; node will simply join all arguments together with a single whitespace character when that option is used. Look at https://github.com/nodejs/io.js/blob/c1de6d249e9b17d53edc0a713c1e43ef9b457ea7/lib/child_process.js#L565-L570 to see how it's done.

Closing this bug as WONTFIX/impossible to fix.

**Comment by andraaspar** [comment]
Thank you for the detailed answer.

I have created a [workaround](https://github.com/andraaspar/node_issue_25339_workaround), which joins all the arguments and parses them into an array. It seems to work for me.

I have looked at the code, but I'm not sure how the `windowsVerbatimArguments` option should be used. Can't find any documentation either.
