### ISSUE TITLE
Error building mongodb on Windows8.1

### ISSUE THREAD

**Issue by rudolfschmidt** [joyent/node#25336]
I get the error

    C:\Users\User\Desktop\test>npm install mongodb
    |

    > kerberos@0.0.11 install C:\Users\User\Desktop\test\node_modules\mongodb\node_m
    odules\mongodb-core\node_modules\kerberos
    > (node-gyp rebuild 2> builderror.log) || (exit 0)

    C:\Users\User\Desktop\test\node_modules\mongodb\node_modules\mongodb-core\node_m
    odules\kerberos>if not defined npm_config_node_gyp (node "C:\Program Files\nodej
    s\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js
    " rebuild )  else (rebuild)
    Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parall
    ele Erstellung zu ermöglichen, müssen Sie den Schalter "/m" hinzufügen.
    C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform
    .Targets(23,7): error MSB8007: Die Plattform für Projekt "kerberos.vcxproj" ist
     ungültig.  Plattform="x64". Diese Meldung wird unter Umständen angezeigt, da e
    in Projekt ohne Projektmappendatei erstellt werden sollte und da eine nicht sta
    ndardmäßige Plattform angegeben wurde, die für das Projekt nicht vorhanden ist.
     [C:\Users\User\Desktop\test\node_modules\mongodb\node_modules\mongodb-core\nod
    e_modules\kerberos\build\kerberos.vcxproj]
    npm WARN installMany nopt was bundled with node-pre-gyp@0.6.4, but bundled packa
    ge wasn't found in unpacked tree
    npm WARN installMany npmlog was bundled with node-pre-gyp@0.6.4, but bundled pac
    kage wasn't found in unpacked tree
    npm WARN installMany request was bundled with node-pre-gyp@0.6.4, but bundled pa
    ckage wasn't found in unpacked tree
    npm WARN installMany semver was bundled with node-pre-gyp@0.6.4, but bundled pac
    kage wasn't found in unpacked tree
    npm WARN installMany tar was bundled with node-pre-gyp@0.6.4, but bundled packag
    e wasn't found in unpacked tree
    npm WARN installMany tar-pack was bundled with node-pre-gyp@0.6.4, but bundled p
    ackage wasn't found in unpacked tree
    npm WARN installMany mkdirp was bundled with node-pre-gyp@0.6.4, but bundled pac
    kage wasn't found in unpacked tree
    npm WARN installMany rc was bundled with node-pre-gyp@0.6.4, but bundled package
     wasn't found in unpacked tree
    npm WARN installMany rimraf was bundled with node-pre-gyp@0.6.4, but bundled pac
    kage wasn't found in unpacked tree
    \
    > bson-ext@0.1.7 install C:\Users\User\Desktop\test\node_modules\mongodb\node_mo
    dules\mongodb-core\node_modules\bson\node_modules\bson-ext
    > (node-pre-gyp install --fallback-to-build) || (node-gyp rebuild 2> builderror.
    log) || (exit 0)

    C:\Users\User\Desktop\test\node_modules\mongodb\node_modules\mongodb-core\node_m
    odules\bson\node_modules\bson-ext>if not defined npm_config_node_gyp (node "C:\P
    rogram Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-g
    yp\bin\node-gyp.js" clean )  else (clean)

    C:\Users\User\Desktop\test\node_modules\mongodb\node_modules\mongodb-core\node_m
    odules\bson\node_modules\bson-ext>if not defined npm_config_node_gyp (node "C:\P
    rogram Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-g
    yp\bin\node-gyp.js" configure --fallback-to-build --module=C:\Users\User\Desktop
    \test\node_modules\mongodb\node_modules\mongodb-core\node_modules\bson\node_modu
    les\bson-ext\build\Release\bson.node --module_name=bson --module_path=C:\Users\U
    ser\Desktop\test\node_modules\mongodb\node_modules\mongodb-core\node_modules\bso
    n\node_modules\bson-ext\build\Release --msvs_version=2012 )  else (configure --f
    allback-to-build --module=C:\Users\User\Desktop\test\node_modules\mongodb\node_m
    odules\mongodb-core\node_modules\bson\node_modules\bson-ext\build\Release\bson.n
    ode --module_name=bson --module_path=C:\Users\User\Desktop\test\node_modules\mon
    godb\node_modules\mongodb-core\node_modules\bson\node_modules\bson-ext\build\Rel
    ease --msvs_version=2012 )

    C:\Users\User\Desktop\test\node_modules\mongodb\node_modules\mongodb-core\node_m
    odules\bson\node_modules\bson-ext>if not defined npm_config_node_gyp (node "C:\P
    rogram Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-g
    yp\bin\node-gyp.js" build --fallback-to-build --module=C:\Users\User\Desktop\tes
    t\node_modules\mongodb\node_modules\mongodb-core\node_modules\bson\node_modules\
    bson-ext\build\Release\bson.node --module_name=bson --module_path=C:\Users\User\
    Desktop\test\node_modules\mongodb\node_modules\mongodb-core\node_modules\bson\no
    de_modules\bson-ext\build\Release )  else (build --fallback-to-build --module=C:
    \Users\User\Desktop\test\node_modules\mongodb\node_modules\mongodb-core\node_mod
    ules\bson\node_modules\bson-ext\build\Release\bson.node --module_name=bson --mod
    ule_path=C:\Users\User\Desktop\test\node_modules\mongodb\node_modules\mongodb-co
    re\node_modules\bson\node_modules\bson-ext\build\Release )
    Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parall
    ele Erstellung zu ermöglichen, müssen Sie den Schalter "/m" hinzufügen.
    C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform
    .Targets(23,7): error MSB8007: Die Plattform für Projekt "bson.vcxproj" ist ung
    ültig.  Plattform="x64". Diese Meldung wird unter Umständen angezeigt, da ein P
    rojekt ohne Projektmappendatei erstellt werden sollte und da eine nicht standar
    dmäßige Plattform angegeben wurde, die für das Projekt nicht vorhanden ist. [C:
    \Users\User\Desktop\test\node_modules\mongodb\node_modules\mongodb-core\node_mo
    dules\bson\node_modules\bson-ext\build\bson.vcxproj]
    gyp ERR! build error
    gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
    ` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
    npm\node_modules\node-gyp\lib\build.js:269:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
    :12)
    gyp ERR! System Windows_NT 6.3.9600
    gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
    les\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Use
    rs\\User\\Desktop\\test\\node_modules\\mongodb\\node_modules\\mongodb-core\\node
    _modules\\bson\\node_modules\\bson-ext\\build\\Release\\bson.node" "--module_nam
    e=bson" "--module_path=C:\\Users\\User\\Desktop\\test\\node_modules\\mongodb\\no
    de_modules\\mongodb-core\\node_modules\\bson\\node_modules\\bson-ext\\build\\Rel
    ease"
    gyp ERR! cwd C:\Users\User\Desktop\test\node_modules\mongodb\node_modules\mongod
    b-core\node_modules\bson\node_modules\bson-ext
    gyp ERR! node -v v0.12.3
    gyp ERR! node-gyp -v v1.0.3
    gyp ERR! not ok
    node-pre-gyp ERR! build error
    node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-
    to-build --module=C:\Users\User\Desktop\test\node_modules\mongodb\node_modules\m
    ongodb-core\node_modules\bson\node_modules\bson-ext\build\Release\bson.node --mo
    dule_name=bson --module_path=C:\Users\User\Desktop\test\node_modules\mongodb\nod
    e_modules\mongodb-core\node_modules\bson\node_modules\bson-ext\build\Release' (1
    )
    node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\User\Desktop\t
    est\node_modules\mongodb\node_modules\mongodb-core\node_modules\bson\node_module
    s\bson-ext\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
    node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
    node-pre-gyp ERR! stack     at maybeClose (child_process.js:1015:16)
    node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_proces
    s.js:1087:5)
    node-pre-gyp ERR! System Windows_NT 6.3.9600
    node-pre-gyp ERR! command "node" "C:\\Users\\User\\Desktop\\test\\node_modules\\
    mongodb\\node_modules\\mongodb-core\\node_modules\\bson\\node_modules\\bson-ext\
    \node_modules\\node-pre-gyp\\bin\\node-pre-gyp.js" "install" "--fallback-to-buil
    d"
    node-pre-gyp ERR! cwd C:\Users\User\Desktop\test\node_modules\mongodb\node_modul
    es\mongodb-core\node_modules\bson\node_modules\bson-ext
    node-pre-gyp ERR! node -v v0.12.3
    node-pre-gyp ERR! node-pre-gyp -v v0.6.4
    node-pre-gyp ERR! not ok
    Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\Users\User
    \Desktop\test\node_modules\mongodb\node_modules\mongodb-core\node_modules\bson\n
    ode_modules\bson-ext\build\Release\bson.node --module_name=bson --module_path=C:
    \Users\User\Desktop\test\node_modules\mongodb\node_modules\mongodb-core\node_mod
    ules\bson\node_modules\bson-ext\build\Release' (1)

    C:\Users\User\Desktop\test\node_modules\mongodb\node_modules\mongodb-core\node_m
    odules\bson\node_modules\bson-ext>if not defined npm_config_node_gyp (node "C:\P
    rogram Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-g
    yp\bin\node-gyp.js" rebuild )  else (rebuild)
    Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parall
    ele Erstellung zu ermöglichen, müssen Sie den Schalter "/m" hinzufügen.
    C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform
    .Targets(23,7): error MSB8007: Die Plattform für Projekt "bson.vcxproj" ist ung
    ültig.  Plattform="x64". Diese Meldung wird unter Umständen angezeigt, da ein P
    rojekt ohne Projektmappendatei erstellt werden sollte und da eine nicht standar
    dmäßige Plattform angegeben wurde, die für das Projekt nicht vorhanden ist. [C:
    \Users\User\Desktop\test\node_modules\mongodb\node_modules\mongodb-core\node_mo
    dules\bson\node_modules\bson-ext\build\bson.vcxproj]
    mongodb@2.0.31 node_modules\mongodb
    ├── readable-stream@1.0.31 (isarray@0.0.1, inherits@2.0.1, string_decoder@0.10.3
    1, core-util-is@1.0.1)
    └── mongodb-core@1.1.26 (kerberos@0.0.11, bson@0.3.2)

    C:\Users\User\Desktop\test>

**Comment by devlo** [comment]
and why do you think it's node fault..? You should write that on mongodb issue tracker.

**Comment by rudolfschmidt** [comment]
Its not the first time node get such errors in smiliar fields like installing mongoose in the past or some python dependecies issues. I guess its also a node problem, isnt?

**Comment by devlo** [comment]
Is this moongose or mongodb issue tracker? If you can't build/install application on some platform for example on Win 8.1, is that microsoft fault ?
Do you even know what you pasted? and what failed? Because it clearly shows what did. Google and your own brain are your best friends, just use them.

**Comment by cjihrig** [comment]
I'm going to close this for now. Please try to resolve this on the issue tracker of the relevant module(s). If it is determined that a bug exists in Node core, we can reopen this. Thanks.
