### ISSUE TITLE
Nodejs Multer event fire issue 

### ISSUE THREAD

**Issue by nurASingh** [joyent/node#25331]
Hi , 

I am using multer module for upload some files to server.
I facing issue while uploading the file. 
Please find the details below.
1. Server Environment  ( Unix - Embedded )
var express = require('express');
var multer = require('multer');
var app = express();
var destFolder = './uploads';
app.use(multer({
		dest : destFolder,
		rename : function (fieldname, filename) {
			return filename;
		},
		onFileUploadStart : function (file) {
			console.log('Starting ' + file.name);
		},
		onFileUploadData : function (file, data) {
			console.log('Recieving Data');
		},
		onFileUploadComplete : function (file) {
			console.log('Completed file!');
		},
		onParseStart : function () {
			console.log('Starting to parse request!');
		},
		onParseEnd : function (req, next) {
			console.log('Done parsing!');
			next();
		},
		onError : function (e, next) {
			if (e) {
				console.log(e.stack);
			}
			next();
		}
}));
app.post('/upload', [multer({
			dest : './uploads/'
		}), function (req, res) {
			res.status(204).end()
		}
	]);

2. Client Side - ( Windows - Chrome Browser / Chrome POSTMAN extension)
	<div id= "developmentMode" class="developmentMode">
			<form id        =  "uploadForm"
				 enctype   =  "multipart/form-data"
				 action    =   "/upload"
				 method    =  "post"
				 class = "formupload"
			>
			<input type="file" name="userwidget"/>
			<input type="submit" id="submitBtn" class="btn btn-primary" value="Upload Widget" name="submit">
			</form>

	</div>

3.Result -
onFileUploadComplete and onError - Never got fired.

output -
node framework.js
Starting to parse request!
Starting main.js
Recieving Data

Starting to parse request!
Starting main.js
Recieving Data

4- System Info
a ) OS - Unix embeded
b)  RAM 2GB

**Comment by jasnell** [comment]
Please direct module specific questions to that module's repository: https://github.com/expressjs/multer
