### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by waqasmughal** [joyent/node#25332]
every one need to parallel http request handling rather then in series . mostly we use library like gogo_thread or webworker etc . why not make default behaviour of multiple parrallel request .

**Comment by cjihrig** [comment]
Is this something you could use the async module for?

**Comment by waqasmughal** [comment]
yes !!! but native approach better than  like behaviour of webworker auto utilize multi core and do parrallel task rather then  use clustering

**Comment by jasnell** [comment]
Since (a) there are userland solutions for this and (b) there is work ongoing within the io.js stream to implement workers (https://github.com/nodejs/io.js/pull/1159), recommend closing this. I doubt that it's something we're going to land in the v0.x stream

**Comment by clayendisk** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  james.ryan.stortz@gmail.com
    Domain clayendisk.net has exceeded the max emails per hour (32/30 (106%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192]:46543 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by us-tx-cp01.imbahost.com with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.85)
	(envelope-from <noreply@github.com>)
	id 1YuOw0-0018AL-0Z
	for {}@clayendisk.net; Mon, 18 May 2015 12:34:36 -0500
Date: Mon, 18 May 2015 10:34:38 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1431970478;
	bh=4heUUd/VReyjMz2t62tEq/wkv2he7NX+3CO2XTmfWpE=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=aIsN0kQAHYs4OIhkPBSPtzSBT4k5ix5NQjaduMzHSKV8W8dvU0RIWh/bIdzfsTObU
	 WZdrSgmaaeMrFGeu7jFNAf+jYwsIYmCpTJJ0vV6sDOCuUHHihlOI94/PYuN8hAsWGe
	 yLON423ArJf0nEGZRzUrhJ4tE17Kd+swhsATkum4=

**Comment by jasnell** [comment]
Closing in favor of the pending io.js work.
