### ISSUE TITLE
ECONNREFUSED thrown after TypeError on load

### ISSUE THREAD

**Issue by derrelldurrett** [joyent/node#25333]
While trying to debug a problem I'm having loading my Cucumber project, I hit the following bug:

    debug> .There was an internal error in Node's debugger. Please report this bug.
    connect ECONNREFUSED
    Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:983:19)

I'm running the debugger thusly:
    >node debug C:\Users\ddurrett\AppData\Roaming\npm\node_modules\cucumber\bin\cucumber.js

This happens consistently after my code hits a TypeError, and the the debugger then produces the following output:

     <long stack trace ignored>
     program terminated
     program terminated
     program terminated
     program terminated
     program terminated
     program terminated
     program terminated
     program terminated
     program terminated
     program terminated

If there's other information that would be useful please let me know.

**Comment by dnakamura** [comment]
what platform & version are you running?

**Comment by derrelldurrett** [comment]
Sorry! Windows 7, and node v0.12.0.

-- Derrell Durrett

**Comment by dnakamura** [comment]
Can you throw up some sample code to help reproduce?

**Comment by derrelldurrett** [comment]
Apologies for the radio silence. I'm not hitting this error if the code I'm running doesn't throw an Error.

If I simply do ```spine app test-app```, and then add a file world.coffee:

    nock= require 'nock'
    Hem= require 'hem'
    App= new Hem
    App.server()
    
    class World
      @apiMock = nock("http://localhost")
      constructor: ->

    module.exports.World= World

, it fails as follows:

    C:\Users\ddurrett\projects\test-app>node debug C:\Users\ddurrett\AppData\Roaming\npm\node_modules\cucumber\bin\cucumber.js
    < Debugger listening on port 5858
    connecting to port 5858... ok
    break in C:\Users\ddurrett\AppData\Roaming\npm\node_modules\cucumber\bin\cucumber.js:2
       1
    > 2 var Cucumber = require('../lib/cucumber');
       3 var cli = Cucumber.Cli(process.argv);
       4 cli.run(function (succeeded) {
    debug> c

    < 0 scenarios
    < 0 steps
    program terminated
    program terminated
    program terminated
    program terminated 
    program terminated
    program terminated
    program terminated
    program terminated
    program terminated
    program terminated
    debug> .There was an internal error in Node's debugger. Please report this bug.
    connect ECONNREFUSED
    Error: connect ECONNREFUSED
        at exports._errnoException (util.js:746:11)
        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:983:19)

Does that help? ```spine``` is [Spine.js](http://spinejs.com), which otherwise works as expected.

**Comment by dnakamura** [comment]
Looks like it was fixed in v0.12.3
```
program terminated
program terminated
program terminated
program terminated
program terminated
program terminated
program terminated
program terminated
program terminated
debug> . failed, please retry
program terminated
debug>
```
Node versions affected: v0.12.0
Platforms affected: windows
High priority/critical category: no
recommended priority: P3
Existing io.js issue: N/A
Pull request included: no
Reproducible: yes
Exists in later version: v0.12.1, v0.12.2
@joyent/node-coreteam

**Comment by mhdawson** [comment]
@derrelldurrett can you validate if it is resolved in v0.12.3/v0.12.4 and if so close

**Comment by derrelldurrett** [comment]
At the moment, ‘npm update node' does nothing (Windows 7). When I can
upgrade, I will verify.

-- Derrell Durrett

**Comment by derrelldurrett** [comment]
I don't see it in 0.12.4.

**Comment by derrelldurrett** [comment]
And thanks for your help!
