### ISSUE TITLE
node v0.12.2 vs v0.12.3 uptate v8 or downgrade?

### ISSUE THREAD

**Issue by kevin2r** [joyent/node#25344]
v0.12.2  V8 version: 3.28.73.0
v0.12.3  V8 version: 3.28.71.19

**Comment by csvan** [comment]
See https://github.com/joyent/node/issues/25324

**Comment by misterdjules** [comment]
@kevin2r It can be considered as a downgrade, or as an update depending on your perspective. More details here: https://github.com/joyent/node/issues/9241. In other words, the previous version of V8 was taken from the same branch as the one shipped in v0.12.3, but the one in v0.12.3 is the one that ended up being the "stable" version for this branch.

Closing, but feel free to add more comments if you have any question.
