### ISSUE TITLE
Fat arrow functions with `call` and `apply`

### ISSUE THREAD

**Issue by mjesun** [joyent/node#25340]
I've observed the following behavior:

```
> a = () => { console.log(this === global); }
[Function]

> a()
true

> a.call({})
false
```

AFAIK, the fat arrow method should always preserve the lexical "this" value, even if called by using `call` or `apply` (at least, this is how it is stated [in the MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Invoked_through_call_or_apply)). Based on that, I think the value of the second call (`a.call({})`) should still be true, since at the moment of defining the function, `this` had the value of `global`).

Currently running node v0.12.0 with the `--harmony` flag.

**Comment by cjihrig** [comment]
Assuming that MDN is in line with the official specification, this does seem like a bug to me. Unfortunately, this is out of our control. You can try reporting this to the V8 team. There is a chance that it is already fixed in newer versions of V8, however it is still present in io.js 2.0.2, using V8 4.2.77.20. You should also be aware that using features hidden behind a flag is generally not advised, as they are not deemed complete.

**Comment by jasnell** [comment]
Closing as it does not appear to be a node issue.

**Comment by clayendisk** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  james.ryan.stortz@gmail.com
    Domain clayendisk.net has exceeded the max emails per hour (30/30 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:52734 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by us-tx-cp01.imbahost.com with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.85)
	(envelope-from <noreply@github.com>)
	id 1YuOtk-00185G-Vz
	for {}@clayendisk.net; Mon, 18 May 2015 12:32:17 -0500
Date: Mon, 18 May 2015 10:32:19 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1431970339;
	bh=g7y6jmISFK/T2Ko+VarkkGHH5XMzt83fHIFPybzrBUs=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Y7Sbz/822gzh2KyN2H/i74YEfI9ktW2D/BIm8itWwJ90okJqqUH1FMbRptQIEpXOn
	 jSeXyA7B/YZL2UjrpqCNtJ7Fv746KoFwR5wKi7BVcTHujhJZHc8/dFp9x5XmvNmug9
	 DsEG6UnLixbCZaOqjzxS/vvNfNSSqNYA0Dp9lUKk=
