### ISSUE TITLE
Streams: Is the .on('data', ...) same as .pipe(..., { end: false}) ?

### ISSUE THREAD

**Issue by edin-m** [joyent/node#25343]
I have read about streams multiple times and I have tried and made some of my own small streams.

I have created stream of zeroes (with buffers) that are sent over TCP on TCP client's command.
Stream is generated by readable stream.

However if I use:

    conn.zeroStream = new ZeroStream(size);
    conn.zeroStream.on('data', function(data) { conn.write(data); });

memory usage goes to infinity with OS shutting down the process.

And if I use 

    conn.zeroStream.pipe(conn, { end: false });

I get no memory performance issues.
Am I misunderstanding streams or is this potentially real memory leak.

https://gist.github.com/edin-m/2c1391e36a0ee6a9c084

**Comment by rlidwka** [comment]
I suspect that `pipe()` slows ZeroStream down requesting data only when it's needed. But `on('data')` callback fires as soon as any data is available. Thus, in case of `on('data')` you'll get 100mb of zeroes all at once, but with `pipe()` you'll generate zeroes when previous data is sent over the wire.

I see no memory leak there, just an inefficient use of the memory. It should get freed up when tcp connection is closed.
