### ISSUE TITLE
timers: recursive setImmediate/setTimeout with Error argument causes memory leak

### ISSUE THREAD

**Issue by ex1st** [joyent/node#25346]
```javascript
// Run with --expose-gc

(function runTest() {
	setImmediate(runTest, new Error(1));
}());


setInterval(function() {
	gc();
}, 100);
```

After few seconds, a process's memory usage grows up to 1.4GB. And after some time, a process will fail with error: "FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
Aborted (core dumped)".

In case of passing other objects (like a "new Foo()" or "new Date()") into arguments such behavior is not occurred.

**Comment by dnakamura** [comment]
What version/platform are you running?

**Comment by ex1st** [comment]
Hello, @dnakamura.

Ubuntu 14.04.2 LTS.
v0.10.38/v0.12.3/io.js 2.0.2

**Comment by dnakamura** [comment]
Node versions affected: 0.10.38
Platforms affected: Linux (ubuntu 14.04)
High priority/critical category: no
recommended priority: P-2
Existing io.js issue: N/A
Pull request included: no
Reproducible: yes
Exists in later version: 0.12.3
@joyent/node-coreteam

**Comment by dnakamura** [comment]
This is expected. Creating an Error object captures a stack trace (which includes arguments passed into the function).  Each call to ```runTest``` gets passed the error object (and hence references to all the previous error objects). Since all the objects have active references none of them can be garbage collected

**Comment by mhdawson** [comment]
@dnakamura that looks right to me.   The following code shows that each Error object has a reference to the previous one, thus keeping the whole chain alive:

<PRE>
// sequence number to be able to identify error objects by
var i = 0;

(function runTest(theError, second) {
   // replace the prepareStackTrace function so we can
   // get access to info maintained in Error
   Error.prepareStackTrace = function(error, structuredStackTrace) {
                                 return (structuredStackTrace[0].getFunction()).arguments[0] }

   // increment the counter for the current call.
   i++;

   // create new Error object with the current sequence
   var newError = new Error(i);

   // call runTest with new Error identified current seq in i.
   setImmediate(runTest, newError);

   if (theError != undefined) {
     // Since we have replaced prepareStackTrace, newError.stack
     // returns the first argument to the first function on the call stack
     // In this case it turns out to be the previous Error object
     // For example:  Error: 1344:Error: 1345
     // therefore we see that each Error object has a reference
     // to the previous one and therefore none of them ever
     // get collected
     console.log(newError.stack + ":" + newError);
   }
} ());

setInterval(function() { gc() }, 100);
</PRE>

It's also consistent with the report that we only see it when we pass in Error objects, as its only in this case where the Object contains a reference to an the arguments

**Comment by mhdawson** [comment]
@ex1st  if you agree with the assessment can you please close the issue.

**Comment by ex1st** [comment]
@dnakamura @mhdawson.
Thank you! It make sense.
