### ISSUE TITLE
Version 0.12.3 x86 and x64 Windows installer problem

### ISSUE THREAD

**Issue by EskelCz** [joyent/node#25351]
I'm stuck in a weird situation. I have previous version of node installed on my windows 7. When I run the latest installer (both 86 and 64), I get 'Invalid drive E' alert and installation aborts.
When I map a virtual drive to E:, it ends with 'The volume E:\ is currently unavailable. Please select another.'.

At no point do I get to choose installation path. Also I'm having problem uninstalling the previous version, it crashes with ''node_modules' is not a valid short file name.'. That is possibly a separate issue but it leaves me stuck with no way to go.

**Comment by dnakamura** [comment]
Did you ever have stuff installed on the E:\ drive?
This is odd since I also ran the latest installer (x64) on win 7 and it did give me the option of selecting the location. 2 suggestions first check the registry to see if ```HKCU\Software\Node.js\InstallPath``` points the the correct place. If that fails, maybe try forcing the install path with
```msiexec /i "c:\path\to\install.msi" TARGETDIR="C:\path\to\node" ```

**Comment by EskelCz** [comment]
That's it, my installation path was set to 'E:\NodeJS\'. No idea why, I never had it mounted. Thanks a lot.

**Comment by EskelCz** [comment]
It doesn't complete thought, I'm getting that 'node_modules in not a valid short file name.' error, same as the uninstall.

**Comment by EskelCz** [comment]
It was a ton of wrong paths in HKLM/SOFTWARE/Microsoft/Windows/CurrentVersion/Installer/Folders/

**Comment by EskelCz** [comment]
still the same thing :(

**Comment by dnakamura** [comment]
is it just the latest version, or does it also happen with older installers?

**Comment by EskelCz** [comment]
I got it working with a pretty large registry cleanup. Somehow a ton of node_modules got registered to E:\, no idea how. Then it failed silently (no error but said it didn't complete successfully) but node -v says the correct version. So I guess I'm fine. Thank you for helping me out.

**Comment by dnakamura** [comment]
no problem

**Comment by AdrianoLG** [comment]
Removing in both places: `HKCU\SOFTWARE\Node.js` and `HKLM\SOFTWARE\Node.js` worked for me. Thanks!
