### ISSUE TITLE
npm update is failed all the time

### ISSUE THREAD

**Issue by Kushi171987** [joyent/node#25361]
Attached the screen shot what I got when i run the npm update. Each time when I run npm update I got this issue. Not exactly sure to fix it.

 
![screen shot 2015-05-22 at 1 10 29 am](https://cloud.githubusercontent.com/assets/6594820/7757372/66deac26-001f-11e5-9cad-f24675aadfb2.png)

**Comment by KenanY** [comment]
@Kushi171987 Issues with `npm` should be opened at its own repository: [npm/npm](https://github.com/npm/npm). Could you upload the _entire_ `npm-debug.log` as a [gist](https://gist.github.com)? Posting only a portion of an entire log is [usually not enough](https://github.com/npm/npm/wiki/Contributing-Guidelines#a-great-bug-report-contains) to fully diagnose an issue.

**Comment by jasnell** [comment]
Does not appear to be a node issue. Can reopen if additional information demonstrates otherwise.
