### ISSUE TITLE
Assertion failed then Abort trap: 6 with node 0.11.0-0.12.3 on OS X 10.10.3

### ISSUE THREAD

**Issue by matthewadams** [joyent/node#25369]
After making some changes in a feature branch to a known working app, I started getting the following error:
```
Assertion failed: (handle->type == UV_TCP || handle->type == UV_TTY || handle->type == UV_NAMED_PIPE), function uv___stream_fd, file ../deps/uv/src/unix/stream.c, line 1528.
Abort trap: 6
```
After the error, `node` immediately exits, so I'm dead in the water.  This happens every time I start `node`.

I'm trying to figure out which change is causing this, but wanted to get the issue on the radar in the meantime and could use some help.  This is happening on all versions of `node` from 0.11.0 through 0.12.3 on Mac OS X Yosemite 10.10.3.

My code is private (client project), so I can't share. :(  Any advice on how to start narrowing this down?  Debugging tools like those in other similar issues?

**Comment by jasnell** [comment]
The only way to narrow it down is to have a test case we can use to reproduce the behavior.

**Comment by matthewadams** [comment]
Sorry, no can do.  I took another approach & got around it.  It's still sitting in a branch, but it's private code.  Closing issue.
