### ISSUE TITLE
x86 Ubuntu Compile Error - v0.12.3

### ISSUE THREAD

**Issue by EngineeringMode** [joyent/node#25380]
Trying to compile on x86 Ubuntu machine on EC2 fails. This seems to still be an issue that was never resolved... #14422

**Comment by jasnell** [comment]
Is the failure output the same as that reported in #14422?

**Comment by mhdawson** [comment]
Adding to James comment are you compiling in the same way ?  Does trying to build using a 

+ clone
+ .configure
+ make 

work ?

**Comment by EngineeringMode** [comment]
I eventually compiled it successfully on x86 v0.12.3. This issue may be localized to linuxbrew.
