### ISSUE TITLE
Clang helps to detect 3 errors in src /udp_wrap.cc in UDPWrap::OnRecv

### ISSUE THREAD

**Issue by socketpair** [joyent/node#25462]
`char* base = static_cast<char*>(realloc(buf->base, nread));`

1. `nread` may be zero. in that case undefined behaviour occur. (in linux, memory is just freed)
2. After that call, `buf->base` may become garbage, since realloc may return different pointer.
3. realloc() may return NULL

**Comment by dnakamura** [comment]
1. As far as I can tell if  ```nread``` is zero, behavior is defined to do what you say (free memory).
2. Potentially not an issue? I need to see where the original ```buff->base``` comes from, but since a new buffer is being made from ```base``` we may no longer care about ```buff->base```
3. Yes, this one could potentially be an issue (assuming ```nread``` > 0, other wise I'm not so sure). Although I believe the only time this happens if there is not enough memory (which shouldnt happen since we are shrinking the buffer), or if ```nread``` = 0. In the case of the latter, since we are creating a buffer of size 0, its pointer should really be irrelevant.

**Comment by socketpair** [comment]
1. On other OS, memory is not freed : https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man3/realloc.3.html 
2. Seems someone forgot to write `buf->base = base` after realloc
3. It is not specified at which conditions realloc may return NULL.

**Comment by dnakamura** [comment]
1. Ah, I was looking at the [POSIX docs] (http://pubs.opengroup.org/onlinepubs/009695399/functions/realloc.html), which states that the memory is freed. Looks like OSX does still free the memory, but  then allocates more. 
2. I would agree ,but I need to check the lifetime of that pointer. If we just discard it later without referencing it, its not really an issue
3.  The [POSIX docs] (http://pubs.opengroup.org/onlinepubs/009695399/functions/realloc.html) (which should mirror the ISO C spec), does specify when this happens.  namely:

> Upon successful completion with a size not equal to 0, realloc() shall return a pointer to the (possibly moved) allocated space. If size is 0, either a null pointer or a unique pointer that can be successfully passed to free() shall be returned. If there is not enough available memory, realloc() shall return a null pointer and set errno to [ENOMEM].

**Comment by socketpair** [comment]
"not enough available memory" is not specified ;) it may be no free space for internal job. i.e. ENOMEM may occur while shrinking [in a common case]. As you see in man pages, no one guarantee that shrinking is always succeeded.

**Comment by dnakamura** [comment]
So after a bit of digging I've come to the following conclusion:
1. If ```nread``` is 0, program will behave as expected. ```realloc`` will free the buffer and return a pointer to a new minimum size object. This new pointer is then used to create a buffer (of size 0). The pointer will be freed when the buffer is destroyed.
2. If ```realloc``` moves the buffer, ```buff->base``` will be garbage, however its not an issue as it never gets used again anyway.
3. If ```realloc``` fails, we end up with a memory leak, and end up creating a buffer with a null pointer.  

Of the 3, only #3 is an issue. Since we are always shrinking the size of the buffer, a simple solution would be to revert to the old value of ```base->buff```

**Comment by sam-github** [comment]
If the buffer is always shrinking, how can realloc fail?

**Comment by mhdawson** [comment]
Resolved by https://github.com/joyent/node/pull/25534.  Closing please re-open if this is incorrect.
