### ISSUE TITLE
node.js error on gitbash

### ISSUE THREAD

**Issue by sarveshpatel** [joyent/node#25473]
![new picture 2](https://cloud.githubusercontent.com/assets/12411241/7959020/ce0428de-0a12-11e5-9d26-3beec681c619.jpg)

I am trying to work on gitbash with node and npm  but something like error on here 
please help me

**Comment by KenanY** [comment]
@sarveshpatel This looks like an issue with your `npm` configuration. This issue tracker is for bugs in Node.js core.
