### ISSUE TITLE
Completely disable automatic GC

### ISSUE THREAD

**Issue by jshkurti** [joyent/node#25478]
I would like to disable automatic GC and do it manually with `--expose-gc`.
Is it possible ?

**Comment by jasnell** [comment]
@piscisaureus @bnoordhuis

**Comment by jshkurti** [comment]
I guess not.
`--gc-interval` was a good candidate but apparently it is a no-op in V8 releases. (only used in dev)

**Comment by jasnell** [comment]
Completely disabling is not possible afaik

**Comment by jshkurti** [comment]
Yep, although setting -`-gc-interval` to a huge value would be kinda a workaround. Too bad it doesn't work.

**Comment by jshkurti** [comment]
I'm closing this. Thanks for your quick response.
