### ISSUE TITLE
installation error on windows 

### ISSUE THREAD

**Issue by vikram06** [joyent/node#25487]
I was try install node.js on my windows.but i getting error message.

**Comment by vikram06** [comment]
<a href='http://postimg.org/image/ca96lq56v/' target='_blank'><img src='http://s23.postimg.org/ca96lq56v/node_js_error.jpg' border='0' alt="node js error" /></a>

**Comment by vikram06** [comment]
Why was closed this issue??? Already fixed??

**Comment by Fishrock123** [comment]
Please try to put as much info as possible into the issue post, it;s the only way we can help you. :)

Always paste error logs if you have them!

*note: I'm not really of help for the issue itself

**Comment by vikram06** [comment]
unable to install node.js 0.12.4 on my windows 8.i has getting error message "required media1.cab or check internet connection or corrputed file installer " ...already posted the issue image
