### ISSUE TITLE
Nominating new collaborators to this repository

### ISSUE THREAD

**Issue by misterdjules** [joyent/node#25481]
I believe this is something new in this repository, so please keep this in mind while we're going through this process the first time.

It's been a very long time since we haven't had new collaborators joining the project although a lot of people have contributed significantly to it. This repository recently adopted parts of the proposed policy for the Node.js Foundation TSC. One of the items that was adopted is the process by which [new collaborators are added to the project](https://github.com/nodejs/dev-policy#collaborators). That allows us to add new collaborators in a more open and transparent way, and I think now is a good time to give it a try.

It's not clear to me yet if joyent/node will still be used to merge changes into the v0.10 and v0.12 branches after the convergence between the io.js and node.js repositories is complete, but in any case I believe adding new collaborators to this repository in the meantime is beneficial. I also think that having these additional collaborators even after the two repositories converge will be useful.

Because the two projects are merging, I think that eventually we would add almost if not all the iojs collaborators as collaborators to this project. However to keep the number of new collaborators manageable for the first round, I would like to first do it on a case by case basis. Depending on how things go with this first round, we can adjust this process.

Any collaborator who would be added to this project would also be added as collaborators to the converged project.

I would like to nominate:
* @othiym23 for his continuous support and work around anything related to npm.
* @sam-github for his work on a lot of bugs and issues, especially related to cluster.
* @shigeki for his contributions to handling security related issues.
* @tunniclm for his help in handling advanced V8 issues.
* @joaocgreis for his help with advanced Windows issues.

If you're nominated, please let @joyent/node-tsc know if you'd like to accept the nomination.

More information about what becoming a collaborator means is available in [the contributing section of nodejs.org](https://nodejs.org/contribute/becoming_collaborator.html).

/cc @joyent/node-tsc @mikeal @Fishrock123 @piscisaureus @rvagg

**Comment by Fishrock123** [comment]
Please see https://github.com/nodejs/io.js/issues/1552 :) (I suggest we close and move this there to avoid confusion)

Also, we already have (30+ collaborators)[https://github.com/orgs/nodejs/teams/collaborators], which are [all listed in the readme](https://github.com/nodejs/io.js#current-project-team-members). :D

Specifically, @othiym23, @sam-github, and @shigeki are already collaborators.

The process is still a bit rough though, and @chrisdickinson hasn't gotten time to do an onboarding (short call) recently. Myself, I possibly could, but I'm not so confident / comfortable with that yet.

**Comment by Fishrock123** [comment]
(Also, the collaborators on io.js will also get access here at some point, I think the plan was to be after we have the fiddly git-bits in place.)

**Comment by Fishrock123** [comment]
> Because the two projects are merging, I think that eventually we would add almost if not all the iojs collaborators as collaborators to this project. However to keep the number of new collaborators manageable for the first round, I would like to first do it on a case by case basis. Depending on how things go with this first round, we can adjust this process.

Actually, this will be the fifth round. We've had some practice. :)

**Comment by Fishrock123** [comment]
Oh, I thought this was on the nodejs/node repo, sorry @misterdjules. I suggest we do a similar thing, and possibly onboard to io.js / nodejs and then give people who want access back here that access. :)

**Comment by shigeki** [comment]
I'm very glad to join here as a collaborator in joyent/node where I made my first contribution to Node years ago.

**Comment by rvagg** [comment]
On the io.js side, we've been fairly active in trying to on-board new collaborators and have a large and growing group, and we're brining that in to the Foundation. On the joyent/node side however this is still a work-in-progress and I'm very keen to see valuable contributors here be raised up to both collaborator and even TSC level in the Foundation so we have a broad representation and an even more diverse collection of people and viewpoints.

Ultimately it'd be great if we could have a single group of collaborators @ https://github.com/orgs/nodejs/teams/collaborators that are managing across the 3 repos that we'll all be managing together. Obviously there will be different priorities amongst the group so people will gravitate to the repos that are most important to them.

**Comment by mikeal** [comment]
Also, keep in mind that the collaborator team on `nodejs/io.js` is also on `nodejs/node`.

**Comment by chrisdickinson** [comment]
:clap: This is great. I'd love to swap onboarding notes at some point, @misterdjules!

**Comment by orangemocha** [comment]
Side question: are there any obstacles to moving this repo to the nodejs org? Mentions don't seem to work across orgs. I think it would be a whole lot smoother if the same sets of teams could collaborate on all the node.js repos.

**Comment by joaocgreis** [comment]
@joyent/node-tsc I'm very happy to accept the nomination and become a collaborator!

**Comment by tunniclm** [comment]
@joyent/node-tsc I will gladly accept the nomination.

**Comment by othiym23** [comment]
As a side note to the procedural stuff, I'm happy to participate more directly on the nodejs side of things in whatever capacity the Node.js collaborators and the TSC deem useful. Thanks for the thought, @misterdjules!

**Comment by misterdjules** [comment]
@mikeal 

> Also, keep in mind that the collaborator team on nodejs/io.js is also on nodejs/node.

OK, if I understand correctly nodejs/node is not yet ready to receive any contribution outside of the merging process, so I would assume it's not really important to add the remaining joyent/node collaborators to @nodejs/collaborators right now, but it will need to be done as soon as it becomes ready. We can do some additional onboarding to update collaborators from joyent/node who are not familiar with the nodejs/node workflow at that time. Sounds good?

@chrisdickinson Yes please, and thank you for the suggestion! Maybe we can continue that conversation via email, or is there a place where I can find your notes?

@orangemocha Great question, although I think it would help to have this discussion in a separate issue, otherwise I can imagine this issue being very confusing with different discussions.

@shigeki @joaocgreis @tunniclm @othiym23 Thank you very much for your patience and support, I'll get back to you with further info soon.

**Comment by sam-github** [comment]
I missed this earlier, thanks for the thoughts, I'd be happy to contribute to this repo as I am able.

**Comment by misterdjules** [comment]
@sam-github Great!

@sam-github @othiym23 @shigeki @tunniclm @joaocgreis The next step is to go through the onboarding process where I'll give you an introduction to how the team of collaborators works together. We will do that via a remote call with Google Hangouts or anything that works for you.

Here's a doodle so that you can let me know what your availabilities are: doodle.com/3n73wswhqwxd4i3reamw3rc2. You should probably reserve an hour just to be safe.

Thank you!

**Comment by Fishrock123** [comment]
@misterdjules depending on the time, if you don't mind, I may want to attend to get a feel how to do/improve the process, would that be ok? :)

**Comment by misterdjules** [comment]
@Fishrock123 Of course! There might be more than one meeting though because everyone might not be available at the same time slot.

**Comment by misterdjules** [comment]
@othiym23 @sam-github Whenever you have some time, please let me know what would be a good time to have the onboarding call here: https://github.com/joyent/node/issues/25481#issuecomment-110943195. Thank you again :+1:

**Comment by shigeki** [comment]
@misterdjules I've joined node-collaborator but I can not set a label and milestone to my PR. Could you look at my privilege?

**Comment by sam-github** [comment]
@misterdjules I don't know if doodle notified you, I added my availabilities.

**Comment by misterdjules** [comment]
@shigeki Looking into that right now!

@sam-github Just sent you a meeting invite, thank you!

**Comment by misterdjules** [comment]
@joaocgreis Are you able to set labels and add issues/PRs to milestones?

**Comment by misterdjules** [comment]
@shigeki It should be fixed now, my apologies for the confusion.

**Comment by joaocgreis** [comment]
@misterdjules I can, it seems ok. Thanks

**Comment by shigeki** [comment]
@misterdjules It's fine. Thanks.

**Comment by misterdjules** [comment]
@joaocgreis @shigeki Can you guys also mention @joyent/node-tsc? I remember during the onboarding meeting that @shigeki couldn't do that.

**Comment by shigeki** [comment]
@joyent/node-tsc I try it. But it still seems to be a private team members and viewed as 404.

![node-tc](https://cloud.githubusercontent.com/assets/782880/8223218/4ec9172e-15b0-11e5-8fd5-4ff086f8c08c.png)

**Comment by mikeal** [comment]
When GitHub migrated to the new org permissions all teams became "secret" so you'll have to go through each one and make it public if you want it back to where it was. I had to do that for the nodejs org, it was a pain in the ass :)

**Comment by misterdjules** [comment]
@mikeal Thank you for the heads up! I don't see how to make a team "public" in the organization management UI. I looked in GitHub's help and I haven't seen any mention of that, would you mind giving more details on how to make a team public?

**Comment by mikeal** [comment]
Org -> "Teams" link -> Click the relevant team -> Click "Settings" -> Set to "Visible"

You can also go right to a team settings page with https://github.com/orgs/{org}/teams/{team}/edit

**Comment by misterdjules** [comment]
@mikeal It seems I don't have any "visible" setting in that team, or any other team, I'll check with GitHub what's going on. Thanks again!

**Comment by mikeal** [comment]
Maybe you weren't migrated to the new permissions :(

**Comment by othiym23** [comment]
@misterdjules Sorry I didn't get back to you last week – I got home from NodeConf and promptly came down with a cold that mostly kept me out of action last week. If I can, I'd like to get this done this week, because my schedule starts to get pretty crowded soon.

**Comment by misterdjules** [comment]
@othiym23 I'll be traveling for work until Thursday night. I'm available Friday all day though. Here's a doodle for you to let me know your availabilities on Friday: http://doodle.com/pqg2sn6bvugmpg3i. Let me know if Friday doesn't work, and we'll add other dates to this doodle.

Thank you!

**Comment by mikeal** [comment]
Update: I think you might not be able to mention teams from other orgs :(

**Comment by jasnell** [comment]
Going to assume it's safe to close this one.
