### ISSUE TITLE
Update libuv to 1.6.0

### ISSUE THREAD

**Issue by dbkaplun** [joyent/node#25488]
This new version of libuv fixes one particular issue that made the TTY completely unusable on OSX since Node 0.11.13. See libuv/libuv#304. It would be great if libuv could be upgraded to 1.6.0 with the next release of Node!

**Comment by Fishrock123** [comment]
Note: uv@1.6.1 is out (but only fixes an issue with uv_os_homedir on windows xp)

**Comment by cjihrig** [comment]
The Windows XP fix is in 1.6.0. The 1.6.1 release actually fixes an issue with FreeBSD, where huge amounts of memory were being allocated by `uv_os_homedir()`.

**Comment by misterdjules** [comment]
@dbkaplun Thank you for the request :+1: It's already tracked by https://github.com/joyent/node/pull/25475 which is scheduled to be shipped with node v0.12.5, so I'll close it as a duplicate of that PR.
