### ISSUE TITLE
Node/express function result sent to index.html

### ISSUE THREAD

**Issue by furytingle** [joyent/node#25499]
Im kinda new to nodejs. I have running icecast server on localhost and found node-icy module, which has .get method to get  song title
var icy = require('icy');

icy.get('http://localhost:8002/dno', function(res){
    res.on("metadata", function(metadata){
        var parsed = icy.parse(metadata);
    });
});
very simple but i dont know how to send the title i retrieve to index.html(or ejs) rendered by res.render. Whole other code is generated by Webstorm/express. I suggest myself very dumb in this kind of situation.

**Comment by sam-github** [comment]
Hi, this question isn't related to node.js directly, could you please direct your question to the author of icy, which you can find on npmjs.org: https://www.npmjs.com/package/icy
