### ISSUE TITLE
Node.js memory usage issue

### ISSUE THREAD

**Issue by viddeshshinde** [joyent/node#25519]
I have created https server using https module. When I hit the server with the requests and run the 'top' command, I can see the memory usage goes on increasing with the subsequent requests. After the server becomes idle the memory usage does't go down, it remains constant as maximum used. If I hit another bunch of transactions again it goes on increasing and stays at same size. 
Is this a normal behaviour of Node.js or there is a memory leak issue in my code?

**Comment by ChALkeR** [comment]
https://github.com/nodejs/io.js/issues/1522
https://github.com/nodejs/io.js/pull/1529

**Comment by viddeshshinde** [comment]
Thanks. I have tried a simple http server example as - 

var http = require("http");

http.createServer(function(req,res){
    res.end('hell world');
}).listen(9999);

Even this code if pumped  with transactions the memory usage goes on increasing. I understand that app  
uses memory and keep it for further use, so don't release it. If we hit requests again then it should be reused, but it keeps on increasing and increasing. 

Is there any way to know whether the application is reusing the memory?
What is highest memory limit node.js uses after which memory is released?

**Comment by ChALkeR** [comment]
What are your exact rss/heapUsed values?

**Comment by viddeshshinde** [comment]
Thanks. I am much clear about it. 

I have tested my code with hitting 1000 requests and concurrency of 10 it works fine but if I increase concurrency to 1000 I see there is a memory leak. I have used memwatch module for tracing it. 

Output:
start: Fri Jun 12 2015 19:59:08 GMT+0530 (IST),
  end: Fri Jun 12 2015 19:59:43 GMT+0530 (IST),
  growth: 4127384,
  reason: 'heap growth over 5 consecutive GCs (35s) - 404.86 mb/hr' }

1. Why does memory leak occurs only when concurrency of requests is increased?
2. How could I know exact parts of the code which causes the leak? 
3. Can you explain in short the output pasted above of the memwatch when found a leak?

**Comment by ChALkeR** [comment]
What's your absolute rss/heapTotal/heapUsed values after those requests?

**Comment by viddeshshinde** [comment]
Hello,

Following are the values before hitting the 1000 concurrent requests and after all the requests are served:

start
mem Usage :  { rss: 77012992, heapTotal: 32171264, heapUsed: 11939824 }

end
mem Usage :  { rss: 252735488, heapTotal: 72670976, heapUsed: 31140224 }

Can you then suggest me how to make sure the code is not leaking out anywhere?

**Comment by ChALkeR** [comment]
Is that https or http?

**Comment by viddeshshinde** [comment]
Its https.

**Comment by ChALkeR** [comment]
@viddeshshinde The above testcase was http-based.
Please share your https-based testcase and node/io.js version.
If you are running anything lower than iojs 2.0.0, your code is probably suffering from https://github.com/nodejs/io.js/issues/1522

**Comment by viddeshshinde** [comment]
The values pasted above are https-based testcase. I am using node v0.10.33.

**Comment by jasnell** [comment]
Closing as there does not appear to be anything to do here.
