### ISSUE TITLE
Node.js - Call a system or external command interactively

### ISSUE THREAD

**Issue by hacdias** [joyent/node#25525]
Hello there!

I've an issue with Node.js. With Python, if I wanted to execute an external command, I used to do something like this:

```python
import subprocess
subprocess.call("bower init", shell=True)
```

I've read about ```child_process.exec``` and ```spawn``` in Node.js but I can't do what I want. And what's I want?

I want to execute an external command (like ```bower init```) and see its output in real time and interact with that program itself. The only thing I can do is receive the final output but that don't allow me to interact with the program.

The best regards =D

**Comment by caspervonb** [comment]
`child_process.spawn` is what you want in this case?

**Comment by hacdias** [comment]
@caspervonb thanks. I figured out how to to this :)
