### ISSUE TITLE
String(symbol) throws TypeError

### ISSUE THREAD

**Issue by mjethani** [joyent/node#25520]
```console
$ node -p 'String(Symbol())'
[eval]:1
String(Symbol())
       ^
TypeError: Cannot convert a Symbol value to a string
    at String (native)
    at [eval]:1:8
    at Object.exports.runInThisContext (vm.js:74:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:460:26)
    at evalScript (node.js:431:25)
    at startup (node.js:90:7)
    at node.js:814:3
```

According to the [specification](http://wiki.ecmascript.org/doku.php?id=harmony:specification_drafts), it should do the same thing as `Symbol().toString()`.

**Comment by mjethani** [comment]
It turns out this is already fixed in v8: https://github.com/v8/v8-git-mirror/commit/6b660f2812d09ab35c46dbb32aeb52c21b65b896

**Comment by jasnell** [comment]
Given the down-level v8 in use, this is not likely to be fixed in v0.12 unless the V8 fix can be backported and floated. @domenic ... have any thoughts? @mjethani ... is this an issue for you in practice or can you just use `Symbol().toString()` for now?

**Comment by mjethani** [comment]
@jasnell not an issue for me in practice right now.

**Comment by jasnell** [comment]
OK closing then. Will pick it up in the converged.
