### ISSUE TITLE
`require.extensions` deprecation + development tools

### ISSUE THREAD

**Issue by impinball** [joyent/node#25526]
`require.extensions` has been deprecated since mid-2013, but it is still relied heavily upon by mainly development tools. Production code doesn't use it for obvious reasons (performance, etc.), but tools like Gulp, Grunt, and even compilers/transpilers provide hooks into `require.extensions` to allow people to transpile on the fly instead of compiling their build scripts.

It removes a language barrier for one-off scripts, where you can use CoffeeScript to download some page off the internet, or write your Gulpfile in TypeScript instead of JavaScript. Also, Babel's `babel-node` Node binary replacement uses `require.extensions` to transpile on the fly and use Node's runtime instead of running its own interpreter. CoffeeScript, LiveScript, React's JSX compiler, and many other transpilers/compilers have this feature as well. Two years after its deprecation, it's still invaluable for people writing development tools.

The community knows it's bad practice to use this feature in production. It slows things down tremendously. Babel is the only transpiler AFAIK that caches the output of its `require.extensions` hook, which means the startup is slowed down further by every other transpiler I've encountered.

Given its incredible usefulness in development environments and the fact removing this could break much of the ecosystem, could the deprecation be removed?

**Comment by sam-github** [comment]
This has been brought up repeatedly, but always rejected. However, note

> Since the Module system is locked, this feature will probably never go away. However, it may have subtle bugs and complexities that are best left untouched.

- https://iojs.org/api/all.html#all_require_extensions

I'd suggest bringing this up in nodejs/io.js if you want to reopen this issue, and perhaps search for the previous issues discussing this.
