### ISSUE TITLE
Weekly meeting schedule

### ISSUE THREAD

**Issue by misterdjules** [joyent/node#25537]
@joyent/node-collaborators

Although there has been [discussions about moving our weekly call to the LTS weekly call and using a different time slot](https://github.com/nodejs/LTS/issues/6), we haven't agreed on a new day and time yet, so let's have our call at the usual time tomorrow (Thursday) at 9:00am PDT.

@shigeki I apologize because I know that time slot is not convenient for you. We'll do our best to provide you with meeting minutes after the meeting is over so that you can catch up and ask any question you may have.

@joyent/node-collaborators If you're not available or have any comment or suggestion, please let us know.

Thank you!

**Comment by shigeki** [comment]
@misterdjules No problem. I will catch up and follow by reading minutes. Please free to call me to join if requested.

**Comment by misterdjules** [comment]
@joyent/node-collaborators Meeting minutes are available here: https://github.com/joyent/node-website/pull/139.

**Comment by misterdjules** [comment]
@joyent/node-collaborators Closing, but please fill out the doodle here: http://doodle.com/myb9svwvuuake76x so that we can schedule LTS meetings asap.

**Comment by misterdjules** [comment]
@joyent/node-tsc @joyent/node-collaborators The goal is to start having meetings with the LTS working group and move our weekly call to that one [next Monday](https://github.com/nodejs/LTS/issues/6#issuecomment-114271493). However, I would like to have a call to talk about joyent/node this week, since we have a lot on our plate and new releases coming up soon hopefully.

So we'll have our last meeting as joyent/node this Thursday at the usual time (9:00am PDT), and starting from next week on Monday, we'll transition to the LTS weekly call.

Sounds good?

**Comment by jasnell** [comment]
:+1:

**Comment by orangemocha** [comment]
:+1:

**Comment by misterdjules** [comment]
@joyent/node-collaborators @joyent/node-tsc I want to apologize sincerely, since it turns out I won't be able to make this meeting. My flight time was changed recently and I didn't take into account that I'm currently in a different timezone, and so I didn't realize until now that I will be heading to the airport at 9:00am PDT tomorrow (Thursday), when the meeting starts.

I still think there's some value in having that meeting if we can gather enough people. Here are the things I wanted to talk about:

* v0.12.5 and v0.10.39 were released at the beginning of this week with upgrades to OpenSSL. While doing the v0.10.39 release, I ran into build issues related to WiX and the new `custom_actions` Visual Studio project, and I submitted a fix with https://github.com/joyent/node/pull/25569. All remaining issues/PRs in the 0.12.5 and 0.10.39 milestones were moved to the 0.12.6 and 0.10.40 milestones repectively. The 0.10.41 and 0.12.7 milestones were also created to add issues we plan to fix after the next upcoming releases.

* I finally had some time to start to put back together the changes that @jasnell and @mhdawson worked on regarding removing RC4 from the default ciphers list in v0.10. I hope to be able to send a PR for that on Friday.

* As discussed during our previous weekly call, [I created a separate issue to discuss the list of breaking changes between v0.12.x and what would be the converged repository's master when convergence is completed](https://github.com/nodejs/LTS/issues/10). I would be happy if we could get more eyes on this.

* Recently an issue has been brought up about [users downloading a completely different installer when downloading the nodejs msi installer from the website](https://github.com/joyent/node/issues/25531). I landed [a PR about enabling HTTPS for all download links on the website](https://github.com/nodejs/nodejs.org/pull/127, thanks @fhemberger!) to try to get more information about what could be happening, hoping that users who can reproduce this problem would now get an invalid certificate error, or an error/warning that would allow us to better understand what's going on. That lead me to creating [an issue about having a better user experience around verifying downloads](https://github.com/nodejs/nodejs.org/issues/144).

* For the next upcoming releases we have a few security related issues to consider: https://github.com/joyent/node/issues/25366, https://github.com/joyent/node/pull/25564, https://github.com/joyent/node/issues/25562 and https://github.com/joyent/node/issues/25366. I would like to make sure there's no redundancy here and that these issues are added to the proper milestones (some of them don't belong to one).  Also, let's make sure we're not breaking existing users' code without providing an acceptable alternative (like a command line option/environment variable to still enable the old behavior).

* The next meeting will be on Monday, and at that time our weekly call will have transitioned to the LTS weekly call. Please make sure that, if you're interested in participating to that meeting, you got an invite from me and the time slot works for you.

That's all I had, I want to apologize again for pushing to have that meeting and not being able to attend it. Hopefully this update helps!

Thank you!

**Comment by orangemocha** [comment]
It seems that the discussion around some of those agenda items would be more productive with input from @misterdjules . Does it make sense to reschedule?

**Comment by jasnell** [comment]
I'm good with rescheduling.

**Comment by jasnell** [comment]
Ok, decided to reschedule for next week.

**Comment by misterdjules** [comment]
Ok, just to make sure everyone is on the same page, starting from Monday there won't be any weekly call about joyent/node on Thursdays anymore. I will add these topics to the agenda for the first LTS working group meeting this Monday.
