### ISSUE TITLE
Node.js concurrency issue

### ISSUE THREAD

**Issue by viddeshshinde** [joyent/node#25538]
I have created node.js https server. When i hit the server with 100 requests at concurrency of 1 then the response is given in very less time say 0.100 sec. As I increase the concurrency lets say 100 concurrent requests, response time goes on increasing until the last request is served. It goes on increasing on subsequent requests and it reaches upto 7-8 secs to give response till the end. Doesn't node.js handle the concurrent requests?

**Comment by manikawnth** [comment]
node.js is by design single-threaded  as it is event-oriented and handles events by asynchronous call backs. So it is efficient within that single-thread. But if you want to use other cores of processors invoking single thread for each, you need to go for node.js clustering

**Comment by viddeshshinde** [comment]
I understand that node.js is single threaded by design and handles async events using callbacks. I have tested using clusters and found significance amount of difference in the performance but not as expected. 

I have read some articles where people using node.js implement 10k - 20k transactions per second. Is that they have very highly configured hardware using multiple cores on multiple machines?


The incoming requests to my server hits the mysql database at least for 5-6 times. Does mysql holds down the transactions in the queue because what I see from the traces is that mysql queries give the result delayed.

**Comment by manikawnth** [comment]
All the drivers of node.js (including MySQL) follow node's async call backs. So once a DB request is made out, a call back is registered as well. So the processor doesn't hold up the resources but processes then next event in the queue. 
Ultimately at processor level it is always synchronous. So there should be something in your code which is CPU intensive, so it is not able to complete concurrent requests. May be you can post piece of code which you feel is problematic.
Also remember when you use clustering, it is not necessary that every request is served on a different core atleast for windows. What is your server? 'coz cluster scheduling policy is not easily controlled on windows

**Comment by viddeshshinde** [comment]
This is the part of the server code. Do you see anything wrong with this code or any good practice that could be followed?

function RunServers() {
        options.passphrase = passphrase[0];
        // Running the server
        log.info("MOB port(s) : ", mobport); // ['1234','8888','7777','6666']
        mobport.forEach(function (port) {

            var s = https.createServer(options,
                function onapprequest(request, response) {
                    log.info("onapprequest()");
                    
                    // Check if the method used is POST in http request
                    if (request.method == 'POST') {
                        var body = '';
                        var chkdata;
                        request.on('data', function (chunk) {
                            body += chunk;
                        });
                        request.on('end', function () {
                            
                            // Parsing the data from POST method to JSON
                            try {
                                json = JSON.parse(body);
                                jsonbool = true;
                            } catch (e) {
                                
                                log.info("could not parse the incoming " +
                                         "request");
                                
                            }
                            PreProcessing();
                            function PreProcessing() {
                                // some processing...
                                }
                            }
                        });
                    }
                }).listen(port);
            servers.push(s);

        });
        
        log.info("server started listening...");
    }

**Comment by misterdjules** [comment]
It doesn't seem, at least for now, that it's an issue with Node.js' core. Please use the [Node.js Google group](https://groups.google.com/forum/#!forum/nodejs) or [StackOverflow](http://stackoverflow.com/questions/tagged/node.js) to ask this question.

If it turns out to be a bug in Node.js itself, then please add a comment here to reopen the issue and provide the information mentioned here: https://nodejs.org/contribute/#index_md_reporting_an_issue.

Thank you!
