### ISSUE TITLE
does require call #inspect automatically?

### ISSUE THREAD

**Issue by sandro-pasquali** [joyent/node#25548]
Not sure what to make of this. If I define a module like so:
```
module.exports = {
        inspect: function() { return {a:1} },
        something: function() { return 'something'; }
}
```
and `require('./path/to/module.js')`
I get
`{ a: 1}`
After removing the `inspect` method:
`{ something: [Function] }`

No problem w/ avoiding the `inspect` "keyword", but is this documented anywhere?

0.12.4 btw (also: io.js 2.3.0)... and doesn't happen w/ 0.10.35

**Comment by oimou** [comment]
Aren't you using console.log to print it? console.log uses custom `inspect` method when printing resulting string. console.dir bypasses the custom `inspect` method.
https://nodejs.org/api/console.html#console_console_dir_obj_options

**Comment by sandro-pasquali** [comment]
Using the REPL (> require('...')) but same thing in the end -- thanks for the info! As mentioned this wasn't occurring with the 0.10 line of Node, so this new behavior surprised me.
