### ISSUE TITLE
REPL multiline output

### ISSUE THREAD

**Issue by BenjaminVanRyseghem** [joyent/node#25553]
I would be very nice if `"foo\nbar" could be printed as

```
foo
bar
```

instead of

```foo\nbar```

Same goes for `\t`

**Comment by jasnell** [comment]
@BenjaminVanRyseghem ... can you provide a test case that demonstrates the behavior?

**Comment by BenjaminVanRyseghem** [comment]
I am not sure what you are precisely asking for but maybe those screenshot will help

- Terminal:
![screen shot 2015-06-23 at 08 18 51](https://cloud.githubusercontent.com/assets/407891/8300028/8c174b18-1980-11e5-8d4d-92a4ac542ed1.png)

- node
![screen shot 2015-06-23 at 08 19 06](https://cloud.githubusercontent.com/assets/407891/8300031/92ecdca0-1980-11e5-9862-42f58597266d.png)

The use case is that I am writing a custom repl, and I would like to format the output to be on multiple lines

**Comment by jasnell** [comment]
Ah.. you want to use console.log. The way you're doing it here, the REPL is just echoing back the result of the expression. try `console.log('foo\nbar')`

**Comment by BenjaminVanRyseghem** [comment]
ok, and how can I achieve this in my own custom repl?

can I provide `custom.log` as writer, or?
