### ISSUE TITLE
Typo in example of util.deprecate() documentation

### ISSUE THREAD

**Issue by danielrentz** [joyent/node#25559]
Example at https://nodejs.org/api/util.html#util_util_deprecate_function_string reads
```javascript
exports.puts = exports.deprecate(function() { ...
```
but should read
```javascript
exports.puts = util.deprecate(function() { ...
```

**Comment by misterdjules** [comment]
@danielrentz Good catch :+1: Do you have some time to contribute a pull request to fix that?

**Comment by danielrentz** [comment]
Never did that before. Will read the docs and try... :)

**Comment by danielrentz** [comment]
> If you are interested in contributing to Node.js, please first read the [contribution guide](https://nodejs.org/documentation/contribute/).

gives a 404... :-(

**Comment by jasnell** [comment]
Have an open PR to land this. Closing this issue. Will land the PR shortly.
