### ISSUE TITLE
Add interface to control max size of readline history

### ISSUE THREAD

**Issue by kovidgoyal** [joyent/node#25577]
Curerntly the max size of the history array is hardcoded as 30. There should be some way to set a per interface custom history size limit.

**Comment by jasnell** [comment]
This would be useful but it's not likely to land in v0.12. The best place to raise this would over in nodejs/io.js or nodejs/node. A PR would be appreciated and if it lands there, we'll pick it up in the converged stream.

**Comment by kovidgoyal** [comment]
Thanks, this is already present in io.js, so I guess I just have to wait :)
