### ISSUE TITLE
How to disable warning: unused variable [-Wunused-const-variable]

### ISSUE THREAD

**Issue by haosdent** [joyent/node#25574]
Hello, how to avoid  warning: unused variable 'xxx' [-Wunused-const-variable].
I try add to "-Wno-unused-const-variable" to "cflags" and "cflags_cc", but it could not work.

**Comment by jasnell** [comment]
@haosdent ... I'm sorry, it's not exactly clear from this what you're asking. Can you provide additional detail please.

**Comment by haosdent** [comment]
Oh, sorry for submit the issue in error path.
