### ISSUE TITLE
Not able to upgrade node in ubuntu

### ISSUE THREAD

**Issue by priyankshah217** [joyent/node#25575]
I was trying to upgrade node with latest one. but it was failing.

 brew upgrade node
==> Upgrading 1 outdated package, with result:
node 0.12.5
==> Upgrading node
==> Downloading https://nodejs.org/dist/v0.12.5/node-v0.12.5.tar.gz
curl: (60) error setting certificate verify locations:
  CAfile: /usr/share/centrifydc/apache/certs/ca-certs.crt
  CApath: none

More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). The default
 bundle is named curl-ca-bundle.crt; you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
Error: Failed to download resource "node"
Download failed: https://nodejs.org/dist/v0.12.5/node-v0.12.5.tar.gz

Thanks,
Priyank Shah

**Comment by dnakamura** [comment]
Sounds more like a issue with your local config. Do you have appropriate file permissions on /usr/share/centrifydc/apache/certs/ca-certs.crt ?

**Comment by jasnell** [comment]
Closing as this does not appear to be an issue with node. Can reopen if necessary.

**Comment by priyankshah217** [comment]
Updated ca-certs.crt files at '/usr/share/centrifydc/apache/certs/'. and issue resolved.
