### ISSUE TITLE
Arrays are using too much memory?

### ISSUE THREAD

**Issue by JTallis** [joyent/node#25584]
I am running my scripts on a Debian server supporting only 512MB of RAM. I am also running various other processes such as Apache, PHP-FPM and three node processes but I still believe too much memory is being consumed by an array. According to `ps aux | less`, the PHP-FPM pools use fairly little Memory as does Apache. The node processes added together use up less than 25%. I'm no mathematician but approximately I'd say 50% of the RAM is already being consumed.

I have a file called Trivia.txt which has a total of 19MB of data and also 276929 lines. I place this in an array. If I do this 4 times, the 4th time is typically a bit slower but what also happens is that it runs out of memory and will kill another node process.

This is the code that I run:

    fs = require('fs');

    var array1 = fs.readFileSync(__dirname + '/Trivia.txt').toString().trim().split("\n");
    console.log('1');

    var array2 = fs.readFileSync(__dirname + '/Trivia.txt').toString().trim().split("\n");
    console.log('2');

    var array3 = fs.readFileSync(__dirname + '/Trivia.txt').toString().trim().split("\n");
    console.log('3');

    var array4 = fs.readFileSync(__dirname + '/Trivia.txt').toString().trim().split("\n");
    console.log('4');

I also do get some messages inside the system messages too. The first message appears as if it's node that was the killer and it killed another process.

    1788 Jun 27 13:37:04 web kernel: [26319390.344305] node invoked oom-killer: gfp_mask=0x201da, order=0, oom_adj=-17,      oom_score_adj=-1000
    1789 Jun 27 13:37:04 web kernel: [26319390.344855] node cpuset=/ mems_allowed=0
    1790 Jun 27 13:37:04 web kernel: [26319390.345110] Pid: 15464, comm: node Not tainted 3.2.0-4-amd64 #1 Debian 3.2.5     4-2
    1791 Jun 27 13:37:04 web kernel: [26319390.345593] Call Trace:
    1792 Jun 27 13:37:04 web kernel: [26319390.345823]  [<ffffffff810b742a>] ? dump_header+0x78/0x1bd
    1793 Jun 27 13:37:04 web kernel: [26319390.346112]  [<ffffffff81164a56>] ? security_real_capable_noaudit+0x40/0x4f
    1794 Jun 27 13:37:04 web kernel: [26319390.346588]  [<ffffffff810b726f>] ? oom_unkillable_task+0x5b/0x91
    1795 Jun 27 13:37:04 web kernel: [26319390.346890]  [<ffffffff8134fdc7>] ? _raw_spin_unlock_irqrestore+0xe/0xf
    1796 Jun 27 13:37:04 web kernel: [26319390.347202]  [<ffffffff810b77f3>] ? oom_kill_process+0x49/0x271
    1797 Jun 27 13:37:04 web kernel: [26319390.347498]  [<ffffffff810b7eee>] ? out_of_memory+0x2ea/0x337
    1798 Jun 27 13:37:04 web kernel: [26319390.347792]  [<ffffffff810bbb85>] ? __alloc_pages_nodemask+0x629/0x7aa
    1799 Jun 27 13:37:04 web kernel: [26319390.348135]  [<ffffffff8119a6ed>] ? blk_flush_plug_list+0x1b9/0x1c8
    1800 Jun 27 13:37:04 web kernel: [26319390.348446]  [<ffffffff810e5246>] ? alloc_pages_current+0xc7/0xe4
    1801 Jun 27 13:37:04 web kernel: [26319390.348765]  [<ffffffff810b6b2f>] ? filemap_fault+0x24f/0x33e
    1802 Jun 27 13:37:04 web kernel: [26319390.349100]  [<ffffffff810ced10>] ? __do_fault+0xc8/0x3ac
    1803 Jun 27 13:37:04 web kernel: [26319390.349394]  [<ffffffff810d12c7>] ? handle_pte_fault+0x298/0x79f
    1804 Jun 27 13:37:04 web kernel: [26319390.349695]  [<ffffffff810ce7d5>] ? set_pmd+0x5/0x8
    1805 Jun 27 13:37:04 web kernel: [26319390.349971]  [<ffffffff810cf89f>] ? __pte_alloc+0x87/0x11e
    1806 Jun 27 13:37:04 web kernel: [26319390.350260]  [<ffffffff810ce865>] ? pte_offset_kernel+0x16/0x35
    1807 Jun 27 13:37:04 web kernel: [26319390.350562]  [<ffffffff81352d2e>] ? do_page_fault+0x320/0x345
    1808 Jun 27 13:37:04 web kernel: [26319390.350861]  [<ffffffff810d670c>] ? mmap_region+0x353/0x44a
    1809 Jun 27 13:37:04 web kernel: [26319390.351155]  [<ffffffff81350365>] ? async_page_fault+0x25/0x30
    1810 Jun 27 13:37:04 web kernel: [26319390.351454] Mem-Info:
    1811 Jun 27 13:37:04 web kernel: [26319390.351671] Node 0 DMA per-cpu:
    1812 Jun 27 13:37:04 web kernel: [26319390.351915] CPU    0: hi:    0, btch:   1 usd:   0
    1813 Jun 27 13:37:04 web kernel: [26319390.352217] Node 0 DMA32 per-cpu:
    1814 Jun 27 13:37:04 web kernel: [26319390.352469] CPU    0: hi:  186, btch:  31 usd:  30
    1815 Jun 27 13:37:04 web kernel: [26319390.352744] active_anon:107839 inactive_anon:5933 isolated_anon:0
    1816 Jun 27 13:37:04 web kernel: [26319390.352745]  active_file:0 inactive_file:15 isolated_file:0
    1817 Jun 27 13:37:04 web kernel: [26319390.352746]  unevictable:0 dirty:1 writeback:0 unstable:0
    1818 Jun 27 13:37:04 web kernel: [26319390.352747]  free:1202 slab_reclaimable:1276 slab_unreclaimable:3126
    1819 Jun 27 13:37:04 web kernel: [26319390.352748]  mapped:4662 shmem:7374 pagetables:5500 bounce:0
    1820 Jun 27 13:37:04 web kernel: [26319390.354220] Node 0 DMA free:2060kB min:84kB low:104kB high:124kB active_anon:11812kB inactive_anon:1276kB active_file:0kB inactive_file:0kB unevictable:0kB isolated(anon):0kB isolated(file):0kB present:15680kB mlocked:0kB dirty:0kB writeback:0kB mapped:660kB shmem:1896kB slab_reclaimable:232kB slab_unreclaimable:332kB kernel_stack:96kB pagetables:20kB unstable:0kB bounce:0kB writeback_tmp:0kB pages_scanned:0 all_unreclaimable? yes
    1821 Jun 27 13:37:04 web kernel: [26319390.356037] lowmem_reserve[]: 0 489 489 489
    1822 Jun 27 13:37:04 web kernel: [26319390.356332] Node 0 DMA32 free:2748kB min:2784kB low:3480kB high:4176kB active_anon:419544kB inactive_anon:22456kB active_file:0kB inactive_file:60kB unevictable:0kB isolated(anon):0kB isolated(file):0kB present:500948kB mlocked:0kB dirty:4kB writeback:0kB mapped:17988kB shmem:27600kB slab_reclaimable:4872kB slab_unreclaimable:12172kB kernel_stack:1864kB pagetables:21980kB unstable:0kB bounce:0kB writeback_tmp:0kB pages_scanned:46 all_unreclaimable? yes
    1823 Jun 27 13:37:04 web kernel: [26319390.358186] lowmem_reserve[]: 0 0 0 0
    1824 Jun 27 13:37:04 web kernel: [26319390.358468] Node 0 DMA: 23*4kB 4*8kB 5*16kB 2*32kB 2*64kB 1*128kB 0*256kB 1* 512kB 1*1024kB 0*2048kB 0*4096kB = 2060kB
    1825 Jun 27 13:37:04 web kernel: [26319390.359119] Node 0 DMA32: 615*4kB 2*8kB 11*16kB 3*32kB 0*64kB 0*128kB 0*256kB 0*512kB 0*1024kB 0*2048kB 0*4096kB = 2748kB
    1826 Jun 27 13:37:04 web kernel: [26319390.359774] 7390 total pagecache pages
    1827 Jun 27 13:37:04 web kernel: [26319390.360036] 0 pages in swap cache
    1828 Jun 27 13:37:04 web kernel: [26319390.360270] Swap cache stats: add 0, delete 0, find 0/0
    1829 Jun 27 13:37:04 web kernel: [26319390.360544] Free swap  = 0kB
    1830 Jun 27 13:37:04 web kernel: [26319390.360763] Total swap = 0kB
    1831 Jun 27 13:37:04 web kernel: [26319390.362683] 131053 pages RAM
    1832 Jun 27 13:37:04 web kernel: [26319390.362914] 3819 pages reserved
    1833 Jun 27 13:37:04 web kernel: [26319390.363139] 70534 pages shared
    1834 Jun 27 13:37:04 web kernel: [26319390.363364] 117719 pages non-shared
    1835 Jun 27 13:37:04 web kernel: [26319390.363630] [ pid ]   uid  tgid total_vm      rss cpu oom_adj oom_score_adj      name
    1836 Jun 27 13:37:04 web kernel: [26319390.364141] [  306]     0   306     5339      141   0     -17         -1000      udevd
    1837 Jun 27 13:37:04 web kernel: [26319390.364630] [ 2015]   102  2015     7517      135   0       0             0      dbus-daemon
    1838 Jun 27 13:37:04 web kernel: [26319390.365121] [ 2341]     0  2341     4064       42   0       0             0      getty
    1839 Jun 27 13:37:04 web kernel: [26319390.370717] [ 2342]     0  2342     4064       41   0       0             0      getty
    1840 Jun 27 13:37:04 web kernel: [26319390.371176] [ 2343]     0  2343     4064       39   0       0             0      getty
    1841 Jun 27 13:37:04 web kernel: [26319390.371633] [ 2344]     0  2344     4064       41   0       0             0      getty
    1842 Jun 27 13:37:04 web kernel: [26319390.372157] [ 2345]     0  2345     4064       41   0       0             0      getty
    1843 Jun 27 13:37:04 web kernel: [26319390.372650] [ 2346]     0  2346     4064       41   0       0             0      getty
    1844 Jun 27 13:37:04 web kernel: [26319390.373151] [ 2353]     0  2353    31945      304   0       0             0      console-kit-dae
    1845 Jun 27 13:37:04 web kernel: [26319390.373635] [ 7534]     0  7534     1029       36   0       0             0      acpid
    1846 Jun 27 13:37:04 web kernel: [26319390.374136] [14662]     0 14662    30623     1232   0       0             0      rsyslogd
    1847 Jun 27 13:37:04 web kernel: [26319390.374612] [  473]   101   473    12890      113   0       0             0      exim4
    1848 Jun 27 13:37:04 web kernel: [26319390.375078] [  564]     0   564     4750       60   0       0             0      cron
    1849 Jun 27 13:37:04 web kernel: [26319390.375568] [  599]     0   599     4198       40   0       0             0      atd
    1850 Jun 27 13:37:04 web kernel: [26319390.376050] [29678]  1000 29678     6187      455   0       0             0      screen
    1851 Jun 27 13:37:04 web kernel: [26319390.376508] [29679]  1000 29679     5195      422   0       0             0      bash
    1852 Jun 27 13:37:04 web kernel: [26319390.376958] [29853]  1000 29853     5195      420   0       0             0      bash
    1853 Jun 27 13:37:04 web kernel: [26319390.377413] [ 2252]     0  2252    25950      366   0       0             0      proftpd
    1854 Jun 27 13:37:04 web kernel: [26319390.377898] [29760]     0 29760    21269      600   0       0             0      apache2
    1855 Jun 27 13:37:04 web kernel: [26319390.378387] [29762]    33 29762    21202      527   0       0             0      apache2
    1856 Jun 27 13:37:04 web kernel: [26319390.378870] [29763]    33 29763    21198      526   0       0             0      apache2
    1857 Jun 27 13:37:04 web kernel: [26319390.379327] [29764]    33 29764   208716     1537   0       0             0      apache2
    1858 Jun 27 13:37:04 web kernel: [26319390.379786] [29765]    33 29765   208652     1415   0       0             0      apache2
    1859 Jun 27 13:37:04 web kernel: [26319390.380292] [10362]     0 10362    98340     2248   0       0             0      php5-fpm
    1860 Jun 27 13:37:04 web kernel: [26319390.380803] [10369]  1000 10369    98290     2220   0       0             0      php5-fpm
    1861 Jun 27 13:37:04 web kernel: [26319390.381283] [10370]  1000 10370    98290     2220   0       0             0      php5-fpm
    1862 Jun 27 13:37:04 web kernel: [26319390.381773] [10371]  1000 10371    98290     2220   0       0             0      php5-fpm
    1863 Jun 27 13:37:04 web kernel: [26319390.382247] [10372]  1000 10372    98290     2220   0       0             0      php5-fpm
    1864 Jun 27 13:37:04 web kernel: [26319390.382723] [10373]  1000 10373    98290     2221   0       0             0      php5-fpm
    1865 Jun 27 13:37:04 web kernel: [26319390.383177] [10374]  1000 10374    98290     2221   0       0             0      php5-fpm
    1866 Jun 27 13:37:04 web kernel: [26319390.383669] [10375]  1000 10375    98290     2221   0       0             0      php5-fpm
    1867 Jun 27 13:37:04 web kernel: [26319390.384203] [10379]  1000 10379    98290     2221   0       0             0      php5-fpm
    1868 Jun 27 13:37:04 web kernel: [26319390.384686] [10380]  1000 10380    98290     2221   0       0             0      php5-fpm
    1869 Jun 27 13:37:04 web kernel: [26319390.385160] [10381]  1000 10381    98290     2221   0       0             0      php5-fpm
    1870 Jun 27 13:37:04 web kernel: [26319390.385631] [10382]  1000 10382    98447     2623   0       0             0      php5-fpm
    1871 Jun 27 13:37:04 web kernel: [26319390.386130] [10383]  1000 10383    98447     2576   0       0             0      php5-fpm
    1872 Jun 27 13:37:04 web kernel: [26319390.386630] [10385]  1000 10385    98518     2615   0       0             0      php5-fpm
    1873 Jun 27 13:37:04 web kernel: [26319390.387139] [10386]  1000 10386    98514     2666   0       0             0      php5-fpm
    1874 Jun 27 13:37:04 web kernel: [26319390.387643] [10388]  1001 10388    98290     2228   0       0             0      php5-fpm
    1875 Jun 27 13:37:04 web kernel: [26319390.388219] [10389]  1001 10389    98290     2227   0       0             0      php5-fpm
    1876 Jun 27 13:37:04 web kernel: [26319390.388692] [10390]  1001 10390    98290     2228   0       0             0      php5-fpm
    1877 Jun 27 13:37:04 web kernel: [26319390.389161] [10393]  1001 10393    98290     2228   0       0             0      php5-fpm
    1878 Jun 27 13:37:04 web kernel: [26319390.389627] [10394]  1001 10394    98290     2228   0       0             0      php5-fpm
    1879 Jun 27 13:37:04 web kernel: [26319390.390109] [10398]    33 10398   100471     4932   0       0             0      php5-fpm
    1880 Jun 27 13:37:04 web kernel: [26319390.390582] [ 2572]  1000  2572     5199      411   0       0             0      bash
    1881 Jun 27 13:37:04 web kernel: [26319390.391051] [ 2615]  1000  2615    34174     1093   0       0             0      irssi
    1882 Jun 27 13:37:04 web kernel: [26319390.391517] [ 4021]  1000  4021   100871     4968   0       0             0      php5-fpm
    1883 Jun 27 13:37:04 web kernel: [26319390.391978] [ 4079]  1000  4079   100552     4623   0       0             0      php5-fpm
    1884 Jun 27 13:37:04 web kernel: [26319390.392515] [ 4082]  1000  4082   100549     4626   0       0             0      php5-fpm
    1885 Jun 27 13:37:04 web kernel: [26319390.393000] [ 7307]  1000  7307   100710     4711   0       0             0      php5-fpm
    1886 Jun 27 13:37:04 web kernel: [26319390.393461] [ 7308]  1000  7308   100718     4733   0       0             0      php5-fpm
    1887 Jun 27 13:37:04 web kernel: [26319390.393946] [ 7589]  1000  7589    98446     2493   0       0             0      php5-fpm
    1888 Jun 27 13:37:04 web kernel: [26319390.394436] [11319]     0 11319    12515      153   0     -17         -1000      sshd
    1889 Jun 27 13:37:04 web kernel: [26319390.394915] [11332]     0 11332    14187      176   0     -17         -1000      sshd
    1890 Jun 27 13:37:04 web kernel: [26319390.395367] [11336]  1000 11336    14249      220   0     -17         -1000      sshd
    1891 Jun 27 13:37:04 web kernel: [26319390.395844] [11337]  1000 11337     4992      610   0     -17         -1000      bash
    1892 Jun 27 13:37:04 web kernel: [26319390.396344] [11422]  1000 11422    11617       89   0     -17         -1000      su
    1893 Jun 27 13:37:04 web kernel: [26319390.396792] [11429]     0 11429     5190      415   0     -17         -1000      bash
    1894 Jun 27 13:37:04 web kernel: [26319390.397251] [11490]     0 11490     5338      141   0     -17         -1000      udevd
    1895 Jun 27 13:37:04 web kernel: [26319390.397705] [11491]     0 11491     5338      141   0     -17         -1000      udevd
    1896 Jun 27 13:37:04 web kernel: [26319390.398156] [12011]     0 12011    12010       89   0     -17         -1000      su
    1897 Jun 27 13:37:04 web kernel: [26319390.398635] [12018]  1000 12018     5188      415   0     -17         -1000      bash
    1898 Jun 27 13:37:04 web kernel: [26319390.399091] [13488]  1000 13488    12010       91   0     -17         -1000      su
    1899 Jun 27 13:37:04 web kernel: [26319390.399538] [13495]     0 13495     5191      417   0     -17         -1000      bash
    1900 Jun 27 13:37:04 web kernel: [26319390.400032] [13577]     0 13577    14187      176   0     -17         -1000      sshd
    1901 Jun 27 13:37:04 web kernel: [26319390.400549] [13579]  1000 13579    14220      191   0     -17         -1000      sshd
    1902 Jun 27 13:37:04 web kernel: [26319390.401052] [13580]  1000 13580     4994      619   0     -17         -1000      bash
    1903 Jun 27 13:37:04 web kernel: [26319390.401511] [14171]  1000 14171   176308     5374   0       0             0      node
    1904 Jun 27 13:37:04 web kernel: [26319390.401971] [14878]  1000 14878    11617       88   0     -17         -1000      su
    1905 Jun 27 13:37:04 web kernel: [26319390.402438] [14885]     0 14885     5190      417   0     -17         -1000      bash
    1906 Jun 27 13:37:04 web kernel: [26319390.402981] [14941]     0 14941    12010       89   0     -17         -1000      su
    1907 Jun 27 13:37:04 web kernel: [26319390.403441] [14948]  1000 14948     5188      413   0     -17         -1000      bash
    1908 Jun 27 13:37:04 web kernel: [26319390.403937] [14992]  1000 14992    12010       91   0     -17         -1000      su
    1909 Jun 27 13:37:04 web kernel: [26319390.404452] [14999]     0 14999     5190      417   0     -17         -1000      bash
    1910 Jun 27 13:37:04 web kernel: [26319390.404955] [15100]     0 15100    12010       90   0     -17         -1000      su
    1911 Jun 27 13:37:04 web kernel: [26319390.405414] [15107]  1000 15107     5189      415   0     -17         -1000      bash
    1912 Jun 27 13:37:04 web kernel: [26319390.405879] [15411]    33 15411    98285     2222   0       0             0      php5-fpm
    1913 Jun 27 13:37:04 web kernel: [26319390.406355] [15418]  1000 15418   193681     5324   0       0             0      node
    1914 Jun 27 13:37:04 web kernel: [26319390.406805] [15454]  1000 15454   207958     4743   0       0             0      nodejs
    1915 Jun 27 13:37:04 web kernel: [26319390.407261] [15464]  1000 15464   364612    65444   0     -17         -1000      node

I originally loaded two Trivia.txt's inside a chat bot that I have. The process without the library included uses around 5% memory but with two Trivia.txt's , it shoots up to around 25%. I also know that a file less than 100KB in an array is capable of using up 8% of memory.

That is A LOT of memory being consumed by arrays in Node.

Anyone know truly what's going on here and how I can reduce the memory consumption? I know that Ruby although a different language, handles memory more efficiently and can load files bigger than 19MB with no problem.

**Comment by JTallis** [comment]
I believe the potential issue is that Arrays in Node are not dynamic in size, so it allocates a certain amount of memory per cell. This means that despite not using all cell space, it uses a lot of memory due to the amount of cells created. If this is the case, what's the possibility of creating dynamic cell size?

**Comment by jasnell** [comment]
There's really nothing to be done in either v0.10 or v0.12 so closing this issue. Can reopen if necessary.
