### ISSUE TITLE
(events): make listenerCount an EventEmitter instance method

### ISSUE THREAD

**Issue by jasonkarns** [joyent/node#25593]
`listenerCount` is currently a class method on EventEmitter, yet the very first argument is the emitter instance whose listenerCount should be returned. Why, then, is it a class method at all if it requires an instance on which to operate?

I propose `EventEmitter.prototype.listenerCount` be added such that:

``` js
var emitter = new require('events').EventEmitter();

EventEmitter.listenerCount(emitter, 'myEvent');
// alias for:
emitter.listenerCount('myEvent');
```

**Comment by brendanashworth** [comment]
It was to avoid breakage for users extending the `EventEmitter`, I'm pretty sure. You can find discussion over here: https://github.com/nodejs/io.js/issues/734.

**Comment by jasonkarns** [comment]
@brendanashworth thanks, I hadn't seen that particular one. I still think it's quite crazy to permanently lock an API from improving simply because people inherit. That's the cost of inheritance, and those who do so should be aware of what follows.

Even though it's an API *addition* (which would normally only warrant a minor version bump), if it strikes people has a backwards incompatible change, then push it with a major version.

**Comment by jasnell** [comment]
This API is not going to change in v0.12 so I'm going to close this here. If a change needs to be made to the API, then the best place to pursue that is either nodejs/io.js or nodejs/node.
