### ISSUE TITLE
Array Buffer does not work and option is gone

### ISSUE THREAD

**Issue by ajcrites** [joyent/node#25596]
It seems that node 0.12 no longer has the `--harmony_array_buffer` option, but this is not built in by default or with `--harmony`.  In iojs@2 it works.

    $ node@0.12 -e 'new Buffer("")[Symbol.iterator]()'
    # undefined is not a function
    $ iojs@2 -e 'new Buffer("")[Symbol.iterator]()'
    # works

**Comment by trevnorris** [comment]
The iterator doesn't come on the default Buffer object and has manually been set in io.js: https://github.com/nodejs/io.js/blob/v2.3.1/lib/buffer.js#L1066
