### ISSUE TITLE
Roadmap for bundling npm 3.x

### ISSUE THREAD

**Issue by mattdsteele** [joyent/node#25597]
npm 3.0.0 was [just released](https://github.com/npm/npm/releases/tag/v3.0.0). As someone working in a Windows shop we'd love to start using it, but will likely wait until it's bundled with Node.

As @iarna noted in the release it's considered beta (and I've run into a few issues with it), but is there any timeline on when it might get included in a release? e.g. once it's declared out of beta, it can be tested and shipped with the next Node release? Or is the plan to be more conservative with an update like this, and it might take a couple months?

Mostly curious, as I've had a few coworkers ask me about it. Thanks!

**Comment by LouiseLi1889** [comment]
I think there is a bug for dist tar file. The node-v0.10.28-linux-arm-pi npm works, but node-v0.11.11-linux-arm-pi npm is not working.It complains missing man3 files. How do I get your npm separately ?
Thanks

**Comment by jasnell** [comment]
General consensus is that npm3 will likely not be delivered in either v0.10 or v0.12, both of which are currently considered LTS. Updating to npm3 will happen most likely after the joyent/node and nodejs/io.js streams fully converge under nodejs/node, and then only once the key issues have been addressed.
