### ISSUE TITLE
Thou shall not code formulaes from mathematical formularies!

### ISSUE THREAD

**Issue by jsfrbr** [joyent/node#25604]
node.js has a Math.sinh(x) function. This function returns wrong values for small x values. It seem to be coded as (exp(x)-exp(-x)/2 which causes cancellation.

**Comment by trevnorris** [comment]
This is a V8 thing. If you give a precise example I'll run it through latest V8 and see if it's been fixed.

**Comment by jsfrbr** [comment]
This is old stuff from the 19siexties; see elefunt (elementary function tests); exp(x) - exp(-x) produces cancellation at subtraction; cmath does that correctly.

I wrote a quick workaround in MathExtension which generates correct results in node.js and rhino (which has't a sinh at all):


// rhino and node functions
if (print === undefined) { function print (x) { console.log (x); } }
if (quit === undefined) { function quit () { process.exit (); } }

if (Math.asinh === undefined) { function asinh (x) { return Math.log (x + Math.sqrt (1+x*x)); } }
else { function asinh (x) { return Math.asinh (x); } }
if (Math.acosh === undefined) { function acosh (x) { return Math.log (x + Math.sqrt (1+x) * Math.sqrt (x-1) ); } }
else { function acosh (x) { return Math.acosh (x); } }
if (Math.cosh === undefined) { function cosh (x) { return (Math.exp (x) + Math.exp (-x)) / 2; } }
else { function cosh (x) { return Math.cosh (x); } }
if (Math.cbrt === undefined) { function cbrt (x) { if (x < 0) return -Math.pow (-x, 1/3); return Math.pow (x, 1/3); } }
else { function cbrt (x) { return Math.cbrt (x); } }
if (Math.hypot === undefined) { function hypot (x, y) { return Math.sqrt (x*x+y*y); } }
else { function hypot (x, y) { return Math.hypot (x, y); } }

var MathExtension = {
    sinh: function (x) { // node.js miscomputes sinh with small x values (cancellation)!
        var h,x2,s, i,i2,n;
        
        if (Math.abs(x)>=0.35) {
            h=Math.exp(x);
            return (h-1.0/h)/2.0;
        } else { /* series */
            n=25; /* |x| < 0.35; eps < 1e-35 */
            x2=x * x;
            s=1.0;
            for (i=n;i+1>1;i--) {
                i2=i+i;
                s=1+x2/i2/(i2+1)*s;
            }
            return x*s;
    } }
}; // take care: without that semicolon the whole thing does not work!

(function () {
    'use strict';

    var i;

    x = 1;
    for (i = 0; i < 20; i++) {
        x = x / 7;
        y = MathExtension.sinh (x);
        print (i + " " + x + " " + y + " " + ((Math.exp(x) - Math.exp(-x)) / 2));
    }

    print ("alles ok");

} ());


>>> Trevor Norris <notifications@github.com> schrieb am 01.07.2015 um 09:59:

This is a V8 thing. If you give a precise example I'll run it through latest V8 and see if it's been fixed.

**Comment by jsfrbr** [comment]
Sorry for that: my first version hat two undeclared variables and did not print nodes Math.sinh

This is old stuff from the 19siexties; see elefunt (elementary function tests); exp(x) - exp(-x) produces cancellation at subtraction; cmath does that correctly.

I wrote a quick workaround in MathExtension which generates correct results in node.js and rhino (which has't a sinh at all):


// rhino and node functions
if (print === undefined) { function print (x) { console.log (x); } }
if (quit === undefined) { function quit () { process.exit (); } }

if (Math.asinh === undefined) { function asinh (x) { return Math.log (x + Math.sqrt (1+x*x)); } }
else { function asinh (x) { return Math.asinh (x); } }
if (Math.acosh === undefined) { function acosh (x) { return Math.log (x + Math.sqrt (1+x) * Math.sqrt (x-1) ); } }
else { function acosh (x) { return Math.acosh (x); } }
if (Math.cosh === undefined) { function cosh (x) { return (Math.exp (x) + Math.exp (-x)) / 2; } }
else { function cosh (x) { return Math.cosh (x); } }
if (Math.cbrt === undefined) { function cbrt (x) { if (x < 0) return -Math.pow (-x, 1/3); return Math.pow (x, 1/3); } }
else { function cbrt (x) { return Math.cbrt (x); } }
if (Math.hypot === undefined) { function hypot (x, y) { return Math.sqrt (x*x+y*y); } }
else { function hypot (x, y) { return Math.hypot (x, y); } }

var MathExtension = {
    sinh: function (x) { // node.js miscomputes sinh with small x values (cancellation)!
        var h,x2,s, i,i2,n;
        
        if (Math.abs(x)>=0.35) {
            h=Math.exp(x);
            return (h-1.0/h)/2.0;
        } else { /* series */
            n=25; /* |x| < 0.35; eps < 1e-35 */
            x2=x * x;
            s=1.0;
            for (i=n;i+1>1;i--) {
                i2=i+i;
                s=1+x2/i2/(i2+1)*s;
            }
            return x*s;
    } }
}; // take care: without that semicolon the whole thing does not work!

(function () {
    'use strict';

    var i, x, y;

    x = 1;
    for (i = 0; i < 20; i++) {
        x = x / 7;
        y = MathExtension.sinh (x);
        print (i + " " + x + " " + y + " " + ((Math.exp(x) - Math.exp(-x)) / 2), Math.sinh (x));
    }

    print ("alles ok");

} ());


>>> Trevor Norris <notifications@github.com> schrieb am 01.07.2015 um 09:59:

This is a V8 thing. If you give a precise example I'll run it through latest V8 and see if it's been fixed.

**Comment by OrangeDog** [comment]
Node.js doesn't provide any Math functions; they're from Google's JavaScript engine (V8).

Give us a value and correct answer for which `Math.sinh` is wrong so we can check newer versions, and/or file a bug with V8.

**Comment by jsfrbr** [comment]
Hi,

I just wrote that to Trevor Norris. The sinh is not Ecmascript (which requires mostly C88 math.h). But is it in C11 and when implemented, it should compute correct values. 

I don't know the language of V8, but if it is C/C++ it could simply link an use the math.h/cmath of 2011, which is correct.

I wrote a workaround. It gives correct answers with node.js and rhino and shows the error in Math.sinh. See


   // rhino and node functions
if (print === undefined)
  {
    function print (x)
    {
      console.log (x);
    }
  }
if (quit === undefined)
  {
    function quit ()
    {
      process.exit ();
    }
  }

if (Math.asinh === undefined)
  {
    function asinh (x)
    {
      return Math.log (x + Math.sqrt (1 + x * x));
    }
  }
else
  {
    function asinh (x)
    {
      return Math.asinh (x);
    }
  }

if (Math.acosh === undefined)
  {
    function acosh (x)
    {
      return Math.log (x + Math.sqrt (1 + x) * Math.sqrt (x - 1));
    }
  }
else
  {
    function acosh (x)
    {
      return Math.acosh (x);
    }
  }

if (Math.cosh === undefined)
  {
    function cosh (x)
    {
      return (Math.exp (x) + Math.exp (-x)) / 2;
    }
  }
else
  {
    function cosh (x)
    {
      return Math.cosh (x);
    }
  }

if (Math.cbrt === undefined)
  {
    function cbrt (x)
    {
      if (x < 0)
 return -Math.pow (-x, 1 / 3);
      return Math.pow (x, 1 / 3);
    }
  }
else
  {
    function cbrt (x)
    {
      return Math.cbrt (x);
    }
  }

if (Math.hypot === undefined)
  {
    function hypot (x, y)
    {
      return Math.sqrt (x * x + y * y);
    }
  }
else
  {
    function hypot (x, y)
    {
      return Math.hypot (x, y);
    }
  }

var MathExtension = {
sinh:function (x) {  // node.js miscomputes sinh with small x values (cancellation)!
  var h, x2, s, i, i2, n; if (Math.abs (x) >= 0.35)
  {
  h = Math.exp (x); return (h - 1.0 / h) / 2.0;}
  else
  {  /* series */
  n = 25;  /* |x| < 0.35; eps < 1e-35 */
  x2 = x * x; s = 1.0; for (i = n; i + 1 > 1; i--)
  {
  i2 = i + i; s = 1 + x2 / i2 / (i2 + 1) * s;}
  return x * s;}
  }
  };  // take care: without that semicolon the whole thing does not work!

  (function ()
   {
   'use strict'; var i, x, y; x = 1; for (i = 0; i < 20; i++)
   {
   x = x / 7;
   y = MathExtension.sinh (x);
   print (i + " " + x + " " + y + " " +
   ((Math.exp (x) - Math.exp (-x)) / 2) + " " +
   Math.sinh (x));}

   print ("alles ok");}

   ());

>>> James Howe <notifications@github.com> schrieb am 01.07.2015 um 11:11:

Node.js doesn't provide any Math functions; they're from Google's JavaScript engine (V8).
Give us a value and correct answer for which Math.sinh is wrong so we can check newer versions, and/or file a bug with V8.

**Comment by trevnorris** [comment]
V8 does not use math.h for these calculations. They've written an implementation in assembly for all supported architectures so the call can be inline by the JIT. The most we can do is test later releases to see if the issue has been fixed. If it hasn't then an issue will have to be filed with them.

**Comment by jasnell** [comment]
Closing this as it does not appear to be a Node issue. can reopen if necessary.
