### ISSUE TITLE
Syntax error undetected by Node when executing the expression “f)(”.

### ISSUE THREAD

**Issue by Mbodin** [joyent/node#25612]
Hi,
I’m running version v0.10.36 of Node, on Fedora, x86, 64 bits.
I get the following output from Node:
```javascript
$ node
> function f () { return 42 }
undefined
> f )(
42
> f)(
42
> function g () { return function () { return 18 } }
undefined
> g(f)()
18
```

As you can see, instead of raising a syntax error when evaluating the expression “f)(”, it accepts it as if it was “f ()”. However, this strange parsing does not seem to appear deeply (as seen with function g, which should have returned a function if parsed as “g(f())”).

It probably is not a major bug, but it might hide some bigger bugs.

Hoping it can help,
Martin.

**Comment by brendanashworth** [comment]
This was fixed by https://github.com/joyent/node/commit/9ef9a9dee54a464a46739b14e8a348bec673c5a5. I don't know whether the maintainers want to backport this to v0.10.

**Comment by Mbodin** [comment]
Thanks!
I didn’t saw any duplicate in my (quick) search, so I reported it. Great to read that it is already fixed in newer versions ☺
This bug does not yield troubles for me, I just wanted the issue to be known.
From the commit message, I understand that “f)(” was actually unexpectedly parsed as “(f)()”. I forgot how complicated it can to parse JavaScript…
I suggest closing this bug, then, as it is already solved in newer versions.
Martin.
