### ISSUE TITLE
toString on native object does not return a valid function declaration.

### ISSUE THREAD

**Issue by Mbodin** [joyent/node#25613]
Hi,
The value “Function.prototype.toString” is defined by the Ecma standard as follows:
```
An implementation-dependent representation of the function is returned. This representation has the syntax of a FunctionDeclaration. Note in particular that the use and placement of white space, line terminators, and semicolons within the representation String is implementation-dependent.
```
In particular, one should be able to parse or to pass to “eval” the result without getting a syntax error. However, there is no guarantee on the behaviour of the returned function.

The problem comes when calling this function with native objects as “this”:
```javascript
$ node
> String.toString === Function.prototype.toString // Just checking whether “String” has a special “toString“ function, which is not the case here.
true
> String.toString()
'function String() { [native code] }'
> eval ('function String() { [native code] }') // Syntax error
```
As you can see, “[native code]” is not a valid body for a function.

What I suggest is to return the following string instead:
```javascript
$ node
> String.toString()
'function String() { "native code" /* native code */ }'
```
It uses a tag to warn users that the following is a native code, and a comment to warn users that there is some code left.
For this part, the specification is extremely loose: I think it would be a good think to follow the specification here, as it is easy to do…

Martin.
P.S.: I’m running version v0.10.36 of Node, on Fedora, x86, 64 bits.

**Comment by cjihrig** [comment]
This functionality is provided to Node, and matches browser output. It doesn't make sense for core to change this. You can easily modify this behavior yourself if you really need to.
