### ISSUE TITLE
Missing 0.12.6 tag

### ISSUE THREAD

**Issue by omphalos** [joyent/node#25626]
I see the 0.12.6 release [here](http://blog.nodejs.org/2015/07/03/node-v0-12-6-stable/) but don't see this tagged in github.

**Comment by misterdjules** [comment]
The [v0.12.6 tag](https://github.com/joyent/node/releases/tag/v0.12.6) was pushed to GitHub later than usual, sorry for the inconvenience.

**Comment by omphalos** [comment]
@misterdjules No problem - thanks for adding it.
