### ISSUE TITLE
Bug in res.json returning an array containing base64-strings

### ISSUE THREAD

**Issue by bitflower** [joyent/node#25622]
First of all this has a reference to Mongoose ticket: https://github.com/Automattic/mongoose/issues/3112

When using res.json() with an array of object inside which a property contains base64 strings the JSON coming out has malformed. It contains the whole array twice.

The problematic array of objects is this one:
https://gist.github.com/bitflower/6249aa8823ba4a8a2090

Workaround: Use JSON.stringify().

What does .json() use internally?

**Comment by cjihrig** [comment]
I don't think this is related to Node core. If I'm wrong, let me know and we can reopen this.
