### ISSUE TITLE
Gracefully shut down the http server

### ISSUE THREAD

**Issue by viddeshshinde** [joyent/node#25639]
I have created a http server which uses cluster module as well. I want to shut down the server gracefully. 

The requirement is as follow:
1. Server should reject new incoming requests to it.
2. Server should process all the requests successfully which are in flight and then restart the server.

After doing some research i found server.close() function which is said to be used in such cases. But I didn't see good results out of it. Sometimes it rejects the new incoming connections or sometimes it restarts the server before finishing the requests which are on the fly. 
I pass a signal to the process through command line which is handled in my server code. 

Also as I use cluster, after closing one instance of the server remaining instances gives the error as no such methode '.close'.

**Comment by dnakamura** [comment]
I've played a bit with the ```close()``` method before and it seems to behave as expected. Note that it only stops accepting new connections, any connections that have been received but not processed still get through.  Also, I've never seen it restart the server. What platform & version are you running on? And could you provide a small code sample to reproduce?

**Comment by viddeshshinde** [comment]
Its working fine if its single process, but if I use cluster 
(I have tried using cluster both the ways: 
1. through pm2 
2. directly from the code). 

It doesn't work properly as it does when tried without cluster. I am using node version 0.10.33 on Mac.

**Comment by cjihrig** [comment]
Can you share some code that reproduces the problem? Ideally, as minimal as possible.

**Comment by viddeshshinde** [comment]
var cluster = require('cluster');
var numCPUs = require('os').cpus().length;

var s = '';
var server = {"_requests" : 0};
var mobport = [9999, 8888, 7777, 6666, 5555];
var serverArray = [];

if (cluster.isMaster) {
    // Fork workers.
    for (var i = 0; i < 1; i++) {
        cluster.fork();
    }
    cluster.on('exit', function (worker, code, signal) {
        console.log('worker ' + worker.process.pid + ' died');
    });
} else {
    RunServers();
}

RunServers = function () {
    mobport.forEach(function (port) {
        s = https.createServer(options,
            function onapprequest(request, response) {
                // some processing.....
                response.end();
                server._requests -= 1;
                if (server._requests === 0) {
                    s.emit('no_more_requests');
                }
            });
    });
}


process.on('SIGTERM', function () {
    console.log("\nGracefully shutting down from SIGTERM ");
    gracefulExit();
});

function gracefulExit() {
    serverArray.forEach(function (s) {
        console.log("s.close()");
        s.close(function (err) {
            if (server._requests === 0) {
                process.exit(0); // exit right away
            }
        });
        s.once('no_more_requests', function () {
            process.exit(0);
        }); // or wait
    });
}

**Comment by viddeshshinde** [comment]
Found the solution which is as follows:

While closing server we had called server.close() once. We changed it to run the foreach loop for the servers array created above and we called sever.close() inside the loop so that server running on each port gets closed individually which solved the problem.
