### ISSUE TITLE
openssl: tracking issue for upcoming security release

### ISSUE THREAD

**Issue by rvagg** [joyent/node#25647]
A tracking issue for the upcoming OpenSSL security patch release coming on the 9th. Announced at https://mta.openssl.org/pipermail/openssl-announce/2015-July/000037.html

Note the severity is "high" (their highest, see [security policy](http://openssl.org/about/secpolicy.html)). As this impacts version 1.0.1 and both Node.js 0.10 and 0.12 bundle this version expect patch releases of both soon after.

io.js is tracking this at https://github.com/nodejs/io.js/issues/2115

**Comment by misterdjules** [comment]
@shigeki or and other @joyent/node-collaborators Do you have some time to do this upgrade tomorrow?

**Comment by shigeki** [comment]
@misterdjules I will work it for v0.10.x after https://github.com/nodejs/io.js/issues/2115 .

**Comment by misterdjules** [comment]
@shigeki That's great, thank you so much once again :+1: If for whatever reason you don't have time to do it, let us know and we'll find someone else to do that.

**Comment by misterdjules** [comment]
Fixed by github.com/joyent/node/pull/25654, landing soon.

**Comment by misterdjules** [comment]
Fixed by0cf9f27703b0052381dec77c89b41a651c3f2791, 82778223444d9717bcd2629443c93677035fc40f, 984e7f9e405b7b427d6bd1ee1e89d224521a8da5, 7ad593877e4b3fae04652037cc6d7106dc87109a and c5d7b315289c993e9b823ce00c2d8ff21abe7507.

**Comment by jasnell** [comment]
+1.. thanks all
