### ISSUE TITLE
Looking to expand the group of release managers

### ISSUE THREAD

**Issue by misterdjules** [joyent/node#25650]
Currently, I'm the only person managing releases of node v0.10 and v0.12. I don't think this is a sustainable model in the long term. I would like to have a team of release managers taking turns in doing releases, supporting each other, sharing knowledge and engaging new contributors interested in doing it. 

It could work pretty much in a similar fashion than working groups, but in a less formal way (no specific repository, but a specific team like @nodejs/release-managers for instance).

The process of releasing a new version of Node.js v0.10 or v0.12 itself takes around 2 hours and is now fairly documented, but there's some preparation and follow-up work to do between releases. Overall, it's not a very time consuming process on a daily basis, but it requires release managers to follow the project very closely all the time.

@joyent/node-collaborators Is anyone interested in helping me do releases? @sam-github @bnoordhuis suggested you might be interested, that'd be great :)

**Comment by cjihrig** [comment]
@misterdjules my uberconference connection was terrible today, but I am interested in learning how to make releases.

**Comment by misterdjules** [comment]
@cjihrig That's great, thank you :+1: I know @jasnell also volunteered to help in the short term. I'll wait to see if more people are interested and we'll schedule a call when I can introduce you to how releases are done and plan for next releases.

**Comment by thefourtheye** [comment]
+1 for the idea of release managers team

**Comment by orangemocha** [comment]
Not sure about my availability as a release manager, but since I am working with build and Jenkins automation I would still like to join the informational call to at least be educated on the process.

**Comment by misterdjules** [comment]
@thefourtheye Do you mean you'd also be interested in managing some of the v0.10.x and v0.12.x releases?

**Comment by misterdjules** [comment]
@cjihrig @orangemocha @thefourtheye @jasnell Here's a doodle with time slots for an introductory meeting: http://doodle.com/nifscqe3sdyqpnz2. Could you please fill it out and let me know if we need to add more time slots?

Thank you!

**Comment by jasnell** [comment]
Done

**Comment by sam-github** [comment]
I'd be interested.

**Comment by sam-github** [comment]
I have standups at 9am, 10am works fine.

**Comment by misterdjules** [comment]
@sam-github That's great :) Please fill out the [doodle](http://doodle.com/nifscqe3sdyqpnz2) for an introductory meeting and let me know if you need other time slots/dates.

**Comment by misterdjules** [comment]
@sam-github OK, I see you already filled it out, thank you :)

**Comment by sam-github** [comment]
@misterdjules I filled out the doodle.

**Comment by sam-github** [comment]
The magic of *almost* instantaneous communication in action, conversation that is always 5 seconds behind.

**Comment by ravi** [comment]
I am curious: what are the necessary qualifications?

**Comment by misterdjules** [comment]
@ravi Currently, you need to [be a collaborator in joyent/node](https://nodejs.org/contribute/becoming_collaborator.html#becoming_collaborator_md_becoming_a_collaborator), which means you're active in fixing bugs and triaging issues for the v0.10.x and v0.12.x versions of Node.js.

**Comment by ravi** [comment]
Thank you for the clarification.

**Comment by orangemocha** [comment]
Filled in the doodle. Not a very good week for me, as I am travelling. Consider me as optional, I can catch up later.

**Comment by misterdjules** [comment]
@cjihrig @sam-github @jasnell @orangemocha Thank you very much for volunteering to help managing releases :+1:

I created the @joyent/node-release-managers GitHub team, please use that handle when you wish to notify release managers specifically.

Onboarding of all volunteers is now done, and @cjihrig is scheduled to do the next v0.10.x and/or v0.12.x release. @sam-github will follow with the next one, and we'll continue in a round robin fashion.

Thank you very much again!
