### ISSUE TITLE
too slow when deal with many object with different keys

### ISSUE THREAD

**Issue by rain1017** [joyent/node#25661]
for(var i=0; i<100000; i++){
   var obj = {};
   obj[Math.random()] = true;
}
//too slow 35.8s!

for(var i=0; i<100000; i++){
   var obj = {k : 1};
   delete obj.k; // trick v8 not to use hidden class
   obj[Math.random()] = true;
}
// 0.19s!

I know this is caused by v8 hidden class (http://www.html5rocks.com/en/tutorials/speed/v8/),

**Comment by rain1017** [comment]
Is there a better way to avoid v8 from creating unnecessary hidden class?

**Comment by tenbits** [comment]
I would use the `Object.create` for the objects with dynamic keys. Though it is slower then plain hash object, but it creates the object with `fast properties`. 
```javascript
test('Object::class', function(){
    var obj = {};
    obj[Math.random()] = true;
});
test('Object::hash', function(){
    var obj = {k : 1};
    delete obj.k; // trick v8 not to use hidden class
    obj[Math.random()] = true;
});
test('Object::create', function(){
    var obj = Object.create({});
    obj[Math.random()] = true;
});

// run with --allow-natives-syntax
CheckFastProperties();

function test(name, tick) {
    console.time(name)
    var count = 10000;
    while( --count !== 0 ) {
        tick();
    }
    console.timeEnd(name)
}

function CheckFastProperties() {
    console.log('\nFast properties\n');
    var objClass = {};
    console.log('Object::class', %HasFastProperties(objClass));

    var objHash = { k: 1};
    delete objHash.k;
    console.log('Object::hash', %HasFastProperties(objHash));

    var objCreate = Object.create({});
    console.log('Object::create', %HasFastProperties(objCreate));
}
```
Output:
```
Object::class: 891ms
Object::hash: 16ms
Object::create: 63ms

Fast properties

Object::class true
Object::hash false
Object::create true
```

**Comment by jasnell** [comment]
Unfortunately there's nothing we're going to be able to do about this in v0.10 or v0.12. The newer V8 that will ship with the upcoming converged release ought to perform better (which you can test by running your test against io.js)
