### ISSUE TITLE
Segfault with nodejs 0.12.6 and 0.12.7 using SSL

### ISSUE THREAD

**Issue by Drazke** [joyent/node#25678]
Hi,

I updated nodejs to version 0.12.6 and now when I use node-mysql with SSL option, it gives me a segmentation fault. I try to update to version 0.12.7 but still no change.

Everything worked fine on nodejs 0.12.4.

I opened an issue at node-mysql if you want to see an example code that segfault https://github.com/felixge/node-mysql/issues/1149

Here is the core dump (v0.12.7):
```
warning: core file may not match specified executable file.
[New LWP 20918]
[New LWP 20920]
[New LWP 20922]
[New LWP 20919]
[New LWP 20921]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
Core was generated by `/usr/bin/node /home/app/test.js'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0070a602 in node::StreamWrap::Shutdown(v8::FunctionCallbackInfo<v8::Value> const&) ()
(gdb) bt no-filters full
#0  0x0070a602 in node::StreamWrap::Shutdown(v8::FunctionCallbackInfo<v8::Value> const&) ()
No symbol table info available.
#1  0x0030adb0 in v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) ()
No symbol table info available.
#2  0x0032c118 in ?? ()
No symbol table info available.
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

For information, I'm on Ubuntu trusty 14.04 LTS on an arm server.

Regards.

**Comment by dnakamura** [comment]
To me it almost sounds like #25365 ,but I cant think of a reason it wouldn't occur in older builds

**Comment by dnakamura** [comment]
What was the last version that behaved properly?

**Comment by Drazke** [comment]
The last version that behaved properly were node v0.12.4.

But I didn't test on v0.12.5.

**Comment by Drazke** [comment]
Hi, I did some new test and this is what I got :

nodejs v0.12.4 --> OK
nodejs v0.12.5 --> NOK (Segfault)
nodejs v0.12.6 --> NOK (Segfault)
nodejs v0.12.7 --> NOK (Segfault)
iojs v2.2.1 --> OK
iojs v2.3.0 --> NOK (Segfault)
iojs v2.3.1 --> NOK (Segfault)
iojs v2.3.2 --> NOK (Handshake inactivity timeout, PROTOCOL_SEQUENCE_TIMEOUT)
iojs v2.3.3 --> NOK (Handshake inactivity timeout, PROTOCOL_SEQUENCE_TIMEOUT)
iojs v2.3.4 --> NOK (Handshake inactivity timeout, PROTOCOL_SEQUENCE_TIMEOUT)
iojs v2.4.0 --> NOK (Handshake inactivity timeout, PROTOCOL_SEQUENCE_TIMEOUT)

**Comment by Drazke** [comment]
Hi

The problem was solved, it was due to my version of mysql-server. Because mysql-server below v5.7.6 use 512 bit DH parameter in the source code (hardcoding) and give an error with the new OpenSSL.

> OpenSSL has added protection for TLS clients by rejecting handshakes
with DH parameters shorter than 768 bits.

I updated mysql-server to v5.7.7-rc and now everything work fine.
