### ISSUE TITLE
timeout option with child_process.spawn

### ISSUE THREAD

**Issue by warrenseine** [joyent/node#25688]
Hi,

I've tried to use `timeout` as an option to `spawn`. Unfortunately, this has no effect, and the documentation seems to confirm that this option only exists for `exec`.

What's the rationale for not including this option? Any plan to include it?

Any workaround?

Regards,
Warren.

**Comment by dnakamura** [comment]
I believe the answer is that spawn is designed to execute longer running commands. Spawn will execute the command and immediately start flowing data to the std out stream, where as exec executes the command and buffers the output and executes the callback when the command completes. A work around is very simple (as internally exec uses spawn).
```
var child_process = require('child_process');
var cp = child_process.spawn(command, args, options);
setTimeout(function(){ cp.kill()}, 5000);
```

**Comment by warrenseine** [comment]
Ok, thanks.

**Comment by alohaninja** [comment]
this same strategy works for child_process `fork()` as well, the `fork()` method ignores the option for `timeout`, seems this would have been trivial to bake-in similar to `exec`, but so long as the workaround exists - I'm happy!
