### ISSUE TITLE
`path.normalize` doesn't have the `splice` method

### ISSUE THREAD

**Issue by fresheneesz** [joyent/node#25684]
I would have expected `path.normalize` to return a standard String object, but tho it has `indexOf` and `slice`, it doesn't have `splice`.

**Comment by cjihrig** [comment]
`splice()` is not a `String.prototype` method as far as I know.

**Comment by fresheneesz** [comment]
@cjihrig Did you try looking it up? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice

**Comment by cjihrig** [comment]
No, I didn't try looking up Array methods.

**Comment by fresheneesz** [comment]
@cjihrig .. I linked you proof that `splice` is a `String.prototype` method. Please reopen this.

**Comment by fresheneesz** [comment]
Nm, my bad
