### ISSUE TITLE
assert.ok() doesn't show on docs.

### ISSUE THREAD

**Issue by gtomitsuka** [joyent/node#25738]
[assert.ok()](https://github.com/joyent/node/blob/master/lib/assert.js#L107-L110) exists and is usable, but it doesn't appear on [the docs](https://nodejs.org/api/assert.html).

**UPDATE:** I noted it's just a [Circular] to `assert()`, but still, there could be something indicating it exists...

**Comment by cjihrig** [comment]
It is listed [here](https://nodejs.org/api/assert.html#assert_assert_value_message_assert_ok_value_message).
