### ISSUE TITLE
broken wiki page Projects, Applications, and Companies Using Node

### ISSUE THREAD

**Issue by austinpickett** [joyent/node#25734]
the format of Projects, Applications, and Companies Using Node page is broken

**Comment by KenanY** [comment]
Duplicate of https://github.com/joyent/node/issues/25651?

**Comment by codevelop** [comment]
well, can you describe the situation in detail?

**Comment by austinpickett** [comment]
@KenanY yes it is

@codevelop it is a wiki page and the markup is broken on it see #25651
