### ISSUE TITLE
res.writeHead - when provided with  cookie - cookie is emitted twice

### ISSUE THREAD

**Issue by osher** [joyent/node#25742]
The following test falls:
```
require('should');
var svr = require('http').createServer( function(req, res) {
    res.writeHead(200, {'Content-Type': 'text/plain', 'Set-Cookie': 'sess=aaaa'});

    if (req.method == 'POST')
        res.end('Hello World in POST');
    else
        res.end('Hello World in GET');
}).bind(1234);

require('request')( "http://localhost:1234/", function(e, r) {
     r.headers["set-cookie"].should.eql("sess=aaaa");
})
```

The result is that 

`r.headers["set-cookie"]` is in fact `["sess=aaaa","sess=aaaa"]`
We resolve to the work-arround of calling `setHeader('set-cookie',....)` in a separate call

on Node v.0.10.x there was no problem
the problem was first encountered after ramping to node 0.12.x (on my PC its 0.12.2, on our servers it's 0.12.7
Thanks....

**Comment by CGavrila** [comment]
Are you sure the example you posted is right? Can't find `bind()` in the docs, so I'll just assume that you meant `listen()`.

Quickly tried it on Ubuntu 12.04, v0.12.4 and it works fine.

**Comment by jasnell** [comment]
Unable to reproduce the problem, although the test case did need some fixing up to work.
