### ISSUE TITLE
Use CMake as build system

### ISSUE THREAD

**Issue by iHateInventNames** [joyent/node#25746]
pros:
   multiplatform
   auto supported project generators for VS, xcode, Eclipse, etc
   supported by KDevelop, CLion, Android Studio
   supported by yocto build system
   deduplicated creation of packages for all platforms
   integration with v8 because it uses cmake
cons:
   which cons, please?

**Comment by Fishrock123** [comment]
* Needs to work with node-gyp
* Requires people's time to switch over

This was also discussed at https://github.com/nodejs/io.js/issues/1425

**Comment by jasnell** [comment]
Closing this as this would never land here. The discussion should be moved to either nodejs/io.js or nodejs/node
