### ISSUE TITLE
Signal parameter in child_process#event_exit not always correct

### ISSUE THREAD

**Issue by akobler** [joyent/node#25744]
Hi

I have the following setup:
A node process starts with `child_process#spawn()` a bash script, whereby the bash script starts two other processes. In order to kill **all** those processes on a certain event from my node code, I followed this hint: http://azimi.me/2014/12/31/kill-child_process-node-js.html.

My most upper spawned process (bash script) was marked as detached (https://nodejs.org/api/child_process.html#child_process_options_detached). With this option, a new process group is created. All processes created from that bash script are also members of that process group.

Killing all processes of this process group: Inside my node code, a `SIGINT` signal is sent to the process group: 
```
process.kill(-child.pid, 'SIGINT');
```
This works great, all processes are killed. 

**BUT**: The exit event handler of the spawned child (bash script) has the parameters `code`and `signal` (https://nodejs.org/api/child_process.html#child_process_event_exit). There, the `signal` parameter is not always set to `SIGINT`, but the process is always killed by a `SIGINT` (under the control of my node code). Sometimes this signal parameter is set to `SIGINT`, sometimes just to `null`. Could not find a real pattern. Can somebody either teach me about what I am missing or confirm that this is a bug? 

Using:
Ubuntu: 14.04
Node: v0.10.25

Thanks a lot

Best, Andi

**Comment by jasnell** [comment]
Are you able to provide a test case that reliably demonstrates the issue? Even if only intermittently?

**Comment by akobler** [comment]
Hi, just had a short look. For this simple case, the error handler gets always a proper SIGINT:

```
var child_process = require('child_process')

var child = child_process.spawn('sh', ['-c', 'cat /dev/random | sed \'s/0/1/g\' > /dev/null'], {detached: true})
child.on('exit', function(exitCode, signal) {
    console.log('exitCode: '+exitCode)
    console.log('signal: '+signal)
})
setTimeout(function() {
    process.kill(-child.pid, 'SIGINT')
}, 1000)
```

The bash script in question is a bit more complicated, essentially a fIcy that writes to a named pipe and an awscli that streams from the pipe to a S3 bucket. As I had to fiddle around with traps to shutdown the fIcy/awscli correctly, I guess, my script is the root of evil.

Core of my script: 
```
clean() {
    kill -INT "$pid"
}
trap clean TERM INT

# 0) aws reads a stream from $TMP/pipe and writes it to the s3 bucket. fIcy writes to $TMP/pipe
# 1) aws is started detached in the background. Reason: if aws is killed by this bash script, the stream is not
#    written to the s3 bucket. Only if aws is terminated by an EOF in its input stream, the stream is finally
#    saved on s3. If aws is nohup'ed in the background, it is not going to be killed when this bash script is
#    terminated, rather the aws process is terminated when the fIcy process is killed and the named pipe is emptied.
# 2) aws's stdout/stderr are redireced to a file for further analyzes below
# 3) fIcy's stderr is redireced to a file for further analyzes below
# 4) signals INT, TERM are forwarded to fIcy (not to aws, since aws must be terminated by EOF in input, 
#    else the data is not written correctly to the bucket!)
nohup aws s3 cp - "$BUCKET/$s3File" < "$TMP/pipe" 1>"$AWS_ERR" 2>&1 &
"$DIR/fIcy" -v "$host" "$port" "$stream" > "$TMP/pipe" 2>"$FICY_ERR" &
pid=$!
wait "$pid"     # wait for any signals -> treat signal in trap above
wait "$pid"     # wait for fIcy (after the signal has been forwarded to fIcy in clean())

out=$(cat "$AWS_ERR" "$FICY_ERR")           # collect any output of aws and fIcy
```

Now, I consider the effect not as an Node issue and close it. I guess, the trap "absorbs" the `SIGINT`, and terminates the script regularly as all blocking commands (2x wait) are finished. Anyone an idea how to "forward" the `SIGINT` to the node spawn `exit` event, after trapping it in the bash script?

Thanks a lot
