### ISSUE TITLE
Open SSL error in node 0.12.6

### ISSUE THREAD

**Issue by jaime-ez** [joyent/node#25758]
Hi, I'm running a server that connects to a postgres database via SSL.
The connection is done, read and writes ok, but every 5 to 10 minutes I get this error:

[Error: select * from "blob" limit $1 - 140282535872288:error:140940E5:SSL routines:SSL3_READ_BYTES:ssl handshake failure:../deps/openssl/openssl/ssl/s3_pkt.c:1038:]

After ~4 consecutive errors, in a time span of ~20 minutes, I get TIMEDOUT and the connection is lost.

Any ideas on how to handle this?
Thanks

**Comment by misterdjules** [comment]
Do you have some some code (ideally with a minimal set of dependencies) with which we can reproduce this problem? Without this, it's very difficult to determine if it's actually a bug in Node.js' core itself.

So closing for now, but we'll be happy to reopen if you can provide us with code to reproduce it and more details like the version of node used and on which platform.

Thank you!
