### ISSUE TITLE
'Can\'t set headers after they are sent.

### ISSUE THREAD

**Issue by gentlecolder** [joyent/node#25757]
< _http_outgoing.js:335
<     throw new Error('Can\'t set headers after they are sent.');
<           ^
< Error: Can't set headers after they are sent.
<     at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
<     at Array.write (\node_modules\connect\node_modules\f
inalhandler\index.js:126:9)
<     at listener (\node_modules\connect\node_modules\fina
lhandler\node_modules\on-finished\index.js:169:15)
<     at onFinish \node_modules\connect\node_modules\fina
lhandler\node_modules\on-finished\index.js:100:5)
<     at callback \node_modules\connect\node_modules\fina
lhandler\node_modules\on-finished\node_modules\ee-first\index.js:55:10)
<     at IncomingMessage.onevent (\node_modules\connect\no
de_modules\finalhandler\node_modules\on-finished\node_modules\ee-first\index.js:
93:5)
<     at IncomingMessage.emit (events.js:104:17)
<     at _stream_readable.js:908:16
<     at process._tickCallback (node.js:355:11)

**Comment by CGavrila** [comment]
Do you have the code for this? You can't set the headers after `writeHead()`, so I assume that's what you're doing.

If your code looks like below, it's wrong.
```
res.writeHead(...);
res.setHeader(...);
```

**Comment by jasnell** [comment]
This is generally triggered by user code bugs.
