### ISSUE TITLE
http.request fails when host contains port

### ISSUE THREAD

**Issue by nfriedly** [joyent/node#25751]
`host` is different from `hostname` in that it may contain a port number. For example:

```js
require('url').parse('http://localhost:8080')
{ protocol: 'http:',
  slashes: true,
  auth: null,
  host: 'localhost:8080',
  port: '8080',
  hostname: 'localhost',
  hash: null,
  search: null,
  query: null,
  pathname: '/',
  path: '/',
  href: 'http://localhost:8080/' }
```
However, `http.request({options})` treats both fields as `hostname` and attempts an invalid DNS lookup when given a `host` with a port. For example:

```js
http.get({host: 'localhost:8080', path: '/'}, console.log)
```
```bash
> Error: getaddrinfo ENOTFOUND localhost:8080
    at errnoException (dns.js:44:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)
```

**Comment by nfriedly** [comment]
Fixed, with a test :)

**Comment by nfriedly** [comment]
I also though about possibly adding a `normalize()` method to the URL library, which would handle this and related things... but that would be a larger change.

**Comment by jasnell** [comment]
This is due to the fact that the object you're passing into `get` does not have enough information to construct the URL properly. If you pass in the full output from `url.parse` then it works fine.
```
var u = require('url').parse('http://localhost:8080');
require('http').get(u, function(err,res) { console.log(res.statusCode); });
```
Closing as it's not actually a bug in node. Yes, the API could be doing things better, but this is the way it's worked for a while and it's not going to be changing in either v0.10 or v0.12.

**Comment by nfriedly** [comment]
I respectfully disagree. There is enough information to make the request correctly, the patch I provided (https://github.com/joyent/node/pull/25752/files) does exactly that with a simple 3-line change.

This bug was found when writing unit tests for a remote server. I change the host that my library uses from "example.com" to "localhost:12345" to match the mock remote server that I set up and then run the tests.

**Comment by nfriedly** [comment]
(BTW, I'm OK if the fix doesn't get included in 0.10 and 0.12 - I'd just like to see it included eventually.)

**Comment by jasnell** [comment]
There are a number of issues with the url.parse response and the way url's are reconstructed from it. It's definitely a known issue, but it's certainly not going to be changing here. What I would recommend is moving discussion over to either the nodejs/io.js or nodejs/node repos.

**Comment by nfriedly** [comment]
Oh, alright. Thanks!
