### ISSUE TITLE
Windows long path because nested modules

### ISSUE THREAD

**Issue by cacio-costa** [joyent/node#25759]
First, sorry about my english. It's not good. Second, the way that modules are organized by Node / NPM is not appropriate. Nested modules are not the better solution for that. I think that a flat diretory, like "node_modules/module@0.0.0" save space and solve the long path problem.

I saw an issue from last year reporting this, but still not fixed.

**Comment by CGavrila** [comment]
@cacio-costa: I've hit this issue as well. The only way to solve it, as far as I know, is to shorten the path, use `subst` or something similar. Either way, that will not be ideal for most use cases.

NPM is a different project/company, however, and Node.js does not have a direct influence over the way it works. NPM has changed the way installed modules will be nested in the `node_modules` folder in version 3, but that might take a while to be upgraded in a Node version. 

What you can try is to upgrade NPM yourself for your Node installation, but then you might run into some weird behaviour.

**Comment by cjihrig** [comment]
You can try npm 3 today, but I believe it's still in beta. This issue has been hashed out in #6960, and npm is fixing it.
