### ISSUE TITLE
row[0].value TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by janototh** [joyent/node#25768]
So I've downloaded a code, upon filling the datas, Its just not working. I'm not an expert coder, but checking the line, and the whole function, Its maybe somethign wrong about the query (checked sql connection datas 9 times).
It would be a tradebot.

![eroq5e2 1](https://cloud.githubusercontent.com/assets/9253068/8891098/c90d9140-331a-11e5-871d-d18c26f024df.png)

Thanks in advance

**Comment by cjihrig** [comment]
Closing, as this is not an issue with node core. You're likely not getting any results back from the database. Check the values of `err` and `row`.
