### ISSUE TITLE
add Fishrock123 as collaborator

### ISSUE THREAD

**Issue by Fishrock123** [joyent/node#25775]
I talked a bunch to @misterdjules about this on IRC and he gave me a bit of a run-down between differences about how stuff was handled between here and io.js.

He also suggested we open an issue to notify everyone that I'd like to join. So cc ~~/*snip that was not the correct people lol*/~~? (I can't cc the core-team or tsc teams because they are set to private.)

Basically I'd like to be able to close/label the occasional issue that pops up into my feed that I end up answering. :P

**Comment by cjihrig** [comment]
+1 to adding @Fishrock123

**Comment by jasnell** [comment]
Obviously +1

**Comment by chorrell** [comment]
+1

**Comment by misterdjules** [comment]
@Fishrock123 Done, thank you very much for helping us go through the issues in this repo!

**Comment by Fishrock123** [comment]
Thanks, and no problem, though I'll only ever be able to handle a couple. :)

**Comment by srl295** [comment]
+11
