### ISSUE TITLE
Regexp inconsistency

### ISSUE THREAD

**Issue by bgdavidx** [joyent/node#25787]
A critical piece of code broke in production today due to a peculiar bug in Node's regular expressions.

The following code will alternate between true and false responses for RegExp.test() : 

    var rgx = /.*@mail.ru/gi

    rgx.test('blah@mail.ru') // true
    rgx.test('blah@mail.ru') // false

    // and it keeps alternating between true and false

How can a regular expression return inconsistent results for the same string?

This happens on:

Node.js v0.12.4
io.js v2.3.4

**Comment by cjihrig** [comment]
This isn't because of Node. The `g` flag on the regex maintains state between calls.
