### ISSUE TITLE
Configure fileName of log4js in RollingFileStream

### ISSUE THREAD

**Issue by viddeshshinde** [joyent/node#25783]
I am using log4js to log in my node js application. I have configured logger to create a new file when the file size reaches certain max size. The logger creates a file with same filename and '.' and index number is appended to the file name where index number is incremented every time a new file is created.

For e.g., running file is having filename as: 20150730060112.log then next files created are as 20150730060112.log.1, 20150730060112.log.2 20150730060112.log.3 and so on...

I want a next file to be created with current timestamp and not with '.1'.

**Comment by georgewhite5** [comment]
Are you sure this is an issue of node, and not an npm package?

**Comment by georgewhite5** [comment]
The first result for `log4js` is https://github.com/nomiddlename/log4js-node, shouldn't you report it as an issue there?

**Comment by eziante** [comment]
This is an issue that should be addressed to log4js indeed but isn't the file already containing the timestamp?
20150730060112 = 2015-07-30T06:01:12

**Comment by viddeshshinde** [comment]
@eziante  The first file is already having timestamp when it was created. Now when a new file is created it takes same name and not the current timestamp when it is being created.

**Comment by viddeshshinde** [comment]
@georgewhite5 Thanks I was not aware of it.
