### ISSUE TITLE
build: VS2015 failure (ICU) back port from io.js

### ISSUE THREAD

**Issue by srl295** [joyent/node#25792]
https://github.com/nodejs/io.js/issues/2279 will affect 0.12+ as well under VS2015 with `Intl` on.

Basically, VS2015 broke ICU. We'll fix it in ICU 56.

It should apply cleanly, but I couldn't get VS2015 to build with `joyent/node/master`.

I will open a PR anyway, but will need some help testing.

NB this also adds a general mechanism for floating patches on top of ICU.
@orangemocha

**Comment by joaocgreis** [comment]
Fixed by 4f2456369c80ae940fb654e16afda15b9bb4a349.
