### ISSUE TITLE
CI / node-accept-pull-request moving to new Jenkins

### ISSUE THREAD

**Issue by orangemocha** [joyent/node#25808]
To all @joyent/node-collaborators:

As part of the CI convergence effort, we want to transition collaborators from the [old Jenkins](http://jenkins.nodejs.org/) to the [new Jenkins](https://jenkins-iojs.nodesource.com/).

node-accept-pull-request is now fully functional in the new Jenkins, so please update your bookmarks to https://jenkins-iojs.nodesource.com/job/node-accept-pull-request/

You should keep using node-accept-pull-request for landing all PRs in joyent/node. And since it now supports v0.10, it should be used for v0.10 PRs as well.

**However, please refrain from using it for io.js.** There are a couple of things that need to be fixed before it can used there (support for flaky tests, speeding up the build). And since collaborators are pushing directly to GitHub in io.js, that would break your node-accept-pull-request run even if you decided to take a chance with flaky tests.
For io.js, please use the existing workflow and [node-test-pull-request](https://jenkins-iojs.nodesource.com/job/node-test-pull-request/) (https://github.com/nodejs/io.js/issues/2263). node-test-pull-request can also be used against joyent/node and for testing-only it is the preferred solution, because it can have multiple parallel runs, unlike node-accept-pull-request. The plan is for the two jobs to coexist in the long term.

Improvements in the new node-accept-pull-request:

1. It works with all branches: including v0.10 and master. Soon, it will support the converged repo and io.js too.
2. The target branch of the PR is inferred automatically. For more advanced operations like changing the target branch or doing branch merges, you can also use the underlying job [node-accept-commit](https://jenkins-iojs.nodesource.com/job/node-accept-commit/build?delay=0sec).
3. The input form now supports up to 4 reviewers on separate lines.
4. If you are landing a PR that only touches docs, you can set NODES_SUBSET to `pure_docs_change` to skip the tests. Otherwise you can leave it set to `auto`.

Note that your full name and email address as set in Jenkins are used to populate the commiter field in the git commit. I already went through and reviewed/updated all the [accounts in the new Jenkins](https://jenkins-iojs.nodesource.com/securityRealm/),
but please take a moment to check that your name and email address correspond to what you would like them to appear in the git logs. On the top-right, click on your name, and then on the left click on 'Configure'.

The old-Jenkins version of node-accept-pull-request will be disabled ASAP so that the two jobs don't conflict with each other. In a couple of weeks, barring any unforeseen issues, we are going to start transitioning some hardware resources to the converged CI.

I will also submit a PR to update the documentation at
https://nodejs.org/contribute/code_contributions/workflow.html#workflow_md_using_jenkins_to_build_test_and_merge_every_pr

Let me know if you have any questions or concerns.

(cc @misterdjules @rvagg @jbergstroem)

**Comment by misterdjules** [comment]
@orangemocha It seems node-test-pull-request fails when I try to use it: https://jenkins-iojs.nodesource.com/job/node-test-pull-request/63/.

**Comment by orangemocha** [comment]
@misterdjules yeah, there was a bug in the rebase logic when a previous job run was aborted in the middle of a rebase. Should be fixed now: https://jenkins-iojs.nodesource.com/job/node-test-pull-request/65/

**Comment by misterdjules** [comment]
@orangemocha Thank you!

My latest run of node-test-pull-request [failed on flaky tests](https://jenkins-iojs.nodesource.com/job/node-test-commit-linux/nodes=ubuntu1204-64/lastBuild/). It seems that it doesn't ignore failures for flaky tests by default, and that there's no parameter to change that. Is that correct or am I missing something?

**Comment by orangemocha** [comment]
That is correct. Support for flaky tests is still missing in io.js, and while it might be useful for the test job as well, I wanted to first introduce it in the context of the node-accept-pull-request workflow, where it's absolutely needed.

You may still use node-accept-pull-request with APPLY_CHANGES unchecked. The only downside is that its runs will be serialized, whereas node-test-pull-request can have multiple concurrent runs. Since very few people are using node-accept-pull-request at the moment, it shouldn't make much of a difference.

Your feedback is definitely appreciated. Thanks!
