### ISSUE TITLE
I can't install with npm

### ISSUE THREAD

**Issue by sespin** [joyent/node#25800]
Hi, I try install yeoman and bower and the installation never finish.

Any can help?
![npm_loop](https://cloud.githubusercontent.com/assets/13623975/9037038/61812c34-39e7-11e5-9465-fe142033be7c.png)
![npm_loop_verbose](https://cloud.githubusercontent.com/assets/13623975/9037042/68ea5edc-39e7-11e5-9371-4ff4afdac9ce.png)

**Comment by cjihrig** [comment]
If you're still having this problem, please open this issue on the npm issue tracker.
