### ISSUE TITLE
http.Server hangs when using child_process.execSync

### ISSUE THREAD

**Issue by JoshWillik** [joyent/node#25810]
The following code causes the `http.Server` to receive connections and never respond.

```js
var exec = require( 'child_process' ).execSync

require( 'http' ).createServer( function( req, res ){
  res.writeHead( 200, {
    'Content-Type': 'text/plain'
  })
  res.end( 'hello' )
}).listen( function(){
  var port = this.address().port
  var command = 'curl http://localhost:' + port
  console.log( command )
  console.log( exec( command ) )
})
```

Placing the `exec( command )` inside a `setImmediate` or `setTimeout` both fail to solve the issue.

**Comment by evanlucas** [comment]
I don't see `exec` even being called in here, but if you are using it inside of the request handler, then, yes, it will block. You would need to use `child_process.exec` over `child_process.execSync`

**Comment by cjihrig** [comment]
You need to use `exec()` instead of `execSync()`. Calling `execSync()` causes the program to block until the server responds, but the server can't respond because the program is blocked.

**Comment by JoshWillik** [comment]
Oh I see. In hindsight, that makes a lot of sense. I forgot that the event loop is still single threaded.
Sorry guys!

**Comment by Tiggs** [comment]
Hi, I found some info and I thought it might be interesting for you, please read more at <http://fripobunka.nathanlinzer.com/lndqxn>

Thx, tiggs@puppyrush.net
