### ISSUE TITLE
Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND __DNS_NAME_OF_MY_PROXY_SERVER__

### ISSUE THREAD

**Issue by nodejs-user** [joyent/node#25837]
When proxy server is defined by DNS name then Node fails with the following error:

> Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND __DNS_NAME_OF_MY_PROXY_SERVER__

Examples of failing commands (proxy is defined by DNS name):
> npm --proxy http://proxy:8080 --https-proxy=http://proxy:8080 search polymer
> npm --proxy http://proxy.intranet.org:8080 --https-proxy=http://proxy.intranet.org:8080 search polymer

Example of successful command (proxy is defined by IP address):
> npm --proxy http://192.168.1.1:8080 --https-proxy=http://192.168.1.1:8080 search polymer

The issue is reproducible on Node releases v0.11.14 - v0.12.7 (latest).
The last release where the issue is NOT reproducible is v0.11.13. 

My environment is:

Characteristic | Value
------------ | -------------
OS | Windows 7
Arch | 64 bit
User Rights | NO Administrator's rights. That's why I'm unable to install Node using installer for Windows. So, I'm manually downloading https://nodejs.org/dist/v0.12.7/x64/node.exe and http://registry.npmjs.org/npm/-/npm-2.11.3.tgz

**Comment by cjihrig** [comment]
Would you mind opening this on the [npm issue tracker](https://github.com/npm/npm)? If it turns out to be an issue with Node core, we can reopen.
