### ISSUE TITLE
Improve support for extending node core

### ISSUE THREAD

**Issue by mcurcio** [joyent/node#2584]
Currently, _third_party_main.js provides an awesomely simple method for packaging node into arbitrary cross-platform executables.  There are a couple of areas where this process could be improved for those of us looking to make "larger" apps out of the node.js infrastructure.

A couple of ideas:
1) Allow custom .gyp files to be passed through configure/make.  The idea here is that I would like to not touch the existing joyent/node repo and put it under a deps/ folder in my build tree so that it can be updated at anytime -- but still be able to pass in _third_party_main and other files to the build process.

2) Support for core js multi-file libraries.  I dont know if this is a V8 limitation, but it would be neat to be able to organize the js core files under a folder hierarchy.  I'm not sure what a require() would look like, so perhaps this idea needs fleshing out.

Edit (April 11, 2012):
3) Move the startup arg parsing to node.js, thereby allowing custom _third_party_main implementations full control.  A trivial example of this would be creating a custom `./app --help` handler.  This is currently handled in C++ before the JS environment is loaded, and therefore cannot be overridden.  A more complex example would be delaying the creation of the debug thread until explicitly created from node.js.  A custom implementation may or may not want to create the debug thread (maybe its default in a Debug build, but disabled in Release).  In short, it would be awesome if ALL of the startup args were handled in javascript.

**Comment by jasnell** [comment]
Would io.js pre-loaded modules apply here?

**Comment by jasnell** [comment]
Not likely to ever happen here.
