### ISSUE TITLE
test-http-dns-fail.js failing on Jenkins

### ISSUE THREAD

**Issue by misterdjules** [joyent/node#25858]
`test-http-dns-fail.js` was in the list of flaky tests at some point, and then [got removed from the list of flaky tests](https://github.com/joyent/node/issues/25673) when all Jenkins agent stopped using the specific DNS server(s) that do not respond with an error when trying to resolve a clearly invalid hostname. 

Now that we started using the CI platform at jenkins-iojs.nodesource.com, some of the Jenkins agents that this platform uses [still trigger a failure for this test](https://jenkins-iojs.nodesource.com/job/node-test-commit-other/123/nodes=smartos14-64/tapTestReport/test.tap-798/). It could be because these agents are still configured to use these "faulty" DNS servers.

@orangemocha @joaocgreis @jbergstroem @rvagg Would you mind checking if these SmartOS CI agents still have `4.2.2.2` in `/etc/resolv.conf`? I currently can't access a shell on these agents.

**Comment by joaocgreis** [comment]
I added `4.2.2.2` in the 32 bit Smart OS machine (was already there in the 64 bit one).

**Comment by joaocgreis** [comment]
... but that was not the machine where the test failed. Let me try to run it manually there.

**Comment by joaocgreis** [comment]
@misterdjules @orangemocha  Ok, the objective was to remove it, not add it. Sorry for the confusion, it is fixed now and works.

@jbergstroem @rvagg on the 64 bit machine, there was also a `216.52.1.1` server in `/etc/resolv.conf`, because of it the test took 1 full minute to complete. I commented that line. Is it ok to remove completely or was there for some reason?

**Comment by misterdjules** [comment]
@joaocgreis Thank you :+1: Can we close this issue then?

**Comment by jbergstroem** [comment]
@joaocgreis not sure where that came from. Happy to let it go.

**Comment by joaocgreis** [comment]
@jbergstroem ok, preparing PR.

@misterdjules sure, seems all ok now.
