### ISSUE TITLE
build: intl: bump ICU from 54 to 55 (backport)

### ISSUE THREAD

**Issue by srl295** [joyent/node#25855]
Retarget of  #25790, backport of nodejs/node#2292 : 
> node is using ICU 54 ( 2014-oct-06 ).
> Bump to 55 ( 2015-apr-08)
> Note that ICU 56 is scheduled for 2015-oct ish.

(Node: the "iojs-backport" label seems like a bit of an anachronism now… )

**Comment by joaocgreis** [comment]
Fixed by 15030f26fdc1f1024748eceaf75eccfb650c9b9c.
