### ISSUE TITLE
typeof process.env.NODE_ENV is string. not undefined

### ISSUE THREAD

**Issue by bells17** [joyent/node#25873]
Become `typeof process.env.NODE_ENV` is `string` when assigned `undefined` to `process.env.NODE_ENV`.
Why?

```
$ node -v
v0.10.26

$ node
> process.env.NODE_ENV
undefined
> process.env.NODE_ENV = 'development'
'development'
> process.env.NODE_ENV
'development'

> process.env.NODE_ENV = undefined
undefined
> process.env.NODE_ENV
'undefined'
> typeof process.env.NODE_ENV
'string'
```

**Comment by ollie314** [comment]
I reproduce the case on the v 0.10.29 on both windows (7) and linux (Debian 8.1) env.

**Comment by a0viedo** [comment]
I don't know if this is the expected behavior or not, but a workaround if you want to actually remove an environment variable is to do `delete process.env.NAME`.

**Comment by thefourtheye** [comment]
This is really not a bug. When you store an object in the environment, first the object is stringified and that string is stored. More examples,

    > process.env.NODE_ENV = {}
    {}
    > process.env.NODE_ENV
    '[object Object]'
    > process.env.NODE_ENV = [1, 2, 3]
    [ 1, 2, 3 ]
    > process.env.NODE_ENV
    '1,2,3'

**Comment by ollie314** [comment]
On rhino, doing the same process 
```javascript
 var t = {};
>> undefined
typeof t.test
>> "undefined"
t.test = 'foo'
>> "foo"
typeof t.test
"string"
t.test = undefined
>> undefined
typeof t.test
"undefined"
t.test === undefined
>> true
```

The last test give me false on node.
```javascript
//...
// same process as above
//...
t.test = undefined
t.test === undefined
>> false
```

**Comment by a0viedo** [comment]
@ollie314 this is the behavior when assigning properties to `process.env`, not with any empty object.

**Comment by ollie314** [comment]
@a0viedo Sorry about this error.

**Comment by bells17** [comment]
@a0viedo Oh, I get it. Thank you for teaching.
