### ISSUE TITLE
Wrong version explicitly specified in ReadMe.md

### ISSUE THREAD

**Issue by pulkitnandan** [joyent/node#25879]
Visit and fire those steps @ https://github.com/joyent/node/wiki/installation#building-on-linux

ver=0.12.7 #Replace this with the latest version available
wget -c http://nodejs.org/dist/v$ver/nodejs-v$ver.tar.gz #This is to download the source code.
tar -xzf node-v$ver.tar.gz
cd node-v$ver
./configure && make && sudo make install

Where wget address is wrong.

**Comment by a0viedo** [comment]
```
wget -c http://nodejs.org/dist/v$ver/nodejs-v$ver.tar.gz
```
should be
```
wget -c http://nodejs.org/dist/v$ver/node-v$ver.tar.gz
```

I would make a PR if I only knew how to do it for the wiki section. @cjihrig @misterdjules any suggestions on how to that?

**Comment by cjihrig** [comment]
Do you have an "Edit" button in the top right corner of the page?

**Comment by a0viedo** [comment]
@cjihrig oh I didn't knew it was THAT easy. Anyone could edit the wiki?

**Comment by cjihrig** [comment]
I think so. A drawback IMO. Anyway, thanks for fixing it.
