### ISSUE TITLE
Feature: Loop introspection

### ISSUE THREAD

**Issue by fresheneesz** [joyent/node#25894]
Every once in a while I have a hanging node.js process, and I have no idea why it hangs. It could take me hours to figure it out. It would be great if there were ways to ask the program things like:
* How many open file descriptors are there? What kinds of things are they: (type [network, file system file, input descriptor], name ["http connection to <some IP address>"], etc)?
* How many waiting timers are there? What callback(s) are associated with them (so you could print out the text of the functions)?

This would go a very long way in making hanging scripts easier to debug.

**Comment by jasnell** [comment]
@fresheneesz ... at this point the right place for feature requests and discussion is the issue tracker on http://github.com/nodejs/node. The joyent/node repo is in mid transition.
