### ISSUE TITLE
Cannot open shared object file: No such file or directory     

### ISSUE THREAD

**Issue by HmidiSlim** [joyent/node#25891]
I create a node application wich need to create from a C program a node module.I used SWIG (Simple wrapper Interface Generator) to do that and I got the node module.The application run successefuly on my PC.I want now to cross compile my application to run it on Beaglebone Black.I run this command:

node-gyp --arch=arm configure
it works very well but when I run :

node-gyp build 
I got this message:
odule.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /home/user/a/build/Release/example.node: cannot open shared object file: No such file or directory
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/user/a/app.js:21:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

**Comment by dnakamura** [comment]
Are you running this on your pc? If so its expected (this behavior happens when you try to load a shared lib for the wrong architecture)

**Comment by HmidiSlim** [comment]
I tried it on the BeagleBone Black.

**Comment by dnakamura** [comment]
Does the given file actually exist? If so can you check what architecture the library is built for? ie
```readelf -h /home/user/a/build/Release/example.node ```

**Comment by HmidiSlim** [comment]
I fixed the problem I cross compile it for arm architecture.Thanks for your help.
