### ISSUE TITLE
Arrow Functions with Rest Paramters, Not Working

### ISSUE THREAD

**Issue by eblahm** [joyent/node#25914]
``` console
$ iojs --version
v3.1.0
$ iojs --harmony_arrow_functions --harmony_rest_parameters -e "var restArrow = (...args) => console.dir(args); restArrow('a', 'b');"
[eval]:1
var restArrow = (...args) => console.dir(args); restArrow('a', 'b');
                 ^^^

SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:53:16)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:430:26)
    at node.js:566:27
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
```

**Comment by eblahm** [comment]
MDN docs for arrow functions say that rest parameters should be supported in Chrome 45.0 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

> // Rest parameters are supported
> (param1, param2, ...rest) => { statements }

**Comment by eblahm** [comment]
Based on testing in the Chrome 45.0 console, it doesn't work so... I guess a bug needs to be opened in v8 and MDN docs need to change.

**Comment by ChALkeR** [comment]
From Readme (as seen on https://github.com/nodejs/node-v0.x-archive):

> New issues and pull requests, for all branches, should be opened at [nodejs/node](https://github.com/nodejs/node). 
> New issues and pull requests opened here will automatically be rejected.

**Comment by ChALkeR** [comment]
Also see https://github.com/nodejs/node/issues/1655.
