### ISSUE TITLE
Should document that Debian packages require a symlink

### ISSUE THREAD

**Issue by alexpdp7** [joyent/node#25925]
Hi all,

https://github.com/nodejs/node-v0.x-archive/wiki/Installing-Node.js-via-package-manager#ubuntu-mint-elementary-os mentions that one can install Node using downstream Debian packages:

> A Node.js package is also available in the official repo for Debian Sid (unstable), Jessie (testing) and Wheezy (wheezy-backports) as "nodejs".

If you install that, you can experience some problems such as:
- https://github.com/Medium/phantomjs/issues/157#issuecomment-42881522

; if you check that ticket, it seems to imply that the Node documentation I linked above explains that you should do:

```
ln -s /usr/bin/nodejs /usr/bin/node
```

, but that's no longer the case.

Can that documentation be reinstated?

Cheers,

Álex

**Comment by bnoordhuis** [comment]
You're welcome to edit it yourself, it's a wiki and community maintained.

**Comment by alexpdp7** [comment]
There you go:

https://github.com/nodejs/node-v0.x-archive/wiki/Installing-Node.js-via-package-manager/_compare/7e18abccb2d445b834e5a8e950ceee002e3c031b...81926dadbf1c4175c54acab79f60c58522e2500e

, if that's OK feel free to close the ticket.
