### ISSUE TITLE
unsuccessful using this debugger

### ISSUE THREAD

**Issue by GarryFlemings** [joyent/node#25927]
I offer the following in case it helps. If it feels like complaint, please ignore.

I followed (or tried to) the instructions at
https://github.com/nodejs/node-v0.x-archive/wiki/Using-Eclipse-as-Node-Applications-Debugger

All went well to below the heading "Sample Debugging Session", at the line, "The breakpoint will be reached within a second:". My running instance of dbgtest.js continued merrily along, oblivious to the breakpoint I'd set. Nertz!

Just below that, I followed instructions to start the script with "node --debug-brk dbgtest.js". All I got was
--- start ---

> node --debug-brk dbgtest.js
> Debugger listening on port 5858
> --- end ---

I'm running Win10 with Node 5.0. I hope that helps ...

**Comment by ChALkeR** [comment]
See [README.md](https://github.com/nodejs/node-v0.x-archive/blob/moved/README.md).

If you believe that this is an issue with Node.js, please open an issue at [nodejs/node](https://github.com/nodejs/node).

**Comment by ChALkeR** [comment]
Ah.

If this is a support question, please ask on the [nodejs/help](https://github.com/nodejs/help/issues) repo, [IRC](http://webchat.freenode.net/?channels=Node.js), [Gitter](https://gitter.im/nodejs/node), or [StackOverflow](http://stackoverflow.com/).
