### ISSUE TITLE
V8 built with Big Endian option when cross-compiled for mips

### ISSUE THREAD

**Issue by pmclee** [joyent/node#25921]
I'm cross-compiling V8 for mipsel as part of the nodejs package. I was able to configure node to compile for mips / little endian and that works. But the little-endian option is not propagating down into the V8 build. When the V8 source is being built I see the compiler option -EB instead of -EL being used and the link fails because the libraries are all little endian.

How do I configure node to build V8 with the little-endian option? I've been digging through the config options and the Makefiles. I'm running this configure command:

```
$ ./configure --dest-cpu=mipsel
```

Is there some other option I also need to be using? I'm pretty good with reading Make files and shell scripts, but I'm gyp-illiterate so I cannot figure out what is going on there.

**Comment by bnoordhuis** [comment]
Have you tried v4.x yet?  While mipsel is not a supported architecture at the moment, v4.x is known to work on it.

**Comment by pmclee** [comment]
It worked! Thanks for the reply. It appears that all the dependencies are being built with -EL now, which is exactly what I was hoping for.

However, there is another issue. Not sure if I should create a new topic for it, so I'll post it here and see how that works. :^)

At the moment our MIPS environment is running an older linux built with gcc 3.4, but our application requires 3.9. It's a long story, but bottom line is that for the next couple of weeks I need to build with 3.9 and run in this older 3.4 environment -- if possible.

My strategy was to build nodejs with static libraries by building/making it like this:

```
export CC=mipsel-linux-gnu-gcc
export CXX=mipsel-linux-gnu-g++
export LINK=mipsel-linux-gnu-g++
export CFLAGS=-EL
export GYPFLAGS=-Dv8_target_arch=mipsel
./configure --fully-static --dest-cpu=mipsel --dest-os=linux && make
```

But when I tried running a test "hello world" node app, I can see that something is not quite right. I'm not sure if I am reading the error messages right, either, because it appears that nodejs has somehow loaded libstdc++.so.6 (which I didn't think it would do, being statically linked). Further, it also appears that the `so` fails because it is looking for 3.4 libraries (which should be what is installed).

```
root@TestMachine:/var/node# node testServer.js
node: /lib/libc.so.6: version `GLIBC_2.19' not found (required by node)
node: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by node)
node: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by node)
```

So maybe I need to back up for a moment and ask some questions:
- is there some different/additional config option that I should be using?
- is there an environment variable that I'm missing?
- or is there some other way to generate a statically linked target?

**Comment by pmclee** [comment]
I am marking this issue as closed and creating a new issue for the second part.
