### ISSUE TITLE
DNS Server address

### ISSUE THREAD

**Issue by tahasiddiqui123** [joyent/node#25939]
Hello, I am new to node.js and i just want to get the DNS server address of both lan and wifi connected interfaces.
How can i get these two different DNS server addresses at the same time.

**Comment by ChALkeR** [comment]
[README.md](https://github.com/nodejs/node-v0.x-archive/blob/moved/README.md):

> New issues and pull requests opened here will automatically be rejected.

If you belive that this is an issue with Node.js, report it to https://github.com/nodejs/node, but to me it looks like a problem with something other than Node.js, most likely a support question — so you should ask this elsewhere.

If this is a support question, then you are asking for help in the wrong place. Please ask on the [nodejs/help](https://github.com/nodejs/help/issues) repo, [IRC](http://webchat.freenode.net/?channels=Node.js), [Gitter](https://gitter.im/nodejs/node), or [StackOverflow](http://stackoverflow.com).

**Comment by ChALkeR** [comment]
Upd: text changed, wrong copy-paste. Please view on GitHub.

**Comment by tahasiddiqui123** [comment]
ohh ok thanks for the suggestion.
