### ISSUE TITLE
dns.js not recognize family. Is always undefined.

### ISSUE THREAD

**Issue by lags** [joyent/node#25933]
I have an error when try install any package via npm.
As explained to https://github.com/npm/npm/issues/10822
The problem is:

```
dns.js
```

in family that return always undefined. Only if i force to:

```
family = 4;
```

work correctly.
How to solve my problem?
Tanky you in advance

**Comment by bnoordhuis** [comment]
From your description in npm/npm#10822 it sounds like your DNS server returns an (unreachable) IPv6 address for `AF_UNSPEC` name lookups; `AF_UNSPEC` is the default when `family` is not specified.  I don't think that is an issue with node.js but it may be an issue with npm if there is no way to override the address family from the command line.

I'll go ahead close this bug report.  If you have more information, please file an issue [here](https://github.com/nodejs/node/issues); this repo is for archival purposes only.
