### ISSUE TITLE
Can't run npm after mup setup

### ISSUE THREAD

**Issue by KalalauEnterprises** [joyent/node#25935]
mup setup ran fine. When running mup deploy, the upload and env setup work fine, but Invoking Deployment Process gets:

<code>
Invoking deployment process: FAILED

```
-----------------------------------STDERR-----------------------------------
/usr/bin/npm: 2: exec: /usr/bin/node: not found
-----------------------------------STDOUT-----------------------------------
 > ./bcrypt: npm install due to binary npm modules
----------------------------------------------------------------------------
```

</code>
When I ssh in and try to run npm, I get:
<code>
/usr/bin/npm: 2: exec: /usr/bin/node: not found
</code>
All of the symbolic links are present in /usr/lib (node and npm) they point to /opt/nodejs/bin/
Any ideas?

**Comment by mbilker** [comment]
Is it possible some libraries were updated? Could you run `ldd /opt/nodejs/bin/node`?

**Comment by ChALkeR** [comment]
[README.md](https://github.com/nodejs/node-v0.x-archive/blob/moved/README.md):

> New issues and pull requests opened here will automatically be rejected.

If you belive that this is an issue with Node.js, report it to https://github.com/nodejs/node, but to me it looks like a problem with something other than Node.js (probably mup?) — so you should report this issue to some other project.

If this is a support question, then you are asking for help in the wrong place. Please ask on the [nodejs/help](https://github.com/nodejs/help/issues) repo, [IRC](http://webchat.freenode.net/?channels=Node.js), [Gitter](https://gitter.im/nodejs/node), or [StackOverflow](http://stackoverflow.com/).

**Comment by mada41** [comment]
i got same error too :cry:
