### ISSUE TITLE
socket stay in ESTABLISHED status 

### ISSUE THREAD

**Issue by gogorush** [joyent/node#25936]
Hello, guys

I found myself in trouble with closing socket properly in nodejs.
I tried to close socket connections from server side(nodejs side) with socket.end() (with socket.destroy() function follows, just to make sure about everything I can do with Javascript). But I found out lots of sockets are not closed (using ss & netstat) and stay in ESTABLISHED status forever.
The problem is  :  I already called socket.end() and listen to the 'close' event (for logging and sure the socket is 'closed' by javascript code).Lots of the sockets supposed to be closed while still open when I check socket connections with netstat. The only difference I could think of is the networks are generally bad in reality so that if send FIN to client, there would be no response and sockets hang there forever. What I don't understand is after I called end() and destroy() in nodejs, the socket is expected be jumped into FIN_WAIT mode.
The solution I used is setKeepAlive(true). And then the ESTABLISHED  sockets could be closed do to the check packages from the system level (By setting net.ipv4.tcp_keepalive_time). 
I found thread #3613 is about sockets stay in FIN_WAIT2 status. Not sure if it is connected with my problem.

Plantform: Ubuntu 14.04
Node : 4.2.x
CPU: 48 cores Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz
Memory: 128GB
Some system settings: 

```
net.ipv4.tcp_sack = 1
net.ipv4.tcp_window_scaling = 1
net.ipv4.tcp_rmem = 4096        87380   4194304
net.ipv4.tcp_wmem = 4096        16384   4194304
net.core.wmem_default = 8388608
net.core.rmem_default = 8388608
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.core.netdev_max_backlog = 262144
net.core.somaxconn = 2621440
net.ipv4.tcp_max_orphans = 3276800
net.ipv4.tcp_max_syn_backlog = 2621440
net.ipv4.tcp_timestamps = 0
net.ipv4.tcp_synack_retries = 1
net.ipv4.tcp_syn_retries = 1
net.ipv4.tcp_tw_recycle = 0
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_mem = 94500000 915000000 927000000
net.ipv4.tcp_fin_timeout = 1
net.ipv4.tcp_keepalive_time = 30
net.ipv4.ip_local_port_range = 1024    65000
vm.overcommit_memory=1
net.ipv4.tcp_max_tw_buckets = 6000
net.netfilter.nf_conntrack_max=13107200
vm.swappiness = 20
fs.file-max = 8000000
fs.nr_open = 8000000
```

**Comment by evanlucas** [comment]
@gogorush can you please open this issue at https://github.com/nodejs/node. This repository is for the archived versions. Thanks!
