### ISSUE TITLE
404 for http://nodejs.org/industry/ on companies using Node.js page

### ISSUE THREAD

**Issue by LarryKlugerDS** [joyent/node#25938]
On page https://github.com/nodejs/node-v0.x-archive/wiki/Projects%2C-Applications%2C-and-Companies-Using-Node

the introduction to the page refers to http://nodejs.org/industry/ 
But it is a dead link.

The same page refers to https://github.com/joyent/node-in-the-industry
but it is an obsolete, unsupported page

**Comment by fhemberger** [comment]
Well, it's a 404 because the information which was originally there has been outdated/unmaintained for a very long time, so it was removed. I removed the first paragraph containing both links mentioned from the wiki article. So there is no redirect needed.

Issue can be closed.
