### ISSUE TITLE
Can't install bower on ubuntu 14.04 using npm

### ISSUE THREAD

**Issue by bekaarcoder** [joyent/node#25934]
I am trying to install bower on ubuntu using the following command:
sudo npm install -g bower;
But I am getting the follwing error in the terminal:-

npm ERR! Linux 3.19.0-39-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "bower"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12

npm ERR! shasum check failed for /tmp/npm-21536-863776a6/registry.npmjs.org/bower/-/bower-1.7.1.tgz
npm ERR! Expected: 8d0c1a31d85237b3629fd2af981bd11e1b1dca82
npm ERR! Actual:   6986215d879369a897bc8b9ca9451c4e62abbba9
npm ERR! From:     https://registry.npmjs.org/bower/-/bower-1.7.1.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /home/shashank/npm-debug.log

Please help this out.

**Comment by MylesBorins** [comment]
hey @shashanksmaty it looks like the sha of you downloaded package is not lining up with the expected sha in the npm meta data.

you may want to try `npm cache clean` and install again. That being said this is not a problem with node so I'm going to close this.

You may get some answers posting this on https://github.com/npm/npm/issues

**Comment by bekaarcoder** [comment]
It worked. Thanks
