### ISSUE TITLE
how to set up node.js express

### ISSUE THREAD

**Issue by ghost** [joyent/node#25930]
Hi, I'm new to Javascript and node.js and would like to ask how do i install node.js express ?
I was given the instruction - npm install express@4.6.1 to run at the command prompt, but I get the message 

C:\Users\Administrator\workspace\LearningJavaScript>npm install express@4.6.1
learningjavascript@1.0.0 C:\Users\Administrator\workspace\LearningJavaScript
└── express@4.6.1  invalid

can anyone tell me where i went wrong ?

**Comment by cjihrig** [comment]
Can you please ask your question at https://github.com/strongloop/express or https://github.com/nodejs/help.
