### ISSUE TITLE
I am getting this error when I execute my script in Nodejs 

### ISSUE THREAD

**Issue by sernapallyanurag** [joyent/node#25979]
OS: Windows 7
Code: 

``` Node.js
     exports.testscript=function(req,res){
    var exec = require('child_process').exec;
    console.log("inside function");

    var child = exec('chef-apply C:\\Users\\xyz\\chef-repo\\azurepro.rb' ,function(error, stdout, stderr){
        console.log(stdout); 
        console.log(stderr); 
        if (error !== null) {
          console.log(error);
        }
            });

    child.stdin.end();

};
```

error:

C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/defaults/operating_system.rb:28:in `expand_path': no implicit conversion of nil into String (TypeError)
{ [Error: Command failed: cmd.exe /s /c "chef-apply C:\Users\xyz\chef-repo\azurepro.rb "

this is due to "," in exec(). I tried putting it in +","+ but doesn't give any output if I do so. Can you suggest me a way to separate **function(error, stdout, stderr)** like in Spawn

**Comment by cjihrig** [comment]
Please open this issue on the nodejs/node repo. This repo is no longer active.
