### ISSUE TITLE
How to resolve this error??

### ISSUE THREAD

**Issue by mueedahmed1** [joyent/node#25977]
![untitled](https://cloud.githubusercontent.com/assets/12622228/13396825/82b16b7c-df18-11e5-9c01-3fedd24d5215.png)

**Comment by joaocgreis** [comment]
@mueedahmed1 this repository is just an archive, can you create an issue in https://github.com/nodejs/node/issues/new if you still have this problem?

If you do, please include an installation log: In the folder where you have the MSI, hold shift and right click the folder (not the MSI) and select "Open command window here". Then run `msiexec /i node-v6.2.0-x64.msi /L*v NodeInstallLog.txt` (adjust the MSI file name).
