### ISSUE TITLE
Make mosaico be accesible over the internet

### ISSUE THREAD

**Issue by eiertee** [joyent/node#25975]
Hey guys,

I'm relatively new to all this and i am trying to have mosaico reachable from an outside server.

Could you please just point me in te right direction to achieve this?

Thank you

**Comment by ChALkeR** [comment]
[README.md](https://github.com/nodejs/node-v0.x-archive/blob/moved/README.md):

> New issues and pull requests opened here will automatically be rejected.

If you belive that this is an issue with Node.js, report it to https://github.com/nodejs/node, but to me it looks like a problem with something other than Node.js, most likely a support question — so you should ask this elsewhere.

If this is a support question, then you are asking for help in the wrong place. Please ask on the [nodejs/help](https://github.com/nodejs/help/issues) repo, [IRC](http://webchat.freenode.net/?channels=Node.js), [Gitter](https://gitter.im/nodejs/node), or [StackOverflow](http://stackoverflow.com).
