### ISSUE TITLE
process.send is sync

### ISSUE THREAD

**Issue by AndreasMadsen** [joyent/node#2598]
testcase: https://gist.github.com/1663885

When using `child_process.fork` a `process.send` method exist in the child, allowing one to send objects and strings to the parent. But the method is sync!. Note that the parent get new messages using `child.on('message')` and this is fully async.

I think this is in violation with the node.JS never block policy.

**Comment by jasnell** [comment]
@indutny ... do you happen to know the status of this one?

**Comment by jasnell** [comment]
This does not actually appear to be a bug. There are fairly straightforward workarounds and the docs are clear that send is sync and that sending large amounts of data using send is not recommended. Closing. Can reopen if new information is received.
