### ISSUE TITLE
Install problem Node, error 1603

### ISSUE THREAD

**Issue by Xamsix** [joyent/node#25987]
Hey Guys,

So yesterday I wanted to update my Node version, unfortunately, even though the update was a success, when checking my Node version it was still displaying an old version. Whatever I tried, there was no way to get Node updated properly. So I decided (I'm on Windows btw) to remove all my Node folders and NPM folders.

Then I downloaded the .msi file from the Node site. However, at the end of installation a rollback was done and the installation ended prematurely. 

So I tried a few things, like starting the installation from command line. Starting command line as an administrator and trying the install. Trying older version, .exe files. Also installed Chocolatey and tried to install Node through there. However, it all failed. So even though I googled for hours, tried it all, I have no more clue what to do. Maybe there is something in Registrar from old Node files that is blocking the install? It's a wild guess. I also removed all temp files and tried the install. No result.

I also logged the installation progress;

CAQuietExec:  Error 0x8007000d: Command line returned an error.
CAQuietExec:  Error 0x8007000d: QuietExec Failed
CustomAction RegisterPerfmonManifest returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)

Any suggestions are superwelcome! I am on Windows 7.

**Comment by eljefedelrodeodeljefe** [comment]
Hi. Can you move this to https://github.com/nodejs/node? This is the archive repo of 0.XX versions. Also please state what version you have tried to install... you'll find a list of todos for issue reporting in the new repo.
