### ISSUE TITLE
Gulp issue 

### ISSUE THREAD

**Issue by hardy091** [joyent/node#25985]
Please any one help me.
I'm using Ubuntu 14.04 64 bit OS.
When i start gulp in terminal then showing:
/var/www/localdir/node_modules/gulp-jshint/node_modules/lodash/index.js:698
  function runInContext(context) {
                       ^
illegal access

**Comment by addaleax** [comment]
Hi! This repository is no longer active and has been replaced by https://github.com/nodejs/node.

For general questions about using or installing Node.js, [nodejs/help](https://github.com/nodejs/help) may be a better place, and that seems the case this time. Please create an issue there and, ideally, provide more details on how to reproduce.

This also sounds like it could be from a rather old version of Node.js. If so, try using a current version as listed on https://nodejs.org/.

**Comment by cjihrig** [comment]
Yes, what @addaleax said. Closing this.
