### ISSUE TITLE
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "whoami"

### ISSUE THREAD

**Issue by dahoom1429** [joyent/node#25980]
`0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'whoami' ]
2 info using npm@3.7.3
3 info using node@v5.9.0
4 verbose config Skipping project config: /home/tom/.npmrc. (matches userconfig)
5 verbose stack Error: this command requires you to be logged in.
5 verbose stack     at EventEmitter.whoami (/usr/local/lib/node_modules/npm/lib/whoami.js:41:18)
5 verbose stack     at Object.commandCache.(anonymous function) (/usr/local/lib/node_modules/npm/lib/npm.js:216:13)
5 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:74:30)
5 verbose stack     at _combinedTickCallback (node.js:376:9)
5 verbose stack     at process._tickCallback (node.js:407:11)
6 verbose cwd /home/tom
7 error Linux 4.2.0-34-generic
8 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "whoami"
9 error node v5.9.0
10 error npm  v3.7.3
11 error code ENEEDAUTH
12 error need auth this command requires you to be logged in.
13 error need auth You need to authorize this machine using`npm adduser`
14 verbose exit [ 1, true ]`

**Comment by whitlockjc** [comment]
Please open this issue on the nodejs/node repo. This repo is no longer active.
