### ISSUE TITLE
node does not sanitize http header field values

### ISSUE THREAD

**Issue by alpercelik** [joyent/node#2602]
Noticed first with express and submitted a pull request to express framework but after our discussions about the issue with @visionmedia, it seemed more logical to have it in node.

You may find the pull request for express which explains details here
https://github.com/visionmedia/express/pull/974

I did sanitizing in http.js where header field values are stored.
https://github.com/alpercelik/node/commit/667aae596cded9336f50574386683ec39ada43f2

**Comment by jasnell** [comment]
New PR opened on nodejs/node. Will continue to track the conversation there. https://github.com/nodejs/node/pull/2526
