### ISSUE TITLE
Issue showing with gulp 

### ISSUE THREAD

**Issue by hardy091** [joyent/node#26045]
When i installed gulp-sass in my local project then show issue. 

sudo npm install gulp-sass --save-dev

undefined symbol: _ZN2v86Object3SetENS_6HandleINS_5ValueEEES3_
npm ERR! node-sass@3.7.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the node-sass@3.7.0 postinstall script.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.13.0-85-generic
npm ERR! command "node" "/usr/local/bin/npm" "install" "gulp-sass" "--save-dev"
npm ERR! cwd /var/www/loc.projectname.com/app/View/Themed/Sc/webroot
npm ERR! node -v v0.11.13-pre
npm ERR! npm -v 1.4.7
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/loc.projectname.com/app/View/Themed/Sc/webroot/npm-debug.log
npm ERR! not ok code 0

**Comment by eljefedelrodeodeljefe** [comment]
This is most likely not an issue related to node itself. The log shows that is likely an issue with node-sass,, gulp-sass dependency. If you still think this is an issue with node, please open an issue at https://github.com/nodejs/node
