### ISSUE TITLE
node v5.5.0 compile on OmniOS: failed to resolve V8DB G_OFF_FP_CONTEXT: Unknown variable name

### ISSUE THREAD

**Issue by hptabster** [joyent/node#26568]
uname -a
SunOS ip-10-203-225-122.ec2.internal 5.11 r151006 i86pc i386 i86xpv

PATH=$PATH:/usr/sbin
export CC=$(which gcc)
git clone https://github.com/nodejs/node.git
cd node
git checkout v5.5.0
gmake -j4 binary
...
  g++ -rdynamic -m32 -pthreads -Wl,-z,allextract  -o /home/mci/node/out/Release/c
ctest -Wl,--start-group /home/mci/node/out/Release/obj.target/cctest/test/cctest/
util.o /home/mci/node/out/Release/obj.target/deps/gtest/libgtest.a /home/mci/node
/out/Release/obj.target/deps/v8/tools/gyp/libv8_libplatform.a /home/mci/node/out/
Release/obj.target/deps/v8/tools/gyp/libv8_base.a /home/mci/node/out/Release/obj.
target/deps/v8/tools/gyp/libv8_libbase.a /home/mci/node/out/Release/obj.target/to
ols/icu/libicui18n.a /home/mci/node/out/Release/obj.target/tools/icu/libicuucx.a
/home/mci/node/out/Release/obj.target/tools/icu/libicudata.a /home/mci/node/out/R
elease/obj.target/tools/icu/libicustubdata.a /home/mci/node/out/Release/obj.targe
t/deps/v8/tools/gyp/libv8_snapshot.a -Wl,--end-group -lnsl -lrt
dtrace: failed to compile script src/v8ustack.d: line 258: failed to resolve V8DB
G_OFF_FP_CONTEXT: Unknown variable name
gmake[2]: **\* [/home/mci/node/out/Release/obj.target/node/src/node_dtrace_ustack.
o] Error 1

**Comment by cjihrig** [comment]
This repo is no longer maintained, and v5.5.0 is end of life. If you have this problem with v0.10, v0.12, v4, v6, or master, please reopen this at https://github.com/nodejs/node.
