### ISSUE TITLE
npm install -g gemfire  command throws and rollas back the install

### ISSUE THREAD

**Issue by BalajiSingh** [joyent/node#26577]
Hi,

I am new to protractor automation so would definitely require your help on this below issue.

As my project application is built on Angular Js and i need to get it tested by Protractor tool.

And we GemFire Database. 

I issue is when i use this "npm install -g gemfire"  command at console it throws an error as shown below.
I don`t know where i am going wrong.
can somebody please help me on this issue.  Sorry for copying the full stack trace.
My system details : windows 7  32 bit OS

C:>npm install -g gemfire
/

> gemfire@0.1.19 install C:\Users\baluzen\AppData\Roaming\npm\node_modules\gemfi
> re
> node-pre-gyp install --fallback-to-build

(node) child_process: options.customFds option is deprecated. Use options.stdio
instead.

C:\Users\baluzen\AppData\Roaming\npm\node_modules\gemfire>if not defined npm_con
fig_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\.
...\node_modules\node-gyp\bin\node-gyp.js" rebuild --name=gemfire --configurati
on=Release --module_name=gemfire --version=0.1.19 --minor=1 --patch=19 --runtime
=node --node_abi=node-v46 --platform=win32 --target_platform=win32 --arch=ia32 -
-target_arch=ia32 --module_main=./lib --host=https://download.pivotal.com.s3.ama
zonaws.com/ --module_path=C:\Users\baluzen\AppData\Roaming\npm\node_modules\gemf
ire\lib\binding\Release\node-v46-win32-ia32 --module=C:\Users\baluzen\AppData\Ro
aming\npm\node_modules\gemfire\lib\binding\Release\node-v46-win32-ia32\gemfire.n
ode --remote_path=./node-gemfire/0.1.19/ --package_name=gemfire-v0.1.19-node-v46
-win32-ia32.tar.gz --staged_tarball=build\stage\node-gemfire\0.1.19\gemfire-v0.1
.19-node-v46-win32-ia32.tar.gz --hosted_path=https://download.pivotal.com.s3.ama
zonaws.com/node-gemfire/0.1.19/ --hosted_tarball=https://download.pivotal.com.s3
.amazonaws.com/node-gemfire/0.1.19/gemfire-v0.1.19-node-v46-win32-ia32.tar.gz )
 else (node "" rebuild --name=gemfire --configuration=Release --module_name=gemf
ire --version=0.1.19 --minor=1 --patch=19 --runtime=node --node_abi=node-v46 --p
latform=win32 --target_platform=win32 --arch=ia32 --target_arch=ia32 --module_ma
in=./lib --host=https://download.pivotal.com.s3.amazonaws.com/ --module_path=C:\
Users\baluzen\AppData\Roaming\npm\node_modules\gemfire\lib\binding\Release\node-
v46-win32-ia32 --module=C:\Users\baluzen\AppData\Roaming\npm\node_modules\gemfir
e\lib\binding\Release\node-v46-win32-ia32\gemfire.node --remote_path=./node-gemf
ire/0.1.19/ --package_name=gemfire-v0.1.19-node-v46-win32-ia32.tar.gz --staged_t
arball=build\stage\node-gemfire\0.1.19\gemfire-v0.1.19-node-v46-win32-ia32.tar.g
z --hosted_path=https://download.pivotal.com.s3.amazonaws.com/node-gemfire/0.1.1
9/ --hosted_tarball=https://download.pivotal.com.s3.amazonaws.com/node-gemfire/0
.1.19/gemfire-v0.1.19-node-v46-win32-ia32.tar.gz )
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: ENOENT: no such file or directory, open 'C:\Users\baluzen\
AppData\Roaming\npm\node_modules\gemfire\undefined'
gyp ERR! stack     at Error (native)
gyp ERR! stack     at Object.fs.openSync (fs.js:549:18)
gyp ERR! stack     at Object.fs.readFileSync (fs.js:397:15)
gyp ERR! stack     at readCAFile (C:\Program Files\nodejs\node_modules\npm\node_
modules\node-gyp\lib\install.js:466:15)
gyp ERR! stack     at download (C:\Program Files\nodejs\node_modules\npm\node_mo
dules\node-gyp\lib\install.js:438:22)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\install.js:185:19
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\mkdi
rp\index.js:48:26
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodej
s\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild" "--nam
e=gemfire" "--configuration=Release" "--module_name=gemfire" "--version=0.1.19"
"--minor=1" "--patch=19" "--runtime=node" "--node_abi=node-v46" "--platform=win3
2" "--target_platform=win32" "--arch=ia32" "--target_arch=ia32" "--module_main=.
/lib" "--host=https://download.pivotal.com.s3.amazonaws.com/" "--module_path=C:\
\Users\baluzen\AppData\Roaming\npm\node_modules\gemfire\lib\binding\Rel
ease\node-v46-win32-ia32" "--module=C:\Users\baluzen\AppData\Roaming\npm\
node_modules\gemfire\lib\binding\Release\node-v46-win32-ia32\gemfire.node"
 "--remote_path=./node-gemfire/0.1.19/" "--package_name=gemfire-v0.1.19-node-v46
-win32-ia32.tar.gz" "--staged_tarball=build\stage\node-gemfire\0.1.19\gemfir
e-v0.1.19-node-v46-win32-ia32.tar.gz" "--hosted_path=https://download.pivotal.co
m.s3.amazonaws.com/node-gemfire/0.1.19/" "--hosted_tarball=https://download.pivo
tal.com.s3.amazonaws.com/node-gemfire/0.1.19/gemfire-v0.1.19-node-v46-win32-ia32
.tar.gz"
gyp ERR! cwd C:\Users\baluzen\AppData\Roaming\npm\node_modules\gemfire
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd rebuild --name=ge
mfire --configuration=Release --module_name=gemfire --version=0.1.19 --minor=1 -
-patch=19 --runtime=node --node_abi=node-v46 --platform=win32 --target_platform=
win32 --arch=ia32 --target_arch=ia32 --module_main=./lib --host=https://download
.pivotal.com.s3.amazonaws.com/ --module_path=C:\Users\baluzen\AppData\Roaming\np
m\node_modules\gemfire\lib\binding\Release\node-v46-win32-ia32 --module=C:\Users
\baluzen\AppData\Roaming\npm\node_modules\gemfire\lib\binding\Release\node-v46-w
in32-ia32\gemfire.node --remote_path=./node-gemfire/0.1.19/ --package_name=gemfi
re-v0.1.19-node-v46-win32-ia32.tar.gz --staged_tarball=build\stage\node-gemfire\
0.1.19\gemfire-v0.1.19-node-v46-win32-ia32.tar.gz --hosted_path=https://download
.pivotal.com.s3.amazonaws.com/node-gemfire/0.1.19/ --hosted_tarball=https://down
load.pivotal.com.s3.amazonaws.com/node-gemfire/0.1.19/gemfire-v0.1.19-node-v46-w
in32-ia32.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\baluzen\AppDat
a\Roaming\npm\node_modules\gemfire\node_modules\node-pre-gyp\lib\util\compile.js
:76:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/chi
ld_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\balu
zen\AppData\Roaming\npm\node_modules\gemfire\node_modules\node-pre-gyp\b
in\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\baluzen\AppData\Roaming\npm\node_modules\gemfire
node-pre-gyp ERR! node -v v4.4.7
node-pre-gyp ERR! node-pre-gyp -v v0.5.31
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd rebuild --name=gemfire --configuration=Release -
-module_name=gemfire --version=0.1.19 --minor=1 --patch=19 --runtime=node --node
_abi=node-v46 --platform=win32 --target_platform=win32 --arch=ia32 --target_arch
=ia32 --module_main=./lib --host=https://download.pivotal.com.s3.amazonaws.com/
--module_path=C:\Users\baluzen\AppData\Roaming\npm\node_modules\gemfire\lib\bind
ing\Release\node-v46-win32-ia32 --module=C:\Users\baluzen\AppData\Roaming\npm\no
de_modules\gemfire\lib\binding\Release\node-v46-win32-ia32\gemfire.node --remote
_path=./node-gemfire/0.1.19/ --package_name=gemfire-v0.1.19-node-v46-win32-ia32.
tar.gz --staged_tarball=build\stage\node-gemfire\0.1.19\gemfire-v0.1.19-node-v46
-win32-ia32.tar.gz --hosted_path=https://download.pivotal.com.s3.amazonaws.com/n
ode-gemfire/0.1.19/ --hosted_tarball=https://download.pivotal.com.s3.amazonaws.c
om/node-gemfire/0.1.19/gemfire-v0.1.19-node-v46-win32-ia32.tar.gz' (1)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "install" "-g" "gemfire"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE

npm ERR! gemfire@0.1.19 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gemfire@0.1.19 install script 'node-pre-gyp install --fal
lback-to-build'.
npm ERR! This is most likely a problem with the gemfire package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs gemfire
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls gemfire
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\npm-debug.log

**Comment by eljefedelrodeodeljefe** [comment]
This is likely a problem with `gemfire`. Please ask at their repo. If you can identify this as a problem with node, please file and issue in the actual node repo https://github.com/nodejs/node
