### ISSUE TITLE
Execute command line in javascript

### ISSUE THREAD

**Issue by cba16** [joyent/node#26576]
Hello,
I have a javascript program that runs on linux. It receives various data and I would like it to execute command lines (entering a folder+executing a program) when it receives specific data. 
How can I do that on a javascript program? 
Thanks (I hope I'm in the right place for that question!)

**Comment by addaleax** [comment]
You may want to take a look at https://nodejs.org/api/child_process.html – that sounds like something you are searching for.

https://github.com/nodejs/help might be a better place for something like this, this issue tracker is mostly abandoned.

**Comment by eljefedelrodeodeljefe** [comment]
Or alternatively search on stackoverflow.com. Closing, due to FAQ task in deprecated node repo..
