### ISSUE TITLE
help://  Error: DEPTH_ZERO_SELF_SIGNED_CERT  on client side 

### ISSUE THREAD

**Issue by ghost** [joyent/node#26572]
![ssl](https://cloud.githubusercontent.com/assets/19684476/17330490/8ce886b0-58f9-11e6-9017-11757bca02c9.png)

![client](https://cloud.githubusercontent.com/assets/19684476/17330507/9b11696e-58f9-11e6-8ec0-202c21576e5f.png)

![server](https://cloud.githubusercontent.com/assets/19684476/17330545/c4cfba94-58f9-11e6-93f9-83b53ebb8cb2.png)

I need to set   rejectUnauthorized: true  on client side but ,it has err I  dont know how to handle

**Comment by princejwesley** [comment]
This is an archive repository. Please open this issue in [nodejs/help](https://github.com/nodejs/help/issues)
