### ISSUE TITLE
Node.js net library: Not getting complete data from 'data' event when data is HUGE

### ISSUE THREAD

**Issue by manthu522** [joyent/node#26585]
Hi Team, I am implementing a TCP socket connections using net module.. Here I am facing issue while Node.js net library: not getting complete data from 'data' event when we have huge data coming from the socket. And getting as chunks... 

Now I am planning to resolve using a delimiter, without delimiter can we solve this issue ??

Is there any builtin lib to do this job ? 

Thanks in advance!!!

**Comment by feikname** [comment]
@manthu522 the repository was moved, this one is for historical purposes only. https://github.com/nodejs/node
