### ISSUE TITLE
Cannot delete or move folder on windows due to folder depts

### ISSUE THREAD

**Issue by nickbe** [joyent/node#26582]
Please take a look at the folder structure here:

![screenshot_63](https://cloud.githubusercontent.com/assets/10890765/19789229/5f74af08-9cae-11e6-9619-53c40e92f0fc.png)

Why would you even consider creating such a mess in the first place? Beside the fact that it breaks functionality when working in windows (I have no idea how to move or delete these folders), the complete folder structure here consists of over ten thousand folders!!!! and subfolders with over 90.000 (ninety thousand !!!!) files.

Seriously??

**Comment by evanlucas** [comment]
This repository is no longer used, so I'm going to go ahead and close the issue. That looks like a directory structure created by npm 2. Updating to npm 3 will by default not nest packages unless required. You should be able to use the rimraf package to delete the directory. Thanks!
