### ISSUE TITLE
New Install of Atom Error: EPERM: operation not permitted, mkdir

### ISSUE THREAD

**Issue by weezieLouise** [joyent/node#26588]
HI, I can't install anything, themes, packages, syntax themes ... nothing, I'm on Windows 10 64bit.

Here is the error

Installing “atom-material-ui@1.3.9” failed.Hide output…

npm ERR! addLocal Could not install C:\Users\DESIGN~1\AppData\Local\Temp\d-117014-21240-1mfld0v\package.tgz
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\Designer#1\\AppData\\Local\\atom\\app-1.13.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Designer#1\\AppData\\Local\\atom\\app-1.13.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Designer#1\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Designer#1\\.atom\\.apmrc" "install" "C:\\Users\\DESIGN~1\\AppData\\Local\\Temp\\d-117014-21240-1mfld0v\\package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=ia32" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! path C:\Users\Designer
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall mkdir

npm ERR! Error: EPERM: operation not permitted, mkdir 'C:\Users\Designer'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, mkdir 'C:\Users\Designer']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: 'C:\\Users\\Designer' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\DESIGN~1\AppData\Local\Temp\apm-install-dir-117014-21240-cm5ys9\npm-debug.log

Ca you advise as to what might be wrong?
Thanks

**Comment by evanlucas** [comment]
Hi, this repo is no longer being used and is mainly here for historical reasons. 

Based on the error message, it looks like you don't have permission to install that into the required directory. Have you tried reinstalling as the Administrator? 

I'm going to go ahead and close. Thanks

**Comment by weezieLouise** [comment]
Hi Evan,

Thanks for your email, running atom as administrator worked.

Thanks for you help.

Louise

On 14 Jan 2017 3:15 p.m., "Evan Lucas" <notifications@github.com> wrote:

Hi, this repo is no longer being used and is mainly here for historical
reasons.

Based on the error message, it looks like you don't have permission to
install that into the required directory. Have you tried reinstalling as
the Administrator?

I'm going to go ahead and close. Thanks

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/nodejs/node-v0.x-archive/issues/26588#issuecomment-272630245>,
or mute the thread
