### ISSUE TITLE
Windows Installer WARNING 1909. 

### ISSUE THREAD

**Issue by thandonguocmo2020** [joyent/node#26587]
I use win 10-64bit.

Warning 1909. Could not create shortcut prompt.lnk. Verify that the destination folder exists and that you can access it

someone please let workarounds. 

I am having the same issue. The guide to fix it in #8141 doesn't work for me.

**Comment by mscdex** [comment]
Wrong issue tracker, see the [readme](https://github.com/nodejs/node-v0.x-archive/blob/moved/README.md).
