### ISSUE TITLE
Croogo Missing Database Table

### ISSUE THREAD

**Issue by hardy091** [joyent/node#26586]
I did installed croogo via git, but when i go to http://localhost/myapp then display error, please Help me.

Missing Database Table

Error: Table types for model Type was not found in datasource default.

Notice: If you want to customize this error message, create app/View/Errors/missing_table.ctp

**Comment by cjihrig** [comment]
Sorry, but this doesn't seem to be an issue with Node core. Seems like your issue is with the database.
