### ISSUE TITLE
Node Installation on ubuntu 16.04 (32 bit)

### ISSUE THREAD

**Issue by pptyasar** [joyent/node#26583]
When installing nodejs i got this error

**Get:1 https://deb.nodesource.com/node_6.x xenial/main i386 nodejs i386 6.9.1-1nodesource1~xenial1 [9,771 kB]
Err:1 https://deb.nodesource.com/node_6.x xenial/main i386 nodejs i386 6.9.1-1nodesource1~xenial1  
  GnuTLS recv error (-54): Error in the pull function.
E: Failed to fetch https://deb.nodesource.com/node_6.x/pool/main/n/nodejs/nodejs_6.9.1-1nodesource1~xenial1_i386.deb  GnuTLS recv error (-54): Error in the pull function.                     

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
**

**Comment by kirillDanshin** [comment]
@pptyasar you miss that repo was moved to https://github.com/nodejs/node. it's only file in the default branch.

**Comment by eljefedelrodeodeljefe** [comment]
The error likely indicates what the problem is. Be sure to run the official installation command.
