### ISSUE TITLE
lstat not permitted, scandir not permitted with ng new xxx command and npm install commands

### ISSUE THREAD

**Issue by Belmiris** [joyent/node#26596]
If you want Windows users to use this, someone really needs to fix these errors. I have my directories wide open to all all uses and I'm still getting these errors. I am in the 'run as administrator' DOS command window. I have to keep rebooting my machine and crossing my fingers hoping that THIS time it will work. Most users will just assume it's broken and give up.

D:\dev\angular>npm -version
5.3.0

D:\dev\angular>ng --version
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.2.0
node: 6.11.1
os: win32 x64

D:\dev\angular>
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>d:

D:\>cd dev

D:\dev>dir
 Volume in drive D is D:
 Volume Serial Number is 56F8-CC3C

 Directory of D:\dev

07/29/2017  12:30 PM    <DIR>          .
07/29/2017  12:30 PM    <DIR>          ..
               0 File(s)              0 bytes
               2 Dir(s)  731,454,070,784 bytes free

D:\dev>mkdir angular

D:\dev>cd angular

D:\dev\angular>ag new ag-grid-test
'ag' is not recognized as an internal or external command,
operable program or batch file.

D:\dev\angular>ng new ng-grid-test
installing ng
  create .editorconfig
  create README.md
  create src\app\app.component.css
  create src\app\app.component.html
  create src\app\app.component.spec.ts
  create src\app\app.component.ts
  create src\app\app.module.ts
  create src\assets\.gitkeep
  create src\environments\environment.prod.ts
  create src\environments\environment.ts
  create src\favicon.ico
  create src\index.html
  create src\main.ts
  create src\polyfills.ts
  create src\styles.css
  create src\test.ts
  create src\tsconfig.app.json
  create src\tsconfig.spec.json
  create src\typings.d.ts
  create .angular-cli.json
  create e2e\app.e2e-spec.ts
  create e2e\app.po.ts
  create e2e\tsconfig.e2e.json
  create .gitignore
  create karma.conf.js
  create package.json
  create protractor.conf.js
  create tsconfig.json
  create tslint.json
Installing packages for tooling via npm.
npm ERR! path D:\dev\angular\ng-grid-test\node_modules\fsevents\node_modules
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall scandir
npm ERR! Error: EPERM: operation not permitted, scandir 'D:\dev\angular\ng-grid-test\node_modules\fsevents\node_modules'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, scandir 'D:\dev\angular\ng-grid-test\node_modules\fsevents\node_modules'
npm ERR!     at Error (native)
npm ERR!   stack: 'Error: EPERM: operation not permitted, scandir \'D:\\dev\\angular\\ng-grid-test\\node_modules\\fsevents\\node_modules\'\n    at Error (native)',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'scandir',
npm ERR!   path: 'D:\\dev\\angular\\ng-grid-test\\node_modules\\fsevents\\node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Rick\AppData\Roaming\npm-cache\_logs\2017-07-29T17_34_45_283Z-debug.log

Package install failed, see above.

D:\dev\angular>

**Comment by vsemozhetbyt** [comment]
This repository is an archive. Please post issues in:
https://github.com/nodejs/node — about bugs in the Node.js.
https://github.com/nodejs/help — other questions.

Be sure your case is really Node.js issue (for npm issues use https://github.com/npm/npm, for Angular issues use https://github.com/angular/angular)
