### ISSUE TITLE
Warning: Unable to read "src/vendors/jquery-timeago/locales/jquery.timeago.en.js" file (Error code: ENOENT). Use --force to continue.

### ISSUE THREAD

**Issue by michaeltking79** [joyent/node#26594]
Can someone please help me get past this error?

root@server:/usr/src/counterwallet# grunt build
Running "build:process" (build) task
Generate jQuery-TimeAgo localizations
Warning: Unable to read "src/vendors/jquery-timeago/locales/jquery.timeago.en.js" file (Error code: ENOENT). Use --force to continue.

Aborted due to warnings.

Thanks!

Michael

**Comment by vsemozhetbyt** [comment]
@michaeltking79 Unfortunately, this is an archive inactive repository. Try to ask in the https://github.com/nodejs/help.

**Comment by michaeltking79** [comment]
Ok thanks!
