### ISSUE TITLE
MaxListenersExceededWarning when websocket reconnect

### ISSUE THREAD

**Issue by NickGatti** [joyent/node#26600]
I get this MaxListenersExceededWarning with a memory leak after trying to reconnect a websocket when unplugging internet cable for testing reconnect

websocket tries in the stack
```
websocket.on('message', ((data) => { /* ... */ });

websocket.on('open', (() => { /* ... */ });
```

if internet cable left unplugged for long enough =>
example of console.log
```
WebSocket Connection Lost...
WebSocket Connection Lost...
WebSocket Connection Lost...
WebSocket Connection Lost...
WebSocket Connection Lost...
WebSocket Connection Lost...
WebSocket Connection Lost...
WebSocket Connection Lost...
WebSocket Connection Lost...
WebSocket Connection Lost...
WebSocket Connection Lost...
(node:25152) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 open listeners added. Use emitter.setMaxListeners() to increase limit
```

then memory leak happens

**Comment by cjihrig** [comment]
General support questions should be directed to https://github.com/nodejs/help. This particular repository is no longer maintained. It's also worth mentioning that Node does not ship WebSockets, so either the leak is in a third party module that you're using, or the leak is from adding the same event handlers over and over again. I'm going to close this issue out. Thanks!
