### ISSUE TITLE
HTTP 0.9 - Response contain disallowed header fields

### ISSUE THREAD

**Issue by Otto-Zwolle** [joyent/node#2916]
Misbehaviour:
-------------

node 0.6.12 answers to a HTTP 0.9 request with HTTP headers before
data.

Required regular behaviour:
---------------------------

An answer to a HTTP 0.9 request must NOT contain any headers.
Payload data transfer must start immediately from byte 0 in response.

RFC sources explaining:
-----------------------

<http://www.ietf.org/rfc/rfc1945.txt>:

If the protocol version is not specified,
the recipient must assume that the message is in the
simple HTTP/0.9 format.

<http://www.ietf.org/rfc/rfc2616.txt>:

we would expect commercial HTTP/1.1 servers to:

- recognize the format of the Request-Line for
  HTTP/0.9, 1.0, and 1.1 requests;
- understand any valid request in the format of
  HTTP/0.9, 1.0, or 1.1;
- respond appropriately with a message in the
  same major version used by the client.

**Comment by jasnell** [comment]
@joyent/node-coreteam ... At this point I doubt http/0.9 is something we'd ever actually support fully. Recommend closing this one.

**Comment by jasnell** [comment]
Closing. Can reopen if HTTP/0.9 is something we feel is necessary.

**Comment by notgiorgi** [comment]
Was HTTP/0.9 support added in future versions?

**Comment by lfernando-silva** [comment]
@notgiorgi I think it doesn't support it yet even in the v7. There is a problem to work with legacy http systems.
