### ISSUE TITLE
fs.watch() not reporting indirect change events (Windows)

### ISSUE THREAD

**Issue by broncha** [joyent/node#3022]
Hi,

I am watching my apache logs using node fs.watch

Here's my code

```javascript
var	fs = require('fs');
fs.watch("C:/xampp/apache/logs/error.log", function (event, filename) {
  console.log(event);
});
```

Every time I refresh a page in my browser something is written to error.log, but I cannot see anything in the console.
But when I manually open the file, it fires the change event.
Wan't that supposed to be fired when apache writes to that file!

**Comment by jasnell** [comment]
@orangemocha ... thoughts on this one?

**Comment by orangemocha** [comment]
If this a log file, it's very likely that the writing process is buffering the changes. I'll verify if this works with non-buffered changes.

**Comment by orangemocha** [comment]
Could not reproduce the issue with non-buffered changes (i.e. editing and saving the file in notepad). This was mostly likely due to buffering in the log writing process.
