### ISSUE TITLE
Signals aren't received when debugging

### ISSUE THREAD

**Issue by ggreer** [joyent/node#3167]
When using child_process.spawn() to run node in debug mode, signals sent to the child aren't received. You can see an example in this gist: https://gist.github.com/2474314/

If you remove the debug argument on line 14 of signals.js, the SIGINT handler in example.js fires. I'm pretty sure the issue is that `node debug` spawns a child process that runs example.js, but it doesn't forward signals along to the child.

I'm using node 0.6.15 on OS X 10.7.3.

If you're curious, the reason I'm doing this craziness is because I'm trying to fix the debugger in [whiskey](https://github.com/cloudkick/whiskey/).

**Comment by jasnell** [comment]
@indutny ... do you happen to recall the status of this one?

**Comment by indutny** [comment]
Sorry, but not really. Guess we worked it out.

**Comment by jasnell** [comment]
@ggreer closing. If this continues to be an issue, we can reopen and revisit.
