### ISSUE TITLE
resolv.conf read once at startup no way to reload it

### ISSUE THREAD

**Issue by joshwilsdon** [joyent/node#3408]
I ran into a problem where I was doing dns.resolve4 in my application that was being run at startup before /etc/resolv.conf was populated.  Since node uses C-Ares for resolution it reads the resolvers from there but it initially is getting the wrong ones (ie. none, since resolv.conf is empty when it first runs).  What I attempted to do was to have my app retry the dns.resolve4 so that I could continue once the resolv.conf was updated.

What I found was that /etc/resolv.conf was read once and never read again, so even when I updated /etc/resolv.conf my dns.resolve4's continued to fail.  Even if I try to reload the dns module.  What I want to be able to do is somehow force node to reload /etc/resolv.conf since I know it will be updated.

I expect this also is a problem for longer lived processes where resolv.conf changes at some point after they've started.  Ideally C-Ares would notice /etc/resolv.conf changed and reload it automatically.  Second best would be some way for me to just pass in resolvers.  Even allowing me to manually reload somehow would allow me to do this in node.

I saw this behavior in SmartOS with node 0.6.17.

**Comment by jasnell** [comment]
@joyent/node-coreteam ... going to assume it's safe to close this one given there's been no action. There are other existing issues regarding the DNS impl (which could likely benefit from some refactoring). Re-open if you feel it is necessary.
