### ISSUE TITLE
dest.destroy() after 'error'

### ISSUE THREAD

**Issue by dominictarr** [joyent/node#3549]
`dest.destroy()` is called if the source emits `'close'` before 'end', 
if it emits `'end'` before close, it will cleanup and remove the `'close'` listener.

but on `'error'`, the pipe is detached, and the rest of the stream is left hanging.

I propose that for consistency, `'error'` be treated like `'close'`

it may also be desireable to check if destroy exists on dest before calling it

Stream people, what do you think? @ry @mikeal @felixge @substack @maxogden @isaacs

**Comment by jasnell** [comment]
@dominictarr ... I know it's been a while, but is this still an issue? Did you have a test case for reproducing this?

**Comment by dominictarr** [comment]
hahaha oh I think we can close this
