### ISSUE TITLE
add a pipe module (feature request)

### ISSUE THREAD

**Issue by VanCoding** [joyent/node#3551]
Hi guys!

Since pipes are very useful for cross platform inter process communication, I think it would be cool to add a pipe module to node.js. Pipes are already used in node.js and there is a nice Pipe wrapper class for the libuv pipe functions, so there wouldn't be much more work for you. Just make the pipe wrapper a module like for example the tcp wrapper, and then add a nice javascript api for it.

This how it could look like:

    var pipe = require("pipe");
    var server = pipe.createServer(function(c){
        c.on("data",function(d){
            //...
        });
    });
    server.listen("somepipename");
    var c = pipe.connect("somepipename",function(){
       c.write("Hello world!");
    });

Also, it would be cool to add a "sendHandle" function and a on("handle",cb) event. This would be absolutely awesome!

Of course, I could do it by myself, but since there is already a very nice implementation, it would make sense to let the node applications use it.

**Comment by jasnell** [comment]
Not likely to happen here.
