### ISSUE TITLE
Windows node installer >= v0.8.0 fails in Windows 7

### ISSUE THREAD

**Issue by briantrice** [joyent/node#3620]
0.7.9 installs correctly, but the 32 and 64 bit versions of 0.8.0 and 0.8.1 fail to install, beginning to rollback near the end of the progress bar. I don't know what install log to consult. The separate node.exe release executables run as expected.

**Comment by jasnell** [comment]
@orangemocha ... this one doesn't seem to be an issue any longer. Can you confirm?

**Comment by orangemocha** [comment]
Could not reproduce on either 0.12.3 or 0.8.21.

**Comment by dipgupta1986** [comment]
Deleting  the registry key worked for me. Thanks :+1:
