### ISSUE TITLE
Small enhancement : add private keys's length for Diffie-Hellman

### ISSUE THREAD

**Issue by Ayms** [joyent/node#3622]
I am more reporting this for the record before I forget, so you can close it if you want.

In some projects the optional parameter length for DH private keys is used for optimization purposes :

#define DH_PRIVATE_KEY_BITS 320
dh = DH_new();
dh->length = DH_PRIVATE_KEY_BITS;

**Comment by jasnell** [comment]
@indutny ... was there ever any action on this one? Is it ok to close?

**Comment by indutny** [comment]
Guess so!
