### ISSUE TITLE
Support for X509, OCSP, CRL, ASN1 and TLS session details.

### ISSUE THREAD

**Issue by rmhrisk** [joyent/node#3662]
Go currently has support for a ton of rich information about TLS and PKI related objects, see: http://golang.org/pkg/ and the TLS, X509 and PKIX objects.

Go's coverage isnt perfect but its enough to do some cool stuff that today can't be done directly in Node.

I would love to see this stuff exposed in node also, a few examples this would enable include:

1. SSL configuration checker - https://www.ssllabs.com/ssltest/index.html
2. Certificate Crawler -  https://www.eff.org/observatory
3. SSL support tools - http://www.sslshopper.com/ssl-certificate-tools.html
4. ASN1 diagostics - http://www.lapo.it/asn1js/

Ryan

**Comment by jasnell** [comment]
@indutny ... any further thoughts on this one?

**Comment by rmhrisk** [comment]
Since this issue was opened a friend and I did this : https://pkijs.org

**Comment by clayendisk** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  james.ryan.stortz@gmail.com
    Domain clayendisk.net has exceeded the max emails per hour (31/30 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o1.sgmail.github.com ([192.254.114.176]:58475)
	by us-tx-cp01.imbahost.com with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.85)
	(envelope-from <bounces+848413-74bf-{}=clayendisk.net@sgmail.github.com>)
	id 1YuOto-00185Y-9n
	for {}@clayendisk.net; Mon, 18 May 2015 12:32:20 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=uYpeNLiMHajZxqyXaU9LL34nmtA=; b=FmsqGquFk6MN9lBk
	kNCewW4g+3Q4XC9JXxIADBpC4SOyhkqUj7ASrI1dUYQ3Hzt//04876fUcJQILReZ
	O/kT+fUCLPJ6+nEpclEFtnrU9vZe2mIVFq7z9VQ2otf9z8zS2au9U9oHxC5fE8Qy
	s6OYvv2JRvgTlw2yXFHheRh4Q4Q=
Received: by filter0234p1mdw1.sendgrid.net with SMTP id filter0234p1mdw1.31554.555A22231C
        2015-05-18 17:32:20.874298112 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd-018 (SG) with ESMTP id 14d68155fca.3ab9.10ff0e
	for <{}@clayendisk.net>; Mon, 18 May 2015 17:32:20 +0000 (UTC)
Date: Mon, 18 May 2015 10:32:20 -0700

**Comment by jasnell** [comment]
@rmhrisk :+1: userland solutions are awesome. If you feel there's still a need for this functionality in core, let us know and we can reopen this issue.

**Comment by stuartpb** [comment]
Doesn't core TLS still need to be extended to support OCSP?

**Comment by rmhrisk** [comment]
Would also be nice if there was a polyfill for webcrypto so user land could do crypto securely

**Comment by indutny** [comment]
It does support OCSP already!
