### ISSUE TITLE
JSON documentation index listing

### ISSUE THREAD

**Issue by mainerror** [joyent/node#3668]
The JSON representation of the documentation is pretty nice and useful, no doubt but it is too complicated to work with it the way it is now.

A listing of the JSON documents and their URL would help a lot when working with the JSON representation of the documentation.

Something like

```json
{
  ...
  "synopsis": {
      "htmlURL": "http://nodejs.org/api/synopsis.html",
      "jsonURL": "http://nodejs.org/api/synopsis.json"
  },
  ...
}
```

**Comment by jasnell** [comment]
@mainerror ... did you still want to pursue this?

**Comment by iapain** [comment]
@jasnell Here is PR #25540

**Comment by jasnell** [comment]
Ok, got it. Sorry, been on vacation and still behind on catching up with github notifications. I'll review the PR this week. Going to close this particular issue, however, in favor of the new PR.
