### ISSUE TITLE
Implicit asynchronous context

### ISSUE THREAD

**Issue by eladb** [joyent/node#3733]
_In continuation to https://groups.google.com/d/topic/nodejs-dev/gBpJeQr0fWM/discussion_

Most environments provide some form of ability to push implicit information into the execution context. In multithreaded environments, it is usually some form of storage associated with the current thread and which can be accessed by code anywhere in the program. See [Thread Local Storage](http://en.wikipedia.org/wiki/Thread-local_storage) for details.

This mechanism enables use cases where it is impossible to pass along data across a call chain from one layer to another in the execution flow (consider the use of many libraries throughout the chain). Common examples are instrumentation and debugging tools like logging and performance counters that need to be associated with the current flow but are usually implemented in a central location within the codebase. For example, one might want to automatically associate a request ID with each emitted log line. The request ID will be added to the execution context when the request comes in and the logging library will extract it and emit it with the log line.

I think that node should enable those scenarios by providing a mechanism to associate data implicitly into the current execution context and extract them along the way. Because of the asynchronous nature of node, this data should traverse async hops in a similar fashion to [Domains](http://nodejs.org/docs/latest/api/all.html#all_domain).

**Comment by jasnell** [comment]
@trevnorris ... any further thoughts or action on this one?

**Comment by trevnorris** [comment]
Nope. A large part of that implementation was removed, and there is now a cls shim in npm.

**Comment by jasnell** [comment]
Ok. I'm leaning towards just closing this one then. If someone wishes to pursue, we can reopen if necessary.

**Comment by robertleeplummerjr** [comment]
Can we get a reference to this "cls shim in npm"?  Is this the answer for this issue?

**Comment by erewh0n** [comment]
@robertleeplummerjr one can probably assume https://www.npmjs.com/package/continuation-local-storage

**Comment by jasnell** [comment]
given the current state of this, closing here. If someone wishes to pursue this further, it would need to be done in http://github.com/nodejs/node
