### ISSUE TITLE
Build a .app bundle for OS X

### ISSUE THREAD

**Issue by isaacs** [joyent/node#3818]
The better to deploy in the App Store.

It should probably be created by `make pkg`.  Not exactly sure what it should do when it is actually run, but perhaps it should just open up Terminal and start /usr/local/bin/node.

Installing/uninstalling should probably be similar to what the pkg installer does.

I really do not know how that works, I just want to get a green hexagon in the AppStore, and push update notifications to users, and have it all Just Work.

**Comment by jasnell** [comment]
Closing this. Would defer to the nodejs/build WG for any further action.
