### ISSUE TITLE
fs.readdir callback is an array which is inefficient to process for large directories

### ISSUE THREAD

**Issue by esprehn** [joyent/node#388]
fs.readdir is very problematic for listing directories if you don't know how large they are in advance. If you used a for loop to iterate over the array to output a directory listing (ex. directory index) and you list a directory with 1000 entries the whole process is blocked.

A DirectoryIterator should be provided instead that returns the directory list sorted and emits events like when reading lines from a file. It's easy to DOS a node HTTP server that implements directory listings by just requesting the listing of a large directory over and over again right now.

**Comment by jasnell** [comment]
@indutny ... did this ever land anywhere?

**Comment by Fishrock123** [comment]
I don't think so, but there is https://github.com/nodejs/io.js/issues/583, which is probably the better route. (Could be fed into a generator for iteration.)

**Comment by jasnell** [comment]
Agree... just not sure if this is something we should address in v0.12+ or push to the converged stream. Regardless, this looks like a feature-request as opposed to a bug. Will leave it open to track.

**Comment by jasnell** [comment]
Actually, on second thought. Let's close this. It's not likely something that would land here and the discussion going on in https://github.com/nodejs/io.js/issues/583 is a better direction. Closing.
