### ISSUE TITLE
IPv6 localAddress gives EADDRNOTAVAIL

### ISSUE THREAD

**Issue by bmeck** [joyent/node#3892]
When using `http.request` I noticed that binding to '::1' and my IPv6 address resulted in EADDRNOTAVAIL

```
git@master bradleymeck npm>node
> var req = require('http').get({localAddress:'::1'});
undefined
> 
events.js:66
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: bind EADDRNOTAVAIL
    at errnoException (net.js:781:11)
    at connect (net.js:634:21)
    at Socket.connect (net.js:716:9)
    at asyncCallback (dns.js:67:16)
    at Object.onanswer [as oncomplete] (dns.js:120:9)
```

Not sure if this is intended but I would presume not.

**Comment by jasnell** [comment]
@bnoordhuis ... what was the outcome on this one?

**Comment by bnoordhuis** [comment]
I don't know / don't remember.

**Comment by jasnell** [comment]
Quick investigation shows that this appears to be fixed. Closing. Can reopen if new information is received.
