### ISSUE TITLE
EPERM Win7 - Uninstalling nodejs does not remove it from the PATH

### ISSUE THREAD

**Issue by nitriques** [joyent/node#3902]
I had this issue on Windows 7 Pro, 64 bits.

I first installed node x86. Then uninstall it and install the x64 version.

After that, I got a lot of EPERM errors (particularly with grunt).

I looked at the logs and found it rather weird to see some `C:\Program Files (x86)` in the errors paths.

So I did a search in Windows' registry and found the culprit as been the System Path variable (not the user defined one).

After removing the x86 directory, everything worked!

I do not know if this is the proper place to record this behavior nor if it is a bug per se, but I think it should be removed from the PATH when uninstalling it.

**Comment by jasnell** [comment]
@piscisaureus .. was there any action on this one?

**Comment by piscisaureus** [comment]
@jasnell No, I'm not sure what to do.

**Comment by jasnell** [comment]
After testing now, i'm unable to recreate the problem with the current installers for v0.12.7 and v3.x. Closing. If this continues to be a problem we can revisit.
