### ISSUE TITLE
[Enhancement] Documentation and Source Lookup in REPL Console

### ISSUE THREAD

**Issue by westurner** [joyent/node#3916]
**[EDIT]**

It would be really great to be able to look up documentation and source from the node REPL console.

After a few quick searches, I am unable to find a structured format Javascript/ECMA documentation reference:

* http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-262.pdf
* http://stackoverflow.com/questions/401969/javascript-reference-for-offline-browsing
* Docco, Groc, JSDoc, Dox

Python IPython supports documentation and source lookup from the REPL.
```python
<Object>?
<Object>??
```

Ruby Pry supports documentation and source lookups from the REPL. 
```ruby
? <Object>
$ <Object>
```

* http://nodejs.org/api/repl.html
* http://nodejs.org/api
* http://nodejs.org/api/all.html
* http://nodejs.org/api/all.json
* https://github.com/langpavel/node-better-inspect/blob/master/index.js

**Comment by jasnell** [comment]
@chrisdickinson ... A separate `node-help` kind of CLI tool would be extremely useful to explore in the future... but as a separate userland add-on. However, do we need to keep this open?

**Comment by westurner** [comment]
From IJavascript (an IPython NodeJS kernel)
https://www.npmjs.com/package/ijavascript :

> **Autocompletion**: press TAB to complete keywords and object properties
>
> **Object inspection**: press Shift-TAB to inspect an object and show its
content or, if available, its documentation

**Comment by jasnell** [comment]
@westurner ... definitely agree that it would be helpful, just not sure it would ever land here (in joyent/node). Going to close this here. If you'd like to pursue (and I encourge you to), please open an issue either over in http://github.com/nodejs/io.js or http://github.com/nodejs/node

**Comment by westurner** [comment]
On Jun 22, 2015 1:39 PM, "James M Snell" <notifications@github.com> wrote:
>
> @westurner ... definitely agree that it would be helpful, just not sure
it would ever land here (in joyent/node).

So, Node will never have tab completion for nodes and properties? That is
unfortunate. Thanks for your time!

**Comment by jasnell** [comment]
Didn't say never, just meant that it wouldn't land in joyent/node for v0.10 or v0.12. If it's something you'd like to pursue further, opening an issue over in http://github.com/nodejs/node or http://github.com/nodejs/io.js would be helpful... a PR is even more helpful ;-)

**Comment by sibelius** [comment]
@westurner have u figure it out how to create a `?` for documentation and source lookup?

**Comment by westurner** [comment]
@sibelius 
- NPM: https://www.npmjs.com/package/ijavascript
  - Src: https://github.com/n-riesco/ijavascript
  - Docs: https://n-riesco.github.io/ijavascript/doc/usage.md.html
  - Docs: **https://n-riesco.github.io/ijavascript/doc/inspect.md.html**
  - NPM: https://www.npmjs.com/package/jp-kernel
  - Src: https://github.com/n-riesco/jp-kernel
    - Src: https://github.com/n-riesco/jp-kernel/blob/master/lib/handlers_v5.js#L264 inspect_request
    - NPM: https://www.npmjs.com/package/nel
      - Src: https://github.com/n-riesco/nel
      - Src: https://github.com/n-riesco/nel/blob/master/lib/nel.js InspectionMessage
      - Src: https://github.com/n-riesco/nel/blob/master/lib/nel_server.js inspect() -> util.inspect()
        - Src: https://github.com/nodejs/node/blob/master/lib/util.js#L181 util. inspect()

**Comment by westurner** [comment]
@jasnell 

> Didn't say never, just meant that it wouldn't land in joyent/node for v0.10 or v0.12. If it's something you'd like to pursue further, opening an issue over in http://github.com/nodejs/node or http://github.com/nodejs/io.js would be helpful... a PR is even more helpful ;-)

This would be useful for projects which move to new repositories:
- https://github.com/piceaTech/node-gitlab-2-github/blob/master/index.js#L293 createIssueAndComments

Unfortunately I'm not very familiar with node?

Q: Where (in which file) would this go?
- https://github.com/nodejs/node/blob/master/lib/repl.js

## \- https://github.com/nodejs/node/blob/master/test/parallel/test-repl.js test-repl-??.js

Q: Does there need to be a mode switch (because `??` isn't valid JS)?

**Comment by addaleax** [comment]
I think I might want to get started working on something like this, at least for including Node.js’ own docs.

**Comment by princejwesley** [comment]
@addaleax Happy to join  if you need an extra pair of hands.

**Comment by addaleax** [comment]
@princejwesley Awesome! I think I’ll be posting a roadmap issue over at nodejs/node shortly.
