### ISSUE TITLE
Node.js child process on windows fails for node installed cli apps

### ISSUE THREAD

**Issue by davglass** [joyent/node#3968]
On Windows if you use `child_process` to exec another npm installed cli app it fails

Here's an example script:
https://gist.github.com/3638530

Running this on OSX/Linux it works as expected, you get the `npm show` output printed.

Running this on Windows (with 0.8.8) you get: 

```
CreateProcessW:
The system cannot find the file specified.

child exited with code 127
```

Seems like maybe the ENV or path is not being passed to the sub process so it can't find it.

**Comment by jasnell** [comment]
Closing. Does not appear to be anything to do. Can reopen if necessary.
