### ISSUE TITLE
public res.headers

### ISSUE THREAD

**Issue by tj** [joyent/node#3992]
pretty lame to use `res._headers` for logging

**Comment by jasnell** [comment]
@indutny ... just confirming, this landed in io.js already correct?

**Comment by jasnell** [comment]
Deferring to the io.js discussion on this. see https://github.com/nodejs/io.js/pull/772

**Comment by Fishrock123** [comment]
In summary: this a huge headache now, probably requires the http re-write to have a reasonable and long-term API.
