### ISSUE TITLE
crypto.createCredentials PKCS12 not works

### ISSUE THREAD

**Issue by tugrul** [joyent/node#4050]
`crypto.createCredentials()` don't resolve PKCS12 to PEM pkey and cert.

I'm trying to use Google's service API with node.js. But I should use oauth to authorize with p12. Following code don't resolve p12 to der format.

```javascript
var crypto = require('crypto');
var fs = require("fs");

var p12 = fs.readFileSync("googleservice.p12");
var credentials = crypto.createCredentials({pfx: p12, passphrase: "notasecret"});

console.log(credentials);
```
output:
```javascript
{ context: {} }
```

I could resolve p12 with openssl toolkit or php to der format. I'm trying to use der format for signer.

**Comment by jasnell** [comment]
Does not appear to have ever landed. Marking as a feature request.

**Comment by jasnell** [comment]
@indutny @bnoordhuis ... any updates on this one?

**Comment by indutny** [comment]
What is the profit of doing it in core? PKCS12 is pretty fully described in https://tools.ietf.org/html/rfc7292, and can be parsed using pure javascript ASN.1 parser (moment of self-promotion: https://github.com/indutny/asn1.js ).

Do I miss something?

**Comment by jasnell** [comment]
@indutny ... I definitely don't disagree. I'm inclined to close this one. If someone wishes to pursue this further, http://github.com/nodejs/node would be the right place to discuss it.
