### ISSUE TITLE
Serial Port

### ISSUE THREAD

**Issue by mikeal** [joyent/node#4092]
I started a conversation about this on IRC a while back and it seemed to make some headway but died out as we all got busy.

The way I see it, node.js' primary job is to abstract the operating system in to a usable JavaScript platform. Right now, we offer access to the network and filesystem, as well as many higher order abstractions (like HTTP). We do not, however, ship with support for access serial devices, like those plugged in over USB. Most other platforms ship with this support, we don't ship with many things other platforms ship with but this is pretty low level and, I would think, more fundamental.

An ever increasing number of talks I see at conferences and projects are people building things with node.js on new low cost hardware and they are all using node-serialport along with several abstractions on top of it. Right now, node-serialport requires a compile step, and node offers no OOTB access to devices.

I would like to get serial device access in to core before 1.0. People from core that have looked at the node-serialport code base have not been positive about adding it "as is" and, as I understand it, we could use some better support in libuv that would greatly simplify it.

I opened this issue so we can track what people think about this and what steps people need to take to get this in if we think it's important.

**Comment by endorama** [comment]
+1

**Comment by MichaelTheriot** [comment]
+1 I've been using Node to get old devices on the web and this has been a roadblock several times.

**Comment by jasnell** [comment]
@mikeal ... do we need to keep this one open? Any further thoughts on it?

**Comment by mikeal** [comment]
The Hardware WG has taken up a better approach.
