### ISSUE TITLE
cluster: ability to change command line arguments for workers

### ISSUE THREAD

**Issue by andrewrk** [joyent/node#4149]
Currently, with the cluster API, a consumer calls cluster.setupMaster({args: "..."}) one time. But what if I want to spin up some workers with different command line arguments?

Also what if I want to send some command line arguments to the node process itself? Ideally I would be able to change these as well.

**Comment by jasnell** [comment]
@cjihrig ... what was the status on this one?

**Comment by cjihrig** [comment]
@jasnell I don't really see a good way of doing this without either breaking `cluster.fork()`, or introducing a completely new method (`fork2()` for lack of a better name).

**Comment by jasnell** [comment]
Agreed. I'm inclined to close this one for now. If someone wishes to pursue it, they can do some legwork and open a PR against nodejs/io.js or nodejs/node.

**Comment by cjihrig** [comment]
FWIW, I'd be glad to work on this if there was an accepted path forward.
