### ISSUE TITLE
Memory not reclaimed/leaked after a fs.createReadStream()

### ISSUE THREAD

**Issue by 3rd-Eden** [joyent/node#4190]
I was working on adding Stream support in Engine.io and started piping in `/dev/random` over websockets to see how it would perform but I saw that the memory was still growing when destination stream was closed.. So I did some digging and found that just a plan `fs.createReadStream()` with no listeners what so ever leaks memory.

I managed to reduce it to a small example: https://gist.github.com/3947755

Running it with --expose_gc and going a gc() after I close the stream and clean it up using
gc(), there is no change. The node process is still hanging around 80 - 100mb instead of the expected 10mb.

**Comment by jasnell** [comment]
Unable to recreate any leak on this. Behavior seems consistent with what is described in https://github.com/joyent/node/issues/6357. Closing. Can reopen if new information is received.
