### ISSUE TITLE
./configure doesn't confirm existence of g++

### ISSUE THREAD

**Issue by anderm3** [joyent/node#4237]
./configure checks $(CC) but never explicitly for g++.  Obviously g++ should be installed, but it is a separate package on many Linux systems and the existence of cc does note guarantee g++.  There is a note in tools/gyp/pylib/gyp/generator/make.py where g++ is assumed but it never checked for, however it looks like this should be fixed in the top level configure probably during compiler_version() check.

**Comment by jasnell** [comment]
Assuming this is no longer an issue. Closing
