### ISSUE TITLE
node debug repl freezes when dumping variables

### ISSUE THREAD

**Issue by ackalker** [joyent/node#4244]
Wanting to play around with some jQuery selectors from within Node, I modded an http-agent demo to get this:

```javascript
var repl = require('repl');

var httpAgent = require('http-agent'),
    jsdom = require('jsdom');

var agent = httpAgent.create('www.google.com', ['finance', 'news', 'images']);

agent.addListener('next', function (err, agent) {
  jsdom.env({
    html: agent.body,
    scripts: [
      'http://code.jquery.com/jquery.min.js'
    ]
  }, function (err, window) {
    var $ = window.jQuery;
    
    // jQuery is now loaded on the jsdom window created from 'agent.body'
    debugger;
    //console.log($('body').html());
    
    agent.next();
  });
});

agent.addListener('stop', function (agent) {
  console.log('the agent has stopped');
});

agent.start();
```

Running `node debug agent.js` and continuing until the breakpoint in the callback, I wanted to inspect the contents of `$('head')`:

```
debug> repl
> $('head')
```

This freezes the repl and the debugger (or at least it might return something after a *very* long time, sometimes minutes).

Doing instead:

```
debug> repl
> console.dir($('head'))
```
returns results immediately, although not nicely colour-coded etc.

**Comment by jasnell** [comment]
@ackalker ... is this still an issue for you?

**Comment by ackalker** [comment]
Using node v0.12.3, I no longer see the issue, i.e. the REPL returns results quickly.

**Comment by jasnell** [comment]
Thanks for checking! Closing for now
