### ISSUE TITLE
Calling fs.readFile with a string containing a null terminator cause the string to end

### ISSUE THREAD

**Issue by janjongboom** [joyent/node#4294]
(Verified in node 0.6.21 and node 0.8.9). The following code:

```javascript
require("fs").readFile("./server.js\0.json", "utf8", function (err, data) {
    console.log(err, data);
});
```

Causes `server.js` to be read, which I would guess is incorrect, because javascript doesn't care about the terminator (in contrary to the underlying C code). For instance:

```javascript
/json$/.test("./server.js\0.json")
true
```

This is a security issue. Let's say that we read a file that is provided to us by the user (for more info about this, I wrote up my way to this finding [here](http://glamour.tweakblogs.net/blog/8476/node-punt-jss-null-terminator-of-death.html)), and we postfix this with `.json`, execute a realpath and verify that we're really in the right directory and reading a `.json` postfixed file.

```javascript
var gimmeFile = function (filename) {
  var fs = require("fs");
  var path = fs.realpathSync(__dirname + "/" + filename + ".json");
  assert.equal(path.indexOf(__dirname), 0);
  assert.equal(/\.json$/.test(path), true);
}
```

`gimmeFile("server.js\0")` will pass all the assertions but still be able to read other files than intended by this code.

**Comment by jasnell** [comment]
Appears to have been fixed.
