### ISSUE TITLE
readline completer bug on a single hit

### ISSUE THREAD

**Issue by pronebird** [joyent/node#4324]
Hi,

So what I am trying to do is a more complex completer than this one on docs page, the one that parses a sequence of space-separated commands and tries to suggest available keywords within specific scope. So basically I am mapping commands to javascript objects with nesting support, it's a simple CLI.

So everything is okay until I have the only one hit, and when I return [hits, line] which is literally [ ['subscription'], 'instagram' ], readline cuts the part of the hit and shows "instagramion" in console instead of "instagram subscription". So to fix the problem in case of the only one hit I build the whole line and return it within hits array. In fact there's no match between my hits and source line, I return available commands within instagram scope, I am not sure, but maybe readline relies on some kind of matching between hit and source line to achieve autocompletition, I should recheck readline.js again.

This code works perfect, but has this workaround for a single hit case.

**UPDATE:**
It's not a bug, it's a feature. If I have more than 1 hit, I can fill hits with whatever I want and it's going to be just displayed on screen, but when there's the only one hit, it used to replace the whole line in console. I think it should be mentioned in documentation that we can manipulate with data displayed on console without a risk to trash anything.

The whole code looks like this:

```
   // @depends on underscore.js
    var vtable = { 
          instagram: {
              subscription: {
                  create: function(){},
                  delete: function(){},
                  list: function(){}
              }
          } 
    };
    // don't ask me how it works, it's magic...
	var completer = function (line) {
		var split = line.trim().split(' ');
		var hits = [];

		function join_cmd(path, subpath) {
			if(path === '') return subpath;
			return path + ' ' + subpath;
		}
		function unjoin_hits(arr) {
			return _.map(arr, function (val) {
				return val.split(' ').pop();
			});
		}

		function iterator(o, words, path) {
			var keys = _.keys(o);
			var kw = words.shift();
			// array.shift() returns undefined when empty
			// ''.split returns array with empty string
			// awesome.
			if(!_.isString(kw) || kw === '') {
				hits = _.map(keys, function (val) {
					return join_cmd(path, val);
				});
				return;
			}
			for(var i in keys) {
				var key = keys[i];
				var item = o[key];
				if(key === kw && _.isObject(item) && !_.isArray(item)) {
					hits = [];
					return iterator(item, words, join_cmd(path, key));
				} else if(key.indexOf(kw) === 0) {
					hits.push(join_cmd(path, key));
				}
			}
		}

		iterator(vtable, split, '');

		// there is a bug in readline.js I guess...
		// if we have more than 1 hit, we can return just scope keys
		// if we have the only one, we should return the whole line within hits
		if(hits.length > 1) // <-- this line can be commented to reproduce the bug
			hits = unjoin_hits(hits);

		return [hits, line];
	};
```

**Comment by jasnell** [comment]
Not clear if there's anything actually to do here. Closing for now. Can reopen if necessary or if new information is received.
