### ISSUE TITLE
new Buffer(0x3fffffff) crashes on Windows, but not *nix

### ISSUE THREAD

**Issue by mscdex** [joyent/node#4332]
node v0.8.15

Windows even crashes on smaller values, like 0x1fffffff. However this particular value actually _does_ work every once in awhile.

`new Buffer(0x0fffffff)` works every time though. It seems anything higher will crash more often than not.

**Comment by jasnell** [comment]
@mscdex @piscisaureus ... is this still an issue? Can it be closed?

**Comment by mscdex** [comment]
@jasnell Well, it doesn't silently crash on latest 0.10 and 0.12, the `new Buffer(0x3fffffff)` actually "succeeds" and nodejs/node master currently throws a `RangeError: Buffer allocation failed - process out of memory`. I will submit a PR to add `LargeAddressAware` to the VC linker settings.
