### ISSUE TITLE
Windows Installer didn't add Node PATH

### ISSUE THREAD

**Issue by benirose** [joyent/node#4356]
I just installed Node using the .msi for Windows 7 64-bit. It seemed to add npm to my PATH but not node. I was able to add it easily, but didn't see this detail in the instructions. A new developer may not know this is something they have to do if the install fails to do it. Adding a note to the installation instructions may be helpful.

**Comment by misterdjules** [comment]
This has been fixed by io.js in https://github.com/iojs/io.js/issues/603. I suggest that we integrate this fix in v0.12. Removing the maybe-close label.

**Comment by misterdjules** [comment]
We might as well start by integrating this in v0.10.

**Comment by zxqfox** [comment]
:+1:

**Comment by joshbosley** [comment]
I just used the Windows x64 MSI and installed it to a drive separate from the C. My default install area is D:\Programs, yet the npm PATH variable was directed at C\Some\Empty\Dir, and there was no node PATH variable as other people described. It was an easy fix, but I thought I should report it.

**Comment by uniring** [comment]
Same problem here.
Just to save others from searching it in SO:
```SET PATH=C:\Program Files\Nodejs;%PATH%```

**Comment by rjt** [comment]
@joshbosley there is a root (have not looked in years) variable in MSI source that determines the root drive letter.  If not defined, programs might be installed to any drive letter C:, D:, E:....

**Comment by orangemocha** [comment]
Fixed with https://github.com/joyent/node/commit/f50c37d99316f2f7dc1618ea2eef4a0201a5ae0e and shipped in v0.12.5.

**Comment by misterdjules** [comment]
This issue was moved to milestone 0.12.6 by mistake because it hadn't been closed after the fix landed and shipped with node v0.12.5. Moving it back to the 0.12.5 milestone to avoid confusion.

**Comment by ArtemKolodko** [comment]
@uniring it works from console, thank you
