### ISSUE TITLE
fs: Support `close` option for streams (default=true)

### ISSUE THREAD

**Issue by isaacs** [joyent/node#4389]
It's annoying that there's no way to make a fs stream *not* close when it reaches the end, especially when you're providing a fd from a pool that you intend to re-use.

Add a `close` flag.  This defaults to `true` if no fd is passed in, or `false` otherwise.  If it's anything other than boolean `false`, then call `fs.close(fd)` when the EOF is reached.

I'm unsure how this should interact with #4387.  Should it still close on error if you've set `close: false`?

**Comment by jasnell** [comment]
Appears to have landed already
