### ISSUE TITLE
test-net-connect-timeout fails due to ICMP unreachable

### ISSUE THREAD

**Issue by JeremyGrosser** [joyent/node#4553]
Unit tests fail with tagged v0.8.17. test-net-connect-timeout attempts to connect to google.com:9999 and 24.24.24.24:9999 to verify that the timeout handler is called. 24.24.24.24 appears to be a random cable modem on the rr.com network based on reverse DNS. At some point, the router directly upstream from this address started returning ICMP unreachable messages, causing it to throw the 'error' event, rather than 'timeout', which has no event handler defined.

Pinging 24.24.24.24 shows the offending response.
PING 24.24.24.24 (24.24.24.24): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
36 bytes from ae10-0.syrcnycsr-rtr03.nyroc.rr.com (24.24.21.220): Destination Net Unreachable
Vr HL TOS  Len   ID Flg  off TTL Pro  cks      Src      Dst
 4  5  00 5400 2104   0 0000  32  01 28ab 10.2.4.201  24.24.24.24 

The fix would be to change 24.24.24.24 to some other IP that we know will never return an ICMP unreachable message, perhaps Joyent can provide a blackhole address, or one of the reserved IANA subnets like 240.0.0.0 could be used as a substitute?

=== release test-net-connect-timeout ===                               
Path: simple/test-net-connect-timeout
events.js:71
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: connect ENETUNREACH
    at errnoException (net.js:770:11)
    at Object.afterConnect [as oncomplete] (net.js:761:19)
Command: out/Release/node /tmp/buildd/nodejs-0.8.17/test/simple/test-net-connect-timeout.js

**Comment by jasnell** [comment]
Does not appear to be an issue any longer. Can reopen if necessary
