### ISSUE TITLE
simplest domain.run use fails without nextTick if surrounded in try/catch

### ISSUE THREAD

**Issue by bmeck** [joyent/node#4570]
From the REPL or other try/catch situation:

```javascript
var domain = require('domain');
var d=domain.create();
d.on('error', function () {console.log('OK')})
d.run(function () {throw e})
```

Domain.run fails to use the domain and emit the `error` event unless the thrown error is on a different tick, should this be documented or changed?

**Comment by jasnell** [comment]
Appears to have been resolved.

**Comment by clayendisk** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  james.ryan.stortz@gmail.com
    Domain clayendisk.net has exceeded the max emails per hour (36/30 (120%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:33699 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by us-tx-cp01.imbahost.com with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.85)
	(envelope-from <noreply@github.com>)
	id 1YuP4W-0018X9-Pl
	for {}@clayendisk.net; Mon, 18 May 2015 12:43:24 -0500
Date: Mon, 18 May 2015 10:43:26 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1431971006;
	bh=47ag4bhwEk6rN8calER5UFlLXZVn7TckQ0qWcEFjhbI=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=zW0epXkJyUg0CFvgrtFLeCxeyyVtPVeDqsffOZ3TKYjgwS4unQljIZVX+o0XafoKe
	 33ZMixM4BQ5t2d36K+5CBw4NXV03tbUK98YsSPu55Wd8Ec8uPrtSzM18RmeoLS1OD/
	 d7Om05PLgkT8AhVV8fFpo1pBOWfojZxmQHjABxDg=

**Comment by clayendisk** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  james.ryan.stortz@gmail.com
    Domain clayendisk.net has exceeded the max emails per hour (37/30 (123%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:34225 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by us-tx-cp01.imbahost.com with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.85)
	(envelope-from <noreply@github.com>)
	id 1YuP4Y-0018XQ-Fq
	for {}@clayendisk.net; Mon, 18 May 2015 12:43:26 -0500
Date: Mon, 18 May 2015 10:43:28 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1431971008;
	bh=6N2mUI5N1PKWuuvneEHjmpXjc25UUphFqXDQU1wamVw=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=ACS69RqRJpFms6WktOvIe2yiglPKPAF9b2aaL+PkBYHLK/NTX3eIja41zaeFOIIfI
	 XBfm3fNqg1SMbIaeyArRZ/qw5PF6srzr/N3XUHVvV1aeySKsPTvHv+c9AbAstfoA+y
	 zzilanyEsStoDlpb3SwprFO2iJjKX/WHfG18YZk4=
