### ISSUE TITLE
fs.close passes "OK" error message to callback

### ISSUE THREAD

**Issue by mscdex** [joyent/node#4574]
When calling fs.close() many times in a short amount of time, the error, "Error: OK, close" is passed to one of the callbacks.

I've fixed my code now so that fs.close() isn't called multiple times on the same fd, but I think that the error should be more accurate/descriptive.

**Comment by jasnell** [comment]
@bnoordhuis @mscdex ... what was the outcome on this one?

**Comment by clayendisk** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  james.ryan.stortz@gmail.com
    Domain clayendisk.net has exceeded the max emails per hour (34/30 (113%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:24004)
	by us-tx-cp01.imbahost.com with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.85)
	(envelope-from <bounces+848413-74bf-{}=clayendisk.net@sgmail.github.com>)
	id 1YuP20-0018R5-Ud
	for {}@clayendisk.net; Mon, 18 May 2015 12:40:49 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=1N3qVYhkzhoN8YSeYNPRQc1U3H0=; b=nFvJX3VSQapCF0zN
	q6f3mQKety2fStkvB9L1XqM3tTVUq4orddr6r/39AVHg8NclCo2A7Ym2quzT1a/s
	ZNg/jk9MAinPT4L5l89lWx7TqBIIOt+76EBHpBlunv/GcbBeGPhTkxgewJSjH/s5
	eOhXIDz1gCZzUR6nSJaizFEzOTA=
Received: by filter0314p1mdw1.sendgrid.net with SMTP id filter0314p1mdw1.4875.555A241E1D
        2015-05-18 17:40:46.8714505 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd-031 (SG) with ESMTP id 14d681d1869.3a35.2f41aa
	for <{}@clayendisk.net>; Mon, 18 May 2015 17:40:46 +0000 (UTC)
Date: Mon, 18 May 2015 10:40:46 -0700

**Comment by mscdex** [comment]
@jasnell I wasn't able to create a simple, reproducible test case, but perhaps @tjfontaine did. After I corrected the cause of the uninformative error, I did not pursue things further.

**Comment by jasnell** [comment]
I'm unable to recreate and the behavior in the given test case appears to be correct. @joyent/node-coreteam recommend closing this for now and we can reopen if new information is received.

**Comment by jasnell** [comment]
Closing.
