### ISSUE TITLE
test: Show list of failures after test run

### ISSUE THREAD

**Issue by isaacs** [joyent/node#4806]
Sometimes a test will fail, but be SUPER noisy, so you can't see any earlier other failures in the scrollback.

It'd be great if the test runner printed out all the failed tests at the end.

**Comment by jasnell** [comment]
@bnoordhuis @isaacs ... assuming we can close this one now?

**Comment by jasnell** [comment]
Doesn't appear that there's anything to do. Closing. Can reopen if new information is received.
