### ISSUE TITLE
Node keeps turning off QuickEdit mode in Command Prompt and Git Bash

### ISSUE THREAD

**Issue by mcandre** [joyent/node#4809]
I frequently want to copy and paste text in my Command Prompt and Git Bash windows. When running Node, or even `npm --version`, QuickEdit becomes disabled for some reason, and I have to turn it back on.

I've set QuickEdit on for my current session, and as a default for future sessions.

System:

	$ specs node os
	Specs:

	specs 0.2
	https://github.com/mcandre/specs#readme

	npm --version
	1.2.10

	node --version
	v0.8.19

	systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
	OS Name:                   Microsoft Windows XP Professional
	OS Version:                5.1.2600 Service Pack 3 Build 2600

**Comment by jasnell** [comment]
@mcandre ... is this still an issue?

**Comment by piscisaureus** [comment]
This has been fixed for a long time (https://github.com/joyent/libuv/commit/4abad2381e126ad7a9eb18342172e495bf6e681d). 
Closing.
