### ISSUE TITLE
UDP throws unhandled error, even if callback is provided to `send`.

### ISSUE THREAD

**Issue by jwalton** [joyent/node#4846]
If you create a udp4 socket and send some data over it to an invalid hostname (as in the Coffee-Script example below), then the callback will be called to indicate that an error occurred.  Unfortunately, the udp socket will ALSO throw a top-level exception which kills the entire app.

Sample:

    socket = (require 'dgram').createSocket 'udp4'
    #socket.on "error", (err) ->
    #  console.log "Error handler: #{err}"
    
    buffer = new Buffer("foo")
    callback = (err, bytes) ->
      if err
        console.log("Error sending: #{err}")
      else
        console.log("Sent #{bytes}")
    socket.send(buffer, 0, buffer.length, 100, "asdkasd", callback)

Run with "coffee sample.coffee".  You'll get the following output:

    Error sending: Error: getaddrinfo ENOTFOUND
    
    events.js:71
            throw arguments[1]; // Unhandled 'error' event
                       ^
    Error: getaddrinfo ENOTFOUND
        at errnoException (dns.js:37:11)
        at Object.onanswer [as oncomplete] (dns.js:124:16)

And the problem If you uncomment the two lines at the top, and define a "on error" handler, then the callback will be called with the error, and the error handler will also be called, and the program will not terminate (since the socket is never closed.)

I would expect that either the presence of a callback *or* a defined error handler would prevent killing the program, and not require both?

**Comment by jasnell** [comment]
@bnoordhuis @indutny ... do we still want to do something with this one?

**Comment by mcollina** [comment]
@jasnell there is a PR here: https://github.com/joyent/node/pull/7738

**Comment by cjihrig** [comment]
This is now fixed on the io.js `next` branch in 77266d7fadd8dfefb107ccb1e3fe97f9620f1288 and 90daf870a00305dcb4b7bf474d8eafaed0117242.

**Comment by jasnell** [comment]
Do we want to backport?

**Comment by cjihrig** [comment]
It is a semver major change, so if so, it needs to go into master.

**Comment by jasnell** [comment]
I'd say no backport then. We can pick it up later in the converged stream.

**Comment by cjihrig** [comment]
Works for me.

**Comment by mcollina** [comment]
Great!!
