### ISSUE TITLE
many tests are too slow

### ISSUE THREAD

**Issue by isaacs** [joyent/node#4932]
There are a lot of tests that are too slow.  Some of them do 1000ms timeouts and stuff, but are perfectly fine to run much faster than that, especially when they should be responding to events rather than waiting on a setTimeout.  A full second is *way* too long for anything in test/simple/, since we run that very frequently.

It'd be great to have most tests run in under 50ms, or perhaps as much as 200ms for cases where timing is actually relevant to the test.

I'd suggest that some tests should just be retired, but every time I think that, some ancient test ends up catching a regression, so they should probably all stay.

**Comment by jasnell** [comment]
Marking this as a potential iojs-backport, but closing. Can reopen if we feel this is still something worth pursuing in this stream.
