### ISSUE TITLE
windows: test runner failing to delete tmp folder sometimes

### ISSUE THREAD

**Issue by isaacs** [joyent/node#4960]
Doesn't seem to break any tests, but produces some annoying output.  Easier to see when using the tap output, because it's not trying to print everything on the same line:

```
c:\node>python tools/test.py simple/test-cluster-[su]* -p tap
1..2
ok 1 - test-cluster-setup-master.js
os.unlink() [Error 32] The process cannot access the file because it is being us
ed by another process: 'c:\\users\\isaacs~1\\appdata\\local\\temp\\tmpdaempw'
os.unlink() [Error 32] The process cannot access the file because it is being us
ed by another process: 'c:\\users\\isaacs~1\\appdata\\local\\temp\\tmpqzaija'
ok 2 - test-cluster-uncaught-exception.js
```

It looks like we're trying to delete a temp file while some node process is still running.

The weird thing is that neither of those tests does anything with common.tmpDir.

**Comment by jasnell** [comment]
Going to assume that it's safe to close this one. Can reopen if necessary
