### ISSUE TITLE
windows: Failing simple/test-cluster-bind-twice-v2

### ISSUE THREAD

**Issue by isaacs** [joyent/node#4966]
In this test, two child processes are set up.  Each of them in turn do `cluster.fork()`.

In the first child process, the worker listens on common.PORT.  Once it is listening, it sends a message to its parent, which is relayed to its grandparent (the top-level node process).

When the grandparent receives that message, it sends a message to the second child.  The second child then relays it to its cluster worker, which creates a new server, and attempts to listen on the same port.

The intended behavior is that second listen() call gets an `EADDRINUSE`.  However, what's happening instead is that, when the second master process tries to send the created and bound server handle to its cluster worker, `uv_write2` returns -1, and thus the `worker.send()` raises an EINVAL on the worker object in the second parent process.

Why is uv_write2 returning -1, I wonder?

I will continue investigating.  If I don't make it back, perhaps @piscisaureus or @sblom will have an idea of where to keep searching.

**Comment by jasnell** [comment]
Appears to be resolved
