### ISSUE TITLE
improve child node process debugging

### ISSUE THREAD

**Issue by segrey** [joyent/node#5012]
Spawning child node process is extremely useful to utilize CPU processors.
At the moment, it's necessary to check whether parent node process is running in debug mode. If yes a free port is found and ```--debug=<free port`>`` or ```--debug-brk=<free port>``` are added to arguments of ```child_process.spawn``` method. As the child process is spawned, it's necessary to attach debugger to the child process (unfortunately, this step requires manual work and amount of this work depends on the spawned child node process count).

Is it possible to improve the situation in Node.js core itself?
Ideally, whenever child node process is spawned by parent node process that is in debug mode, an IDE/node-inspector suggests you to start debugging it.
Ideas?

As a possible solution ```child_process.spawn``` could invoke callback JavaScript function ```isNodeChildProcessInDebugMode()``` that returns boolean (```true``` means it's necessary to add ```--debug=<port>``` or ```--debug-brk=<port>``` parameter. And the second callback function is  ```nodeChildProcessSpawnedOn(port)``` that is called as child node process is already spawned.
These callback functions could be implemented in ```child_node_process_spawn_listener.js```.
In this case Node.js app could be started like this:
```$ node --child_node_process_spawn_listener=/path/to/child_node_process_spawn_listener.js app.js```

Thanks!

**Comment by jasnell** [comment]
@segrey ... is this still something you're interested in pursuing?

**Comment by segrey** [comment]
@jasnell Nope, no need in this issue anymore.
