### ISSUE TITLE
Major performance degradation in crypto.createHash

### ISSUE THREAD

**Issue by 3rd-Eden** [joyent/node#5015]
A really simple snippet:

```js
var crypto = require('crypto');
 
console.time('iterations');
for (var i = 0; i < 100000; i++) {
  crypto.createHash('md5').update(i + '').digest();
}
console.timeEnd('iterations');
```

Node.js 0.8.22: **329ms**
Node.js 0.10.0: **2291ms**

These results were generated on Mac OSX 10.8.2

**Comment by jasnell** [comment]
@trevnorris ... was this pursued further?

**Comment by jasnell** [comment]
Running in v0.12 on osx...
```
> for (var i = 0; i < 100000; i++) {
...   crypto.createHash('md5').update(i + '').digest();
... }
<Buffer d3 eb 9a 92 33 e5 29 48 74 0d 7e b8 c3 06 2d 14>
> console.timeEnd('iterations');
iterations: 361ms
undefined
> 
```
Going to assume this is resolved. Closing. Can reopen if new information is presented.

**Comment by 3rd-Eden** [comment]
WTF. I don't even.. You run it on one version without comparing regression with the old node to see if its actually resolved. How does that logic even work?!

**Comment by indutny** [comment]
```bash
$ ~/Code/voxer/voxnode/node -e "console.log(process.version);console.time('hash');crypto = require('crypto');for (var i = 0; i < 100000; i++) crypto.createHash('md5').update(i + '').digest();console.timeEnd('hash')"
v0.8.26
hash: 161ms

./iojs -e "console.log(process.version);console.time('hash');crypto = require('crypto');for (var i = 0; i < 100000; i++) crypto.createHash('md5').update(i + '').digest();console.timeEnd('hash')"
v2.0.3
hash: 180ms

~/.node/0.12/bin/node -e "console.log(process.version);console.time('hash');crypto = require('crypto');for (var i = 0; i < 100000; i++) crypto.createHash('md5').update(i + '').digest();console.timeEnd('hash')"
v0.12.0
hash: 386ms
```

So it is resolved in io.js and not resolved in node v0.12

**Comment by mscdex** [comment]
Additionally we should really be using `process.hrtime()` instead of `console.time*()`/`Date.now()`.

**Comment by jasnell** [comment]
@mscdex @indutny ... do you see reason to keep this particular issue open then? The original issue showed a degradation between v0.8 and v0.10. While there are still improvements that definitely can be made, the converged stream will bring along the io.js improvements. Unless you think there's something we need to backport into v0.12, I'm inclined to defer to the converged stream.

**Comment by indutny** [comment]
I don't see any point in having it open.

**Comment by bnoordhuis** [comment]
If there are at least two people willing to do the back-porting work (one to back-port, one to review), it might be reasonable to keep the issue open.  I'm going to guess however that no one is volunteering.
