### ISSUE TITLE
FreeBSD Support

### ISSUE THREAD

**Issue by isaacs** [joyent/node#5025]
It'd be nice to support FreeBSD as a first-class citizen in Node.

As it is, we've got our hands full with sunos, linux, windows, and os x.  When bugs come up, we do what we can or add whatever ifdefs we need to, but no one really cares THAT much to get to the bottom of things.

In order to make FreeBSD a Unix that we officially support, we'd need someone to adopt this, and be in charge of making sure that it builds/etc.  It'd be nice to even have a nice up to date port install, etc.

Until someone can lead this charge, this issue will sit here waiting to be adopted.

**Comment by jasnell** [comment]
While FreeBSD support is good, this is fairly non-specific and not a directly actionable issue. Closing. Can reopen if necessary
