### ISSUE TITLE
debug internal error ECONNREFUSED

### ISSUE THREAD

**Issue by ne222** [joyent/node#5043]
Reproducible everytime debug used. Reporting it as requested.
Install node-v0.10.0-x86.msi on Windows 7 x64.

node debug test.js
< debugger listening on port 5858
connecting... ok
break in test.js:1
  1 console.log("start test.js");
  2 debugger;
  3 console.log("end test.js");
debug> c
< start test.js
break in test.js:2
  1 console.log("start test.js");
  2 debugger;
  3 console.log("end test.js");
  4
debug> c
< end test.js
program terminated
program terminated
program terminated
program terminated
program terminated
program terminated
program terminated
program terminated
program terminated
program terminated
debug> .There was an internal error in Node's debugger. Please report this bug.
connect ECONNREFUSED
Error: connect ECONNREFUSED
    at errnoException (net.js:863:11)
    at Object.afterConnect [as oncomplete] (net.js:854:19)

test.js
console.log("start test.js");
debugger;
console.log("end test.js");

**Comment by jasnell** [comment]
@ne222 and @budajeff ... are you still having issues with this? And if so, on what version of node did you test?

**Comment by joaocgreis** [comment]
I was able to reproduce on v0.10.0 as reported, but not on v0.10.39 or v0.12.5, so closing.

@ne222 , @budajeff , thanks for reporting and let us know if you still have this problem with recent versions, we can reopen and investigate more.
