### ISSUE TITLE
Readable stream with highWaterMark==0 behavior

### ISSUE THREAD

**Issue by kanongil** [joyent/node#5085]
I have made a Readable object-stream which takes a highWaterMark option. This works fine for the most part, but I find that the Readable interaction is buggy and/or strange when highWaterMark==0.

With hwm==0, I would expect the stream to match any `read()` calls from a consumer with an internal `_read()` call. Currently I see _two_ `_read()` calls before my first `read()` has returned, and the remaining `_read()` calls always seems ahead.

Expected flow from client:
  1. Client registers `r.on('readable')` which triggers a `r._read()`.
  1. Readable triggers 'readable' from async `r.push()`.
  1. Client calls read() which returns the pushed object.
  1. Client calls read() again which triggers `r._read()` and returns null since data is async.
  1. goto 2.

**Comment by jasnell** [comment]
@isaacs ... was there ever any action on this? This looks like a feature request, yes?

**Comment by kanongil** [comment]
I just had another a look at this, and it appears that this has been fixed in streams3.

Test script:
```js
var R = require('readable-stream').Readable;

var cnt = 0;
var r = new R({ highWaterMark: 0, objectMode: true });
r._read = function(n) {
  console.log('_read');
  setImmediate(function() {
    if (cnt > 1) return r.push(null);
    r.push(cnt++);
  });
};

r.on('readable', function() {
  var obj;
  while (null !== (obj = r.read())) {
    console.log('object', obj);
  }
});
```

Result using `readable-stream@1.0.33`:
```
_read
_read
object 0
_read
object 1
```

Result using `readable-stream@1.1.13` (note the initial double `_read` is gone):
```
_read
object 0
_read
object 1
_read
```

**Comment by jasnell** [comment]
Great! Then I'll close. Can reopen if necessary
