### ISSUE TITLE
net.js - possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by aimnadze** [joyent/node#5108]
I don't know exactly when this happens. But I know this is not caused by my code. This happens in Node v0.10.0. Line numbers have changed a little bit since then but the stack trace might be usefull:

    (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
    Trace
        at Socket.EventEmitter.addListener (events.js:160:15)
        at Socket.Readable.on (_stream_readable.js:653:33)
        at Socket.EventEmitter.once (events.js:179:8)
        at TCP.onread (net.js:512:26)
    FATAL ERROR: Evacuation Allocation failed - process out of memory

**Comment by nicholas-c** [comment]
Still getting this error on V0.13.0-pre...

    (node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at PoolConnection.addListener (events.js:179:15)
    at /srv/nodeServer/app/rest-api.js:48:14
    at Ping.onPing [as _callback] (/srv/nodeServer/app/node_modules/mysql/lib/Pool.js:94:5)
    at Ping.Sequence.end (/srv/nodeServer/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Ping.Sequence.OkPacket (/srv/nodeServer/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:105:8)
    at Protocol._parsePacket (/srv/nodeServer/app/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/srv/nodeServer/app/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/srv/nodeServer/app/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/srv/nodeServer/app/node_modules/mysql/lib/Connection.js:82:28)
    at Socket.emit (events.js:107:17)

**Comment by v0lkan** [comment]
Getting the error with PubNub especially under poor network conditions.

First I suspected it was due to event loop being congested (I was programming a microcontroller, so blocking the event loop is easier than a beefier web server) — though no matter how slow I open the sockets, yield things with setTimeout/setImmediate etc; I still got the error.

node v0.10.32 on Tessel TM-00-04 (firmware updated on Feb 9th 2015)

I don’t have diagnostic info to share right now; I will post when I have some.

**Comment by Kurtz1993** [comment]
Still happening in 0.10.36 :S

**Comment by nicholas-c** [comment]
Still getting this on mysql connection pool  - 0.10.28 (Different server than above)

    (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
    Trace
    at PoolConnection.EventEmitter.addListener (events.js:160:15)
    at .../nodejs/nodeServer/app/rest-api.js:47:15
    at Ping.onPing [as _callback] (.../app/node_modules/mysql/lib/Pool.js:94:5)
    at Ping.Sequence.end (...app/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Ping.Sequence.OkPacket (.../app/node_modules/mysql/lib/protocol/sequences/Sequence.js:105:8)
    at Protocol._parsePacket (.../app/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/.../app/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (...app/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/.../app/node_modules/mysql/lib/Connection.js:82:28)
    at Socket.EventEmitter.emit (events.js:95:17)

**Comment by mz3** [comment]
I'm getting this error using Grunt with Node v0.12.2.

**Comment by sam-github** [comment]
I think this should be closed. Its expected to get this warning when adding more than 11 event listeners to an emitter. You can get all the listeners from the EE and investigate what listeners were added, but unless there is evidence that node itself is leaking emitters, this is expected behaviour. Gather that evidence and reopen when if it can be found.

**Comment by jasnell** [comment]
@sam-github :+1:

**Comment by amir-rahnama** [comment]
I am still getting this error with Node 4.2.1 using JSDom 7.1.1 when trying to scrape a page every second:

``` bash
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Socket.addListener (events.js:239:17)
    at Socket.Readable.on (_stream_readable.js:665:33)
    at Object.done (/Users/ara/dev/iteam/data-mining/streamers/scrape/inloggedcars.js:24:22)
    at /Users/ara/dev/iteam/data-mining/streamers/node_modules/jsdom/lib/jsdom.js:271:18
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)
```

**Comment by rizvanhaider** [comment]
I got the same issue on this code with strongloop(loopback)

```
module.exports = function (app) {
    var dataSourceDS1 = app.dataSources.DS1;
    var dataSourceDS2 = app.dataSources.DS2;
    var ReLocationTbl = dataSourceDS1.models["ReLocationTbl"]
    var MmLocationTbl = dataSourceDS2.models["MmLocationTbl"]
    MmLocationTbl.find(function (err, data) {
            if (!err) {
                console.log(data.length)
               data.forEach(function(location){
                   console.log(location)
                     ReLocationTbl.create(
                        location,
                        function (err, obj) {
                            if (!err) {
                                console.log("Success posting "+ location)
                            } else
                                console.log("Failed  posting "+ location)
                            console.log(err)
                        })
               }) 

            }
        })
}
```

**Comment by aldegoeij** [comment]
+1

**Comment by calzoneman** [comment]
This has probably been mentioned multiple times in this thread, but because nobody bothers to read it, here's a comment from literally 5 comments above mine:

> I think this should be closed. Its expected to get this warning when adding more than 11 event listeners to an emitter. You can get all the listeners from the EE and investigate what listeners were added, but unless there is evidence that node itself is leaking emitters, this is expected behaviour. Gather that evidence and reopen when if it can be found.

**Comment by tuwid** [comment]
having the same issue with request (that uses the http core module )

**Comment by ghost** [comment]
Please read: 
https://github.com/angular-fullstack/generator-angular-fullstack/issues/1136#issuecomment-128668154

**Comment by neurohacked** [comment]
I'm having this issue when I run `foundation new` in my CLI, trying to set up a new [Foundation Project](http://foundation.zurb.com/sites/docs/installation.html). Using Node v6.5.0, I get the same repeating error (approx. 23 times)

`(node:12342) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit`

The node number is always different each time I try to start a new Foundation Project but the warning and number of warnings is always the same.

If I downgrade to Node v.4.5.0 I still get the error, but it is only displayed once and not with any number attached:

`(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit`

**Comment by neurohacked** [comment]
I'm having this issue when I run `foundation new` in my CLI, trying to set up a new [Foundation Project](http://foundation.zurb.com/sites/docs/installation.html). Using Node v6.5.0, I get the same repeating error (approx. 23 times)

`(node:12342) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit`

The node number is always different each time I try to start a new Foundation Project but the warning and number of warnings is always the same.

If I downgrade to Node v.4.5.0 I still get the error, but it is only displayed once and not with any number attached:

`(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit`

**Comment by blaskovicz** [comment]
I agree with @calzoneman, the fix in my case was that I had to call:
`someEmitterObj.removeListener('eventName', func);`.

[doc reference](https://nodejs.org/api/events.html#events_event_removelistener)
