### ISSUE TITLE
document architecture node.js / node.cc

### ISSUE THREAD

**Issue by othiym23** [joyent/node#5156]
A lot of the important implementation details of Node are in these two files, and due to their performance sensitivity, they're written in a style that's pretty forbidding to newcomers, who may be only interested in one piece of what's going on (say, the interaction between the event loop and domains, or how the nextTick queue gets processed). A technical overview of how all the pieces are put together would be very useful.

/cc @trevnorris

**Comment by jasnell** [comment]
@trevnorris ... did this ever happen?

**Comment by trevnorris** [comment]
@jasnell there was further discussion off this thread. there was some disagreements about how it was supposed to get done. then never did.

**Comment by jasnell** [comment]
Ok, closing then. This is something that would still likely be good to do but given the lack of action...
