### ISSUE TITLE
Chunked encoding + setNoDelay

### ISSUE THREAD

**Issue by molnarg** [joyent/node#5204]
I'm using chunked encoding to send data in HTTP responses. I turned on NO_DELAY for HTTP responses, because if I don't, there's a 500ms wait before sending the last chunk of the answer. (as I understand, this is because of Nagle's algorithm)

But in this configuration, every length specification string (that's sent before every chunk in chunked encoding), and then every \r\n goes into a new package. That means huge TCP overhead, because in these packets there's at most 10 bytes of data and 68 byte of IP/TCP header.

The node.js HTTP implementation should write the length specification, the following newline, and the data in one write operation.

(PS: I didn't find a way to batch write operations other than to concatenate them into one buffer. Is there a more friendly solution for this?)

**Comment by jasnell** [comment]
@indutny ... was there any resolution on this one?

**Comment by indutny** [comment]
Yep, it is fixed!
