### ISSUE TITLE
Error message problem: "Error: no error" (Windows)

### ISSUE THREAD

**Issue by medikoo** [joyent/node#5254]
In certain circumstances, see e.g. https://github.com/ncb000gt/node.bcrypt.js/issues/143
Node crashes with `Error: no error` message.

It seems to come from node internals, as it fires right at the require of compiled module.

It would be helpful if it's replaced with meaningful message that could shed more light on what might be the cause.

**Comment by jasnell** [comment]
@medikoo ... I know it's been a while, but is this still an issue?

**Comment by medikoo** [comment]
@jasnell I had this error on machine long time ago, to which I don't have access now, so I'm unable to reproduce it.
This issue was mainly about fixing the message of the error, which said some nonsense, and not necesarry the error, which might have been thrown for right reason.

**Comment by jasnell** [comment]
Ok, the "no error" is likely from uv but the issue, I suspect, was actually in bcrypt (the "no error" message is a legitimate response from uv). Given that this cannot be reproduced, I'm closing. Can reopen if new information is received.
