### ISSUE TITLE
Test Failure - test-tls-securepair-client

### ISSUE THREAD

**Issue by dsn** [joyent/node#5264]
OS: Fedora Core 16
Arch: x64
Node Version: 0.10.3
Python Version: 2.7.3
Make Version: 3.82

=== release test-tls-securepair-client ===                                     
Path: simple/test-tls-securepair-client
Using default temp DH parameters
ACCEPT
   0 items in the session cache
   0 client connects (SSL_connect())
   0 client renegotiates (SSL_connect())
   0 client connects that finished
   0 server accepts (SSL_accept())
   0 server renegotiates (SSL_accept())
   0 server accepts that finished
   0 session cache hits
   0 session cache misses
   0 session cache timeouts
   0 callback cache hits
   0 cache full overflows (128 allowed)
getaddrinfo: Name or service not known
Using default temp DH parameters
ACCEPT
getaddrinfo: Name or service not known
   0 items in the session cache
   0 client connects (SSL_connect())
   0 client renegotiates (SSL_connect())
   0 client connects that finished
   0 server accepts (SSL_accept())
   0 server renegotiates (SSL_accept())
   0 server accepts that finished
   0 session cache hits
   0 session cache misses
   0 session cache timeouts
   0 callback cache hits
   0 cache full overflows (128 allowed)
socket error: Error: connect ECONNREFUSED
client close
socket error: Error: connect ECONNREFUSED
client close
WAIT-ACCEPT
WAIT-ACCEPT
WAIT-ACCEPT
WAIT-ACCEPT
WAIT-HELLO

assert.js:98
  throw new assert.AssertionError({
        ^
AssertionError: "WAIT-SERVER-CLOSE" == "WAIT-HELLO"
    at process.<anonymous> (/opt/dist/node-v0.10.3/test/simple/test-tls-securepair-client.js:198:12)
    at process.EventEmitter.emit (events.js:117:20)
Command: out/Release/node /opt/dist/node-v0.10.3/test/simple/test-tls-securepair-client.js

**Comment by jasnell** [comment]
Unable to reproduce failure.
