### ISSUE TITLE
Test Failure - test-net-pingpong

### ISSUE THREAD

**Issue by dsn** [joyent/node#5265]
OS: Fedora Core 16
Arch: x64
Node Version: 0.10.3
Python Version: 2.7.3
Make Version: 3.82

=== release test-net-pingpong ===                                              
Path: simple/test-net-pingpong
  server.on('exit', function(code) {
    serverExitCode = code;
    clearTimeout(timeout);
    if (next) next();
  });

  function startClient() {
    var s = new net.Stream();

    var sslcontext = crypto.createCredentials({key: key, cert: cert});
    sslcontext.context.setCiphers('RC4-SHA:AES128-SHA:AES256-SHA');

    var pair = tls.createSecurePair(sslcontext, false);

    assert.ok(pair.encrypted.writable);
    assert.ok(pair.cleartext.writable);

    pair.encrypted.pipe(s);
    s.pipe(pair.encrypted);

    s.connect(PORT);

    s.on('connect', function() {
      console.log('client connected');
    });

    pair.on('secure', function() {
      console.log('client: connected+secure!');
      console.log('client pair.cleartext.getPeerCertificate(): %j',
                  pair.cleartext.getPeerCertificate());
      console.log('client pair.cleartext.getCipher(): %j',
                  pair.cleartext.getCipher());
      if (check) check(pair);
      setTimeout(function() {
        pair.cleartext.write('hello\r\n', function() {
          gotWriteCallback = true;
        });
      }, 500);
    });

    pair.cleartext.on('data', function(d) {
      console.log('cleartext: %s', d.toString());
    });

    s.on('close', function() {
      console.log('client close');
    });

    pair.encrypted.on('error', function(err) {
      console.log('encrypted error: ' + err);
    });

    s.on('error', function(err) {
      console.log('socket error: ' + err);
    });

    pair.on('error', function(err) {
      console.log('secure error: ' + err);
    });
  }

  process.on('exit', function() {
    assert.equal(0, serverExitCode);
    assert.equal('WAIT-SERVER-CLOSE', state);
    assert.ok(gotWriteCallback);
  });
}
/opt/dist/node-v0.10.3/test/tmp/test.sock
server listening on /opt/dist/node-v0.10.3/test/tmp/test.sock undefined
server listening on 12346 undefined
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRNOTAVAIL
    at errnoException (net.js:878:11)
    at Server._listen2 (net.js:997:19)
    at listen (net.js:1038:10)
    at net.js:1112:9
    at dns.js:72:18
    at process._tickCallback (node.js:415:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:901:3
Command: out/Release/node /opt/dist/node-v0.10.3/test/simple/test-net-pingpong.js

**Comment by jasnell** [comment]
Unable to reproduce failure.
