### ISSUE TITLE
Lookup SRV-records for http/https requests (feature request)

### ISSUE THREAD

**Issue by VanCoding** [joyent/node#5279]
What about looking up SRV-records of DNS servers to decide to which server the program should connect for making a http/https request?

I know that it's currently not supported in any browser, but since Node.js has more and more influence to the web, this could set a sign to browsers as well.

SRV-Records are used for almost all other popular protocols, just not for HTTP. We can change this! SRV records are a key feature in intelligent load balancing and in reducing the need of proxy servers (to run multiple web-services on a single server for example), so they are a nice thing.

They are also standardized for a very long time (also for the use with HTTP/HTTPS), so you don't have to invent some new standard, you just can follow the standard and it will work great.

Here are some links for you about the topic:
http://blog.milkfarmsoft.com/2009/09/dns-srv-records-support-in-http-browsers/
http://homepage.ntlworld.com/jonathan.deboynepollard/FGA/dns-srv-record-use-by-clients.html
http://www.pantz.org./software/bind/srvdnsrecords.html
https://code.google.com/p/chromium/issues/detail?id=22423

What do you think?

**Comment by jasnell** [comment]
SRV support is already implemented
