### ISSUE TITLE
misleading example in http.request(options, callback) docs 

### ISSUE THREAD

**Issue by tsojcanth** [joyent/node#5317]
The example at http://nodejs.org/api/http.html#http_http_request_options_callback does not mention that the response can come in different chunks and does not set up an "on end" event.

I suggest replacing the relevant parts with something similar to the following:
```js
var body ='';

var req = http.request(options, function(res) {
  console.log('STATUS: ' + res.statusCode);
  console.log('HEADERS: ' + JSON.stringify(res.headers));
  res.setEncoding('utf8');
  res.on('data', function (chunk) {
    console.log('ANSWER CHUNK: ' + chunk);
    body  += chunk;
  });
  res.on('end', function () {
    console.log('COMPLETE ANSWER: ' + body);
  });
  req.on('error', function(e) {
    console.log('problem with request: ' + e.message);
  });
});

```

**Comment by OrangeDog** [comment]
Your example doesn't handle the case when the chunk boundary falls in the middle of a UTF-8 sequence.

**Comment by jasnell** [comment]
@OrangeDog ... suggestions on further specific improvements? :-) Would like to keep it fairly concise.

**Comment by jasnell** [comment]
Landed in https://github.com/joyent/node/commit/6f9b1789d2239ad23e97f9ff8ac14e03635d6412
