### ISSUE TITLE
net: remove net.Server#maxConnections

### ISSUE THREAD

**Issue by bnoordhuis** [joyent/node#5372]
Category: pre-v1.0 cleanup.

I move to remove net.Server#maxConnections in v1.0 (with proper deprecation in v0.12) for no other reason than that it's such a silly feature. It doesn't belong in core, it wasn't added for any particular reason, it's trivial to emulate in user land. It's not really hurting right now but it very well might in the future.

Ditto for net.Server#connections (though that's already deprecated) and net.Server#getConnections(). The latter is excellent proof of why adding features just for the sake of it is a bad idea.

Not sure who to cc on this. @isaacs, @TooTallNate?

**Comment by jasnell** [comment]
@bnoordhuis ... was there any action taken on this one?

**Comment by bnoordhuis** [comment]
No, I'll close it.  I still think it's silly though; it doesn't even work the way people expect it to: https://github.com/nodejs/io.js/issues/1744
