### ISSUE TITLE
v0.10.5 spawned processes behave differently from v0.8.15

### ISSUE THREAD

**Issue by bpytlik** [joyent/node#5386]
Here's the js script that will be spawned. Let's call it listen.js:
```javascript
// Generated by CoffeeScript 1.6.2
(function() {
  var readline, rl;

  readline = require("readline");

  rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });

  rl.on("line", function(line) {
    console.log("saw this line:" + line);
    return rl.close();
  });

}).call(this);
```
It reads one line from the user, prints it then exits. When run from the command line under node v0.8.15 and v0.10.5, it behaves as expected.

Let's take a second script which spawns listen.js:
```javascript

// Generated by CoffeeScript 1.6.2
(function() {
  var cmd, spawn,
    _this = this;

  spawn = require("child_process").spawn;

  cmd = spawn(pth_to_node, ["./listen2.js"], {
    stdio: "pipe"
  });

  cmd.on("exit", function(code, signal) {
    return console.log("got shutdown");
  });

  cmd.stdout.on("data", function(data) {
    return console.log("stdout got:" + data);
  });

  cmd.stderr.on("data", function(data) {
    return console.log("stderr got:" + data);
  });

  cmd.stdin.write("hello\n");

}).call(this);
```
If `<pth_to_node>` in the `<spawn>` call is set to node v0.8.15, then the initial program sends "hello" to the 'listen' process which echoes it then exits. The parent program displays:
    stdout got:saw this line:hello
    
    
    got shutdown
then exists as expected. If `<pth_to_node>` is set to node v0.10.5, then the parent program displays:
    stdout got:saw this line:hello
    
    
but never displays "got shutdown" nor exits. The behavior difference happens whether the parent program was started using node v0.8.15 or node v0.10.5.

The final bit of info that I have is that if I add this line
```javascript
    cmd.stdin.end()
```
immediately after the write, then the processes exit as expected under v0.10.5.

I didn't see anything in the documentation or changelog that would suggest this change of behavior. The closest I found were these changes in the 0.9.6 change log:
* child_process: Fix {stdio:'inherit'} regression (Ben Noordhuis)
* child_process: Fix pipe() from child stdio streams  (Maciej Małecki)
but it's unclear from the summary.

Issue #4510 looks similar (specifically the third comment) though the conversation there focuses on sockets.

Thanks.

**Comment by jasnell** [comment]
Appears to have been resolved
