### ISSUE TITLE
Debugging support broken after v0.8.23

### ISSUE THREAD

**Issue by dandv** [joyent/node#5395]
This is an end-user-level bug report, as I don't have much insight into Node.js yet.

The problem is that debugging Node.js from IDEs such as WebStorm and Komodo is broken in several ways after v0.8.23 (which is the last version that supports breakpoints relatively well):

1. Breakpoints aren't honored - [Komodo bug](http://bugs.activestate.com/show_bug.cgi?id=98886), [WebStorm bug](http://youtrack.jetbrains.com/issue/WEB-7605#comment=27-496443)
2. Erratic console output - [Komodo](http://bugs.activestate.com/show_bug.cgi?id=98761), [WebStorm](http://youtrack.jetbrains.com/issue/WEB-7598)

With v0.9.2 on Windows 7 (though [this thread](http://community.activestate.com/node/9586) suggests a cross-platform problem), both Komodo and WebStorm exhibit the problems mentioned above, so I thought I'd file a ticket here and help the teams fix this.

**Comment by jasnell** [comment]
Closing. Can reopen if new information is presented.
