### ISSUE TITLE
refactor setting object properties in cc

### ISSUE THREAD

**Issue by trevnorris** [joyent/node#5539]
I create a test to examine the [performance difference setting object properties in cc and in js](https://github.com/trevnorris/talks/tree/master/js-vs-cc-set-properties). Here's an excerpt from the commit message:
```
Each method creates a new Object then iterates over and sets the
properties on that Object.

setInCCSlow - Creates a new String for each key every time
setInCCSym - Uses pre-defined Persistent Strings for keys
setInJS - The Object and values are passed to a js Function where the
          Object properties are set
SetInJSObj - js creates the object and sets its properties

The mean speeds on my box:

setInCCSlow - 1615ns
setInCCSym  - 830ns
setInJS     - 405ns
setInJsObj  - 112ns
```
Basically, when we need to create an `Object` and set several properties it's substantially faster to do so in js, then pass the object back to cc. The case in particular I'm thinking of is `node_http_parser`.

I'd like to refactor these to take advantage of the fact doing specific operations is substantially faster in js.

A [bug has been filed](http://code.google.com/p/v8/issues/detail?id=2696) about this. Hopefully it'll be fixed and this will becomes a non-issue.

**Comment by jasnell** [comment]
@trevnorris ... any reason to keep this open?

**Comment by trevnorris** [comment]
nope.
