### ISSUE TITLE
Incorrect default install path for x64 node .msi

### ISSUE THREAD

**Issue by natecain** [joyent/node#5592]
Hello,

On my windows 8 laptop the 64-bit msi installers from the node download page show a default install path of "\Program Files (x86)\" instead of the expected "\Program Files\" path.  This adds a counter-intuitive step in the install workflow, and is especially problematic when both architectures are to be installed side-by-side.

**Comment by joaocgreis** [comment]
Fixed by 14db629497d0eb97a5f0fbb70cf3e534e460deec, but this will only work on fresh installs starting from the next release. Thank you!
