### ISSUE TITLE
Repl in node debug can only be exited using ctrl-c

### ISSUE THREAD

**Issue by srathbun** [joyent/node#5631]
Node debug allows you to drop into a repl at your current location using the `repl` command. To exit this, the only allowed method is to use `ctrl-c` since `.exit` does not work. As shown [here](https://github.com/joyent/node/blob/master/lib/_debugger.js#L1545), the repl listens to SIGINT, but sending it a sigint with kill, breaks the debugger. 

I'm not sure, but [digging into the repl source](https://github.com/joyent/node/blob/master/lib/repl.js#L169) seems to indicate that it only pays attention to SIGINT from the attached terminal, instead of in general. This is a problem if the debugger is a child process of a script, and SIGINT on the script causes an exit.

If `.exit` acted the same as `ctrl-c` during debugging, this problem would be solved.

**Comment by jasnell** [comment]
New PR opened over in nodejs/node. Will continue to track this discussion from there. https://github.com/nodejs/node/pull/2369
