### ISSUE TITLE
[bug] CryptoStream.prototype.destroySoon() in tls.js breaks strict mode

### ISSUE THREAD

**Issue by binarykitchen** [joyent/node#5649]
running my node app with node.js v0.10.10 in `--use-strict` mode causes this stack trace:

```
tls.js:649
    function finish() {
    ^^^^^^^^
SyntaxError: In strict mode code, functions can only be declared at top level or immediately within another function.
    at NativeModule.compile (node.js:891:14)
    at NativeModule.require (node.js:861:18)
    at https.js:22:11
    at NativeModule.compile (node.js:892:5)
    at Function.NativeModule.require (node.js:861:18)
    at Function.Module._load (module.js:297:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    ...
```

nothing serious but would be good to fix this soon and to make a rule saying the node.js core is always compatible with the strict mode.

cheers

**Comment by jasnell** [comment]
There are a number of known issues using strict mode in v0.10 and v0.12 that are resolved in the io.js stream. Once we converge, those issues will be resolved. I'm inclined to defer this issue until then. @joyent/node-coreteam

**Comment by cjihrig** [comment]
I'd say just wait until the converged branch. You shouldn't use `--use-strict` anyway.

**Comment by jasnell** [comment]
+1, given that, I'm inclined to close this.
