### ISSUE TITLE
Proposal: increment NODE_MODULE_VERSION on each dev release

### ISSUE THREAD

**Issue by rvagg** [joyent/node#5789]
Each 0.11 release seems to have some breakage of the C++ API, which is to be expected. But this causes breakage for native addons and even though dev release are caveat emptor we have a simple mechanism in place to help deal with the breakage: NODE_MODULE_VERSION.

I'd like to propose that, regardless of what's going on with the C++ API, that this number be incremented for each 0.11 (dev) release. it can be incremented for stable releases when absolutely necessary but this is rare. The incrementing between dev and stable would need to be synchronized, so if we got to 0.11.10 and were on `15` and a stable 0.10.20 needed to be incremented then it could just be made `16` and 0.11.11 would become `17`. There's no great significance to these numbers except that they need to be unique for each version of the API.

Lots of people are jumping on 0.11 because of the --harmony goodness (generators seem to be exciting atm), how about we make it easier for them when they're also doing it with native addons and instead of giving them cryptic errors because of incompatibilities when they hit them, give them a clear message about version incompatibilities and the need to recompile.

**Comment by jasnell** [comment]
@rvagg ... any reason to keep this open here?

**Comment by rvagg** [comment]
hah, 2 years old .. closing

**Comment by mikemorris** [comment]
Discovered that the Node.js v0.12.x **stable** series is [upgrading v8 and libuv in patch versions](https://nodejs.org/changelog.html) without bumping `NODE_MODULE_VERSION`. This is breaking important assumptions in node-pre-gyp, and is causing binaries built on v0.12.0 to be ABI-incompatible when attempting to run on v0.12.4.

> libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: libuv version mismatch: headers report 1.0.2, but library reports 1.5.0
