### ISSUE TITLE
child_process.spawn should allow strings for UID and GID

### ISSUE THREAD

**Issue by grudzinski** [joyent/node#5824]
Original title: require('child_process').spawn throws "TypeError: options.uid should be a number" when options.uid is a string:

```javascript
require('child_process').spawn('true', [], {uid: 'ec2-user'})
```

According to API doc [spawn](http://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options) should work as [setuid](http://nodejs.org/api/process.html#process_process_setuid_id) and accept a string.

**Comment by jasnell** [comment]
@bnoordhuis ... any reason to keep this open given the lack of activity?

**Comment by bnoordhuis** [comment]
I'm fine with closing it.
