### ISSUE TITLE
QueryString.stringify and Buffers

### ISSUE THREAD

**Issue by zxqfox** [joyent/node#5827]
typeof Buffer is an object.
So if we pass some buffer instantly to stringify we've got that:
```js
> require('querystring')stringify(new Buffer([0x10]))
'0=16&length=1&parent=&offset=16'
```
It's not the same what we want to see here but try again and wrap Buffer into an Object:
```js
> require('querystring').stringify({buff: new Buffer([0x10])})
'buff='
```
Again, we didn't see buff=%10 as expected.
And btw, when we trying to overload .escape method of querystring, we getting empty string there instead of Buffer object because of stringifyPrimitive and stringify's inner logic.

But let's make it another way. Let's try to convert buffer to string of hexes and:
```js
> function yuppie (buff) { return buff.toString('hex').replace(/([\d\w]{2})/, '%$1'); }
> require('querystring').stringify({buff: yuppie(new Buffer([0x10]))})
'buff=%2510'
```
God damn it!

1. Why querystring doesn't know about Buffers?
2. How to pass a Buffer (or binary data) to querystring.stringify or to some library based on it?
3. Can we just add support of Buffers to querystring? Does it wrong or why it can't be added?

**Comment by jasnell** [comment]
@trevnorris ... is there a reason to keep this open?

**Comment by trevnorris** [comment]
@jasnell nope.
