### ISSUE TITLE
node-v11 dns.lookup for IP do not invoke the callback

### ISSUE THREAD

**Issue by harlentan** [joyent/node#5873]
```javascript
//...  
 callback = makeAsync(callback);
//...
var matchedFamily = net.isIP(domain);
  if (matchedFamily) {
    callback(null, domain, matchedFamily);
    return {};
  }
```

dns.lookup(), if the domain is a ip, the callback will not be invoked sometime after
makeAsync().

Why the other callback in onanswer is called with  callback.immediately = true, but 
the lookup ip?

**Comment by jasnell** [comment]
@cjihrig ... see any reason to keep this one open?

**Comment by cjihrig** [comment]
Let's close this. Nobody ever seemed to really understand what the reported issue is. If needed, we can always reopen.
