### ISSUE TITLE
timers: set{Immediate,Timeout} and general event loop clarification

### ISSUE THREAD

**Issue by trevnorris** [joyent/node#5943]
Add better documentation about the event loop so people can easily understand why things like the following occur:
```javascript
setImmediate(function() { console.log('setImmediate'); });
setTimeout(function() { console.log('setTimeout'); }, 0);
process.nextTick(function() { console.log('nextTick'); });

// output:
// nextTick
// setTimeout
// setImmediate
```

@isaacs think this should go in the standard API docs, or some other location we can reference?

**Comment by jasnell** [comment]
@trevnorris ... assuming we can close this also since #5950 was closed.
