### ISSUE TITLE
Support for TLS ALPN

### ISSUE THREAD

**Issue by molnarg** [joyent/node#5945]
TLS Application Layer Protocol Negotiation Extension is a [new standard][1] designed to be an alternative to NPN. It will be used for [negotiating HTTP2 over TLS][2]. This ticket is meant to track progress of inclusion of ALPN in node.js.

AFAIK, this depends on OpenSSL to implement ALPN. There's a [patch][3] floating around for OpenSSL, but it's not merged yet.

[1]: http://tools.ietf.org/html/draft-friedl-tls-applayerprotoneg-02
[2]: http://tools.ietf.org/html/draft-ietf-httpbis-http2-04#section-3.3
[3]: http://www.mail-archive.com/openssl-dev@openssl.org/msg32727.html

**Comment by tbetbetbe** [comment]
FYI: ALPN support landed in the recent [1.0.2 version](https://www.openssl.org/news/openssl-1.0.2-notes.html) release of openssl.

**Comment by molnarg** [comment]
1.0.2 is stable release, so please reopen, this is an actionable bug now.

**Comment by mattva01** [comment]
Not sure @bnoordhuis is gonna see this without an actual mention. :stuck_out_tongue_winking_eye:

**Comment by bnoordhuis** [comment]
Indeed I didn't.  Reopening and cc @shigeki.

**Comment by shigeki** [comment]
I'm now working on upgrading openssl-1.0.2 at https://github.com/iojs/io.js/issues/589 . It will be finished soon and can also be applied to Node as far as I can see. Probably I think that it's not on 0.12 but the next version.

**Comment by gunta** [comment]
+1

**Comment by jarrodconnolly** [comment]
Great work on closing iojs/io.js/issues/589 @shigeki !
Looking forward to seeing openssl-1.0.2 and ALPN in node.js as well.

**Comment by misterdjules** [comment]
Adding to the 0.13.1 milestone, thank you @shigeki!

**Comment by grein46087** [comment]
Great to see there is some traction on this front - as we looking to start work building out out our platform with http2 support.  @misterdjules  to confirm this is being targeted in the 0.13.1 release of node.js? Is there a estimated release date?

**Comment by jasnell** [comment]
@shigeki @misterdjules ... what's the current status on this one? Is this something we'll see land in v0.12.x at all or should we defer to the converged repo?

**Comment by shigeki** [comment]
This cannot be landed in v0.12. This issue should be moved to iojs and  converged repo that has openssl-1.0.2. I'm going to open a new issue or PR soon and refer here.

**Comment by grein46087** [comment]
@shigeki please let us know what the new PR issue issue,  as we are also keen on the ALPN support in node.js and would like to confirm that it is still on track for 0.13.1
