### ISSUE TITLE
Unit test failure (Windows): test-regress-GH-746

### ISSUE THREAD

**Issue by sblom** [joyent/node#5948]
C++ repro of the underlying Windows behavior: https://gist.github.com/sblom/a4e0bde388a0a5ceb4cc

Turns out that Windows isn't causing a `ReadConsole` call to return when `stdin` is closed out from under it. :(

I can run the test, hit <enter> and the test completes. Without human input the test just hangs. It is not clear from the ReadConsoleA documentation what expected behavior should be here.

Thoughts on what the right fix is? Hack around the issue with another thread for ReadConsole that is killed when closing the stdin handle? Disable the unit test?

**Comment by jasnell** [comment]
@piscisaureus ... are you aware if this is still an issue?

**Comment by piscisaureus** [comment]
@jasnell The issue still exists, but node itself won't trigger it any more.
I believe that starting with windows 8.1 it's possible to use CancelSynchronousIo to cancel a line-buffered read, but it doesn't seem all that important to fix that now. Also it would be a change to libuv, not node.

**Comment by jasnell** [comment]
Ok. Given that then I'll close this here. If it's something that ends up needing to be done, we can revisit
