### ISSUE TITLE
path: Joining driver letters

### ISSUE THREAD

**Issue by Acconut** [joyent/node#5989]
On Windows we have [driver letter assignment](http://en.wikipedia.org/wiki/Drive_letter_assignment). If you want to merge two paths like following, you'll get an "incorrect" return:

```javascript
path.join("foo/bar", "C:/hello")
'foo\\bar\\C:\\hello'
```

In my opinion this should return "C:\\hello" because it's an absolute path.

On Windows you can't create a directory which contains a ":", so this would be no issue. But it seems like you're able to do on Linux.

Is this behavior wanted or should we change it?

**Comment by jasnell** [comment]
As far as I can tell, `path.join` is operating here exactly how it is intended and documented. Closing. We can separately entertain a possible feature request to change the behavior.
