### ISSUE TITLE
crypto: documentation says to use a function not in the documentation

### ISSUE THREAD

**Issue by Pomax** [joyent/node#5994]
crypto.createHmac(algorithm, key) lists this as doc:

```
Creates and returns a hmac object, a cryptographic hmac with the given
algorithm and key.

It is a stream that is both readable and writable. The written data is used
to compute the hmac. Once the writable side of the stream is ended, use
the read() method to get the computed digest. The legacy update and
digest methods are also supported.
```

nowhere in the crypto docs is read() explained, and the actual HMAC class docs only list update() and digest(), suggesting these are not legacy functions, but simply how you use this crypto class.

If read() is current, where is the explanation of it's use? If it's not, can mention of it be removed? (it's mentioned a few more times)

**Comment by jasnell** [comment]
The documentation can definitely be improved on this.

**Comment by jasnell** [comment]
On second thought, the current docs are clear that it's a stream. Closing this for now. If someone would like to pursue with a Pull Request then that works too.
