### ISSUE TITLE
child_process re-registers SIGCHLD handler, overwrites whatever was there

### ISSUE THREAD

**Issue by jaredly** [joyent/node#5995]
It seems to me that node should only register it's `SIGCHLD` handler at the very start, so that other modules (specifically [pty.js](https://github.com/niallo/pty.js)) can also register handlers. Node 0.8 did this, but in 0.10 the `SIGCHLD` handler is registered with every `spawn`.

[Here's the code from pty.js](https://github.com/niallo/pty.js/blob/master/src/unix/pty.cc#L109) for managing sigchld.

Is there a special reason that the change was made to register it on every `spawn`?

**Comment by jasnell** [comment]
@cjihrig @trevnorris ... any thoughts?

**Comment by trevnorris** [comment]
no idea why `SIGCHILD` is being used. Possibly @piscisaureus has an idea.

**Comment by piscisaureus** [comment]
As part of the [removal of libev](https://github.com/libuv/libuv/commit/75ba6819135d4bd3a7ed93ad5f625d56c65e3102), libuv started relying on `uv_signal` handles internally for getting a notification when a SIGCHLD signal is received. This is the way for libuv to know that a child process has exited. And uv_signal has no other option than to install a handler to get there.

I don't know if this is actually still an issue for pty.js. If it is, they should just use uv_signal too and everything would work fine for them.
