### ISSUE TITLE
stream/fs: support writing ArrayBuffers

### ISSUE THREAD

**Issue by trevnorris** [joyent/node#6005]
Right now not much will happen if an `ArrayBuffer` is passed to `fs.write`. Should be trivial to implement, and will make people happy.

**Comment by jasnell** [comment]
@trevnorris ... was there ever any progress on this?

**Comment by domenic** [comment]
@jasnell opened https://github.com/nodejs/io.js/issues/1826 for the more general issue

**Comment by jasnell** [comment]
Ok, given that I'll close this issue here as it's extremely unlike to land here.
