### ISSUE TITLE
Clarification: Destroying Streams

### ISSUE THREAD

**Issue by bitmage** [joyent/node#6012]
I'm wondering what the correct method for destroying streams is.  In my case I'm creating around a dozen streams (readable, transform and writable) for a given user that connects via websockets to the server.  I'd like to make sure all these resources get cleaned up when the user disconnects.  I presume all the bi-directional references set up by the pipes are going to prevent memory cleanup.

What are people doing to avoid memory leaks in a situation like this?  I see there's cleanup code in the Stream API:

https://github.com/joyent/node/blob/master/lib/stream.js#L102...L116

It would be nice to trigger cleanup code like this, but it doesn't seem that it would propagate.  E.G. if I have:

Readable -> Transform -> Transform -> Writable

I would like to be able to call end/destroy/whatever on the end Writable and have the whole chain be cleaned up.

Thanks!

**Comment by jasnell** [comment]
Does not appear to be an actionable issue.
