### ISSUE TITLE
possible race condition in UDP multicasting

### ISSUE THREAD

**Issue by AndreasMadsen** [joyent/node#6017]
By creating a socket and closing it and then again creating a socket there sends a multicast dgram to itself, a race condition where the message is not received, seems to occur in 1/5 tries.

But if the first first _bind and close_ step is skipped it receives the message every single time. (I know that UDP don't guarantee it, but in my test the message always returned).

Here is the testcase I have been using: https://gist.github.com/AndreasMadsen/6184840

and here is the output I get, the first try got the message back, the second try didn't:
```shell
$node test.js 
step 1
step 2
got message
step 3

$node test.js 
step 1
step 2
```

**Comment by jasnell** [comment]
@AndreasMadsen ... I know it's been a while, is this still an issue?

**Comment by jasnell** [comment]
Going to close due to lack of activity and inability to reproduce. Can reopen if new information is received.
