### ISSUE TITLE
setTimeout(fn, 0) running before setImmediate

### ISSUE THREAD

**Issue by kesla** [joyent/node#6034]
Running
```js

setTimeout(function() {
  console.log('setTimeout')
}, 0)

setImmediate(function() {
  console.log('setImmediate')
})

```

will result in
```
setTimeout
setImmediate
```

even though the current docs state that "To schedule the "immediate" execution of callback after I/O events callbacks and before setTimeout and setInterval." (http://nodejs.org/docs/latest/api/all.html#all_setimmediate_callback_arg)

Are the docs unclear or is this a real bug?

cc @trevnorris

**Comment by jasnell** [comment]
@trevnorris ... is this something we still need to keep open?

**Comment by trevnorris** [comment]
nope
