### ISSUE TITLE
Better error message for nonexistent "main" file

### ISSUE THREAD

**Issue by xixixao** [joyent/node#6050]
If I require a module **A** from `node_modules` which has `main` field in its package.json set wrong (pointing to a non-existent file) I get a `Cannot find module A` error, which doesn't really point to the problem.

 `Main module of A not found` would be much clearer.

**Comment by jasnell** [comment]
Appreciate the report, but this is minor and not likely to be done in either v0.10 or v0.12. If you wish to pursue, a PR is helpful.
