### ISSUE TITLE
Invalid working directory exception is not handled in node.js

### ISSUE THREAD

**Issue by bengentil** [joyent/node#6060]
If the current working directory is invalid node fail to start.

It seems that the exception is never handled when calling process.cwd, at least in resolveArgv0 and evalScript (node.js:701 & node.js:414)

see https://github.com/joyent/smartos-live/issues/244 for more details

**Comment by jasnell** [comment]
This is an edge case but testing shows that the behavior still occurs under v0.12 and io.js. Marking it as a lower priority tho.

**Comment by brendanashworth** [comment]
@jasnell are you sure you can reproduce this in io.js? I think https://github.com/nodejs/io.js/pull/1194 fixed this.

**Comment by jasnell** [comment]
Will have to check again. May have been testing a down level build.

**Comment by jasnell** [comment]
finally getting back to this, yes, this is resolved in v3.x. Can potentially backport https://github.com/nodejs/node/pull/1194 to v0.12 if necessary but given the lack of priority on this, I'm inclined to close here.
