### ISSUE TITLE
node interpreter v0.10.16 overzealous REPL keyword parsing

### ISSUE THREAD

**Issue by dbkaplun** [joyent/node#6070]
> require('underscore').chain([1, 2, 3]) \
    ... .reduce(function (memo, n) {
    Invalid REPL keyword
    undefined
    >

**Comment by jasnell** [comment]
@dbkaplun @misterdjules ... still an issue?

**Comment by dbkaplun** [comment]
Sure is, on both Node 0.10.38 and 0.12.4:
```sh
$ node
> Array().join(' ')
''
> Array() \
... .join(' ')
Invalid REPL keyword
undefined
```

**Comment by misterdjules** [comment]
I'm available to guide anyone willing to pick this issue up and submit a PR that fixes it. Ping me on GitHub by mentioning @misterdjules or find me on IRC (jgi in #libuv on Freenode).

**Comment by thefourtheye** [comment]
@misterdjules I wanted to take your help to fix this, but I wanted to try something before straight away asking for help :-) I submitted a PR with my attempt, PTAL :-)

**Comment by jasnell** [comment]
Given that these changes landed in io.js and aren't critical. Will close this issue off here. Can reopen if any feels it is necessary.
