### ISSUE TITLE
Cluster/Worker 'listening' event is only available when using a native net.Server.

### ISSUE THREAD

**Issue by EdJ** [joyent/node#6092]
When implementing a node application that uses a PULL-based server (in this case, a RabbitMQ listener) as opposed to a net.Server, then clustering using the native cluster module, there is no way to emit the 'listening' event that a worker emits when a net.Server is started.

This event is emitted in the Master of the cluster, as opposed to the Worker, as the net.Server is started in the Master (and therefore emits all events on Master) and shared between the workers, whereas in the PULL-based solution each Worker has its own "server" which receives PUSH messages from the queue.

This causes an issue with hot-patching new workers into the cluster when using either Domains or zero-downtime deployments. A good approach to ZDDs is shown in the PM2 patch sound at https://github.com/truongsinh/pm2/commit/4f60ce4511b943f8489950a439ffc88266b81e4c. This basically uses the 'listening' event to wait for a new Worker to start, then emits the disconnect() event on the previous worker, ensuring the new Worker is available before the old one stops listening for new connections.

I strongly believe that the cluster functionality should be server-agnostic, as it is common in an SOA or CQRS architecture to have servers that do not simply listen on a port for incoming requests but that still need to be clustered and resilient. I would suggest that a method to manually raise the 'listening' event needs to be provided, whether that is to provide an actual Worker.emit('listening') event, or to provide a non-TCP base class that is equivalent to Server that can be implemented by non-receive servers and consumed by the cluster in the same manner.

Implementing this fix will unify the cluster handling for non-TCP endpoints with standard TCP servers, allowing for write-once-use-anywhere multi-process handling. Clearly node is used for things other than raw webservers, and it would seem to be sensible to apply the modular approach evangelised by npm within the node core.

**Comment by jasnell** [comment]
@EdJ @sam-github ... any reason to keep this open?

**Comment by sam-github** [comment]
no
