### ISSUE TITLE
vcbuild.bat failure in windows : node_js2c.vcxproj error in building

### ISSUE THREAD

**Issue by ashishnegi** [joyent/node#6154]
Error on building node.sln is
2>CustomBuild:
2>  node_js2c
2>  'C:\Program' is not recognized as an internal or external command,
2>  operable program or batch file.
2>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.CppCommon.targets(172,5): error MSB6006: "cmd.exe" exited with code 1.
2>
2>Build FAILED.

This comes from line in node_js2c.vcxproj:
<Command>call call C:\Program Files (x86)\Python27\python.exe \&quot;tools\js2c.py\&quot; &quot;$(OutDir)

The python path after "call" should be in quotes.

**Comment by jasnell** [comment]
Appears to have been resolved.
