### ISSUE TITLE
process.stdin evaluation results in non-blocking stdout reads

### ISSUE THREAD

**Issue by inolen** [joyent/node#6175]
I was tracking down a peculiar issue this morning where the evaluation of process.stdin was causing a Python test script that was redirecting the stdout of the node process to a pipe to receive -1 (EAGAIN) while reading.

The Python script:

	import os
	from subprocess import Popen, PIPE

	process = Popen(['node', 'stdin.js'], stdin=None, stdout=PIPE, stderr=PIPE)
	(stdout, stderr) = process.communicate()

	print stdout

The node script:

	process.stdin;

	for (var i = 50000; i >= 0; i--) {
		process.stdout.write('in ' + i + '...\n');
	}

	process.stdout.write('success!\n');

Commenting out the process.stdin evaluation makes this work seemingly properly.

I'm a bit fuzzy with regards to piping and I didn't investigate this much beyond writing the test case, but this seems to be an error due to the action inside of process.stdin's lazy evaluation.

**Comment by dazld** [comment]
Looks like scripts as written above are working 0.11.15

**Comment by jasnell** [comment]
@inolen ... is this still an issue for you?

**Comment by inolen** [comment]
@jasnell I'm way out of the loop. Feel free to close if it seems well to you.

**Comment by jasnell** [comment]
Ok, closing. Can reopen if new information is received.
