### ISSUE TITLE
process.chdir is not thread-safe

### ISSUE THREAD

**Issue by piscisaureus** [joyent/node#618]
Calling process.chdir() while libeio is processing fs operations that require resolving a relative pathname to an absolute one could be dangerous because chdir() may not be thread-safe, so a new CWD could be partially applied when a relative path is resolved in a thread.

Apart from that, it yields unpredictable result, because you can never know which cwd is used in a fs operation that is pending while chdir is called.

Consensus solution is to absolute-ize paths before they hit the thread pool. It could be done by calling path.resolve() in fs.js before invoking the binding.

Known affected: open, symlink, mkdir, maybe more

A test is here: https://gist.github.com/805263#file_test.js

This is assigned to piscisaureus. Remind him if he forgets.

**Comment by jasnell** [comment]
Going to assume that since the test is passing this isn't an issue any longer. Closing.
