### ISSUE TITLE
[process.argv] node debug script VERSUS node script

### ISSUE THREAD

**Issue by gagle** [joyent/node#6216]
0.10.18

The path of the script in debug mode is the file name, whilst the path in NO debug mode is the absolute path. Is this correct or both should be absolute?

```
$ node debug script.js
process.argv
["node", "debug", "script.js"]
```

```
$ node script.js
process.argv
["node", "/absolute/path/to/script.js"]
```

**Comment by jasnell** [comment]
There is still some inconsistency between the outputs, but the filename appears to be consistent between the two.

```
bash-3.2$ node test.js
[ 'node', '/Users/james/tmp/test.js' ]
bash-3.2$ node debug test.js
< Debugger listening on port 5858
connecting to port 5858... ok
break in test.js:1
> 1 console.log(process.argv)
  2 
  3 });
debug> cont
< [ '/usr/local/bin/node', '/Users/james/tmp/test.js' ]
debug> 
(^C again to quit)
debug> 
bash-3.2$ 
```

@gagle ... you still having issues with this?

**Comment by gagle** [comment]
I didn't remember this. I guess it can be closed after 2 years without a response...
