### ISSUE TITLE
server threads die with assertion error

### ISSUE THREAD

**Issue by mxk1235** [joyent/node#6222]
using node 0.10.18 on Ubuntu 12.04 LTS.

../deps/uv/src/unix/stream.c:494: uv__server_io: Assertion `events == 1' failed

happens several times a second, effectively killing the threads.  I found an old thread that is closed now because of no repro.  

thanks in advance.

**Comment by ljwagerfield** [comment]
I also receive the following error when running `grunt connect` on Ubuntu 14.04 (x64) with node `v0.10.25`, but only when running from `crontab`. The same user is invoking the process in both `crontab` (which fails) and the manual execution (which succeeds).

`grunt: ../deps/uv/src/unix/stream.c:494: uv__server_io: Assertion `events == 1' failed.`

**Comment by chicagobuss** [comment]
For people having problems with running these commands from jenkins or cron, try adding the --norc flag to your bash script - it worked for us and we were seeing the exact same behavior (worked when running manually, failing on cron and jenkins).

**Comment by jasnell** [comment]
@indutny ... was there a resolution on this one?

**Comment by indutny** [comment]
I suppose it is resolved now, didn't see any report except this.

**Comment by indutny** [comment]
But no formal resolution either.

**Comment by jasnell** [comment]
Ok, closing then. Can reopen if new information is received.

**Comment by bostrom** [comment]
Any news on this one? 

I'm getting this error when jenkins executes `grunt karma` on a Ubuntu slave. Adding `#!/bin/bash --norc` or just `bash --norc` to the beginning of my "Execute shell" build step doesn't work. 

I've tried searching the net for answers, but I got nothing.

Slave:

```
uname -a
Linux jenkins-slave 3.16.0-38-generic #52~14.04.1-Ubuntu SMP Fri May 8 09:43:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

node --version
v0.10.25

npm --version
1.3.10
```

**Comment by tsukasagenesis** [comment]
just never use FD directly, it's not correctly supported and if you close one he can still try to use it and crash. that all for me.
