### ISSUE TITLE
Http agent doesn't close sockets if stream is piped and destination is closed before end is reached (causes maxSockets to be reached)

### ISSUE THREAD

**Issue by sgerace** [joyent/node#6227]
If I create a simple REST API (using express, for simplicity) which streams an http response to the express response, the http agent doesn't close sockets if the requesting client is closed before the response is complete. For example, this is my express route:

```javascript
var express = require('express');
var http = require('http');
var server = express();
server.get('/goog', function (req, res, next) {

    http.get("http://www.google.com/", function (stream) {
        stream.pipe(res);
    }).on('error', function (e) {
        console.log("Got error: " + e.message);
    });

    console.log(http.globalAgent);
});

server.listen(3000, function () {
    console.log('Listening on port 3000');
});
```

Now, if you fire up this server and make a request via curl, it works fine:

    curl -O http://localhost:3000/goog

However, (and this is the reason for the `console.log(http.globalAgent)`), if you execute curl and **very** quickly hit `Ctrl-C` to cancel the request, the socket is never closed by the http agent. If you do this several times in a row, you'll see that the `sockets` property of the `http.globalAgent` will continue to add items (despite all of these old connections being closed). Once you hit the value of `http.globalAgent.maxSockets` (default of 5), the server will stop responding to the http requests because the connection pool is waiting for an available socket, but the maximum number has been reached.

Obviously increasing the value of `maxSockets` can help alleviate the symptoms, but it doesn't fix the root cause in that whenever any client of the REST API closes the request before the response is received (i.e., network disconnected, vpn failure, etc.) there will be a "leak" of an available socket...until **eventually** the `maxSockets` is reached and the http agent will no longer provide a new socket connection.

**Comment by FelikZ** [comment]
Experienced probably the same behavior but without pipes - node get a lot of established connections during some period of time that causes server to drop new connections.

Should I use @TooTallNate 's suggestion in order to handle this situation?

**Comment by jasnell** [comment]
Does not appear to be an actual bug here. Can reopen if new information is received.
