### ISSUE TITLE
My v0.13 performance enhancements list

### ISSUE THREAD

**Issue by trevnorris** [joyent/node#6252]
**Things for v0.13**

(note: not sure how much of this is already in place)

Brain spew of crazy things I think will be beneficial to Node.js.

**Thing 1:**

On the JS side, each `*Wrap` that exposes functionality directly to JS
will have it's own very thin `require('*-wrap');` module (right now not
meant to be officially used outside of core). These would offer the most
basic amount of functionality necessary for the module to run, with a
slightly nicer API than just setting a .on* callback on the object.

A very simplified event system that integrates with the C++ module side.
This will involve several things:

- Each class will contain a `Persistent<Function>` field for the associated
  callback that is called directly from `MakeCallback`.

- Callbacks can accept a maximum of 3 arguments.

- A default callback can be assigned that all newly initialized classes
  will automatically receive:

```javascript
var TCPWrap = require('tcp-wrap');
TCPWrap.onconnection(function(c) { });
```

- A callback is passed to each instance that can overwrite the default:

```javascript
var TCPWrap = require('tcp-wrap');
var server = new TCPWrap();
server.onconnection(function(c) { });
```

- If proves to be necessary at this level, instead of an upper level of
  abstraction, a second boolean argument can be passed telling the event
  system that callback should be removed from either the individual
  instance or the default class callback. Though this implementation would
  bring a tremendous amount of complexity, so would be avoided at all
  costs.

- An extremely simplified event system will exist in the case multiple
  callbacks are assigned to the class. The main reason for this is
  backwards compatibility with the current EventEmitter. Basics operations
  are as follows:

  - If no callback has been assigned then the passed function will be
    assigned to the `Persistent<Function>` spot on the class.

  - If multiple callbacks are detected then the `Persistent<Function>` is
    replaced with a super slim event callback that'll be called directly
    from `MakeCallback()`. This will loop through the array of passed
    callbacks, calling each in turn.

  - If benchmarks show that passing empty arguments is a performance hit,
    then the `MakeCallback` will always pass back 3 arguments and just set
    the remaining to `Undefined()`.

- The class that needs to set the `Persistent<Function>` will have a single
  function assigned to do so (was thinking possibly create an EventWrap
  class to reduce code). The flag of which to be set won't be passed as an
  argument but set on external memory using the state sharing technique.
  Since these operations are synchronous, it should be possible to share
  a single location for state that all inheriting classes read from.

**Thing 2:**

Share state with the inheriting class instance and `StreamWrapCallbacks`.
The point being a flag can be set by `setEncoding()` on the class of how
to parse the data once it's come in. This will bypass the need to create a
buffer, then convert it to a string.

**Thing 3:**

Create `HTTPWrap` that will probably inherit from `TCPWrap` and overwrite
`StreamWrapCallbacks::DoRead()` so incoming data can be internally
buffered and then directly passed to the `node_http_parser`.

**Thing 4:**

Have `node_http_parser` call a JS function to create and return all the
object properties that will be returned to the user.

**Thing 5:**

Share state with `StreamWrap::UpdateWriteQueueSize()` instead of needing
to set an object property on every transaction.

**Thing 6:**

`process._immediateCallback` is static, and `_needImmediateCallback` is
simple state sharing. No reason to waste the cycles getting the same
function from the same object every time, or checking the same object
property. Instead persist the function to `env.h` and pass directly to
`MakeCallback`, and use memory state sharing to inform C++ that the
function needs to be run.

**Comment by jasnell** [comment]
@trevnorris ... any action on this?

**Comment by trevnorris** [comment]
have done some of this, and will continue to work on what I can. but can close this. the list is out of date.
