### ISSUE TITLE
nextTick — specifc context

### ISSUE THREAD

**Issue by KenanSulayman** [joyent/node#6290]
I propose adding a second parameter to nextTick analogous to Array.prototype.map et al. which forwards a context (`this`) to the deferred function.

	var x = function () {
		var self = this;

		nextTick(function () {
			// self === this
		}, this);
	}

In this context, we could quote David Herman's snippet from his book (68 Specific Ways to Harness the Power of Javascript):

	function CSVReader(separators) {
	    this.separators = separators || [","];
	    this.regexp =
	        new RegExp(this.separators.map(function(sep) {
	            return "\\" + sep[0];
	        }).join("|"));
	}

	// wrong way

	CSVReader.prototype.read = function(str) {
	    var lines = str.trim().split(/\n/);
	    return lines.map(function(line) {
	        return line.split(this.regexp); // wrong this!
	    });
	};

	// ECMAScript way

	CSVReader.prototype.read = function(str) {
	    var lines = str.trim().split(/\n/);
	    return lines.map(function(line) {
	        return line.split(this.regexp);
	    }, this); // forward outer this-binding to callback
	};

Of course we could scope an instance of this (var self = this) and use it; however I'd love to see ECMA conformance here. Any objections?

**Comment by jasnell** [comment]
@trevnorris ... any reason to keep this one open?

**Comment by trevnorris** [comment]
nope
