### ISSUE TITLE
0.11.3 and up break connect.compress middleware

### ISSUE THREAD

**Issue by mrlucmorin** [joyent/node#6295]
Playing around with 0.11.6 I noticed that the connect.compress middleware was serving garbage to the browser.

Problem started with 0.11.3 as 0.11.2 works fine. 0.10.x branch also works fine.

#### Steps to reproduce: 

simply generate an "out of the box" Express application using the express utility with default options, then add the following line before the *app.use(express.favicon());* line:

app.use(express.compress());

#### expected result:

the default app's css file should be properly zipped and served

#### observed result:

the css file is received garbled up on the browser

**Comment by jasnell** [comment]
Closing due to lack of any activity or determination if it's still relevant. Can reopen if necessary.
