### ISSUE TITLE
assert: doesNotThrow doesn't show message

### ISSUE THREAD

**Issue by pkorzeniewski** [joyent/node#6400]
In the documentation, `assert.doesNotThrow` takes two arguments: `(block, [message])`, but calling

```javascript
assert.doesNotThrow(function() {
    // some code throwing an error
}, "Error occured");
```

won't display the "Error occured" message, but the thrown error instead. I've inspected the `assert.js` file, and the problem is probably caused by line 304:

```javascript
if (!shouldThrow && expectedException(actual, expected)) {
```

`expectedException` will always return `false`, because `expected` is always set to `null`

```javascript
 if (util.isString(expected)) {
    message = expected;
    expected = null;
  }
```

**Comment by jasnell** [comment]
There is a new PR opened in nodejs/node tracking this issue. Closing here.
