### ISSUE TITLE
path.relative() not working with network shares

### ISSUE THREAD

**Issue by cepharum** [joyent/node#6401]
Method relative() of core module path fail to properly support network shares as used in Windows OS. As it's possible to read a file's content from a network share using a pathname like

    \\\\server\\folder\\sub\\subsub\\target

this limited support in module path might be considered limiting cross-platform support of nodejs. Tested the following code blocks with node.exe 0.10.20 downloaded from nodejs.org.

### Test 1

```javascript
var a = "\\\\server";
var b = "\\\\server\\folder\\sub";
require("path").relative(a, b);
```

#### Actual Output

```
\\\\server\\folder\\sub
```

#### Expected Output

```
folder\\sub
```

### Test 2

```javascript
var a = "\\\\server";
var b = "\\\\server\\folder\\sub";
require("path").relative(b, a);
```

#### Actual Output

```
'C:\\server'
```

#### Expected Output

```
'..\\..'
```

### Test 3

```javascript
var a = "\\\\server\\folder\\sub";
var b = "\\\\server\\folder\\sub\\subsub\\target";
require("path").relative(a, b);
```

#### Actual Output

```
'folder\\sub'
```

#### Expected Output

```
'subsub\\target'
```

**Comment by jasnell** [comment]
This particular issue appears to have been resolved.
