### ISSUE TITLE
vm: OOM error when creating many contexts

### ISSUE THREAD

**Issue by bnoordhuis** [joyent/node#6408]
```
$ cat t.js
var vm = require('vm');
function f() {
  for (var a = [], i = 0; i < 1e4; ++i) a.push(vm.createContext({}));
}
f();

$ /usr/bin/time v0.10/out/Release/node t.js
        4.28 real         3.78 user         0.48 sys

$ /usr/bin/time master/out/Release/node t.js
FATAL ERROR: Heap::ReserveSpace Allocation failed - process out of memory
       57.36 real        57.00 user         1.03 sys
```

Tested with today's master, commit 0079e57.

**Comment by jasnell** [comment]
@indutny ... how did this land?

**Comment by indutny** [comment]
@jasnell what?

**Comment by jasnell** [comment]
lol.. sorry, wondering if happened to know the status on this.

**Comment by indutny** [comment]
hm... I don't know it, sorry...

**Comment by jasnell** [comment]
@bnoordhuis ... any further thoughts on this?

**Comment by bnoordhuis** [comment]
It's still an issue but I'm not sure if it's really fixable at this point and I've made peace with that.  I'm fine with closing it.

**Comment by jasnell** [comment]
Hmm.. ok. I'm going to at least mark it defer. Maybe someone will eventually be able to get around to it. Closing!
