### ISSUE TITLE
Compilation of v0.11.8 fails on Solaris 10 and some Illumos distros due to missing libproc.h

### ISSUE THREAD

**Issue by ptribble** [joyent/node#6439]
Building recent v0.11.X source on Solaris 10 fails with:

../deps/mdb_v8/mdb_v8.c:53:21: fatal error: libproc.h: No such file or directory
compilation terminated.

That's expected. The interfaces in libproc.h are private and the header file is explicitly excluded from packaging, so this will be true of Solaris and most Illumos-based distros. (I suspect you don't realize this for SmartOS, because it ends up in the proto area.)

I can work around this by explicitly turning off node_use_mdb in the configure script, but this ought to be handled properly.

**Comment by jasnell** [comment]
@ptribble @davepacheco ... any updates on this one?

**Comment by ptribble** [comment]
I'm manually patching configure to disable mdb on Solaris 10, which seems to work.

On other illumos variants I'm temporarily dropping in a copy of libproc.h (and currently adding an unversioned symlink for libavl.so.1, although that should shortly be unnecessary). Ideally the fix would be on the illumos side, to make libproc a public and committed interface.

**Comment by rmustacc** [comment]
Which is something I'm slowly working on from the illumos side.

**Comment by dago** [comment]
Would it be possible to merge the above commits to a release version?

**Comment by jasnell** [comment]
@joyent/node-tsc @orangemocha @misterdjules ... any thoughts? should we land this here or defer to the converged repo?

**Comment by cgalibern** [comment]
I have proposed this pull request #9349 , it allow configure --without-mdb.
Is it possible to merge it ?
thanks

**Comment by jasnell** [comment]
@misterdjules @orangemocha ... what do you think?

**Comment by misterdjules** [comment]
@jasnell #9349 seems like it would be useful.

**Comment by orangemocha** [comment]
I am really out of my depth here, but would it make sense to set node_use_mdb to false by default for Solaris? It's the only platform for which it's set to true.

The original change is here: https://github.com/joyent/node/commit/e851fef60f5368927ea0a6b7bfc984ef18e93d6f

Also, https://github.com/joyent/node/pull/9349 is against master. It should probably be rebased against v0.12.

**Comment by misterdjules** [comment]
@orangemocha Let's continue the discussion in #9349.

**Comment by misterdjules** [comment]
Added the P-1 label because it prevents Solaris and derivatives' users from building Node.js on their platform.

**Comment by ip1981** [comment]
libproc is used to be a private interface.

**Comment by misterdjules** [comment]
Fixed with 8b81f98c41158856c09b57afc4cf879e9b65efe9, thank you @cgalibern :+1:
