### ISSUE TITLE
test-debug-signal-cluster.js failing sporadically

### ISSUE THREAD

**Issue by isaacs** [joyent/node#6440]
Example: http://jenkins.nodejs.org/job/node-pullrequest/1471/DESTCPU=ia32,label=linux/tapTestReport/test.tap-104/

Running the test a bunch of times in a loop usually makes it fail within 10 or so iterations for me.

**Comment by misterdjules** [comment]
It seems that now `test-debug-signal-cluster.js` passes on all platforms, but fails all the time on SmartOS. Here's one instance of such a failure: http://jenkins.nodejs.org/job/nodejs-v0.12/DESTCPU=ia32,label=smartos/lastBuild/tapTestReport/simple.tap-126/. Adding it to the 0.11.15 milestone as it's one of the very few failing tests remaining.

**Comment by misterdjules** [comment]
Fixed by e9df9a0216550abab4923bcfc6dea4f4b32368d2 and 58fcc6598561b5b99a8c6756b3b1cca55b635b0f, thanks @tjfontaine!
