### ISSUE TITLE
Child process hanging

### ISSUE THREAD

**Issue by OrangeDog** [joyent/node#6473]
Node 0.8.26

I have a Java app that waits for stdin to close and then prints true or false to stdout and exits.
This is called from Node (see [gist](https://gist.github.com/OrangeDog/63a33a644b03a65d329f)) using `child_process.spawn()`.
Occasionally in our production system, the Java process remains open, and the `'close'` event never happens. Once this happens, all future spawned Java instances do the same thing.

Other Nodes running on the same box are not affected. Sending a TERM to one of the hung processes ends it but no trace of this is seen in the Node logs. Restarting the Node instance fixes this.

Testing with `gdb` on a stuck Java process:

- Closing fd 0
    - process exits abnormally
    - no output shown in node logs

- Redirecting fd 1 and 2 to files, and closing fd 0
    - process exits abnormally
    - stderr shows a file descriptor exception
    - no output shown in node logs

- Redirecting fd 1 and 2 to files, redirecting 0 to a named pipe and sending eof
    - process exits normally
    - false is written to stdout
    - no output shown in node logs.

- Redirecting 0 to a named pipe and sending eof
    - process exits normally
    - no output shown in node logs

This seems to suggest that a particular Node process gets into a state where it can no longer manage child processes properly. It is unknown whether input is being sent by Node, but given that the next line after this in the code is to send eof, and we know that this would terminate the process, I imagine this is not happening.

**Comment by jasnell** [comment]
@bnoordhuis @OrangeDog ... any reason to keep this open?

**Comment by bnoordhuis** [comment]
I think you can close this.  v0.8 is even deader now.
