### ISSUE TITLE
dns.reverse() throws on error

### ISSUE THREAD

**Issue by skenqbx** [joyent/node#6505]
```js
var dns = require('dns');
try {
  dns.reverse('not_an_ip_address', function(err, result) {
    console.log(err, result);
  });
} catch (err) {
  console.log(err);
}
```

I get an error 'EINVAL' in the catch block, but in my understanding it should be passed to the callback.

Similar Issues: #2900 #2901
This affects node v0.10.x & v0.11.x

**Comment by hannesmuehleisen** [comment]
+1

**Comment by jasnell** [comment]
@trevnorris @indutny ... any further thoughts on this? I know this is an old debate but at this point I doubt the current behavior is going to change without a tsc decision to alter the throw model here. Recommend closing this particular issue.

**Comment by trevnorris** [comment]
ditto on closing the issue.

**Comment by jasnell** [comment]
Closing. Can reopen if folks feel it's worthwhile continuing the discussion
