### ISSUE TITLE
Rethrowing exception prints wrong excerpt

### ISSUE THREAD

**Issue by joliss** [joyent/node#6512]
V8 now correctly preserves stack traces for rethrown errors (see Chromium bug [60240](https://code.google.com/p/chromium/issues/detail?id=60240)). However, Node v0.10.22 still prints the wrong code excerpt above the stack trace. Using the following slightly-modified snippet from bug 60240:

```
function g() { error; }
function f() { g(); }
function rethrow(e) { throw e; }
function test() {
  try {
    f();
  } catch (e) {
    rethrow(e);
  }
}
// try { test() } catch (e) { console.log(e.stack) }
test()
```

Node prints:

```
/home/.../test.js:3               <----- not correct, should be test.js:1
function rethrow(e) { throw e; }  <----- not correct, should be function g() { error; }
                            ^
ReferenceError: error is not defined
    at g (.../test.js:1:78)       <----- correct (though weird column), thanks to 60240
    at f (.../test.js:2:16)
    at test (.../test.js:6:5)
    at Object.<anonymous> (.../test.js:12:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

This may be a V8 issue, but I haven't looked into Node's error-reporting code enough to produce a useful bug report for V8.

**Comment by jasnell** [comment]
@trevnorris ... is this still relevant?

**Comment by trevnorris** [comment]
don't think so.

**Comment by joliss** [comment]
@trevnorris It's still an issue on Node, but it looks like it should really be reported on the Chromium bugtracker. Can you try to reproduce this with up-to-date V8 and let me know what it prints? (I'm having trouble compiling V8.)

**Comment by trevnorris** [comment]
@joliss Sorry. Reason I said this isn't relevant is because it isn't something we can deal with. Throwing from a different location doesn't allow us to back track to the original throwing location.
