### ISSUE TITLE
(libuv) Failed to create kqueue (24)

### ISSUE THREAD

**Issue by michaelswe** [joyent/node#6535]
OSx Maverics: Node v0.10.21
Win 8.1: Node 0.8.22

I found another issue for this, but it is closed:
https://github.com/joyent/node/issues/5658

This might be as it should be, but it would be great with better error messages and more consistent behaviour. It behaves different on Win/OSx and writeFile behaves different vs writeFileSync.

On OSx I get the error (Failed to create kqueue..)
On Windows I end up with files of zero bytes instead of an error.
writeFileSync solves all problems on booth OSx and Windows.

Increasing ulimit -n solves the issue in OSx. I suppose that the async version ends up with open file descriptors for the whole queue. Is there any node:ish way to throttle this? For now my solution is to use writeFileSync.

Code to reproduce (set writeBurst to higher number that your "ulimit -n"):

var fileCount = 0;
var writeBurst = 1000;

for(var i=0;i<writeBurst;i++) {
      writeFile(fileCount + '.txt');
}

function writeFile(fileName) {
      var fs = require('fs');
      fs.writeFile("./tmp/" + fileName, 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghilkjlmopqrstuvwxyz', function(err) {
          if(err) {
              console.log(err);
          } else {
              fileCount++
              console.log(fileCount);
          }
      });
}

**Comment by jasnell** [comment]
Unable to reproduce with v0.12
@michaelswe ... is this still an issue for you?

**Comment by michaelswe** [comment]
@jasnellNo. I think I reworked my code around the issue. Good that it seems to be solved in 0.12 though.
Thanks for pinging back on this.

**Comment by jasnell** [comment]
Ok, will close. Can reopen if new information is received.
