### ISSUE TITLE
http: chunked is freaky slow

### ISSUE THREAD

**Issue by trevnorris** [joyent/node#6545]
Using chunked encoding is 10-20x slower than non-chunked. Need to take a better look as to why this is happening. This is just a reminder to investigate and fix before v0.12 release.

/cc @bnoordhuis @isaacs

**Comment by jasnell** [comment]
@trevnorris ... were you ever able to get back around to this?

**Comment by trevnorris** [comment]
Still happens to me in node.js and io.js. IIRC found out it's actually an issue in wrk itself. not node. Using chunked with `ab` doesn't exhibit the same behavior.

**Comment by jasnell** [comment]
Yeah, I spent some time over the weekend looking at this one and wasn't able to recreate the issue without wrk. I'm leaning towards closing unless it can be demonstrated to be an actual issue with node.

**Comment by jasnell** [comment]
Closing for now. Can reopen if it does turn out to be a problem in node as opposed to wrk
