### ISSUE TITLE
util.format doesn't use util.inspect as the docs claim

### ISSUE THREAD

**Issue by sam-github** [joyent/node#6551]
Described:
```
If there are more arguments than placeholders, the extra arguments are converted to strings with
util.inspect() and these strings are concatenated, delimited by a space.
...
If the first argument is not a format string then util.format() returns a string that is the concatenation
of all its arguments separated by spaces. Each argument is converted to a string with util.inspect().
```
- http://nodejs.org/api/util.html#util_util_format_format

Actual:

```
> util.format(1,f)
'1 [Function: f]'
> util.format("r",f)
'r function f(){return "something"}'
```

I ran into this while trying to figure out why console.log() sometimes printed function code, and sometimes not, and cargo-cultishly adding strings to the front of my debug msgs was feeling wrong.

Underlying cause is [this](https://github.com/joyent/node/blob/master/lib/util.js#L52).

I assume its intended, but I'm puzzled as to why. I can PR the docs if someone confirms the docs are wrong, and not the code.

**Comment by jasnell** [comment]
@sam-github ... I note this never landed here or in io.js. Interested in updating the PR?

**Comment by sam-github** [comment]
I will do that

**Comment by sam-github** [comment]
@TooTallNate it sounds like you like the old behaviour, please weigh in on https://github.com/nodejs/io.js/pull/1878

I now remember how it works, so maybe its best to leave it like it is... but I think the existing behaviour is a bit weird.

I use a `%j` to get strings inspected, fwiw, though the leading 0 trick is interesting, though a bit obscure.

**Comment by jasnell** [comment]
I'm going to close this issue in favor of continuing the conversation in https://github.com/nodejs/io.js/pull/1878. If that lands, we'll pick up the changes in the converged repo.
