### ISSUE TITLE
Add .stop() to _stream_readable

### ISSUE THREAD

**Issue by rschooley** [joyent/node#6588]
I would like the feature to stop reading a stream midway through to be added to _stream_readble.

I see by the comment on https://github.com/joyent/node/blob/master/lib/_stream_readable.js#L884 the stream is meant to read the entire content of the source.  Is this something we are open to changing?  

Use case:
I drop a ```fs.readStream``` onto a 500MB file containing 2 million lines of data.  After the first 10 I have what I want from that file, a preview of data.  At that point there is no reason to continue reading the remainder of the file, it can just stop.

As a quick parity check, both Java and C# support the notion of closing streams prior to completion.

**Comment by jasnell** [comment]
No longer relevant?
