### ISSUE TITLE
HTTPParser becoming increasingly opaque

### ISSUE THREAD

**Issue by jcoglan** [joyent/node#6621]
As of (I tihnk) v0.11.6, the API of `process.binding('http_parser').HTTPParser` has started using magic numbers instead of names for things.

One such change is replacing `parser.onMessageComplete` and friends with `parser[3]`, although thankfully those magic numbers can be replaced with `parser[HTTPParser.kOnMessageComplete]`.

The HTTP method yielded by these callbacks have also been replaced with numbers. I use this parser in websocket-driver and have had to include my own number->name map in my class that wraps `HTTPParser`  in a stable API.

https://github.com/faye/websocket-driver-node/commit/2dff35d3e4f6bace42ae0f4eb7f1620e64c76e89

I don't know if this is intended to be a public API, but if so could it be kept more expressive and informative, and if not can you let me know what I should use instead.

**Comment by jasnell** [comment]
Going to close this. There is work underway to reimpl http parser in javascript in io.js.
