### ISSUE TITLE
stream.read(0) should not trigger the `end` event if there is no underlying data

### ISSUE THREAD

**Issue by jonathanong** [joyent/node#6634]
unless you want to undocument it, `.read(0)` for me is "start getting data from the underlying source but don't consume this stream yet". thus, it shouldn't emit `end` until `.read(n)` is called with anything but `n === 0`. 

test case:

```js
var stream = new (require('stream')).Readable
stream.on('end', function () { console.log('end')})
stream._read = function(){}
stream.push(null)
stream.read(0)
// `end` is emitted but should not
stream.read()
// now `end` should be emitted
```

**Comment by jasnell** [comment]
@chrisdickinson ... does this need to stay open?

**Comment by jasnell** [comment]
Closing due to lack of further activity. Can reopen if necessary.
