### ISSUE TITLE
http: if chunked-encoding then writev on nextTick

### ISSUE THREAD

**Issue by trevnorris** [joyent/node#6654]
There's a bug that http will writev for every write on chunked encoding. Instead the stream should be `cork()`'d on the first write, then `uncork()`'d on `process.nextTick()`.

Just a reminder for myself.

**Comment by jasnell** [comment]
@trevnorris ... what's the status on this one?

**Comment by trevnorris** [comment]
Believe it was fixed by the referenced PR.
