### ISSUE TITLE
Document path.isAbsolute

### ISSUE THREAD

**Issue by domenic** [joyent/node#6705]
I noticed it in the source but not the docs and now I'm scared to use it.

**Comment by jaridmargolin** [comment]
safe to use?

**Comment by domenic** [comment]
Unclear, it's undocumented and therefore in theory could be removed at any time!

**Comment by jaridmargolin** [comment]
found here: https://github.com/joyent/node/blob/master/doc/api/path.markdown#pathisabsolutepath
not here: http://nodejs.org/api/path.html

**Comment by domenic** [comment]
Ah cool, looks like someone documented it then in 90266750617adb1ce1ca4ce43fe48f9b0fa11343.
