### ISSUE TITLE
test: test-child-process-fork-getconnections.js fails on OSX 10.9

### ISSUE THREAD

**Issue by fardjad** [joyent/node#6711]
$ sw_vers

    ProductName:	Mac OS X
    ProductVersion:	10.9
    BuildVersion:	13A603

    $ git --no-pager log -n1

    commit 8803aa3af7031e4844eb6eeb6d6e53919808ea3d
    Author: Fedor Indutny <fedor.indutny@gmail.com>
    Date:   Sat Dec 14 03:16:52 2013 +0400

        deps: update v8 to 3.22.24.9
    
    $ git status

    # On branch master
    nothing to commit, working directory clean

    $ make test-simple

    ln -fs out/Release/node node
    /usr/bin/python tools/test.py simple
    === release test-child-process-fork-getconnections ===
    Path: simple/test-child-process-fork-getconnections
    /Volumes/node/test/simple/test-child-process-fork-getconnections.js:39
              throw new Error('[c] closing by accident!');
                    ^
    Error: [c] closing by accident!
        at Socket.<anonymous> (/Volumes/node/test/simple/test-child-process-fork-getconnections.js:39:17)
        at Socket.EventEmitter.emit (events.js:120:20)
        at _stream_readable.js:896:16
        at process._tickCallback (node.js:599:11)

    /Volumes/node/test/simple/test-child-process-fork-getconnections.js:57
          throw new Error('child died unexpectedly!');
                ^
    Error: child died unexpectedly!
        at ChildProcess.<anonymous> (/Volumes/node/test/simple/test-child-process-fork-getconnections.js:57:13)
        at ChildProcess.EventEmitter.emit (events.js:101:17)
        at Process.ChildProcess._handle.onexit (child_process.js:862:12)
    Command: out/Release/node /Volumes/node/test/simple/test-child-process-fork-getconnections.js
    
Actually I tried to debug the test but I think I need some help with that

    $ ./node debug test/simple/test-child-process-fork-getconnections.js
    
    < Debugger listening on port 5858
    connecting to port 5858... ok
    break in test/simple/test-child-process-fork-getconnections.js:22
     20 // USE OR OTHER DEALINGS IN THE SOFTWARE.
     21
    >22 var assert = require('assert');
     23 var common = require('../common');
     24 var fork = require('child_process').fork;
    
    debug> cont
    
and nothing happens.

I also put some breakpoints around [here](https://github.com/joyent/node/blob/master/test/simple/test-child-process-fork-getconnections.js?source=cc#L39) but they don't get hit.

**Comment by jasnell** [comment]
@misterdjules @tjfontaine .... was this ever investigated further? fwiw, the test appears to be passing consistently on v0.10 and v0.12 on osx 10.10.3

**Comment by jasnell** [comment]
Closing. Can open if necessary.
