### ISSUE TITLE
faster url parser

### ISSUE THREAD

**Issue by jonathanong** [joyent/node#6788]
https://github.com/petkaantonov/urlparser

@petkaantonov said you guys won't merge this in core, but i don't see a reason _not_ to, especially when you guys are/will be focusing on performance improvements, there are no regressions, there are _more_ tests, and the code is easier to read. 

last thing i want are PRs for faster node modules (and the consequential maintenance burden) in every repo when node should be improving performance themselves.

related: https://github.com/senchalabs/connect/issues/986

**Comment by jasnell** [comment]
Given the excellent work that @petkaantonov has been doing on the io.js side, significant performance improvements will be landing in the converged stream. We can decide whether or not we want to backport those here once that work is complete.
