### ISSUE TITLE
build from source has v8_use_snapshot:true, breaks heap profiler

### ISSUE THREAD

**Issue by metamatt** [joyent/node#6799]
Apologies in advance if this is the wrong way to ask -- what I have here is something between a bug report, a question, or maybe a documentation issue.

I've been trying to use [node-webkit-agent](https://github.com/c4milo/node-webkit-agent) for heap profiling a NodeJS app.

Using Node 0.10.x (as built by [chris lea's ppa](https://launchpad.net/~chris-lea/+archive/node.js/)), I'm able to `npm install webkit-devtools-agent`, and use the heap profiler just fine.

I check out the Node 0.10.24 branch and build from source with `./configure; make`, and the resulting `node` binary works just fine for my app, passes all tests, etc, but if I then try to use the heap profiler, `node` dies with SIGSEGV. I tried using `node-gyp rebuild` to regenerate the `profiler.node` native code extension against the source tree I built from, and that doesn't help.

By comparing the *.gypi files in ~/.node-gyp/0.10.24 and the source tree where I built node, I noticed a possibly important difference regarding the v8_use_snapshot flag. Running `strings` on the binaries, the `node` binary I'd gotten from the PPA has `v8_use_snapshot: false`, and the one that I'd built myself has `v8_use_snapshot: true`.

I verified that if I change v8_use_snapshot to false (by invoking `./configure --without-snapshot`) and rebuilding, I can use the heap profiler with my private build.

My questions, then:
* is it expected and proper that that heap profiler causes Node to SEGV if it was built with v8_use_snapshot: true?
* is it known best practice to build Node without v8_use_snapshot (that is, to invoke configure with `--without-snapshot`)? (Apparently Chris Lea / upstream Ubuntu or Debian packaging people know this and I didn't?)
* should --without-snapshot be the default in the source tree, if you just check out and build, since that's how Node is being run in the real world (or at least the Debian-influenced part of the real world, or am I way off base here?)
* my impression is the v8 snapshot stuff is for quicker process startup, and in Node on my servers, I don't notice a huge difference. Is it a bad idea to turn this off? (Maybe this is the same question as before, which is why does Ubuntu/Debian turn this off, but I don't know whether that is true for all Debian packages, all Ubuntu packages, or just Chris Lea's PPA packages...)
* if leaving the v8 snapshot enabled is the right thing for performance, and it's expected that this crashes the heap profiler, should this be documented somewhere...

Thanks.

**Comment by jasnell** [comment]
@indutny ... I'm going to wager a guess that this has been resolved?

**Comment by indutny** [comment]
I suspect so! There have been tons of changes to v8.

**Comment by jasnell** [comment]
Ok, closing then. Thanks!
