### ISSUE TITLE
Domain#exit() clears domains stack

### ISSUE THREAD

**Issue by rmg** [joyent/node#6819]
I was reading through the source in lib/domain.js and came across odd behaviour. I'm not sure if it is intentional, but it is surprising and undocumented..

The domain module maintains a stack of domains to allow for nesting. Calling `Domain#exit()` on a domain pops it (and any contained domains) off that stack.

If the domain that `#exit()` is called on is *not* on that stack, the entire stack is cleared in the process of looking for it. This happens if the domain has already had `#exit()` called on it or if `#enter()` has never been called on it.

According to the documentation, "Enter and exit can be called an arbitrary number of times on a single domain." but clearly this has side effects outside of the domain in question.

I'm not sure of the consequences of this, but I thought it weird enough to report just in case.

```javascript
var domain = require('domain')
  , d1 = new domain.Domain()
  , d2 = new domain.Domain()
  , d3 = new domain.Domain()
  , d4 = new domain.Domain()

console.log("Starting: ", domain._stack)
d1.enter()
console.log("Entered d1: ", domain._stack)
d2.enter()
console.log("Entered d2: ", domain._stack)
d3.enter()
console.log("Entered d3: ", domain._stack)
d2.exit()
console.log("Exitted d2: ", domain._stack)
d2.exit()
console.log("Exitted d2 again: ", domain._stack)

d1.enter()
d2.enter()
d3.enter()
console.log("Re-entered d1, d2, d3: ", domain._stack)
d4.exit()
console.log("Exitted unused d4: ", domain._stack)
```

Results in:
```
Starting:  []
Entered d1:  [ { domain: null, _events: {}, _maxListeners: 10, members: [] } ]
Entered d2:  [ { domain: null, _events: {}, _maxListeners: 10, members: [] },
  { domain: null, _events: {}, _maxListeners: 10, members: [] } ]
Entered d3:  [ { domain: null, _events: {}, _maxListeners: 10, members: [] },
  { domain: null, _events: {}, _maxListeners: 10, members: [] },
  { domain: null, _events: {}, _maxListeners: 10, members: [] } ]
Exitted d2:  [ { domain: null, _events: {}, _maxListeners: 10, members: [] } ]
Exitted d2 again:  []
Re-entered d1, d2, d3:  [ { domain: null, _events: {}, _maxListeners: 10, members: [] },
  { domain: null, _events: {}, _maxListeners: 10, members: [] },
  { domain: null, _events: {}, _maxListeners: 10, members: [] } ]
Exitted unused d4:  []
```

/cc @sam-github @piscisaureus

**Comment by jasnell** [comment]
Appears to have been fixed
