### ISSUE TITLE
doc: fs docs should mention that `mode` is ignored when file exists

### ISSUE THREAD

**Issue by bnoordhuis** [joyent/node#6847]
See subject.

On that topic, it's kind of odd that `fs.createReadStream()` accepts a mode argument.  I guess it makes sense if you allow people to pass e.g. flags='w' but otherwise it's always a no-op.

**Comment by jasnell** [comment]
Landed in https://github.com/joyent/node/commit/1b027eedb9316aa761d9dba6d94a3915875a3dfb
