### ISSUE TITLE
Module Loading: Syntax Error Printed Irrespective of Try-Catch

### ISSUE THREAD

**Issue by skeggse** [joyent/node#6873]
If I'm dynamically loading modules and need to fail gracefully, I can wrap a try-catch around the `require` call:

```js
function tryRequire(path) {
  try {
    return require(path);
  } catch (err) {
    // let's just say we indicate results by returning a value
    if (err.code === 'MODULE_NOT_FOUND') {
      return null;
    }
    return err;
  }
}
```

Unfortunately, even if the error is caught, a filename and partial line context is still printed.

```sh
/path/to/test.js:1
(function (exports, require, module, __filename, __dirname) { #hello
```

In 0.10.24 it looks like this is as a result of the `DisplayExceptionLine` hack in node_script.cc.

In 0.11.10 it looks like the `DisplayExceptionLine` function is still called, and still prints, as seen from a simplified usage of the `vm` module:

`fail.js`

```js
var runInThisContext = require('vm').runInThisContext;
var Module = require('module');

function fail(code, display) {
  var wrapper = Module.wrap(code), compiledWrapper;

  if (display) {
    compiledWrapper = runInThisContext(wrapper, {filename: __filename});
  } else {
    compiledWrapper = runInThisContext(wrapper, {filename: __filename, displayErrors: false);
  }

  return compiledWrapper;
}

try {
  fail('#hello', false);
} catch (err) {
  console.log('it did a fail!');
}

try {
  fail('#hello', true);
} catch (err) {
  console.log('and again!');
}
```

```sh
$ node fail
it did a fail!

/path/to/test.js:1
(function (exports, require, module, __filename, __dirname) { #hello
                                                              ^
and again!
```

While I can load the module by hand and run it with the `vm` module directly, it would be nice if when `require` throws an exception and it is caught, it not also print the offending line.

Is there a better solution here?

**Comment by jasnell** [comment]
Unable to reproduce the error in either v0.10 or v0.12
