### ISSUE TITLE
Broken certificate chain hangs tls.connect() when rejectUnauthorized = false

### ISSUE THREAD

**Issue by franksrevenge** [joyent/node#6875]
Premise: HTTPD serving a properly signed SSL certificate (*not* self-signed), but not the certificate chain. So:

```bash
$ openssl s_client --connect my.domain.com:443 --showcerts
CONNECTED(00000003)
depth=0 C = gb, ST = Place, L = Somewhere, OU = IT Operations, O = Company Limited, CN = *.domain.com
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 C = gb, ST = Place, L = Somewhere, OU = IT Operations, O = Company Limited, CN = *.domain.com
verify error:num=27:certificate not trusted
verify return:1
depth=0 C = gb, ST = Place, L = Somewhere, OU = IT Operations, O = Company Limited, CN = *.domain.com
verify error:num=21:unable to verify the first certificate
verify return:1
(snip)
```

```js
require( 'tls' ).connect( 443, 'my.domain.com', { rejectUnauthorized: false },
    function() {
      // never reached
} ).on( 'error',
function( err ){
        // this is reached only when (if) the connection times out
});
```

It seems that in the scenario described abvove, Node fails to igonre the broken certificate and move on the way programs like `wget` and `curl` would when told to ignore the certificate. The result is a hang, which eventually (+60s?) resolves itself with `ECONNRESET`, but I suspect that's simply because our server decides to hang up on Node at that point. 

If unable to proceed, at least the error shoud be raised as early as possible. Although, behavior in line with `curl` and `wget` might make more sense, since in this case we're actively telling `connect()` to ignore the certificate.

Extends to HTTPS, of course, and anything else that relies on the TLS module.

Tested on Node 0.10.24 Win x64

(Workaround is of course to serve the SSL certificate with the complete certificate chain)

**Comment by jasnell** [comment]
@franksrevenge ... I know it's been a while but is this still an issue for you?

**Comment by jasnell** [comment]
Closing. Can reopen with more information (such as a test case that can be used to reproduce)
