### ISSUE TITLE
Performance regression with Rework

### ISSUE THREAD

**Issue by joliss** [joyent/node#6979]
Running [rework](https://github.com/reworkcss/rework) master on a sample file with Node v0.11.10 is 36% slower than Node v0.10.24, installed via nvm on Ubuntu.

I don't have time right now to dig into it and apologize for the shoddy bug report -- feel free to close it if it's too vague -- but the performance drop seemed big enough that I thought I'd report it. Perhaps it's a V8 issue, but even then it's probably worth forwarding to V8.

```bash
#!/bin/bash

mkdir tmp.$$

for i in {0..99999}; do
  echo ".x$i{color:green;}"
done > tmp.$$/main.css

(
  set -e
  cd tmp.$$
  echo '{}' > package.json
  npm link rework > /dev/null
  time node -e "require('rework')(require('fs').readFileSync('main.css', {encoding: 'utf-8'})) + ''"
)

rm -r tmp.$$
```

Node 0.10 gives 1.77 seconds real (1.65 user + 0.12 sys).
Node 0.11 gives 2.41 seconds real (2.07 user + 0.35 sys).

Only 0.015 seconds of the difference is owing to slower startup time, and 0.01 seconds to slower `readFileSync` time.

Node master lands somewhere in the middle (2.09 seconds), but I compiled it myself, so I don't trust the timing.

/cc @visionmedia

**Comment by jasnell** [comment]
@joliss ... I know it's been a while, but is this still an issue for you?

**Comment by joliss** [comment]
No, can't reproduce it anymore. Both 0.10 and 2.1.0 are now in the 2.5 second range. Weird. Might have been a fluke.
