### ISSUE TITLE
better network error messages

### ISSUE THREAD

**Issue by tj** [joyent/node#7005]
I've brought this up before but I can't find the issue, or if/why it was denied, but anyway I think we could do a lot better with network related error reporting:

```
Error: connect ECONNREFUSED
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)
```

isn't overly informative, it would be awesome if (when available) we tack on some information, host/port etc. It's easy to argue that when you receive the error you should be printing it or doing something with it in a way that makes the message more useful, but it certainly wouldn't hurt for cases where you just use a console.error(err.stack) etc

**Comment by jasnell** [comment]
@joyent/node-coreteam ... do we want to keep this open here? error message improvements were made in io.js and will come along in the converged stream. It's possible we may want to backport many of those fixes, and it's possible that many more improvements could still be made.

**Comment by trevnorris** [comment]
I'd just wait until they're converged before backporting.

**Comment by jasnell** [comment]
Agreed. Closing. Can reopen if folks feel it's worthwhile to backport those changes.
