### ISSUE TITLE
Symmetry in the clearBreakpoint API

### ISSUE THREAD

**Issue by wavded** [joyent/node#7026]
The build in debugger has a lot to love so kudos there.  However, I think the clearBreakpoint API could be improved.  Essentially, have it behave in all the ways the setBreakpoint API does.

For example.  I would expect if I can set a breakpoint on a line with

```
debug> sb(4)
  1 var a = 0
  2
  3 function changeA () {
* 4   a = 50
  5 }
  6
```

That I should be able to clear that breakpoint with the same parameters:

```
debug> cb(4)
```

However, instead I get:

```
Script : 4 not found
```

Which doesn't make sense intuitively.  Also I can set a breakpoint on the line I'm paused at with just:

```
debug> sb()
```

However, if I try to clear the breakpoint.  I would think it would just be `cb()` (mimicking the sb API), but that gives me a similar error:

```
debug> cb()
Script : undefined not found
```

So it seems the clearBreakpoint(cb) API only works if I used the signature `cb(scriptName,lineNo)` which is one of the ways I can use sb.  Yet even this API needed to be discovered by different parameters since it isn't documented in the official docs very well:

http://nodejs.org/api/debugger.html#debugger_breakpoints

It just states the API is:

```
clearBreakpoint, cb(...) - Clear breakpoint
```

At a minimum we could update the docs to be explicit on how to clear a breakpoint but I think it would rock more if we provided a symmetric API to setBreakpoint.

Thoughts?

FYI. It it helps any, I am running Node 0.10.25 on MacOS.

**Comment by jasnell** [comment]
@joyent/node-coreteam @misterdjules @alFReD-NSH .. is this still relevant?

**Comment by jasnell** [comment]
Closing this here. If this is something that someone would like to pursue, opening a new PR against nodejs/node master would be the right approach.
