### ISSUE TITLE
Error after 302 then 304

### ISSUE THREAD

**Issue by Hamdy** [joyent/node#7051]
Hello, 
am having an http action that redirects user to another action when user has met some condition.
the problem is I get frequently  get garbage HTML in my browser page like:

```
	</div>
	</div>
</div>
		<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
		..........
	</body>
</html>HTTP/1.1 304 Not Modified
ETag: "-485306310"
Date: Wed, 05 Feb 2014 17:32:56 GMT
Connection: keep-alive
```

This case sometimes happens for me when there's 302 then 304 HTTP responses.

```
debug: discarding transport
Passport: DeSerialzing User from session 52f254ffa33d553431b2faf6
GET / 302 31ms - 66b
Passport: DeSerialzing User from session 52f254ffa33d553431b2faf6
GET /go 304 27ms
```
Then I get that garbage HTML in my browser

**Comment by jasnell** [comment]
Closing. @Hamdy if this is still an issue, please provide a complete test case as @indutny asked and we can reopen if necessary.
