### ISSUE TITLE
url: resolve fails on a local string with double slash

### ISSUE THREAD

**Issue by ianstormtaylor** [joyent/node#7097]
this should be a relative url still i think:

```js
> url.resolve('.//dir/another/', 'image.svg')
'/dir/another/image.svg'
```

```js
> url.resolve('./dir/another/', 'image.svg')
'dir/another/image.svg'

> path.normalize('./dir/another/')
'dir/another/'

> path.normalize('.//dir/another/')
'dir/another/'
```

**Comment by jasnell** [comment]
While it looks a bit strange, the behavior on url.resolve is correct and consistent with browsers. For instance, if you attempt to navigate to `http://example.org/.//dir/another/` in chrome, it will normalize it to `http://example.org//dir/another/`
