### ISSUE TITLE
Debug options for IRHydra (deoptimizations tracing)

### ISSUE THREAD

**Issue by puzrin** [joyent/node#7122]
It would be nice to have more options for deoptimizations debug: http://mrale.ph/irhydra/2/

1. `--print-opt-code`
2. patch for IRHydra2

Is it possible to enable those by default? If not, is it possible to have ready dev binaries, that can be installed easy via `nvm` and so on. Building dev configuration manually is not convenient.

**Comment by jasnell** [comment]
@trevnorris @bnoordhuis ... any further thoughts on this one?

**Comment by trevnorris** [comment]
I know the disassembler was enabled in the io.js build, but I forget if it was done in Node.js.

**Comment by jasnell** [comment]
Ok, so the question then becomes: should we enable it in joyent/node master or v0.12 going forward or simply pick it up in the converged stream?

**Comment by bnoordhuis** [comment]
I think @indutny did that in #7639?  Or was that reverted?

**Comment by jasnell** [comment]
Don't believe so. Will close this then!
