### ISSUE TITLE
Improve Process & Documentation for Security Issues

### ISSUE THREAD

**Issue by evilpacket** [joyent/node#7143]
While I know that a [security mailing list](https://groups.google.com/forum/#!topic/nodejs-sec/cr9wp8_8sHk) has been established to announce security issues related to node. As well as a email security@nodejs.org 

I don't believe the process as it exists is documented well enough and located at a convenient enough location to be as accessible as it should be.

We should establish the page at nodejs.org/security and recommend documenting it and structuring it in a similar way to the [ember security page](http://emberjs.com/security/). I also believe this process should be described in a SECURITY.md file.

It also makes it clear how the process should work, communications expectations, and makes it easier to find for "researchers" who might get frustrated and just pop a public issue or go full disclosure. It also makes it clear for users that want to report or find out about security issues as patches become available.

**Comment by jasnell** [comment]
@evilpacket @trevnorris ... is there reason to keep this open here?

**Comment by trevnorris** [comment]
not from me.
