### ISSUE TITLE
http: optimize writes from same tick

### ISSUE THREAD

**Issue by bnoordhuis** [joyent/node#7154]
Example:

```javascript
var http = require('http');

http.createServer(function(req, res) {
  res.write('a');
  res.write('b');
  res.end('c');
  this.close();
}).listen(function() {
  http.get({ host: this.address().address, port: this.address().port });
});
```

Master currently writes out the response like this:

```
write(12, "HTTP/1.1 200 OK\r\nDate: Thu, 20 Feb 2014 02:26:50 GMT\r\nConnection: close\r\nTransfer-Encoding: chunked\r\n\r\n1\r\na\r\n", 109) = 109
write(12, "1\r\nb\r\n", 6)              = 6
writev(12, [{"1\r\nc\r\n", 6}, {"0\r\n\r\n", 5}], 2) = 11
```

Not bad but in practice that still means three TCP round-trips.  I would suggest corking more aggressively.

Another optimization that is possible here is to send the response with a `Content-Length: 3` header, that avoids the 5 byte overhead for each chunk.  Relevant for applications that write out the response in small increments.  Should also help reduce the number of TCP packets.

/cc @indutny

**Comment by jasnell** [comment]
@bnoordhuis @trevnorris ... any further thoughts on this one?

**Comment by trevnorris** [comment]
http now automatically uses writev with core/uncork. so should be solved.
