### ISSUE TITLE
repl: Proposal for further automatic requires

### ISSUE THREAD

**Issue by fb55** [joyent/node#7223]
There are two workflows of the repl which I'd like to simplify:

- `require` the current directory (according to it's `package.json` or `index.js`), as a quick way to debug it.
- `require` a module installed somewhere accessible from the current working dir.

The first could be done by simply defining an additional getter (the same way native modules are already required - I'd propose `__` or similar as a shortcut), the second requires the use of ES6 proxies (so that eg. `request` directly requires the request module). Of course, as long as proxies aren't enabled by default, there should be a check in front of that code, with the current logic for including core modules as a fallback.

Is this something that's wanted (especially the conditional use of proxies)? If it is, I'll create a pull request.

**Comment by jasnell** [comment]
@fb55 othiym23 ... any reason to keep this one open?

**Comment by othiym23** [comment]
@jasnell Not from my end, no.
