### ISSUE TITLE
readline does not send last line

### ISSUE THREAD

**Issue by lapo-luchini** [joyent/node#7238]
When the input file does not have a \n in the last line, that data is never sent to the 'line' event (nor any other).
It might be nice to generate a 'line' event on 'close' with remaining data.

**Comment by mmontag** [comment]
`brew upgrade node` and now my code works (node 0.12.2_1). :smile: Maybe this can be closed again?

**Comment by jasnell** [comment]
Confirmed, working in v0.12. Closing. Can reopen if necessary.
