### ISSUE TITLE
TCP_wrap core dump

### ISSUE THREAD

**Issue by morgante** [joyent/node#7248]
When using LearnBoost/knox, I encountered this bizarre error (the library attempts to connect to s3):

```
../src/tcp_wrap.cc:375: static void node::TCPWrap::Connect(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[2]->Uint32Value()' failed. Aborted (core dumped)
```

**Comment by jasnell** [comment]
@morgante ... I know it's been a while but is this still an issue for you?

**Comment by morgante** [comment]
To be honest, I don't even remember which code I filed this issue in relation to. Sorry!
