### ISSUE TITLE
stdout broke on Android

### ISSUE THREAD

**Issue by jdarling** [joyent/node#7290]
I can successfully build node 10 and 11 on my Android device using Debian Kit or build it and upload it to the device.  It runs fine and reports as version 0.10.xx or 0.11.xx but when you run anything there is no console output.

I've done quite a bit of reading and it seems that Android doesn't support stdout and instead prefers logcat.  The closest I've come to finding a "solution" to this is the article by Hanyu (http://hanyugeekingstyle.blogspot.com/2013/01/nodejs-for-android-with-consolelog.html) and his PR to add in support for logcat, but it doesn't seem that actually ever went anywhere.

Any chance that when the target OS is Android Node can use logcat instead of stdout?

Other than no output on the console everything works fine.

Oh, and I'm using VX ConnectBot to get a console, I have tried sending logcat to stdout using the android preference files, but since you have to wait for logcat to overflow this really isn't much good in a REPL.

**Comment by jasnell** [comment]
@jdarling ... I know it's been a while but is this still an issue for you?

**Comment by jdarling** [comment]
Not so much, haven't played with Node on Android in a long time.
