### ISSUE TITLE
ObjectWrap API changes

### ISSUE THREAD

**Issue by mscdex** [joyent/node#7312]
While writing a binding I ran into a problem where I was passing in an External to my class's New method via NewInstance() and using that External to wrap `args.This()`. I noticed that when I did that, the object I got back out with Unwrap() was not the same as the one I just Wrapped.

I narrowed it down to ObjectWrap::Wrap's setting of the internal field to `this` instead of the External object. I can manually re-set the internal field after calling Wrap(), but I'd rather have the option to pass in what to use for the internal field value and set it from the get-go.

What do you think about adding this kind of parameter (for v0.12)?

**Comment by jasnell** [comment]
@mscdex @indutny ... any reason to keep this open here?

**Comment by jasnell** [comment]
Closing. There does not appear to be an actionable issue here. Can reopen if that assumption is false.
