### ISSUE TITLE
Possible redundant check `if (util.isObject(handler))` in node/lib/events.js (line 117)

### ISSUE THREAD

**Issue by BioticPixels** [joyent/node#7321]
[event.js, line 117](https://github.com/joyent/node/blob/828f14556e0daeae7fdac08fceaa90952de63f73/lib/events.js#L117) - `util.isObject(handler)` may not necessarily need to be invoked if it is guaranteed to be true.
If it is not guaranteed, then `emit()` should return false or throw an error, considering the event has not been handled.

**Comment by jasnell** [comment]
Closing this. Can reopen if original poster wishes to pursue
