### ISSUE TITLE
Crypto: Add RSA public/private encrypt/decrypt functionality

### ISSUE THREAD

**Issue by charleswli** [joyent/node#7359]
Currently, only symmetric encryption (via `Cipher` and `Decipher` classes) is supported through the [Crypto library](http://nodejs.org/api/crypto.html).  [Public guidance](http://stackoverflow.com/questions/8750780/encrypting-data-with-public-key-in-node-js) points to using the [ursa module](https://github.com/Obvious/ursa) ([the most popular 3rd-party OpenSSL RSA wrapper](https://nodejsmodules.org/tags/openssl)), but it does not appear to be actively maintained as the last commit was over a year ago; ursa also does not offer explicit support for Node v0.10.x and has [installation issues](https://github.com/Obvious/ursa/issues/46) on Node v.11.x.

Ideally, given the existence of the Crypto library, this functionality would be native to Node itself (as it is with [PHP](http://www.php.net/manual/en/function.openssl-public-encrypt.php)) without requiring the use of a 3rd-party module.

**Comment by jasnell** [comment]
Associated PR seems to have landed. Assuming this can be closed. Can reopen if that's incorrect.
