### ISSUE TITLE
v.0.11.12 vs. 0.11.11 can't debug worker --> killed

### ISSUE THREAD

**Issue by Ognian** [joyent/node#7368]
I'm spawning several workers. When a worker hit's the breakpoint, the worker get's quickly killed, so that I'm unable to debug anything. This works in 0.11.11. Have you added some watchdog mechanism? How can this be disabled for debugging?

**Comment by jasnell** [comment]
@Ognian ... I know it's been a while, but is this still an issue for you? If it is, is it possible for you to provide a test case that demonstrates the issue.

**Comment by Ognian** [comment]
@jasnell I'm now on 0.11.14 and it is no longer an issue, if I remember correct it wasn't an issue with 11.13 either. My App actually creates 8 Workers and handles there web requests. I was using webstorm IDE and when setting a breakpoint it happened that the breakpoint was hit and then, before being able to do anything the process terminated... At the moment I'm short of time, so I'm not able to try to make a test case. You can close this issue and lets hope that it is solved.
