### ISSUE TITLE
Windows Installer Warning 1909

### ISSUE THREAD

**Issue by nameanyone** [joyent/node#7369]
Getting a warning at the end of installation. 
"Warning 1909.Could not create Shortcut Node.js command prompt.lnk. Verify that the destination folder exists and that you can access it."
Checking after installation, there is no such shortcut in "c:\Users\me\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Node.js\" folder.
"c:\Users\me\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Node.js\Node.js" is there and working. So not sure what the other (failed to be created) shortcut is for even.

node-v0.10.26-x64.msi
Win7 64-bit

**Comment by jasnell** [comment]
Unable to recreate this currently. *appears* to have been resolved but can reopen if that is incorrect.

**Comment by teckjon** [comment]
I am having the same issue.  The guide to fix it in #8141 doesn't work for me.
