### ISSUE TITLE
v0.11.12 missing from 'npm-versions.txt'

### ISSUE THREAD

**Issue by springmeyer** [joyent/node#7409]
It appears that v0.11.12 is missing from http://nodejs.org/dist/npm-versions.txt even though it has been released: http://nodejs.org/dist/v0.11.12/. I noticed this when running https://github.com/mapbox/node-pre-gyp/blob/master/scripts/abi_crosswalk.js.

**Comment by davidebbo** [comment]
Unfortunately, the using https://raw.githubusercontent.com/joyent/node/v0.8.27-release/deps/npm/package.json for the mapping no longer works for Node 4.0. i.e. https://raw.githubusercontent.com/joyent/node/v4.0.0-release/deps/npm/package.json doesn't exist.

Does anyone know of an alternate way to get the mapping? I know the matching npm is 2.14.2, but we need a way to automate that going forward.

**Comment by ChALkeR** [comment]
@davidebbo https://raw.githubusercontent.com/nodejs/node/v4.0.0/deps/npm/package.json works for versions v1.0.0 to v4.0.0.

**Comment by davidebbo** [comment]
@ChALkeR awesome, thanks much!

**Comment by rvagg** [comment]
https://nodejs.org/download/release/index.json might be what you're after, there's also a .tab version of this and I'm going to add more historical versions to this shortly. Generated with https://github.com/nodejs/build/tree/master/setup/www/tools/dist-indexer

**Comment by davidebbo** [comment]
@rvagg Nice! Did that always exist, or is it new? Looks like a better version of the defunct http://nodejs.org/dist/npm-versions.txt.

**Comment by rvagg** [comment]
@davidebbo new, we've been doing it with iojs.org and have only been doing it with nodejs.org for the past 2 weeks

**Comment by davidebbo** [comment]
@rvagg Thanks, it's a great resource to have for easily looking up what maps to what.
