### ISSUE TITLE
Streams: Make uncork behavior configurable on end

### ISSUE THREAD

**Issue by ashaffer** [joyent/node#7470]
Cross-posting from here: https://github.com/isaacs/readable-stream/issues/91 per request.

I understand the logic behind defaulting to uncorking on end, to prevent people forgetting to uncork, but you lose an enormous amount of power and flexibility by not making this optional.  For instance, I am trying to write a streaming ssh module, which pipes commands from some source over a connection, like this:

```javascript
fs.createReadStream('script.sh')
  .pipe(ssh({host: 'server.com'})
  .pipe(consoleStream());
```

And I would like to simply cork the ssh stream until the connection is open.  The problem of course is that the read stream usually finishes (causing an uncork) before the connection has fully opened.

If this behavior is made configurable, streams are capable of completely replacing flow-control libraries like async/seq/step, among other things.  It seems like an enormous amount of power to sacrifice just to avoid a certain type of error, especially if its simply an opt-in configuration option.

**Comment by jasnell** [comment]
@dominictarr @indutny @vkurchatkin ... any updates on this? any reason to keep this open?

**Comment by jasnell** [comment]
Going to close this one here. This is not something that's going to land against v0.12 or v0.10. If there's any reason to pursue this, nodejs/node would be the right place.
