### ISSUE TITLE
debugger: overview and improve

### ISSUE THREAD

**Issue by bmeck** [joyent/node#7473]
As discussed on IRC the Node debugger could use some care to improve user experience this issue will be used to aggregate goals and discuss improvement vs. refactor. More can be added to the list as needed.

Features:

- [x] ability to not listen on a port, but rather a fd
- [x] blackboxing (in particular built: in modules)
- [x] exposing require for bootstrapping (req. by @bajtos for node-inspector)
- [x] break on tick
- [x] break when tick is queued
- [x] break on require (evaluation phase)
- [x] source maps
- [ ] child debugging (isolate / child / cluster)
  - this should propagate up the process tree ideally, and not require the use of sockets (but be able to for things like http://strongloop.com/strongblog/whats-new-nodejs-v0-12-debugging-clusters/ ) 
- [x] gdb syntax
- [x] default mode is non repl
- [x] way to insert callback at breakpoint
- [x] expose heap profiler (maybe just for dumping to disk?)
- [x] expose cpu profiler
- [ ] features in devtools async errors http://www.html5rocks.com/en/tutorials/developertools/async-call-stack/
- [x] JS API to extend the debugging protocol / better integrate with 3rd party tools.
- [ ] Propagate breakpoints when swapping source files (req. by @Slava for meteor)
- [x] Custom pretty printer hooks
- [ ] Reverse debugging (would need v8 snapshot/restoration [performance will be terrible])

**Comment by jasnell** [comment]
@bmeck ... do we need to keep this one open?

**Comment by bmeck** [comment]
close it.
