### ISSUE TITLE
fs.createReadStream

### ISSUE THREAD

**Issue by skypjack** [joyent/node#7496]
The documentation for readable stream states that the internal buffer's size is 16Kb by default.
The readable stream returned by fs.createReadStream has the parameter highWaterMark equal to 64Kb and it's not documented.
Should we correct the documentation in order to avoid misunderstanding?

If it's so, I can pack and submit the patch.

**Comment by jasnell** [comment]
@skypjack ... still interested in submitting a PR?

**Comment by skypjack** [comment]
Yeah, I'm sorry, completely forgotten. Am I still in time?

**Comment by jasnell** [comment]
@skypjack ... yes, of course, if you can submit a PR targeting master then it should be easy to get reviewed.

**Comment by jasnell** [comment]
Landed
