### ISSUE TITLE
Configure python script not detecting if g++ not present

### ISSUE THREAD

**Issue by cryptomail** [joyent/node#7510]
On RHE(and probably *NIX), if g++ is not present, ./configure will not fail.  Then when going onto compilation/build the make will obviously fail if g++ is not installed.  I believe ./configure should afford a check to see if g++ is installed and fail if it can't find g++.

**Comment by jasnell** [comment]
@cryptomail ... is this still an issue for you?

**Comment by cryptomail** [comment]
no.  I've moved on and just assumed that g++ is available on every system that I try to build node.js on.
I think it's a fair assumption that it's there.
