### ISSUE TITLE
vm: context can't be a proxy

### ISSUE THREAD

**Issue by doughsay** [joyent/node#7526]
I know I'm probably completely going off the deep end of "nobody ever does this" here, but here goes:

When creating a VM context, it seems you can't use a proxy:

```javascript
var vm = require('vm')
  , proxy = Proxy.create({}, {foo: 'bar'})
  , context = vm.createContext(proxy)
  , script = new vm.Script('this.foo')

console.log(script.runInContext(context))
```

This (when run with `node --harmony`) throws `TypeError: sandbox must be an object`

I'd like to be able to control what properties can be accessed and set on the context object when running scripts in it.  Is this possible in any other way?

**Comment by jasnell** [comment]
Closing given the current state of Proxy.

**Comment by ghost** [comment]
I hope proxies will be real object soon at v8.
