### ISSUE TITLE
dns.resolve is synchronous when ethernet adapters are down

### ISSUE THREAD

**Issue by FrozenCow** [joyent/node#7532]
This situation happens on Linux on NodeJS v0.10.26. I don't know whether other OSes are affected.

I have the following program:
```js
var dns = require('dns');
console.log('Before resolve call');
dns.resolve4('nodejs.org',function(err) {
        console.log('Callback called');
});
console.log('After resolve call');
```

When the ethernet adapter is up (`sudo ip link set eth0 up`) I get the following (expected) output:
```
Before resolve call
After resolve call
Callback called
```

When I disable the ethernet adapter (`sudo ip link set eth0 down`) I get the following (unexpected) output:
```
Before resolve call
Callback called
After resolve call
```
Please note that if any of the other adapters (wlan0, tun0, etc) is enabled, this situation does not occur. It only occurs when *all* adapters are disabled.

## Workaround: process.nextTick fails
A sensible workaround for me was to use `process.nextTick` like the following:
```js
var dns = require('dns');
console.log('Before resolve call');
dns.resolve4('nodejs.org',function(err) {
        process.nextTick(function() {
                console.log('Callback called');
        });
});
console.log('After resolve call');
```
However, for whatever reason, this also results in the (unexpected) output(!):
```
Before resolve call
Callback called
After resolve call
```
## Workaround: setTimeout succeeds
When using `setTimeout` like the following:
```
var dns = require('dns');
console.log('Before resolve call');
dns.resolve4('nodejs.org',function(err) {
        setTimeout(function() {
                console.log('Callback called');
        },0);
});
console.log('After resolve call');
```
Things work like they should, giving me the expected output once again, while having all ethernet adapters disabled:
```
Before resolve call
After resolve call
Callback called
```

I don't know why `process.nextTick` fails, but I thought it might give some more insight to the problem. I can attempt to fix things, but I need to know on what level this needs to be solved: dns.js, c-ares wrapper or c-ares itself?

EDIT: I noticed that this issue does not happen in NodeJS v0.9.9. I used git bisect to determine that this behavior happens since 875e4a0c59efb0657389a353363fbd2f924cc9cf

EDIT2: By request of @tjfontaine, this is the error I got back from the callback:
```
Error: queryA ECONNREFUSED
    at errnoException (dns.js:41:10)
    at Object.onresolve [as oncomplete] (dns.js:149:19)
    at Object.query [as resolve4] (dns.js:172:15)
    at Object.<anonymous> (/home/bob/tmp/test.js:3:5)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:349:32)
    at Function.Module._load (module.js:305:12)
    at Function.Module.runMain (module.js:490:10)
    at startup (node.js:124:16)
```

**Comment by jasnell** [comment]
@FrozenCow ... I know it's been a while but is this still an issue for you?

**Comment by FrozenCow** [comment]
Ah, I already forgot about this (the workaround worked nicely for 0.10). I just tried nodejs 0.12 and the test above now gives the correct expected output. Consider this issue as resolved!
