### ISSUE TITLE
http: connection on data/readable has different behavior

### ISSUE THREAD

**Issue by trevnorris** [joyent/node#7581]
Script with each example:
```javascript
var http = require('http');
var PORT = 8123;

var server = http.createServer();

function onData(chunk) {
  console.log('chunk.length:', chunk.length);
}

function onReadable() {
  console.log('readable', this.read());
}

server.on('connection', function(conn) {
  // Uncommend each of these to see the difference.
  //conn.on('data', onData);
  //conn.on('readable', onReadable);
});

server.on('request', function(req, res) {
  console.log('received request');
  res.end('bye\n');
});

server.listen(PORT, function() {
  console.log('Listening on ' + PORT);
});
```
Remove the comment from each line in `server.on('connection'` then hit it with:
```
$ curl -b test=`for i in $(seq 18586); do echo -n $i; done` 'http://localhost:8123/'
```
For the `on.('data'` example you'll see:
```
Listening on 8123
chunk.length: 65535
received request
chunk.length: 16382
```
For the `on.('readable'` example you'll see:
```
Listening on 8123
received request
readable null
```

**Comment by plafer** [comment]
From the [docs on http's connection event](https://nodejs.org/api/http.html#http_event_connection): the socket will not emit readable events because of how the protocol parser attaches to the socket.

From what I understand, this behavior is known and documented. Are you saying we should change it so that the underlying socket emits `readable` events?

**Comment by trevnorris** [comment]
Don't remember that documentation being there when I filed this. Thanks for pointing it out.

It surprised me that I could get data one way but not the other. Seemed to lack consistency, but doesn't bother me enough to pursue a fix.
