### ISSUE TITLE
Node stdlib should take inherited properties into account and do so consistently

### ISSUE THREAD

**Issue by moll** [joyent/node#7587]
Hey,

Inherited properties are a core part of JavaScript and can be used to great extent beyond just for classes. Unfortunately there are inconsistencies with regards to how inherited properties are handled when passed to various functions or classes in the Node stdlib. It's a case where the the implementation leaks to the public API and the main culprit is `Util._extend`.

`Util._extend` is implemented to ignore inherited properties of the `source` (2nd param) and that creates hidden and undocumented public API limitations and difference. Functions using `Util._extend` will ignore inherited properties while those doing things in the traditional way with `for in` do not. The common practice of checking for truthyness with `if (options.handle) ...` of course *does* take inherited properties into account, so the status quo is bound to remain inconsistent.

I propose the API is made consistent by taking inherited properties into account everywhere.
This may entail changing `Util._extend`, too, to iterate over all properties, but fortunately it's a private function and those people who expect various Node stdlib functions to ignore inherited properties are treading on thin ice anyways.

If the proposition is okay, I can submit a patch/PR with tests.

**Comment by jasnell** [comment]
Closing this. The conversation appears to have gone stale. Can reopen if anyone feels it needs to be.
