### ISSUE TITLE
buffer: toArrayBuffer() memory leak

### ISSUE THREAD

**Issue by trevnorris** [joyent/node#7609]
Simple test script:
```javascript
var ITER = 1e6;

var b = new Buffer(1024 * 1024);

for (var i = 0; i < ITER; i++) {
  b.toArrayBuffer();
}
```
This would cause my machine to swap to death if I hadn't set application memory consumption limits.

**Comment by jasnell** [comment]
@trevnorris ... any updates on this one?

**Comment by trevnorris** [comment]
@jasnell Never got a response. Starting in 4.3 Buffers are backed by Uint8Array anyway so it's a non-issue down the pipe. I don't think it's worth the time to reimplement this feature before then.

Anway, technically this was fixed when the commit was reverted.
