### ISSUE TITLE
Why isn't it possible to listen for Runtime_StackGuard

### ISSUE THREAD

**Issue by remy** [joyent/node#7648]
I've been hit with problems in production in the past where an infinite loop occurs (partly triggered by user content, partly triggered by a third party npm module that had a nasty bug in it).

The only way I could debug it was via @mraleph giving me a walk through as to how I should hook the process using gdb and listen for the `Runtime_StackGuard`.

I wrote up what I did on my [blog](http://remysharp.com/2013/09/11/how-i-fixed-an-anonymous-infinite-loop-in-jsbin/) and @mraleph also posted (a better) explanation: https://gist.github.com/mraleph/6453431

I'm *guessing* this event is the same as this one in Chrome:

![screen shot 2014-05-19 at 23 04 20](https://cloud.githubusercontent.com/assets/13700/3020598/92c9bd34-dfa1-11e3-990a-83242d0ac755.png)

If that's the case, is it possible to be exposed to our Node code (via something like `process.on('Runtime_StackGuard`, fn)` - because getting some kind of insight or notification that this is happening inside our node apps would be incredibly useful.

**Comment by jasnell** [comment]
@bmeck ... any updates on this one?

**Comment by bmeck** [comment]
@jasnell still recommend doing this outside of process, DevTools suffers same thing, use gdb/lldb/mdb if you need this

**Comment by jasnell** [comment]
I agree. Perhaps we can close this one then?

**Comment by bmeck** [comment]
ya
