### ISSUE TITLE
About performance

### ISSUE THREAD

**Issue by py8765** [joyent/node#7672]
We have a large system which maintaining millions of clients using long connection. We use v0.10.0 before, and its performance is ok. Recently we decide to upgrade to 0.10.25, but it does not work. When we start the cluster, the cpu of every server is 100%, and it never falls. And we find that v0.10.10, v0.10.25, v0.10.28 all have this problem, but v0.10.0, v0.10.3 is ok, though the cpu will go high at start, it will falls when clients are stable. Why this happens ?

**Comment by jasnell** [comment]
Closing for lack of test case.
