### ISSUE TITLE
Error#stack can cause infinite loops with .toString for in 0.10.x

### ISSUE THREAD

**Issue by benjamingr** [joyent/node#7693]
Originally found [here](http://stackoverflow.com/q/23877022/1348195):

In older versions of v8, such as those used in the 0.10 branch in NodeJS, the error stack property lazy evaluation algorithm could cause endless loops when debugging.

**Steps to reproduce**

Step 1: save the following code as `example.js`

```js
ReferenceError.prototype.toString = function () {
  var that = this,
    source;

  if (this.stack) {
    source = this.stack.match(/([a-zA-Z0-9._-]+\.(?:js|coffee))(:\d+):\d+/);
  }

  return '<dummy-result>';
};

try {
  throw new ReferenceError('ABC');
} catch (e) {
  console.log(e.toString());
}
```

Step 2: type `node debug example.js`

Step 3: step through the code, you'll notice it loops from .toString to FormatStackTrace and back endlessly.

Problem manifested itself when using the `vows` library which does something similar.

Note that this has been fixed in newer V8 since and node acts correctly in 0.11.x . I'm not sure this is the correct place to report this - but I'm not sure where else.

**Comment by jasnell** [comment]
@bnoordhuis ... I'm inclined to close this and pick up the fixes from the converged stream. Thoughts?

**Comment by bnoordhuis** [comment]
Seeing how this has been open for over a year with no action, I'm inclined to agree.
