### ISSUE TITLE
Add support for deferring a callback to last, i.e. opposite of setImmediate/nextTick

### ISSUE THREAD

**Issue by rogierschouten** [joyent/node#7703]
In node.js 10.28, due to the difference in how events are processed on the first cycle w.r.t. the next cycles, it is not possible to reliably ensure that a callback comes after other callbacks. This prevents from solving certain race conditions.

Use case:
---------------

The Sentinel Event design pattern is used for cancelling/aborting an a-synchronous action. Since aborting a running a-synchronous action races with its completion, the caller needs to be told whether to still expect the a-synchronous result or not. This can be accomplished by giving the cancel() method an a-synchronous callback, which signals completion of the cancellation. Provided that both the result callback and the cancellation callback end up in the same queue, the client can wait for the cancellation callback and then be sure that no result callbacks will take place anymore.

Example:
```javascript

function startWork(workCallback) {
    do_work(workCallback);
}

function cancelWork(cancelCallback) {
   // todo cancel work here if still running.
   // It might be that workCallback has already been sent.
   setTimeout(cancelCallback, 0); // try to send cancelCallback after possible workCallback
}


startWork(function() { console.log("work done"); });
cancelWork(function() { console.log("cancel done"); });
```

<edit>
This example is supposed to output either 

```shell
cancel done
```
or 

```shell
work done
cancel done
```

but never

```shell
cancel done
work done
```
</edit>
 
Problem in Node.js currently:
------------------------------------------

This does not work in Node.js in all circumstances. Suppose the do_work() method might send the workCallback synchronously, or as a result of a setTimeout, setImmediate, process.nextTick, or I/O operation. 
<edit>
In Node.js, two things make it difficult to implement this: 
1. There seem to be different "queues" for different types of events, so the cancelWork method has to know which method (setTimeout etc) was used in do_work() so it can match the method for its callback. Otherwise the order between the workCallback and cancelCallback cannot be guaranteed. 
2. The relative order of processing timeouts, immediates, nextTicks etc. differs in the first execution cycle from what happens in later execution cycles (undocumented). 
</edit>

First cycle:

```javascript
setTimeout(function() {
    console.log("setTimeout");
}, 0);

setImmediate(function() {
    console.log("setImmediate");
}, 0);

process.nextTick(function() {
    console.log("process.nextTick()");
});
```

Outputs:

```shell
process.nextTick()
setTimeout
setImmediate
```

Next cycles:

```javascript
setTimeout(function() {

    setTimeout(function() {
        console.log("setTimeout");
    }, 0);

    setImmediate(function() {
        console.log("setImmediate");
    }, 0);

    process.nextTick(function() {
        console.log("process.nextTick()");
    });

}, 0);
```

Outputs:

```shell
process.nextTick()
setImmediate
setTimeout
```

Question / Request:
----------------------------------
I think a good solution to facilitate this use case would be a function that schedules a callback after anything that is currently waiting to get executed (at the point in code where this new function is called). 

But if anyone knows a better way of solving the race condition from the use case, I'm all ears.

**Comment by jasnell** [comment]
Closing. There doesn't seem to be anything actionable here. Can reopen if necessary
