### ISSUE TITLE
bad error message "TypeError: Usage: Buffer.concat(list, [length])"

### ISSUE THREAD

**Issue by tj** [joyent/node#7766]
"array expected, passed \<type\>" or something would be more obvious to assert that it's a type issue, something consistent throughout core for type issues would be nice. AFAIK no others use "Usage: ..."

**Comment by misterdjules** [comment]
Fixed in d01a900 for v0.10, and merged in v0.12 and master with b0425f0 and a995a6a. Thank you @chrisdickinson!
