### ISSUE TITLE
Bug in http request's pipe() method

### ISSUE THREAD

**Issue by dhruvbird** [joyent/node#777]
I've noticed that if I use the HTTP request stream's pipe method to pipe the input to an output stream (which is an http client - proxy scenario), then there are times when 'end' is NOT called on the response stream, even though the request stream triggers it, thus hanging the proxy. This means that even though the response has been received from the remote end, it is not reflected at the local endpoint. I've had to resort to using my own 'data' and 'end' handler to make this work reliably.

**Comment by jasnell** [comment]
Closing for lack of concrete test case and clear indication that it's still a problem. If issue persists, please comment with a simple test case we can use to verify and we'll re-open
