### ISSUE TITLE
node.exe from node.js conflicts node.exe from Microsoft HPC Pack

### ISSUE THREAD

**Issue by fyears** [joyent/node#7773]
node.exe is kind of not-so-usual name. But sadly I installed Microsoft HPC Pack that added its path into PATH in Windows environment and had a node.exe in the path before I installed node.js with official Windows installer.

To avoid any conflicts besides the one caused by Microsoft HPC Pack, I created a `nodejs.cmd` in `C:\Program Files\nodejs`, since nodejs is likely to be well known and unique.

```cmd
:: nodejs.cmd
:: Created by fyears, modified from npm.cmd
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe" %*
) ELSE (
  node %*
)
```

Maybe joyent could consider adding this `nodejs.cmd` in the official Windows installer.

**Comment by jasnell** [comment]
Nothing to do here.

**Comment by theoutlander** [comment]
I usually end up renaming HPC's node.exe to HPCNode.exe. Microsoft needs to be smart about this. They can very easily prefix everything with HPC....given that half the exe's in that folder are HPC*.exe!
