### ISSUE TITLE
Make it easier to debug unhandled stream errors in pipes

### ISSUE THREAD

**Issue by binarykitchen** [joyent/node#7804]
We all fear the infamous EPIPE and ECONNRESET errors like these:

```
Error: write EPIPE
  at errnoException (net.js:904:11)
  at Object.afterWrite (net.js:720:19)
```

thrown from https://github.com/joyent/node/blob/v0.10.28/lib/stream.js#L94

These are a bitch to debug, see https://gist.github.com/binarykitchen/339305eeadfb1629e57f

I think it would make our lives sweeter if more information were added to that exception before it's thrown.

For example more information about the source and destination. So that it's easier to narrow down the problem.

**Comment by jasnell** [comment]
@binarykitchen ... any updates on this? do we need to keep this open?

**Comment by binarykitchen** [comment]
no idea @jasnell - a lot has changed since then

**Comment by jasnell** [comment]
Ok, going to close this issue for now then. General improvements to error reporting is always an open issue ;-) Can reopen if there's anything specific from this that needs to land in v0.12 or v0.10
