### ISSUE TITLE
Modules with relative and absolute path are not the same

### ISSUE THREAD

**Issue by sateffen** [joyent/node#7926]
I just started to test my application with verison 0.11.13, and there is a pretty "interesting" bug, that is new:
> console.log(require('c:/Users/sateffen/Documents/Projects/nodgine/Tests/ApplicationTest/TestObject.js') == require('./ApplicationTest/TestObject.js'));

will log *false*.

I tested this with some more files, and every time the required file is not the same, if one side uses the relative path, and the other one the absolute path.

This is new in version 0.11.13, with version 0.10.29 it's not like this. Is this intended?

I'm using windows 8.1 64bit. If you need to know something, let me know.

**Comment by jasnell** [comment]
Closing as a duplicate.
