### ISSUE TITLE
Use GPG and SSL to protect downloads

### ISSUE THREAD

**Issue by wtogami** [joyent/node#7946]
http://nodejs.org/download/
Downloads of the official source and binaries are not protected by SSL, so a malicious entity could easily target users with a MITM attack in order to have them run compromised code.

Please add these two mitigation measures
* Protect downloads with SSL.
* http://nodejs.org/dist/v0.10.29/SHASUMS.txt  GPG sign the SHASUMS.  `gpg -a -b -s SHASUMS.txt` and provide the `SHASUMS.txt.asc` file for download alongside the SHASUMS.

**Comment by wtogami** [comment]
http://nodejs.org/dist/v0.12.4/node-v0.12.4-linux-x64.tar.gz
You didn't make the downloads SSL by default.  reopen?

**Comment by jasnell** [comment]
Can you open an issue over in http://github.com/nodejs/website ? That's
likely the best place to handle this moving forward.

**Comment by misterdjules** [comment]
@wtogami See https://github.com/nodejs/nodejs.org/issues/38#issuecomment-114619976.
