### ISSUE TITLE
execSync and spawnSync will hang forever unless stdio is set to "inherit" or "ignore"

### ISSUE THREAD

**Issue by tjwebb** [joyent/node#7967]
Occasionally, execSync and spawnSync processes will never return if there's no stdio set, or if it's set to "pipe". I can discern no pattern regarding type of child process spawned, length of output, whether or not errors are thrown, etc. It seems totally random.

**Comment by jasnell** [comment]
@tjwebb ... I know it's been a while, but do you have a test case that can be used to reproduce the problem?

**Comment by tjwebb** [comment]
No sorry, moved on to new projects. I just remember this was on node 0.11.something.

**Comment by cjihrig** [comment]
I'm going to close this as I was never able to reproduce it. If it happens again, we can reopen.
