### ISSUE TITLE
child_process: Expose constructor & optionally delay spawn

### ISSUE THREAD

**Issue by wesleytodd** [joyent/node#7981]
I am working on a module that would lightly wrap the child_process commands so that you can chain them together.  Currently I have copied over most of that core module to get the functionality I like.  Two small changes could get my module all the way there without having duplicate code from core:

1. Expose the ChildProcess constructor function like is done with the EventEmitter and other core "classes"
2. Add an option for not calling spawn right away.  Effectively all my module is doing is delaying this call until after `close` of the previous process.

I would be happy to PR both of these separately if anyone thinks they would actually be useful.  Or if anyone wants to tell me why I am wrong and show me the light, here is the WIP module: https://github.com/Node-Ops/child-process/blob/master/index.js

**Comment by jasnell** [comment]
@wesleytodd ... any updates on this one? Are you still pursuing this? Any reason to keep this open?

**Comment by cjihrig** [comment]
The `ChildProcess` constructor is exposed in io.js.

**Comment by jasnell** [comment]
We'll pick it up in the converged repo then. Thanks @cjihrig !

**Comment by wesleytodd** [comment]
Hey, I actually totally left this one off.  But it sounds like the real work has been done, so awesome work :)
