### ISSUE TITLE
No deprecation notice for CleartextStream in v0.11.13 docs

### ISSUE THREAD

**Issue by alexgorbatchev** [joyent/node#8017]
I'm reviewing changes in v0.11 compared to v0.10 and found that [Class: tls.CleartextStream](http://nodejs.org/dist/v0.10.29/docs/api/tls.html#tls_class_tls_cleartextstream) is completely gone from the [v0.11 docs](http://nodejs.org/dist/v0.11.13/docs/api/tls.html) without a deprecation notice.

Is that intentional?

**Comment by jasnell** [comment]
@trevnorris @indutny ... any reason to keep this open?

**Comment by indutny** [comment]
Yeah, there is still no docs on this :(

**Comment by jasnell** [comment]
Landed in https://github.com/joyent/node/commit/ba6c0866dc63f9070bc5cb2afd5fa5226b0b21e9
