### ISSUE TITLE
Confusing documentation for dgram.createSocket(options, [callback]) in v0.11

### ISSUE THREAD

**Issue by alexgorbatchev** [joyent/node#8019]
http://nodejs.org/dist/v0.11.13/docs/api/dgram.html#dgram_dgram_createsocket_options_callback

`dgram.createSocket(options, [callback])` new `options` is mangled together with previous function documentation and is unclear.

> options Object. Should contain a type property and could contain reuseAddr property. false by default. When reuseAddr is true - socket.bind() will reuse address, even if the other process has already bound a socket on it.

The possible options should be broken out properly, perhaps like so (I don't have the knowledge in the are to do it correctly)?

---

`options` `Object`

* `type` - ??
* `reuseAddr` - `Boolean` Required. `false` by default. When `true` - `socket.bind()` will reuse address, even if the other process has already bound a socket on it.

---

**Comment by jasnell** [comment]
Appears to already have been fixed.
