### ISSUE TITLE
Can't build node as a shared libary

### ISSUE THREAD

**Issue by samehkamaleldin** [joyent/node#8064]
I'm trying to build `node` as a shared library on `ubuntu 12.4.4`, but I'm getting an error in the `make` job.

I've changed the build target type in `node.gyp` to be a shared library as the following:
``` gyp
'targets': [
    {
      'target_name': 'node',
      'type': 'shared_library'
```
then I've executed `./configure` then `make -j8`, but an error occurred during the build process.
```
/out/Release/libopenssl.a(bio_ssl.o): relocation R_X86_64_32S against `
.rodata' can not be used when making a shared object; recompile with -fPIC
```
I don't know what's the problem exactly and how this can be fixed ?

**Comment by jasnell** [comment]
Closing this for now in favor of https://github.com/nodejs/roadmap/issues/9. Essentially, deferring this to the converged repo
