### ISSUE TITLE
Mind-blowing push('') in the Stream documentation

### ISSUE THREAD

**Issue by makoven** [joyent/node#8078]
Hello. 

In section [Example: SimpleProtocol v1](http://nodejs.org/api/stream.html#stream_example_simpleprotocol_v1_sub_optimal) push('') used twice. However, later [written](http://nodejs.org/api/stream.html#stream_stream_push): 

> If you find that you have to use stream.push(''), please consider another approach, because it almost certainly indicates that something is horribly wrong.

I'm horribly confused! If push('') so wrong, then can I get an example of SimpleProtocol v1 without it?

Thanks.

**Comment by jasnell** [comment]
While the design here is less than great, it doesn't appear to be an actual bug. Closing. Can reopen if my assumption is wrong.
