### ISSUE TITLE
setTimeout drifts after busy wait

### ISSUE THREAD

**Issue by bjouhier** [joyent/node#8105]
if you call `setTimeout` after a busy wait the delay can be much longer than expected.

I created a gist: https://gist.github.com/bjouhier/c7adb5f54caf9fc86d6e

OSX 10.9.4, node 0.10.27

**Comment by misterdjules** [comment]
Fixed by d38e865fce93c00cb128034202fb1e26987efdbc. Released in v0.10.39 and v0.12.5.

**Comment by natbro** [comment]
nice fix - thanks & sorry i didn't spot it.

**Comment by misterdjules** [comment]
@natbro No worries, and thank you for investigating and reporting your findings :+1:
