### ISSUE TITLE
Node API capitialization is not consistent

### ISSUE THREAD

**Issue by sam-github** [joyent/node#8157]
- `dns.resolveSoa`, ... (acronym capitalized as word)
- `tls.TLSSocket`, `fs.FSWatcher` (acronym all caps)
- `tls.CleartextStream` (crypto jargon word not internally camel-cased)
- `buf.writeUInt8` (c jargon word internally camel-cased)
- `crypto.createCipheriv` (acronym not capitalized at all)
- `crypto.pbkdf2` (acronym not capitalized)

The decision for each API's capitalization is usually justifiable on a case-by-case basis, but when scanning the entire API, it doesn't make sense any more.

I don't know what can be done at this point. Using completely capitalized acronyms seems to be the majority style in node, with the dns resolveXxx APIs being the glaring exception.

Maybe we can shoot for consistency for 1.0, leaving backwards compat into until 1.1? Or am I the only one bothered by this? Would a PR be rejected?

**Comment by jasnell** [comment]
While this is unfortunate, changing the documented API just to fix capitalization is not likely to happen.
