### ISSUE TITLE
Man page is not world-readable

### ISSUE THREAD

**Issue by nyuszika7h** [joyent/node#8217]
```
-rw-r----- 1 root staff 19312 Feb 28 18:51 /usr/local/stow/node/share/man/man1/node.1
```

This causes a *Permission denied* error with `mandb` when doing a system upgrade on my Debian 7.6 server.

**Comment by jasnell** [comment]
@nyuszika7h ... I know it's been a while but is this still an issue for you?

**Comment by nyuszika7h** [comment]
Sorry for the late reply. I cannot reproduce this on the latest git master now.

**Comment by jasnell** [comment]
Ok, then will close! Thank you!
