### ISSUE TITLE
make `ee._maxListeners` public

### ISSUE THREAD

**Issue by jonathanong** [joyent/node#8237]
any reason it's private? i'd like to increment/decrement the value as i add/remove listeners to avoid the stupid warning while not being irresponsible. specifically:

```js
ee.maxListeners++

ee.once('event', function () {
  // do stuff
  ee.maxListeners--
})
```

**Comment by cjihrig** [comment]
Oops. GitHub went ahead and closed that on its own.

**Comment by jasnell** [comment]
Landed in io.js. Will pick it up in the converged stream. see https://iojs.org/api/events.html#events_emitter_getmaxlisteners
