### ISSUE TITLE
Mouse support in Windows console?

### ISSUE THREAD

**Issue by Maximus5** [joyent/node#8292]
[slap](https://github.com/slap-editor/slap)'s description says
```Most terminal emulators in Windows do not support mouse events```
However, that is not true. Windows console [supports](http://msdn.microsoft.com/en-us/library/windows/desktop/ms683499(v=vs.85).aspx) mouse events.
Seems like Node.js ignores that events: tty.c, uv_process_tty_read_raw_req has lines

      /* Ignore other events that are not key or resize events. */
      if (handle->last_input_record.EventType != KEY_EVENT) {
        continue;
      }

So, I'm wondering, how it is possible to implement mouse support in Windows consoles?

BTW, I'm an author of [ConEmu](https://github.com/Maximus5/ConEmu) - windows console alternative and can send to the Node.js input buffer special ANSI codes, but I can't find corresponding code in Node.js sources. Any hints?

**Comment by TheSpiderPig** [comment]
I don't think this is an incredibly useful feature; what you're really asking for is a nodejs GUI framework.

**Comment by jasnell** [comment]
Likely never to happen in joyent/node. It can, perhaps be looked at in the future. If you'd like to pursue, please open an issue in nodejs/node
