### ISSUE TITLE
0.11.13 leaking memory?

### ISSUE THREAD

**Issue by stephenmathieson** [joyent/node#8300]
valgrind says the script:

```js
console.log('hello')
```

is leaking:

```
==10120== LEAK SUMMARY:
==10120==    definitely lost: 136 bytes in 2 blocks
==10120==    indirectly lost: 82,440 bytes in 5 blocks
==10120==      possibly lost: 936 bytes in 3 blocks
==10120==    still reachable: 160 bytes in 3 blocks
==10120==         suppressed: 0 bytes in 0 blocks
```

see [full valgrind report](https://gist.github.com/stephenmathieson/18a11d82898bd7fd8b5f)

**Comment by jasnell** [comment]
@stephenmathieson ... closing this. can reopen if you do happen to get those test cases together and can demonstrate there's an issue.
