### ISSUE TITLE
please mention AtExit in the documentation

### ISSUE THREAD

**Issue by kapouer** [joyent/node#8324]
Hi,
it would be nice to have [AtExit](https://github.com/joyent/node/commit/e4a8d2617b49727c4de09ad9ca9bc8fa270adf1e) mentioned in
https://github.com/joyent/node/blob/master/doc/api/addons.markdown

It would save developers a lot of time ;|

**Comment by jasnell** [comment]
Closing since the PR was closed and never landed.
