### ISSUE TITLE
Inherits with passing new properties

### ISSUE THREAD

**Issue by jtangelder** [joyent/node#8436]
I think an third argument to pass properties for the utils/inherits method would be useful. This could make some code a bit cleaner and easier to read.

````js
util.inherits(MyClass, events.EventEmitter, {
   someMethod: function() {
      this.emit('someEvent');
   },
   otherProperty: 1337
});
````

I'm willing to make a PR!

**Comment by jasnell** [comment]
Pretty certain this would not happen in joyent/node. If you wish to pursue this, a PR against io.js or the converged repo would be the ideal approach.
