### ISSUE TITLE
dist: windows x64 build of 0.11.14 has `nightly` tag

### ISSUE THREAD

**Issue by refack** [joyent/node#8460]
```
c:\node>wget http://nodejs.org/dist/v0.11.14/x64/node.exe -O node.exe
--2014-09-27 12:40:18--  http://nodejs.org/dist/v0.11.14/x64/node.exe
Resolving nodejs.org... 165.225.133.150
Connecting to nodejs.org|165.225.133.150|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8356576 (8.0M) [application/octet-stream]
Saving to: `node.exe'

100%[======>] 8,356,576   1.77M/s   in 7.7s

2014-09-27 12:40:26 (1.03 MB/s) - `node.exe' saved [8356576/8356576]


c:\node>node --version
v0.11.14-nightly-20140819-pre
```

Breaks `semver` semantics
```
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "c:\\node\\\\node.exe" "c:\\node\\node_modules\\npm\\bin\\npm-cli.js" "i" "ionic@1.2.6-beta2"
npm ERR! node v0.11.14-nightly-20140819-pre
npm ERR! npm  v2.0.2
npm ERR! code ENOTSUP

npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your version of node/npm: vinyl-fs@0.3.7
npm ERR! notsup Required: {"node":">= 0.10"}
npm ERR! notsup Actual:   {"npm":"2.0.2","node":"0.11.14-nightly-20140819-pre"}
```

**Comment by misterdjules** [comment]
Reopening as I don't know when we'll be able to release 0.11.15. @tjfontaine I don't think I can do the release myself as I wouldn't be able to sign the checksums, do you have some time to re-upload a release of 0.11.14, at least for Windows x64?

**Comment by kvrana1** [comment]
> Reopening as I don't know when we'll be able to release 0.11.15

Why? A month ago it was supposed to be 'tomorrow'?

Is there anything I can do to help speed things up?

**Comment by JiangJie** [comment]
@misterdjules Thanks anyway.
I think you should keep information more public and make a clear release schedule.

**Comment by misterdjules** [comment]
@kvrana1 At the time we thought 0.11.15 would be ready the next day, but that ended being a poor estimation. Working as a small distributed team around christmas/new-year while stable versions are broken is a difficult challenge.

As far as I know, the only blocker to release 0.11.15 is the merge of the v0.10 branch into v0.12 (see https://github.com/joyent/node/pull/8886). It's a difficult merge. My plan is to continue working on it today, but I don't know yet when we'll be able to finish it.

**Comment by tjfontaine** [comment]
http://nodejs.org/dist/v0.11.14/ now has the updated binaries, and a new set of signed SHASUMS that have been postfixed with '-win' to indicate that they cover the new binaries.
