### ISSUE TITLE
net: Allow custom DNS resolvers

### ISSUE THREAD

**Issue by chrisdickinson** [joyent/node#8475]
Per @bnoordhuis's suggestion in #2868:

> [...] a change that makes the DNS resolver configurable in the call to net.connect() might be acceptable. [...]
> The API I have in mind is something like this:
>
> ```javascript
> net.connect({
>  host: "nodejs.org",
>  port: 80,
>  resolver: function(host, type, callback) {
>    return dns.resolve(host, type, callback);
>  }
> });
> ```
>
> It's up for debate if the 'type' argument should be called 'family' instead and be a number, like how dns.lookup() works. I'm open to well-reasoned suggestions.

The PR should be against master -- this would be a good first feature for someone looking to contribute (be sure to include tests, doc updates, and to follow the [guidelines for contributing](http://nodejs.org/documentation/contributing/)).

**Comment by jasnell** [comment]
@chrisdickinson @trevnorris @bnoordhuis ... any further thoughts on this one?

**Comment by bnoordhuis** [comment]
It's been added to io.js.  It should be possible to back-port to joyent/node if someone wants to take that on.  If not, I suggest closing.

**Comment by jasnell** [comment]
I'll mark it as iojs-backport and defer but will also close it. I'm happy just to pick it up downstream
