### ISSUE TITLE
Unable to install on Windows

### ISSUE THREAD

**Issue by yankees9920** [joyent/node#8523]
I am trying to install node on Win 8.1 and I'm getting an error with both the .msi and .exe installers 32 and 64 bit. This happened with the version posted on the website 0.10.32.

When trying the MSI I get an error stating:
"The installation package could not be opened. contact the application vendor to verify that this is a valid windows installer package"

When trying the EXE I get an error stating: 
"This application can't run on your PC"

I was able to install by using the 0.10.28 version

**Comment by joaocgreis** [comment]
There is a very similar issue: https://github.com/joyent/node/issues/25347

@yankees9920 is this still an issue for you?

**Comment by jasnell** [comment]
Closing. Can reopen if new information is presented.
