### ISSUE TITLE
Core module `constants` is not documented

### ISSUE THREAD

**Issue by julien-f** [joyent/node#8533]

**Comment by jasnell** [comment]
@joyent/node-coreteam ... I doubt this is something we'd ever land here. Recommend deferring to converged.

**Comment by trevnorris** [comment]
+1

**Comment by orangemocha** [comment]
I think there might be some portability issues that are lurking in the constants module. I have some old notes on the subject:

Libuv maps system errors to UV_* error codes. These can have different values depending on the platform (uv-errno.h).
However, constants (from Node_constants.cc) and errno_string() (from Node.cc) define values that correspond to the system headers version of things (i.e. ENOENT). Some of these are defined on both on Unix and Windows (and again they can be different across the two).
In general, these codes can be different (and they are on Windows). For example constants.ENOENT != UV_ENOENT. 

So I am -1 on documenting this module before reviewing these issues.

**Comment by jasnell** [comment]
Ok, going to close this issue then. We can revisit this later after convergence.

**Comment by Dzenly** [comment]
Just for Info.

Public documentation:
https://nodejs.org/docs/latest-v0.12.x/api/tls.html

> Node.js (since v0.10.33) explicitly disables the use of SSLv3 and SSLv2 by setting the secureOptions to be SSL_OP_NO_SSLv3|SSL_OP_NO_SSLv2 (again, unless you have passed --enable-ssl3, or --enable-ssl2, or SSLv3_method as secureProtocol).
> ...
> secureOptions: Set server options. For example, to disable the SSLv3 protocol set the SSL_OP_NO_SSLv3 flag. See SSL_CTX_set_options for all available options.

According to this public API documentation, I now use
`secureOptions: constants.SSL_OP_NO_SSLv3 | constants.SSL_OP_NO_SSLv2 | constants.SSL_OP_NO_TLSv1 | constants.SSL_OP_NO_TLSv1_1,
`
in my code.

There is no support for 'secureOption' in new API documentation, and no mention about these constants though.
