### ISSUE TITLE
dist: latest package for npm

### ISSUE THREAD

**Issue by am11** [joyent/node#8550]
Copy: https://github.com/npm/npm/issues/6474

To package node.exe and npm.exe in [web-essentials](https://github.com/madskristensen/WebEssentials2013/), we have using `http://nodejs.org/dist/latest/node.exe` <sup>[[1]](https://github.com/madskristensen/WebEssentials2013/blob/master/EditorExtensions/PreBuildTask.cs#L102)</sup> and `http://nodejs.org/dist/npm/npm-{latest-package-version}.zip` <sup>[[2]](https://github.com/madskristensen/WebEssentials2013/blob/master/EditorExtensions/PreBuildTask.cs#L113)</sup> . 

As you can see, we can automate our script to fetch the latest `node.exe` but for npm, there is no "latest" in the directory structure; we have to manually specify the version number every time the version is bumped. 

For instance, the current release v2.1.3 is not [there](http://nodejs.org/dist/npm/) yet. It would be really nice if you guys maintain latest `npm.zip` at http://nodejs.org/dist/latest/ (npm.zip / .tar / .gzip) or `http://nodejs.org/dist/npm/npm-latest.zip` (/ .tar / .gzip).

**Comment by jasnell** [comment]
Closing.
