### ISSUE TITLE
CA bundle disappears after some time

### ISSUE THREAD

**Issue by Nowaker** [joyent/node#8552]
@RushPL and I are using [http-master](https://github.com/CodeCharmLtd/http-master) as our HTTP server. This is passed directly to node.js:

```json
{
  "key": "priv key here",
  "cert": "cert here",
  "ca": "ca certs here"
}
```

All is OK after start. CA bundle is served - ssllabs.com can see that, reports site as "trusted", reports no issues with the CA chain.

After some time CA is gone. It may be a day or two. ssllabs.com reports the site is "trusted", but reports incomplete CA chain. This results in Android phones seeing a message the site is not trusted. Desktop browsers don't see any problem because they have more certs in their trusted store. (And that's the reason why it has gone unnoticed for so long)

HTTP server wasn't restarted in mean-time. I'd see this in application log, or `systemctl` output (there's no way to trick pid 0 the process wasn't restarted).

I believe this is a problem in node.js as there's no way to alter CA during runtime, so http-master or node-http-proxy are not to blame, they are just passing the CA to nodejs internals.

node v0.10.32

Maybe @indutny can help? Thanks.

**Comment by jasnell** [comment]
@Nowaker ... I know it's been a while, but if this is still an issue can you please provide a simple test case that demonstrates the problem?

**Comment by Nowaker** [comment]
@jasnell No simple test case could be provided back then - I used node.js based HTTP server instead of nginx on a production system that served a lot of requests. Gave up in the end. 0.10 was okayish from a stability perspective (this problem was the only issue; not such a big deal when there's a job that checks whether all's okay and if not - restart the server) but terrible from a security point of view (no elliptic curve ciphers). SSL in 0.11 wasn't reliable at all. Now that I haven't run Node HTTP server in production for some time now, let's close the issue. Thanks for getting back to me, better late than never. ;)
