### ISSUE TITLE
streams: data/pipe and readable can't be used together

### ISSUE THREAD

**Issue by iliakan** [joyent/node#8568]
`data/pipe` events and `readable` can't be used together, the latter is ignored.

E.g. in this example, there are many `data` events, but no `readable` events (except the last one), so only 1 dot is printed:
```
fileStream.on('data', function(data) { console.log(data); });
fileStream.on('readable', function() { console.log('.');  });
```

The same with pipe - only 1 dot even if there are many data chunks:
```
fileStream.pipe(outputStream);
fileStream.on('readable', function() { console.log('.');  });
```

It is quite visible in the node code why that happens, but I couldn't find any mentions in the docs that "data/pipe" and "readable" are antagonists.

Also, it is not obvious from the common sense standpoint why the examples above don't work "as intended".

Is there a reason for such decision? Anything in the docs about that?

P.S. Node 0.11.14, the stream is `fs.ReadStream`.

**Comment by jasnell** [comment]
Landed in b436e59
