### ISSUE TITLE
ES6/7 roadmap ?

### ISSUE THREAD

**Issue by arcanis** [joyent/node#8607]
Hi,

It's a kind of long-term question related to the API.

Is there any plan to take account of ES6 (and 7) fundamental changes ? I especially mean the asynchronous APIs which are using callbacks. Using promises instead would streamline the development (especially with the ES7 async / await, already kinda available with the ES6 generators / yield hack) and help spread the good word, at the expense of a non-trivial work, and possible breaking changes.

I guess a way to alleviate these breaking change would be to check for the last parameter. If no callback as last parameter, then use promise, otherwise keep standard. It's a bit weird, but it could work.

Anyway, what's your position on this issue ?

**Comment by jasnell** [comment]
This is more a discussion for the converged repo and the long term roadmap (http://github.com/nodejs/node). Closing in favor of that.
