### ISSUE TITLE
Installing Node.js via package manager (CentOS 6.5)

### ISSUE THREAD

**Issue by infolock** [joyent/node#8613]
Let me say first that I understand that the nodejs team doesnt' maintain the packages as is said fairly clearly with: "Note: The packages on this page are maintained and supported by their respective packagers, not the Node.js core team. Please report any issues you encounter to the package maintainer. If it turns out your issue is a bug in Node.js itself, the maintainer will report the issue upstream."

That being said, this is not so much as a bug report but a "gotcha" for anyone else that may encounter an issue while installing node/npm on Centos 6.5 (not sure about other versions).

After running `curl -sL https://rpm.nodesource.com/setup | bash -` and then attempting to run `yum install -y nodejs`, you may notice that it doesn't install.  The message after installing will be: "**Package nodejs-0.10.33-1nodesource.el6.x86_64.rpm is not signed**"

The way I got this to install was by appending `--nogpgcheck` to the end of the install, which then installs both node and npm correctly.

`yum install -y nodejs --nogpgcheck`

You can then verify its installed by checking node/npm versions:
```bash
# node --version
v0.10.33
# npm --version
1.4.28
```

Hope it helps someone.  Apologizes if this happens to pollute the issues queue.

**Comment by jasnell** [comment]
@trevnorris ... should we keep this open?

**Comment by trevnorris** [comment]
No idea. This is out of my expertise.

**Comment by jasnell** [comment]
Ok, going to mark this as a defer for later and close for now. This can be revisited if someone really wants to pursue it.
