### ISSUE TITLE
https.request() misfiring error event?

### ISSUE THREAD

**Issue by gm112** [joyent/node#8647]
Hey,

So I have an HTTPs Proxy Tunnel that is using https.request() to send over the request to another server. And in some cases, the error event handler is firing with an empty error object. 

i.e. error = {}; given, request.on('error', handleError);
var handleError = function(error) {
console.log(error); //outputs {}/
};

Any potential thoughts?

**Comment by jasnell** [comment]
@gm112 ... I know it's been a while but if this is still an issue for you, would you be able to provide a simple test case that can be used to demonstrate the problem?

**Comment by gm112** [comment]
I haven't had the issue happen in testing and in production since I migrated to iojs a few months ago. :( More than likely some upstream patch corrected whatever the issue was that was happening, and it could have even been in my own app.. 

Thank you for reminding me that this issue was here. Considering this error's been quiet for quite some time, I'm going to go ahead and close this issue for you guys. :) :+1: for the followup, @jasnell
