### ISSUE TITLE
Can't install in Windows 10 Dev preview

### ISSUE THREAD

**Issue by vishnurajoasys** [joyent/node#8661]
I tried installing nodejs msi in Win 10. The installation stops at around 90%. I tried both 64 bit and 32 bit msi files. Both having same issues. 
![capture](https://cloud.githubusercontent.com/assets/7620713/4874489/3ee3bbfc-625a-11e4-9118-40e8e378ed69.PNG)

**Comment by joaocgreis** [comment]
Closing for now. @vishnurajoasys let us know if this is still an issue for you, share the installation log and I'll try to help.
