### ISSUE TITLE
needed: crypto.getSigners

### ISSUE THREAD

**Issue by dominictarr** [joyent/node#8675]
the `crypto` module has `getHashes`, which returns a list of supported hashes, and `getCiphers`, which returns a list of supported ciphers. Now, there are multiple signing algorithms that are supported ("RSA-<HASH>", which seems to work with any supported hash algorithm) and ("ecdsa-with-sha1", which doesn't seem to work with any other hashes );

I propose a `getSigners` method is added to return the list of available signing algorithms.

**Comment by jasnell** [comment]
@dominictarr ... still an issue for you?

**Comment by dominictarr** [comment]
can close this
