### ISSUE TITLE
v0.10.33 does not build when openssl disabled

### ISSUE THREAD

**Issue by lovebug356** [joyent/node#8676]
v0.10.33 does not build when openssl disabled, v0.10.32 builds fine if openssl is disabled.

> In file included from ../src/node.cc:85:0:
> ../src/node_crypto.h:30:25: fatal error: openssl/ssl.h: No such file or directory
> #include <openssl/ssl.h>

**Comment by tedu** [comment]
Still an error with v0.12.0. Same fix.

**Comment by misterdjules** [comment]
@lovebug356 @joerg-krause @jsiei97 @tedu Thank you for your help, and sorry for the delay. Adding this issue to the v0.10.40 release milestone, because we want to get v0.10.39 out as quickly as possible due to OpenSSL vulnerabilities and we don't want to add anything more to that milestone.

**Comment by misterdjules** [comment]
I'm available to guide anyone willing to pick this issue up and submit a PR that fixes it.

**Comment by whitlockjc** [comment]
I'd like to take a shot at this.  I'll get started and will hit you up with any questions I come up with.

**Comment by misterdjules** [comment]
@whitlockjc Excellent! Thank you :+1:

**Comment by whitlockjc** [comment]
I can reproduce with the latest `v0.10` branch using `./configure --without-ssl && make`:

```
Undefined symbols for architecture x86_64:
  "node::SSL2_ENABLE", referenced from:
      node::Init(int, char**) in node.o
  "node::SSL3_ENABLE", referenced from:
      node::Init(int, char**) in node.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I'll get a PR together shortly.

**Comment by joerg-krause** [comment]
This is the patch we use to build nodejs 0.10.40 with Buildroot: http://git.buildroot.net/buildroot/tree/package/nodejs/0.10.40/0004-fix-build-error-without-OpenSSL-support.patch

And this is the PR I already did to fix this issue: https://github.com/joyent/node/pull/8761

**Comment by whitlockjc** [comment]
Cool, I didn't see your work before.  I'll stop working on this then.  I got pulled into other work yesterday so after reproducing, I didn't work on the fix.

**Comment by whitlockjc** [comment]
@joerg-krause Your PR in #8761 seems to reference a deleted repository and cannot be reopened.  Do you want to close that PR and create a new one, linking to this issue?  If not, I don't mind creating a new PR to fix this issue I just don't want to do it without giving you the chance to.

**Comment by joerg-krause** [comment]
@whitlockjc Done so in PR https://github.com/joyent/node/pull/25862.

So this can actually be closed, but I don't see a `Comment and Close` button here :confused:

**Comment by joerg-krause** [comment]
Sorry, I know why I cannot close this! I am not the opener :smile:

**Comment by whitlockjc** [comment]
I don't think you want to close this.  :)  This will be closed when your PR is resubmitted and accepted.

**Comment by jasnell** [comment]
Yeah, just go ahead and leave this open for now. We'll close when the corrected PR lands.

**Comment by jasnell** [comment]
Landed.
