### ISSUE TITLE
Node should not automatically change rlimits

### ISSUE THREAD

**Issue by bmeck** [joyent/node#8704]
This changed in https://github.com/joyent/node/commit/6820054d2d42ff9274ea0755bea59cfc4f26f353 .
Which appears to have landed in 0.11.14 but there is not a clear reason why.

I feel it should be reverted.

1. principle of least surprise is violated by altering system resource limits automatically, not even configurable via a command line switch
2. we can no longer set a low limit for `node` and higher limit in child processes
3. this alters logic where `EMFILE` for soft limits was respected in 0.10.x- but now only hard limits are respected in 0.11.x+

**Comment by bmeck** [comment]
since 0.12 has landed I'm going to close this unless there are further comments and consider node's stance on unix conventions as being wavy when discussing

**Comment by jasnell** [comment]
@bmeck @piscisaureus @sam-github @joyent/node-coreteam @bnoordhuis ... what do we want to do with this one? Worth keeping open? Is this resolved?

**Comment by rvagg** [comment]
argh! I don't think either @bmeck or I want to give up on this but it's landed so it'd probably be a breaking change for both io.js and 0.12 to revert it.

**Comment by bmeck** [comment]
i would prefer it be reverted, but yes it would be a breaking change to revert, though was a breaking change to add as well.

**Comment by jasnell** [comment]
Well, should we put it up for TSC review?

**Comment by rvagg** [comment]
sure, let's have that discussion at least

**Comment by trevnorris** [comment]
I don't really care much either way, but a revert should require much more helpful error messages about what happened. Make it very easy for newb devs to find a fix.

**Comment by jasnell** [comment]
Ok, I've marked it tsc-agenda but let's lay out some of the basics and see if we can work it out here first.

1. Is this change limited to Node.js or did it land in io.js also?
2. What is the concise one sentence reason why the change was made? What does this fix?
3. What breaks if it's reverted?
4. What is the work around / alternative if it is reverted?

**Comment by piscisaureus** [comment]
I stated my opinion [here](https://github.com/joyent/node/issues/8704#issuecomment-62634404) and I don't have much to add to it. At some point I also did some digging to find other software that changes the soft limit, and it turned out that chrome does it too (and others that I don't remember).

The only argument I am susceptible to is that node shouldn't raise the limit for the (non-node) child processes it may spawn. Therefore:

-1 on reverting this patch
+1 on restoring the original ulimit after fork()

@jasnell 

> Is this change limited to Node.js or did it land in io.js also?

It landed before the fork.

> What is the concise one sentence reason why the change was made? What does this fix?

OS X has a really low soft "open file" limit. This makes node crash with an 'EMFILE' error when the number of open files (or network connections) goes up.

> What breaks if it's reverted?

Node starts crashing unexpectedly again.

> What is the work around / alternative if it is reverted?

The workaround is that all node users have to manually raise the limit (for all processes) with the ulimit command. This has to be done after every reboot.

**Comment by OrangeDog** [comment]
A bit biased. A valid workaround is to start node or your shell with increased limits.
Doesn't have to be every process, and doesn't have to be manually re-done every reboot (.bashrc could deal with shell limits, or aliasing `node`).

**Comment by sindresorhus** [comment]
It would be really disappointing if this was reverted. The [majority of node users](https://github.com/joyent/node/issues/8704#issuecomment-62845855) benefited from this change. You could of course improve the error message (should be done regardless), but the reality is that every single OS X user would have to fix this manually, which makes it harder to get started with Node, and [wastes a LOT of time](https://github.com/search?l=JavaScript&q=EMFILE&type=Issues&utf8=%E2%9C%93).

**Comment by Fishrock123** [comment]
How about we only turn this on for OS X? I am very -1 on anything other than having this as the default for OS X.

**Comment by rmg** [comment]
I still don't understand the objection to the behaviour. It's not changing the hard limit, which is the only limit that the sys admin (aka, user) can reasonably expect to be obeyed. It seems more reasonable to me that a handful of apps adopt some boilerplate to _lower_ their soft limit on startup than have the majority of apps adopt some boilerplate to _raise_ their soft limit like the commit in question does already.

With the current behaviour, the workaround boilerplate is:
```js
// this app has a memory leak, so lower the to hide our ENOMEM with an EMFILE crash
require('posix').setrlimit('nofile', {soft: 100});
```

If reverted, the boilerplate is:
```js
// this app can handle a lot more than the soft limit because node is awesome
var posix = require('posix');
var limits = posix.getrlimit('nofile');
posix.setrlimit('nofile', {soft: limits.hard});
```

**Comment by bmeck** [comment]
@rmg my problem is:

1. are not following convention, which even if this is a common problem saw breakage when this rolled out. notably it broke the `sandbox` module.
2. are overriding any soft limit a user may be using, thus forcing hard limits.
3. cannot recover the original soft limit.

**Comment by rmg** [comment]
@bmeck thank you, those are excellent points that I hadn't been able to distill from this thread.

Somewhat ironically, between your points and my own boilerplate examples, I suddenly care a lot less about this behaviour one way or the other.

**Comment by piscisaureus** [comment]
The resolution was:
* The current (rlimit-changing) behavior will be maintained.
* Node/libuv should restore the ulimit for the child processes it spawns.
* Support for leaving the ulimit untouched by setting an an environment variable will be added.
* Bradley Meck is going to create (node and libuv) patches for this.
So it doesn't need to be discussed at the TSC meeting of june 17th.

**Comment by rvagg** [comment]
can you remove the label please?

**Comment by piscisaureus** [comment]
Closing this issue; let's continue when the PRs come in.
