### ISSUE TITLE
license restrictions on joyent logo included in documentation assets ?

### ISSUE THREAD

**Issue by kapouer** [joyent/node#8728]
Hi,
the joyent logo is included in the documentation assets (since somewhere between 0.10.29 and 0.10.33). There are surely some restrictions regarding its usage, but they are not written in the LICENSE file.

**Comment by jasnell** [comment]
I assume that this will be resolved by the convergence effort under the foundation. Closing this issue in deference to that. If it continues to be a problem, please raise the issue at http://github.com/nodejs/node or http://github.com/nodejs/website
