### ISSUE TITLE
please make it possible to change the path installed to in the OS X package installer

### ISSUE THREAD

**Issue by digital-discuss** [joyent/node#8766]
It's great you have an OS X package installer available, but having to install into "/usr/local" creates cascading effects for the tools installed, as the installed path forces you to use sudo, not only for node and npm but also for installed tools like Yeoman, Grunt and generators. I'm unable to use these tools effectively. There are several discussions on places like Stackoverflow on how to fix this, but I've yet to find a straightforward method.

As it's possible to make a package installer ask where to install its payload, please add this feature to the package installer.

**Comment by jasnell** [comment]
Closing. Would defer further discussion on this to nodejs/build
