### ISSUE TITLE
Questions about the document describes

### ISSUE THREAD

**Issue by tudousi** [joyent/node#8797]
Can increase the detailed explanation of the api

fs.rename(oldPath, newPath, callback)#
Asynchronous rename(2). No arguments other than a possible exception are given to the completion callback.

fs.renameSync(oldPath, newPath)#
Synchronous rename(2).

fs.ftruncate(fd, len, callback)#
Asynchronous ftruncate(2). No arguments other than a possible exception are given to the completion callback.

fs.ftruncateSync(fd, len)#

Sometimes really do not understand what to do an api. ths

**Comment by jasnell** [comment]
Closing by tagging with a "defer" to convergence. We may want to revisit this one later
