### ISSUE TITLE
newListener event

### ISSUE THREAD

**Issue by smart--petea** [joyent/node#8853]
In http://nodejs.org/api/events.html is written:
```
Event: 'newListener'#
event String The event name
listener Function The event handler function
This event is emitted any time someone adds a new listener. It is unspecified if listener is in the list returned by emitter.listeners(event).
```
From this snippet I learnt that if listener is in listeners the `newListener` event is not fired.

I did 
```
var EE = require('events');
var ee = new EE;

var fnOk = function(){}

ee.on('newListener', function(){
  console.log('NEW LISTENER', arguments);
})

ee.on('ok' , fnOk); //fnOk is in ee.listeners('ok')
ee.on('ok', fnOk);
```
event `newListener` is fired twice in spite of fact that listener is just in listeners array.

May be I am wrong.

**Comment by jasnell** [comment]
Resolved in the io.js docs. Will pick up the change from there in the converged repo
