### ISSUE TITLE
There is no 0.11.14 for Windows x64

### ISSUE THREAD

**Issue by dougwilson** [joyent/node#8855]
The Node.js binaries and stuff in http://nodejs.org/dist/v0.11.14/x64/ are wrong; they report `v0.11.14-nightly-20140819-pre` as their version and act differently from the binaries in http://nodejs.org/dist/v0.11.14/ for Windows, which also has the correct version string.

For example, the x32 Windows binary includes the commit https://github.com/joyent/node/commit/64d6de9f34abe63bf7602ab0b55ff268cf480e45 but the x64 binary is missing that commit.

**Comment by theHazzard** [comment]
thanks @ben-page

**Comment by dougwilson** [comment]
I'm closing this because 0.11.15 was released.
