### ISSUE TITLE
repl: Assigning a value to `process` global causes segfault

### ISSUE THREAD

**Issue by xiam** [joyent/node#8885]
The `process` variable of the default context is writable, so a script like this cannot be run by node:

```javascript
/* test.js */
(function() {
  process = null;
})();
```

An example:

```
node test.js

module.js:499
  process._tickCallback();
          ^
TypeError: Cannot call method '_tickCallback' of null
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:906:3

````

If `process` is reassigned from within Node's repl, the entire process segfaults instead of throwing an error.

```
node
> process = null 
...
zsh: trace trap (core dumped)  node
```

Tested on:

```
node -v
v0.10.33
```

**Comment by cjihrig** [comment]
@trevnorris what are your thoughts on this? I'm in favor of closing.

**Comment by trevnorris** [comment]
@cjihrig Yeah. Looks like the right thing to do. Thanks.
