### ISSUE TITLE
readline doesn't respect multibyte character's width

### ISSUE THREAD

**Issue by hibiyasleep** [joyent/node#8917]
![movie: example with repl](http://d.hibiya.moe/5e7.gif)
(example with repl)
typing is OK, but cursor seeking and deleting is problem

Sample text here: `1 이상의 너비를 가진 문자`

**Comment by jasnell** [comment]
Getting back to this finally... the issue appears to have been resolved in v0.12.x and in io.js somewhere along the line. Unable to recreate the original problem. Given that, I'm inclined to close as v0.10 is in maintenance now and this is not critical at this point. Can open a new issues in nodejs/node if this continues to be a problem or if there are other concerns around multibyte char widths.
