### ISSUE TITLE
How to debug memleaks in http and fs library caused by deoptimization?

### ISSUE THREAD

**Issue by martensms** [joyent/node#8931]
It seems as the http response methods have a memory leak and that's why my server clusters are being shut down by the kernel. How can I properly debug what exactly is leaking or if I'm mistaken?

I have the heap snapshots laying around that indicate what is going on, but I have no idea what's going on internally in your javascript code. The snapshot indicates that the _storeHeader method (for example) is keeping references that GC can't trace and delete. It is a serious issue, because the lil' kilobytes per request sum up pretty fast and downtimes of servers cost money - and cronjobs for restarts are php-like solutions that I want to avoid.

Also, I think the EventEmitter leaks, but I'm not sure about that.

Link to methods (please fill in missing):
https://github.com/joyent/node/blob/master/lib/_http_outgoing.js#L191

Link to screenshots of the snapshot:
http://imgur.com/a/wQbvN

**Comment by jasnell** [comment]
@martensms ... is this still an issue for you? If so, are you able to provide a test case that reproduces the problem?

**Comment by martensms** [comment]
I had no possibility to create a reduced test case.
I only have my live system that totally leaks and has to be restarted once a day because of that issue :-/

As I have no clue on how to trace or isolate this issue because of the lack of proper debugging tools, I gave up.

**Comment by jasnell** [comment]
Ok, without having a test case and without any further information, it's going to be impossible to debug this. Closing. Can reopen if necessary.

**Comment by martensms** [comment]
Isn't this a chicken/egg sort of problem?

What kind of tools do you use to debug the memleak, so that I can put out a reproducible test case?

**Comment by jasnell** [comment]
Well yes, but unless we have some way of recreating the issue, it's going to be impossible for someone to debug it. The one thing I can ask is what version of node are you using and have you tried it out on one of the more recent io.js builds?
