### ISSUE TITLE
Debugger in 0.10.35 is corrupted

### ISSUE THREAD

**Issue by 3y3** [joyent/node#8948]
After 45f1330425b671905a02fe30ee7a1dd9544c2709 there is some problem in `debug-debugger.js`
[L1964](https://github.com/joyent/node/blob/v0.10.35-release/deps/v8/src/debug-debugger.js#L1964), [L2224](https://github.com/joyent/node/blob/v0.10.35-release/deps/v8/src/debug-debugger.js#L2224)

I'm not sure that this is all errors.

[Related issue in Node Inspector](https://github.com/node-inspector/node-inspector/issues/461#issuecomment-68174466)

**Comment by pflannery** [comment]
+1

**Comment by sbrinkmann** [comment]
+1

**Comment by justsml** [comment]
Ahhhhhhh, I wasted way too much time on this bug.... +1

**Comment by ariellyrycs** [comment]
+1

**Comment by bajtos** [comment]
Pull request that should fix the problem: #8973

**Comment by wlepinski** [comment]
@dotnetCarpenter You had to install it from source? The only available source for me on nodesource is 0.10.35 and 0.10.25 on archive.ubuntu :+1:

**Comment by dotnetCarpenter** [comment]
@wlepinski I'm on Mac OSX at the moment. But you can always find the linux binaries on *nodejs.org/dist/*.
Linux 64: http://nodejs.org/dist/v0.10.33/node-v0.10.33-linux-x64.tar.gz
Linux 32: http://nodejs.org/dist/v0.10.33/node-v0.10.33-linux-x32.tar.gz

**Comment by ekulabuhov** [comment]
@dotnetCarpenter thank you! Downgrading to 0.10.34 helped.
Packages for all OSs here: http://blog.nodejs.org/2014/10/23/node-v0-10-33-stable/

**Comment by 2color** [comment]
+1

**Comment by misterdjules** [comment]
We're most likely going to revert the breaking change with #8999. If you guys had some time to give it a try and let us know if it fixes your issues, that would be very much appreciated.

If you need help with testing it, please let me know and I'll be more than happy to assist you.

Thank you!

**Comment by misterdjules** [comment]
Landed in 31051e5c7b253b6a0006b536188fc0494bd6e082 and forward ported to v0.12 in merge commit fbfe562d71ae8d8f8bbf627808c755e513e4e905.

**Comment by bajtos** [comment]
That's great news, thank you. Is there any estimate when the next v0.10 release will be published?

**Comment by misterdjules** [comment]
@bajtos There's no definite date yet, but I'll keep you posted.

**Comment by misterdjules** [comment]
@bajtos So the goal is to release 0.10.36 with the following changes: https://github.com/joyent/node/issues?q=milestone%3A0.10.36+. Once [the upgrade of OpenSSL](https://github.com/joyent/node/issues/9052) is done, 0.10.36 will be released. There's no date scheduled, but hopefully we'll be able to do that next week.

Thank you again for your help and patience.

**Comment by EloB** [comment]
+1

**Comment by Mayayushi** [comment]
+1

**Comment by jarilamb** [comment]
still no remedy available, annoying

**Comment by thedug** [comment]
It's actually fixed. You'll have to clone the git repo, apply the patch, then build the source.

Works great.

**Comment by misterdjules** [comment]
The fix is available in the [v0.10.36 release](http://blog.nodejs.org/2015/01/26/node-v0-10-36-stable/).
