### ISSUE TITLE
Code only works if I print something before defining a method to 'Function.prototype'

### ISSUE THREAD

**Issue by tiagofischer** [joyent/node#8950]
I'm creating a new 'bind' method to 'Function.prototype'. The parameter is an object that I use to pass to the 'apply' function.
The code is working fine in any browser, but not in node.js. It's only work if I print anything before the 'Function.prototype'.
```javascript
console.log('if I comment this line, the second console.log() will print nothing');
Function.prototype.bind = function (that) {
	var method = this;
	return function() {
		return method.apply(that);
	}
};
var x = function ( ) {
	return this.value;
}.bind({value: 666});
console.log(x());
```
Prints:
**************************
if I comment this print, the second console.log() will print nothing
666
**************************

If I comment the first line, prints a empty line:
**************************

**************************

$ node -v
v0.10.25

Is this a bug?
Thank you!

**Comment by jasnell** [comment]
Does not appear to be a bug in node
