### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by khaldoun1** [joyent/node#8954]
I've got a ( segmentation fault ) error while my script is running, so I used the module (segfault-handler) and when the error occured I got the following:

PID 8328 received SIGSEGV for address: 0x319
/srv/cv-preuploader/node_modules/segfault-handler/build/Release/segfault-handler.node(+0x10e5)[0x7f166e7d80e5]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x10340)[0x7f166edb0340]
/usr/lib/x86_64-linux-gnu/libzmq.so.3(+0x2d070)[0x7f166c18c070]
/usr/lib/x86_64-linux-gnu/libzmq.so.3(zmq_getsockopt+0x1f)[0x7f166c1a062f]
/usr/lib/x86_64-linux-gnu/libzmq.so.3(zmq_poll+0x99)[0x7f166c1a12a9]
/srv/cv-preuploader/node_modules/cv-zmq/node_modules/zmq/build/Release/zmq.node(_ZN3zmq6Socket18UV_MonitorCallbackEP10uv_timer_si+0x63)[0x7f166c3bd6f3]
node(uv__run_timers+0x57)[0x9a2287]
node(uv_run+0x85)[0x998115]
node(_ZN4node5StartEiPPc+0x17f)[0x94745f]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7f166e9fbec5]
node[0x595890]

what does that mean and how to fix it?

this happend on each of node versions 0.10.34, 0.10.32 and 0.10.30
where I thought that if changed the version the problem may be solved according of some articles I've read trying to unferstand what's happening.

any help is highly appreciated

**Comment by misterdjules** [comment]
Closing as it's not clear currently if it's an issue with Node.js' core or with zmq. Please let us know if the investigation of this problem identifies that this is a problem with node, and we'll reopen this issue.
