### ISSUE TITLE
String.prototype.normalize always returns the original string

### ISSUE THREAD

**Issue by devongovett** [joyent/node#8957]
Not sure if this is a v8 issue, but it works in Chrome so I thought I'd report here. [String.prototype.normalize](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize) seems to always return the original string, rather than actually normalizing it. Tested in node v0.11.14. You can run this to confirm (run in node v0.11.14 and Chrome 34+):

```javascript
String.fromCharCode(7690).normalize('NFD').length // should be 2, returns 1
```

[This is the patch](https://code.google.com/p/v8/issues/detail?id=2943) adding support for the method in v8.

Currently, polyfills won't be enabled unless they also test for a correct implementation, breaking code that previously worked under versions of node without any implementation of `String.prototype.normalize` at all.

Perhaps something with the way ICU is built in node could cause this? I noticed one mention of normalization in #7719. If ICU is not going to be built/linked by default with node, then `String.prototype.normalize` should also be disabled by default. IMHO it needs to be supported eventually since the method is part of the language, but if fixing the issue is a big deal, disabling it for now would be a fine option I think.

**Comment by jasnell** [comment]
Resolved in v0.12
