### ISSUE TITLE
Windows: endless node_modules subdirs make backup IMPOSSIBLE

### ISSUE THREAD

**Issue by andreszs** [joyent/node#8961]
Congratulations to the node developers for finding the most effective way to ensure PhoneGap projects cannot be copied or backed up under Windows, by implementing and endless subdir method that ensures the path length at node_modules subdirs exceeds the path limit for Windows.

In over 20 years of using Windows, this is the second time I get this error. Maybe the developers do not use Windows, but don't forget that the entire world actually DOES use it, and preventing the user from making backups is not very nice from your part.

Please be so kind to implement a more reasonable approach that makes backups possible under ALL platforms, thank you.

**Comment by cjihrig** [comment]
I apologize. This is a well known issue that has been discussed at length in #6960. Please take a look at the discussion on that issue.
