### ISSUE TITLE
Bizarre stream.pipe behavior

### ISSUE THREAD

**Issue by devTristan** [joyent/node#8963]
First, I apologize for the relative complexity of the script I wrote that reproduces this bug. This is as simple as I could manage to get it.

You can see that script [here](https://gist.github.com/devTristan/33c8a753560dbb40ae3e). In order to run it, you'll need npm packages through2 and fast-csv. For your convenience:

```console
npm install through2 fast-csv
```

In order to reproduce this issue, you will also need a large CSV file. I've been able to reproduce it consistently with 50,000 (wide) lines with a total file size of about 60 megabytes. If you find it difficult to get a CSV file of this size, let me know and I'll build one for you.

Basically, the issue here is that `stream.Readable.prototype.pipe` doesn't seem to be properly handling backpressure. In a convoluted process of reading, parsing, stringifying, then writing a large CSV file, something very strange happens. At some point, instead of handling backpressure, the [final pipe function](https://gist.github.com/devTristan/33c8a753560dbb40ae3e#file-wtf-js-L37) just doesn't write to the file. The end result is that the output file is missing lines. The number of lines that go missing increases based on the speed that they are written. Due to the way fast-csv works, the write speed drastically increases near the end, so most of the lines are lost at that time.

I've isolated the issue to the pipe function [here](https://github.com/joyent/node/blob/master/lib/_stream_readable.js#L466-L596). When I use Stream.prototype.pipe [here](https://gist.github.com/devTristan/33c8a753560dbb40ae3e#file-wtf-js-L31), it works. When I try copying the data manually [here](https://gist.github.com/devTristan/33c8a753560dbb40ae3e#file-wtf-js-L40-L52), it works.

I'm using node v0.10.25 on ubuntu 14.04.

Can anybody figure out what's going on here?

**Comment by devTristan** [comment]
Wait, nope, this isn't a bug in node, this is something else.

**Comment by devTristan** [comment]
Edited original comment, this is definitely probably a bug in node after all.

**Comment by chrisdickinson** [comment]
It's hard to say whether this is a bug in Node based on the third-party modules. Could you try to reproduce without them? It may also be an issue with the lack of a `flush` param [passed to through2](https://gist.github.com/devTristan/33c8a753560dbb40ae3e#file-wtf-js-L25) at the end.

**Comment by devTristan** [comment]
It was a bug in a third-party module. Shocking, I know.
