### ISSUE TITLE
Support ES6 Classes

### ISSUE THREAD

**Issue by steelbrain** [joyent/node#8969]
I have to use a separate ES6 to ES5 transpiler and then run the transpiled file, It'd be great to have the native support for it. 'Cause it makes managing Node Apps a lot easier.

**Comment by cjihrig** [comment]
ES6 features arrive once they are available in the version of v8 used by Node.

**Comment by Fishrock123** [comment]
* Does not guarantee node will implement them in it's API.

**Comment by vkurchatkin** [comment]
@Fishrock123 I don't think you can distinguish between constructor created with `class` and `function`

**Comment by Fishrock123** [comment]
@vkurchatkin I was just making sure people would understand that colin's statement does not mean we will be implementing APIs with them yet. :)
