### ISSUE TITLE
Intl: Document timezone data

### ISSUE THREAD

**Issue by srl295** [joyent/node#8982]
Follow up to #8981 
- [ ] Update https://github.com/joyent/node/wiki/Intl to document how to access updated timezone data without a rebuild. See srl295/node#9

**Comment by srl295** [comment]
added some content to https://github.com/joyent/node/wiki/Intl#updating-timezone-data

**Comment by misterdjules** [comment]
Although [it's already present in the ICU user guide](http://userguide.icu-project.org/datetime/timezone#TOC-Updating-the-Time-Zone-Data), It could be nice to include in this wiki page a small paragraph stating why one would want to update timezone data. I think it would just provide some explicit context to this part of the documentation.

**Comment by misterdjules** [comment]
@srl295 I made the change, but feel free to question it :)

**Comment by srl295** [comment]
Perfect!
