### ISSUE TITLE
Publish tarball that contains only full ICU data

### ISSUE THREAD

**Issue by misterdjules** [joyent/node#8996]
Eventually, binary installers will ship with full ICU data (see #8995). However, other binaries (binary tarballs, custom builds from source) will still not ship and load the full ICU data by default.

To allow users of these other binaries to use the full ICU data, we should generate and publish a separate tarball that contains only the full ICU data as a separate `.dat` file.

To use the full ICU data, users could put this file in `$PREFIX/share/node/icu/` or could pass its path on the command line using `--icu-data-dir=`. 

The tarball would be automatically generated and published by a Jenkins job.

This depends on #8983.

cc @srl295 @tjfontaine

**Comment by srl295** [comment]
You can pull the full data file out of `deps/icu/source/data/in/*.dat` after a successful build. However, it won't necessatily have the right endianness.

**Comment by srl295** [comment]
Note: this is blocked by #9046 - we can't generate the big endian tarball for the same reason (conversion).  Probably the solution proposed there needs to go in first, IF we want to publish BE data.

**Comment by srl295** [comment]
@misterdjules ^^ thoughts on #9091 ?

**Comment by srl295** [comment]
FYI @sxa555 - how does this look?

**Comment by srl295** [comment]
- [ ] add a `README` to the tarball with some instructions. maube lodge it in `tools/icu/README-data-tarballs.md`

**Comment by srl295** [comment]
- [ ] add a command line to `test-intl.js` to verify full
- [ ] add another test to upload the tarball, download it and test it.

**Comment by srl295** [comment]
@misterdjules where should the extended tests ^^ live?

**Comment by sxa555** [comment]
Seems good - subject to an assumption that Windows users will be ok with a .tgz instead of a ZIP.

**Comment by srl295** [comment]
@sxa555 yeah wasn't sure about that. Make a .zip also? make them all zips?

**Comment by misterdjules** [comment]
@srl295 Thank you very much for your work, and sorry for taking so long to do a first review.

It's not clear to me yet how to add tests for that, since I believe we don't currently have any similar "integration" test.

I would put them in a separate directory in `test`, maybe in `test/integration` (I don't like this name, but `test/i18n` might be too specific). 

The test doesn't need to upload the tarball, it could just build node with `small-icu` support, generate the data tarballs, and then run node such that it loads the data in this tarball and run a small script that tests for full localization support.

We would also want to have that work on all supported platforms (OS X, Linux, SmartOS and Windows).

What do you think?

**Comment by sxa555** [comment]
Tricky to say on tgz vs zip since in the general case you cant' assume that UNIX users will have an unzip/jar command either ... but I guess that might be more likely than a windows user have gzip+tar ...

Another thought though - how practical would it be to ship the ICU data as an NPM module which users could install globally - if you did that it might be possible to also have node default to searching in the global location for the ICU data file if no alternative was explcitly specified?

**Comment by srl295** [comment]
@sxa555 actually, the npm module idea makes some sense. This could morph into a 'generator' that auto publishes into npm the appropriate versions. And actually, we could install with node (part of the normal build) a text file containing:  `npm install node-icu-data-le@54.1` ( in other words the exact command line needed to go fetch the apporpriate data version and the appropriate endianness.).

**Comment by srl295** [comment]
While I look into the `npm` module idea, at least just to fetch the data itself (ala @rxaviers' [cldr-data-npm](https://github.com/rxaviers/cldr-data-npm) would this make some sense:
* have a (separate?) repo that has a builder script that generates `package.json` (with probably a more or less static version `1.0.0` or whatever), ICU license files, readme, etc
* then push an instance of the `npm` module with:  `npm publish ./generated/ --tag icudt54l` and `npm publish ./generated/ --tag icudt54b` 
* then users can get what they need with `npm install [-g] node-icudata@icudt54l` or `npm install [-g] node-icudata@icudt54b` for big endian

Alternate options:
* commit each and every `package.json` to the repo
* commit each version of the ICU data to the repo

Any thoughts about the npm package naming and use of the tag?

**Comment by srl295** [comment]
OK, NPM package published here - https://www.npmjs.com/package/icu4c-data

snippets:
```
node -e 'console.dir("npm install icu4c-data@"+process.config.variables.icu_ver_major+process.config.variables.icu_endianness)'
npm install icu4c-data@54l
node --icu-data-dir=node_modules/icu4c-data -e "console.dir(new Date().toLocaleString('ru',{month:'long'})));"
```

**Comment by sxa555** [comment]
I'd probably install the latest LE version by default if you don't specify , but otherwise LGTM

I guess we need to encourage people to specify the version properly anyway to ensure the ICU version patches what's built into their node anyway.

**Comment by srl295** [comment]
@sxa555 yeah, I think the default has to do with the 'real' npm package version being the highest. Maybe I can retag 'latest' somehow.

**Comment by srl295** [comment]
ICU link: http://bugs.icu-project.org/trac/ticket/11617

**Comment by stuartpb** [comment]
Why is endianness part of the package *name*? Doesn't NPM have a means of selecting platform-specific binaries?

Also, what's wrong with using semver for the package version, rather than putting the version in the name as well?

**Comment by srl295** [comment]
> Why is endianness part of the package name? Doesn't NPM have a means of selecting platform-specific binaries?
It's part of the tag, not the name. I'm not aware of that means but I will look, do you have a link?

**Comment by stuartpb** [comment]
I guess npm's means of selecting platform-specific binaries is to include a .gyp in the package, which then runs on install.

Other approaches that seem simple enough to my untrained eye:

- Just include both as part of the package. (What's another 5MB?)
- Include little-endian, and have big-endian platforms read from the little-endian data and dynamically convert at runtime.

Specifying the endianness as part of the package spec is no good, as it unnecessarily limits your package to a specific platform.

**Comment by srl295** [comment]
@stuartpb I was hoping to keep the dependencies more lightweight than gyp.  Also, you *have* to select the right version number of the ICU data anyways, so if v8 was linked against icu 54 you already need to select 54 and not 53 or 55 - so selecting 54l versus 54b doesn't seem to add that much of a burden.

What you could have is a node module that on 'install', turns around and like [this](https://www.npmjs.com/package/icu4c-data#what-version-do-i-need) executes the command output by this.
`node -e 'console.dir("npm install icu4c-data@"+process.config.variables.icu_ver_major+process.config.variables.icu_endianness)'`

> just include both

`54l` and `54b` are each 25MB.

**Comment by sxa555** [comment]
@srl295 Wasn't sure where you were storing the source for the NPM, but the usage example in the MD has ")))" at the end which is one too many - should just be "))"

**Comment by srl295** [comment]
@sxa555 thanks, it's actually on [icu-project](http://bugs.icu-project.org/trac/browser/tools/branches/srl/npm11617) at the moment. I'll fix that.

**Comment by srl295** [comment]
The ICU ticket has been accepted by the ICU PMC. For now, this will be a task done and updated by the ICU release process (me). If ICU fails to update it, the updating could be taken over by node.js or some other party.

**Comment by jasnell** [comment]
@srl295 ... what's the status on this one?

**Comment by jasnell** [comment]
@srl295 ... going to assume we can close this. Feel free to reopen if that assumption is incorrect.
