### ISSUE TITLE
[Security] OpenSSL 1.0.1j -> 1.0.1k

### ISSUE THREAD

**Issue by steakknife** [joyent/node#9000]
http://packetstormsecurity.com/files/129867/secadv_20150108.txt

**Comment by steakknife** [comment]
1.0.1l was released yesterday, so node is now 2 revs behind.

**Comment by steakknife** [comment]
Will close after it's merged into 0.10.x branch/es at least

**Comment by misterdjules** [comment]
Thank you @steakknife and sorry for not getting back to you earlier. I will close this as a duplicate of #9052 if you don't mind, because #9052 has a bit more info on how the upgrade will be done, and not having duplicates helps us track things and avoids confusion.

**Comment by steakknife** [comment]
@misterdjules Over a week with no response on a security issue.  Is security@joyent.com valid for node?

**Comment by misterdjules** [comment]
@steakknife The actual email is security@nodejs.org. I'm sorry this information was not easily available when you submitted this issue. It should be after https://github.com/joyent/node-website/pull/60 is merged.

**Comment by steakknife** [comment]
So a safe bet would be security@nodejs.org cc: report@nodesecurity.io

GPG .asc URL?

**Comment by misterdjules** [comment]
That seems good. What do you mean by "GPG .asc URL?"? @tjfontaine Could you please confirm.

**Comment by steakknife** [comment]
Probably simpler to negotiate with a named individual email person to send encrypted confidential info w/ GPG.  Having a shared GPG key can be a chore, initially.  A reminder to not send confidential info in the clear might be wise.

**Comment by steakknife** [comment]
@misterdjules Thanks for clarifications.  Happy Friday or weekend as the case may be. :)
