### ISSUE TITLE
url.parse() will lead to null query even parseQueryString  is true under v0.11.x 

### ISSUE THREAD

**Issue by yanni4night** [joyent/node#9008]
Under v0.10.x

    require('url').parse('/main.css',true).query => {}

But under v0.11.x it's `null`.

Is that designed on purpose?

**Comment by cjihrig** [comment]
I believe this should have been fixed by b705b73e46193c7691be40b732330a49affacedb in #8332. Can you give it a try with 0.12. If it's still broken, we can reopen.
