### ISSUE TITLE
[0.10.26] Debug mode is listening on localhost:5858 instead of 0.0.0.0:5858

### ISSUE THREAD

**Issue by Maxwell2022** [joyent/node#9012]
I'm trying to connect to the debug socket but I can't because node debugger is listening on localhost:5858

```
$ netstat -ao
tcp        0      0 localhost:5858              *:*                         LISTEN      off (0.00/0/0)
[...]
```

So when I tried to access the debugging server, I get a connection refused
(my firewall is fully opened)
```
$ curl -I http://xx.xx.xx.xx:5858
curl: (7) Failed connect to xx.xx.xx.xx:5858; Connection refused
```

On the local server it's working fine tho:

```
$ curl -I http://localhost:5858
Type: connect
V8-Version: 3.14.5.9
Protocol-Version: 1
Embedding-Host: node v0.10.26
Content-Length: 0

Content-Length: 96
```

Is it possible to bind something else than `localhost:5858`, for instance `0.0.0.0:5858` ?

Cheers, Maxime

**Comment by sam-github** [comment]
`--debug-port=XXX` with node 0.12, can't recall with v0.10 if its possible.

**Comment by Maxwell2022** [comment]
This is to specify the port number, I want to specify the interface, instead of `localhost:5858` I want to bind `0.0.0.0:5858`

**Comment by Maxwell2022** [comment]
Anyone knows if it's possible?

To reproduce try running your node server in debug mode:
`./node_modules/coffee-script/bin/coffee --nodejs --debug=5859 server.coffee`

Then check in `netstat` on which interface the debugger is listening:
```
$ netstat -an | grep LISTEN
tcp4       0      0  *.5000                 *.*                    LISTEN
tcp4       0      0  127.0.0.1.5859         *.*                    LISTEN
[...]
```

Get your local IP address and try to curl it:
```
$ curl -I http://10.0.1.1:5859
curl: (7) Failed connect to 10.0.1.1:5859; Connection refused
```

As you can see the connection is refused because the debugger is listening on another interface. Now if you try doing a curl to localhost you'll see that it's working:

```
$ curl -I http://localhost:5859
Type: connect
V8-Version: 3.14.5.9
Protocol-Version: 1
Embedding-Host: node v0.10.26
Content-Length: 0
```

I want to be able to change the interface on which the debugger is running so that I can debug remote server, is that possible ?

Cheers, Maxime

**Comment by Maxwell2022** [comment]
Ok, so it's not possible to do it launching the server in debug mode. V8 debugger can only listen on `localhost`. You need to create an SSH tunnel to bind the port on another interface.

Here is a good explanation on how to do it:
https://rollbar.com/blog/post/2014/12/19/Debugging-Node.js-Apps-in-Production-with-PyCharm

Thanks for those who took time to look at this issue, hopefully it will help some
