### ISSUE TITLE
Node js code protection techniques

### ISSUE THREAD

**Issue by rahuldeshpande11** [joyent/node#9013]
I want to deploy the node js code as a part of application installation on laptop/desktop.
I don't want anyone to read my code.

What are tools and techniques available to achieve that?
Do I need to encrypt the code or I should just turn in to one executable?

Please help.

**Comment by micnic** [comment]
This is not an issue related to the Node core, your question should be already answered on http://stackoverflow.com/questions/tagged/node.js please check there.

**Comment by cjihrig** [comment]
You can also try the Node.js mailing list.
