### ISSUE TITLE
Cannot read property 'ajax' of undefined

### ISSUE THREAD

**Issue by vladidi** [joyent/node#9014]
Plz help me, I'm using the following code:

index.js:

    var $ =  require('./node_modules/jquery/dist/jquery.min');
    var _ = require('./node_modules/underscore/underscore-min');
    var Backbone = require('./node_modules/backbone/backbone-min');
    require('./model/models');

    run();

    function run(){
        var session = new ****.***.Models.CustomerSession();
        session.save({
            "authenticators": ["********","****"]
        }).always(function(xhr){
            do_something...
        });
    }
models.js:

    **** = {};
    ****.*** = {};
    ****.***.Models = {};

    var _ = require('../node_modules/underscore/underscore-min');
    var Backbone = require('../node_modules/backbone/backbone-min');

    /////////////MODELS/////////////

    ****.***.Models.CustomerSession = Backbone.Model.extend({
        urlRoot : 'https://*****.****.com/api/***/customer_session/'
    });

    ****.***.Models.Transaction = Backbone.Model.extend({
        urlRoot : 'https://*****.****.com/api/***/transaction/'
    });

    ****.***.Models.FaultType = Backbone.Model.extend({
        urlRoot : 'https://*****.****.com/api/***/fault_type/'
    });

    ****.***.Models.FaultTypeSet = Backbone.Model.extend({
        urlRoot : 'https://*****.****.com/api/***/fault_type/'
    });

    ****.***.Models.Task = Backbone.Model.extend({
        urlRoot : 'https://*****.****.com/api/***/task/'
    });
    ///////////////////////////////
And get the following ERROR: "Cannot read property 'ajax' of undefined"...
This is all the code in the project except the node_modules libraries...
I think that backbone don't recognize the $ sign, but I'm not sure and don't know what to do with the problem... 
Plz help me...

Here is the error log as I see it:

    c:\ce\test_script\node_modules\backbone\backbone-min.js:1
    h:"PATCH","delete":"DELETE",read:"GET"};e.ajax=function(){return e.$.ajax.appl
                                                                    ^
    TypeError: Cannot read property 'ajax' of undefined
    at Object.e.ajax (c:\ce\test_script\node_modules\backbone\backbone-min.js:1:14801)
    at e.sync (c:\ce\test_script\node_modules\backbone\backbone-min.js:1:14518)
    at i.extend.sync (c:\ce\test_script\node_modules\backbone\backbone-min.js:1:3208)
    at i.extend.save (c:\ce\test_script\node_modules\backbone\backbone-min.js:1:5716)
    at run (c:\ce\test_script\index.js:14:13)
    at Object.<anonymous> (c:\ce\test_script\index.js:10:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

    Process finished with exit code 8

**Comment by cjihrig** [comment]
This is not likely a bug in Node core. From this snippet `e.ajax=function(){return e.$.ajax.appl`, it looks like perhaps there is an issue with the `$`.

**Comment by vladidi** [comment]
Yes, it's definitely issue with $...
I can see it when I log the $ variable like so : 
    
    console.log($);

it prints this:

    [Function]

It look like the following line not working...
    
    var $ =  require('./node_modules/jquery/dist/jquery.min');
or

    var $ =  require('jquery'); 

Cen't get it...
