### ISSUE TITLE
docs: emitter.listeners return a copy of original array rather than an array reference

### ISSUE THREAD

**Issue by StevenRoan** [joyent/node#9022]
As title, the document use the description 
- **Returns an array of listeners for the specified event.**

However, return an array usually indicating return an array reference, and here is different.
Maybe we can consider to modify this part of document, Thanks!

Example code
```
var EventEmitter = require('events').EventEmitter;
var eventEmitter = new EventEmitter();
var arrListeners = eventEmitter.listeners('test-event');
console.log(arrListeners.length);
eventEmitter.addListener('test-event', function(){
  //Do sth.
});
console.log(arrListeners.length); // log 0 because the this array reference is different with current one. 
arrListeners = eventEmitter.listeners('test-event');
console.log(arrListeners.length);
```

get output
0
0
1

**Comment by BSteephenson** [comment]
https://github.com/joyent/node/blob/master/lib/events.js#L155
addListener is optimized to not even make an array if there's only one listener. Calling .listeners(), it just makes an array on the fly. Changing the documentation rather than the feature makes more sense.
