### ISSUE TITLE
RangeError: Port should be > 0 and < 65536

### ISSUE THREAD

**Issue by pepone** [joyent/node#9023]
try{ 
    var fd = require('net').createConnection({host:'127.0.0.1', port:0});
    fd.on('error', function(err){
      console.log("fd on error");
    });
    }catch(e){ 
      console.log("error"); 
    }

With 0.11.14 the above code produces an unhalted RangeError the on error callback is not called and the catch block is not entered, with 0.10.35 the on error callback is called.

**Comment by cjihrig** [comment]
As of b636ba8186d191c52ee36f2f2b1aebbbb4d95575, in the 0.12 branch, the error is thrown synchronously, and can be handled with `try...catch`.
