### ISSUE TITLE
Invalid object

### ISSUE THREAD

**Issue by blakemcbride** [joyent/node#9045]
Assigning an object to an object element containing an array creates an invalid object.  For example:

> x = {}
{}
> x.y = []
[]
> x
{ y: [] }
> x.y.z =5                              ASSIGNMENT
5
> x
{ y: [ z: 5 ] }                            THIS IS WRONG
> JSON.stringify(x,null,4)
'{\n    "y": []\n}'                        DOESN'T AGREE WITH NATIVE DISPLAY OF X
> x.y.length
0

1.  The ASSIGNMENT should either issue a run-time exception, substitute an object for the array, or ignore the assignment (as Rhino does).

2.  The native display of x and the stringify of x should be equivalent.

3.  Because of this error, I was able to create object elements that contained both an array AND several objects at the same time!

Thanks.

Blake McBride

**Comment by cjihrig** [comment]
I don't believe this is an issue (meaning I think it's valid JS). Entering the same sequence of commands in Chrome yields pretty much the same results (with the exception of displaying `{ y: [ z: 5 ] } `).

**Comment by blakemcbride** [comment]
It is a problem because if you persist the object (stringify) and then retrieve it (parse), they don't agree.

Also, debuggers (like WebStorm) see the element as an array with objects stored AFTER the array (rather than inside the array).  While it might be easy to point a finger at WebStorm, the fact that stringify and native display show different things indicated that there is confusion internally.

**Comment by cjihrig** [comment]
It is bad practice to use an array as an object. Also, node does not provide the `JSON.stringify()` and `JSON.parse()` methods - they are provided by v8. You can use `util.inspect()` for your own purposes, as I believe it will include these additional properties.

**Comment by blakemcbride** [comment]
Thanks. Think I am getting it.  Is there a way to parse the string from inspect (since JSON.parse can't)?

**Comment by cjihrig** [comment]
I don't think so. If I'm wrong, someone else feel free to chime in.

**Comment by bjouhier** [comment]
All these behaviors are specified by EcmaScript. If something does not work as specified then it is a V8 bug, not a node bug. But it looks ok to me.

BTW, this is just one of many examples of JSON not roundtripping. Try `JSON.parse(JSON.stringify({ x: undefined }))`.
