### ISSUE TITLE
deps: update openssl to 1.0.1l

### ISSUE THREAD

**Issue by jasnell** [joyent/node#9052]
The openssl dependency needs to be updated. 
This landed previously is io.js here: 
https://github.com/iojs/io.js/commit/eebdf7ac85b36223833330ff7f1057591dcbe651
https://github.com/iojs/io.js/commit/b910613792dac946b295855963869933a9089044
https://github.com/iojs/io.js/commit/ced41b07dd6ebeaceb2a9be1d2bb6376eb7d0db4

I am working on applying this to v0.12. Will submit a PR for review once I'm sure it at least builds and passes the initial sniff-test

There's also this:

https://github.com/iojs/io.js/commit/a76811c811f8e1602181f1c4368370c192adff0c

But it touches a test that currently does not exist in v0.12 (/test-crypto-stream.js)

**Comment by jasnell** [comment]
Ok, located /test-crypto-stream.js ... in io.js it's been moved out of simple.

**Comment by jasnell** [comment]
See: https://github.com/jasnell/node/tree/v0.12-openssl-k

**Comment by misterdjules** [comment]
Thanks @jasnell! 

Usually changes are landed in the most stable or oldest active branch where they apply. In this case it would be v0.10. Moreover, that would be a good candidate to include for the next 0.10 release (0.10.36).

Also, instead of floating the build fix for windows by landing https://github.com/iojs/io.js/commit/ced41b07dd6ebeaceb2a9be1d2bb6376eb7d0db4, we could first land the changes from io.js you mentioned except this one, and then upgrade from OpenSSL 1.0.1k to OpenSSL 1.0.1l which is supposed to include the build fix for Windows.

How does that sound?

**Comment by jasnell** [comment]
Ok... so just so I'm clear: apply the patch to branch v0.10 (without ced41b0) and resubmit?

**Comment by steakknife** [comment]
Latest OpenSSL is 1.0.1l

**Comment by misterdjules** [comment]
@jasnell Yes, and also apply the upgrade from 1.0.1k to 1.0.1l in a separate commit if it actually fixes the Windows build for Node.js and more generally doesn't bring anything in that would potentially break. I haven't looked at the diff, it's possible that the code changes are the same as https://github.com/iojs/io.js/commit/ced41b07dd6ebeaceb2a9be1d2bb6376eb7d0db4.

**Comment by steakknife** [comment]
@jasnell @misterdjules 1.0.1l *[Build fixes for the Windows and OpenVMS platforms](https://www.openssl.org/news/openssl-1.0.1-notes.html)*

**Comment by misterdjules** [comment]
@steakknife Yes, that's why the plan is to upgrade to 1.0.1l. Also, changing the title of this issue so that it reflects that.

**Comment by steakknife** [comment]
@misterdjules :cake: Btw, node security reports compliance@joyent.com / report@nodesecurity.io / https://github.com/joyent/node/issues ?

**Comment by jasnell** [comment]
Upgrade to 1.0.1l on v0.10 is mostly ok except I'm seeing a new build error...

**Comment by jasnell** [comment]
Ok, nevermind the build error, appears to have just been a problem with the way I was merging 1.0.1l in. New pull request: #9056 targeted on v0.10.

**Comment by misterdjules** [comment]
@jasnell @steakknife Thank you! Landed in b28c76e9d265d42934adc7833c77f57c1d80d6eb, deef605085be2dcd76bd2538ec32691e60a5e362, f5e9b6e84a47a6990bd3b44d004026a6f0faaba2 and 9e387fb611e29aad3118e0b226199fdc70bbd0cd.
