### ISSUE TITLE
Checksum files

### ISSUE THREAD

**Issue by mathiask88** [joyent/node#9062]
Hi,

node-gyp is failing checksums for 0.11.14 on windows because in 0.11.14 ```SHASUMS256-win.txt``` and ```SHASUMS-win.txt``` are introduced. Will future releases contain these files too, so that node-gyp needs an update? Then I will create an issue at https://github.com/TooTallNate/node-gyp. It is a bit annoying because AppVeyor fails for latest 0.11 release.

Best regards

//Edit: Example https://ci.appveyor.com/project/mathiask88/node-snap7/build/job/jpusn4v50s6k95kx

**Comment by misterdjules** [comment]
@tjfontaine Could you please look into this? Thanks!

**Comment by mathiask88** [comment]
Files are gone in 0.11.15 so everything is working again. But 0.11.14 will stay broken relating to node-gyp.
