### ISSUE TITLE
Process hangs with specific RegEx and specific string

### ISSUE THREAD

**Issue by TheRealKerni** [joyent/node#9065]
The following code causes the `match` method on a string to never finish:

    var pattern = new RegExp('^\\({1}((0x\\w+).*)*\\){1}','m');
    var stringValue = '(0x1846e5e48 0x194e240e4 0x1846e5acc 0x10074caf8 0x1007d7428 0x1007d6a48 0x1007d4504 0x1007d5e78 0x1007c72d8 0x1007c6ea0 0x10079b6f8 0x1007bdba8 0x1007cc5a4 0x100740bec 0x184439270 0x19546936c 0x1954734c0 0x19546c474 ';
    var testResult = stringValue.match(pattern); // This causes the process to hang forever
    console.log('Done'); // This is never reached

When removing some of the hex addresses (values are random) it will proceed successfully but still take some time.

Not sure if this is a bug in node itself or an underlying component that is used.

**Comment by Mickael-van-der-Beek** [comment]
This looks like a RegExp DDOS:

https://www.owasp.org/index.php/Regular_expression_Denial_of_Service_-_ReDoS

I think that ```((0x\\w+).*)*\\)``` group generates too many possibilities (branches) and thus exhausts your CPU resources.

**Comment by cjihrig** [comment]
Agreed. I had the same web page open and was executing the program. If by some chance it's not a regex DoS, then it would be a v8 issue, not Node. Thanks for reporting this.

**Comment by Mickael-van-der-Beek** [comment]
If you need help with the RegExp itself I could help you but would need to explain what you are trying to achieve and / or maybe open a StackOverflow issue.

**Comment by TheRealKerni** [comment]
Thanks, no need :) Just wanted to make sure this behaviour is reported. I implemented an additional checking to avoid getting into this scenario.
