### ISSUE TITLE
console.timeEnd('hasOwnProperty') fails hilariously

### ISSUE THREAD

**Issue by pluma** [joyent/node#9069]
Because the timers are currently stored as named properties of an object, timers with funny labels will result in `console.timeEnd` dutifully logging `NaNms`.

This affects `hasOwnProperty`, `__proto__` and likely anything else that lives on `Object.prototype`.

A solution would be using ES6 symbols when they land in node.

A workaround would be prefixing the property names with some arbitrary string (except `_`, which would re-create the problem for timers labelled `_proto__`) instead of using the label verbatim.

**Comment by dougwilson** [comment]
Does changing the line at https://github.com/joyent/node/blob/master/lib/console.js#L43 to `prop.value = Object.create(null)` fix it?

**Comment by pluma** [comment]
Nope, because even `Object.create(null)` has the magical `__proto__`.

**Comment by dougwilson** [comment]
Sure, but at most, all you'll get is `Error: No such label: __proto__`. Everything else seems to work fine besides that, right?

**Comment by pluma** [comment]
Yes, that should work with that caveat.

**Comment by cjihrig** [comment]
I have verified that this can be solved with `Object.create(null)`. I'll submit a patch.

**Comment by pluma** [comment]
Indeed. The `__proto__` issue seems to be absent in newer versions of V8 (as in io.js).

**Comment by cjihrig** [comment]
Fixed in 6c3647c38d73f729ce85633a0440cd939d93dea2

**Comment by misterdjules** [comment]
@cjihrig Do we want to leave this issue open, or open another issue to fix this in v0.10?

**Comment by cjihrig** [comment]
@misterdjules I don't think there is a really clean fix for 0.10. I would say either leave as is with the existing few edge cases, or apply this patch, which would leave `__proto__` as the only edge case.

**Comment by misterdjules** [comment]
@cjihrig We could use a different data structure for `_times` to store times. For instance, [it could be an array of `{ label: 'someLabel', time: Date.now() }`](https://gist.github.com/misterdjules/60705983a991e8ed67d4).

I have never used `console.time` and `console.timeEnd` before. As a result, I'm not aware of its uses cases and I'm not sure how such a change would impact performance.

What do you think?

**Comment by cjihrig** [comment]
@misterdjules I think that solution would work. The slight performance hit should be fine since it's a console operation. However, a similar problem exists with event names, and I wouldn't recommend this approach in that code.

I would move the `Date.now()` call in `timeEnd()` before the call to `findTimeWithLabel()` so that you aren't timing the array search.

**Comment by misterdjules** [comment]
@cjihrig Good point, thank you! Created https://github.com/joyent/node/pull/9215.

**Comment by misterdjules** [comment]
Fixed in v0.10 by c8239c0.
