### ISSUE TITLE
Specification for Node.js callback style

### ISSUE THREAD

**Issue by morris** [joyent/node#9082]
Motivated by questions like:

- [Which is a better way of writing callbacks?](http://stackoverflow.com/questions/13965174/which-is-a-better-way-of-writing-callbacks)
- [What is the suggested callback style for Node.js?](http://stackoverflow.com/questions/7116722/what-is-the-suggested-callback-style-for-node-js-libraries)

I figured Node's main callback style might need a spec, so I attempted to write one: [Continuation-Passing Style 1](https://github.com/morris/cps1). I think there are only a few exceptions in Node that don't conform, like http.request. Looking forward to discussing it!

**Comment by cjihrig** [comment]
I think this should be moved to the mailing list or some other forum. The issue tracker is for reporting problems with Node core. If you end up hashing out something, then maybe open a documentation PR.
