### ISSUE TITLE
`node` command line tool does not remember previous inputs

### ISSUE THREAD

**Issue by Domiii** [joyent/node#9083]
A proper command line always remembers inputs from previous runs.

Since things stay cached in Node through-out a single run, if a non-trivial application crashes or while developing, one needs to restart the command line interpreter to discard of broken state. However, once restarted, none of the previous commands are remembered, even though the commands we use might not change a lot between runs, potentially requiring a whole lot of extra typing.

**Comment by misterdjules** [comment]
Do you mean that node's REPL should support a history of command lines in a way similar to a UNIX shell? There's already PR #3178 for that, could you please let us know if that corresponds to what you described?

**Comment by Domiii** [comment]
@misterdjules That sounds just about right! I'm not too familiar with *nix jargon, so I did not know what to search for. Sorry!
