### ISSUE TITLE
fs.readdir and fs.readdirSync is not work like the description on API

### ISSUE THREAD

**Issue by AliTiger** [joyent/node#9089]
The two method above was not wokred like the description when i got data from remote server by http request . it returns an array of files name with suffix.

**Comment by hautlixiaodong** [comment]
it worked when i used it on my local test directory.

**Comment by amir-s** [comment]
Which version are you using?

Can you post your code?

**Comment by hautlixiaodong** [comment]
v0.10.26 



var getConfigByServerName = function(serverName){
    var configNames = [];
    var configNamesWithSuffix = [];

    async.waterfall([
        function(cb){
            http.get('http://192.168.1.268:30000/api/getConfigNameByServer?server='+serverName, function(res) {
                res.on('data',function(data){
                    configNamesWithSuffix = JSON.parse(data) || [];
                });
                res.on('end',function(){
                    console.log('获取配置文件名成功!');
                });
                cb();
            });
        },
        function(cb){
            console.log('configNamesWithSuffix:',configNamesWithSuffix);
            for(var i = 0;i < configNamesWithSuffix.length; i++){
                var index = configNamesWithSuffix[i].indexOf('.')
                var name = configNamesWithSuffix[i].substring(0,index);
                configNames.push(name);
            }
            async.mapSeries(configNames,function(item,call){
                if(fs.existsSync('../game-server/dataConfig/'+item+'.json')){
                    fs.unlinkSync('../game-server/dataConfig/'+item+'.json');
                }
                call();
            },function(err,data){
                cb();
            });
        },
        function(cb){
            async.mapSeries(configNames,function(item,call){
                var file = fs.createWriteStream('../game-server/dataConfig/'+item+'.json');
                http.get('http://192.168.1.268:30000/api/config?name=' + item + '&server='+serverName, function(res) {
                    res.on('data', function(data) {
                        file.write(data);
                    });
                    res.on('end', function() {
                        file.end();
                        call();
                    });
                });
            },function(err,result){
                cb();
            });
        }
    ],function(err,result){
        if(!err){
            console.log('获取配置文件成功!');
        } else{
            console.log(err);
        }
    });
}


console.log result is :+1: 

configNamesWithSuffix: [ 'base.json',,,,,]

**Comment by hautlixiaodong** [comment]
I need to handle the result to get the configNames without suffix.

**Comment by amir-s** [comment]
Did you used `readdirSync` on your server api? Because I didn't see it in your posted code.

And are you expecting `readdirSync` to return a list of file names without their extensions?

Extensions are a part of the file names so `readdirSync` should include them in the names of the files. You need to manually remove the extension from the name if you want, just like you did in your code.

**Comment by hautlixiaodong** [comment]
I`m sorry . I forgot post server code.

app.get('/getConfigNameByServerName',function(req,res){
        var server  = req.param('server');
        var fs = require('fs');
        var path = './data/'+server;
        var configNames = fs.readdirSync(path)  || [] ;
        res.send(200,configNames);
});

fs.readdirSync(path)#
Synchronous readdir(3). Returns an array of filenames excluding '.' and '..'.

The readdirSync method is not the same as descried on API excluding '.' .

**Comment by amir-s** [comment]
Can you post the output of `fs.readdirSync`?

Are you saying that this function does not exclude '.' and '..'?

**Comment by hautlixiaodong** [comment]
I mean it`s different while i use it get from localhost dir and get data from remote server dir.
the output from remote server :      [ 'base.json',['player.json'],,,,,].
the output from localhost :   [ 'base',['player'],,,,,].

**Comment by amir-s** [comment]
Do you run the same version on both sides?

That's odd!
Just to be clear, tell me if I'm wrong.
You have two scripts: one for server and one for client.
When you run your server script on your actual remote server and the client script on your machine, the extension of the files are included in their names.
But when you run both client script and server script on your machine, the names do not have their extensions?

**Comment by hautlixiaodong** [comment]
fs.readdirSync(path)#
Synchronous readdir(3). Returns an array of filenames excluding '.' and '..'.

I think it`s not 'excluding' but 'including'.

I tried on my local computer using fs.readdir and fs.readdirSync method . Returns an array of filenames incluing '.'.

**Comment by jtokoph** [comment]
I think you might be confused by what the documentation means by `.` and `..`.

Normally when you list the contents of a directory it will list all files and folders in the directory as well as two special items `.` and `..`. The single dot represents the current directory and the double dot represents the parent directory. 

The docs are pointing out that this function will not include those two special items in it's response.

For your actual goal, you'll need to iterate through each of the returned files and trim off the file type suffix yourself. You can use [`path.extname`](http://nodejs.org/api/path.html#path_path_extname_p)

**Comment by bjouhier** [comment]
Side note: you should not use `Sync` methods when handling requests. You should use async APIs instead.

**Comment by hautlixiaodong** [comment]
sorry , i was confused by . and ..  . Thank you very much .
