### ISSUE TITLE
A soap non-wsdl connection example

### ISSUE THREAD

**Issue by VictorQueiroz** [joyent/node#9094]
Someone can help me to make a non-wsdl soap connection with node? It is possible? I can do it with PHP and SoapClient(), but no with node and not even with node-soap.

**Comment by misterdjules** [comment]
This issue tracker is used to track bugs in Node.js' core. For more general questions or to get help on how to achieve something with Node.js, please use the [Node.js Google group](https://groups.google.com/forum/#!forum/nodejs). Thank you!
