### ISSUE TITLE
fs.symlinkSync requires admin privileges in Windows with type `junction`

### ISSUE THREAD

**Issue by muratsu** [joyent/node#9101]
Creating a symlink normally requires admin privileges in Windows however creating a `junction` doesn't. This behavior is not reflected on `symlinkSync` method:
```javascript
fs.symlinkSync(pathA, pathB, 'junction');
```
will throw error `Error: EPERM, operation not permitted` whereas
```javascript
exec('mklink /J pathB pathA', /* ... */)
```
will work just fine. 
It is expected to be able to create a `junction` without admin privileges.

**Comment by piscisaureus** [comment]
@muratsu
The EPERM error you're getting probably isn't related to junctions requiring elevation.
What are the actual parameters you are passing to symlink?

**Comment by piscisaureus** [comment]
@muratsu 
There are two known issues with `symlink` in node:
* The docs are wrong (parameters are in the wrong order) (https://github.com/joyent/node/pull/8936)
* When the target path is a relative path it's resolved incorrectly (https://github.com/iojs/io.js/commit/764c5c7fd176c90513406797182cde1d0f24e1cf)

**Comment by muratsu** [comment]
You seem to be right. The code I was using had bad parameters, nothing wrong in the platform.
Closing the issue, thanks!
