### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by coderxlsn** [joyent/node#9106]
My Error
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: read ECONNRESET
    at errnoException (net.js:904:11)
    at TCP.onread (net.js:558:19)
I use
var EventEmitter 	= require('events').EventEmitter;

**Comment by cjihrig** [comment]
Can you please provide more details? For example, the version of Node that you're running, on which operating system, and a self contained piece of code (no external dependencies) that demonstrates that problem.

**Comment by jgdev** [comment]
We are not in stackoverflow, but ... have you tried this ?:

```js
var EventEmitter = require('events').EventEmitter;
EventEmitter.on('error', function(err) {
   console.log(error); // throw exception message.
});
```

**Comment by coderxlsn** [comment]
with this problem figured out. launched 8 threads. now the problem is server load at 100%

**Comment by misterdjules** [comment]
This issue tracker is used to track bugs in node's core. This seems to be a more general issue, and it is not necessarily a bug in node's core. I suggest moving this discussion to StackOverflow or the [Node.js Google group](https://groups.google.com/forum/#!forum/nodejs).

Thank you!
