### ISSUE TITLE
Bug: for loop becomes endless loop in 0.11.15

### ISSUE THREAD

**Issue by freiit** [joyent/node#9113]
The following one-liner runs in an endless loop on 0.11.15.
node --harmony --use-strict -e 'for (let i = 0; i < 3; ++i) { if (i == 1) { continue; } }'

Replace 'let' with 'var' to avoid the bug.

Bug does not show up in 0.11.14.

Tested with a clean docker image, created like this:
FROM node:0.11.15
CMD node --harmony --use-strict -e 'for (let i = 0; i < 3; ++i) { if (i == 1) { continue; } }'

**Comment by cjihrig** [comment]
This is almost certainly related to the v8 3.28.73 update in 0.11.15.

**Comment by trevnorris** [comment]
I bisected as far back as 3.28.10 and the issue still occurred.

**Comment by freiit** [comment]
Can't reproduce that on 0.12.

**Comment by Y--** [comment]
I do reproduce the bug on 0.12.0.

**Comment by Y--** [comment]
FYI, it's fixed in iojs 1.6.1

**Comment by misterdjules** [comment]
Adding to milestone 0.12.3 as it seems it would be fixed by #14411.

**Comment by misterdjules** [comment]
Fixed in 2a5f4bd7ce40b9537c5d77558687858c7246d896 and cb55a05f528f57e350063f618274b5a182261387, thank you!
