### ISSUE TITLE
Float32Array undefined when evaluated in vm.runInNewContext()

### ISSUE THREAD

**Issue by jmm** [joyent/node#9121]
Can someone clue me in as to why `Float32Array` is undefined when referenced in a script executed by `vm.runInNewContext()`? I arrived here while debugging test failures after bumping the [traceur](https://github.com/google/traceur-compiler) version in [es6ify](https://github.com/thlorenz/es6ify).

Given the following:

* Node v0.10.32 on Ubuntu 12

* `Float32Array.js`:

  ```js
  Float32Array;
  ```
  
* `vm-Float32Array.js`:

  ```js
  var
    fs = require('fs'),
    vm = require('vm');

  vm.runInNewContext(
    fs.readFileSync('./Float32Array.js')
  );
  ```

`node ./Float32Array.js` is fine, but `node ./vm-Float32Array.js` results in:

```
/.../vm-Float32Array.js:5
vm.runInNewContext(
   ^
ReferenceError: Float32Array is not defined
    at evalmachine.<anonymous>:1:1
    at Object.<anonymous> (/.../vm-Float32Array.js:5:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by cjihrig** [comment]
This doesn't appear to be an issue in the latest 0.12 code. For older versions, such as 0.10.32, you can try this:

```javascript
require('vm').runInNewContext('new Float32Array()', {
  Float32Array: Float32Array
});
```

**Comment by jmm** [comment]
@cjihrig Thanks for the quick reply and suggestion. That gets the test passing again, so I think that's a viable solution for now.
