### ISSUE TITLE
How event cycle is working ?

### ISSUE THREAD

**Issue by Anubh** [joyent/node#9122]
So guys, I am wondering how the event loop is working ?

If there are so many pending requests in event cycle and for them different different callbacks are waiting, and these requests will never gonna fulfilled then what will happen of these registered callbacks ? Are they going to be ignored or removed from event cycle if yes then when and how ??

Thank you

**Comment by misterdjules** [comment]
This issue tracker is used to track bugs in node's core, not to answer more general questions. I suggest asking this question on StackOverflow or in [the Node.js Google group](https://groups.google.com/forum/#!forum/nodejs), where I'll be happy to discuss this topic.

Thank you!
