### ISSUE TITLE
Protocol-relative urls are not parsed correctly

### ISSUE THREAD

**Issue by jasonkarns** [joyent/node#9123]
```
$ node -v
v0.11.15
$ node
> url = require('url')
> url.parse("//google.com")
{ protocol: null,
  slashes: null,
  auth: null,
  host: null,
  port: null,
  hostname: null,
  hash: null,
  search: null,
  query: null,
  pathname: '//google.com',
  path: '//google.com',
  href: '//google.com' }
```

`host` and `hostname` should be successfully parsed from a protocol-relative URL.

**Comment by jasnell** [comment]
Honestly, without additional information, the url parser is not able to extract that information... To do it right, you first need to resolve against a base:

```javascript
var url = require('url');
var m = url.resolve('https://example.org', '//google.com');
var n = url.parse(m);
console.log(n);
```

**Comment by jasonkarns** [comment]
I might be reading the spec incorrectly, but the parse rules describe the ability to parse the host while leaving scheme relative (or unset).
