### ISSUE TITLE
assert.notEqual doesn't work for NaN

### ISSUE THREAD

**Issue by DinisCruz** [joyent/node#9127]
While debugging https://github.com/o2platform/fluentnode/issues/57 and https://github.com/TeamMentor/TM_4_0_Design/issues/147#issuecomment-71878103, I realised that [assert.notEqual](http://nodejs.org/api/assert.html#assert_assert_notequal_actual_expected_message) does not seem to handle NaN

Is the the expected behaviour?

Here is the test that replicates this behaviour

```coffee
  it.only 'assert.notEqual does not work for NaN',->

    # there are all fine
    (-> assert.notEqual 1, 1         ).assert_Throws (error)-> error.message.assert_Is '1 != 1'
    (-> assert.notEqual 2, 2         ).assert_Throws (error)-> error.message.assert_Is '2 != 2'
    (-> assert.notEqual 'a','a'      ).assert_Throws (error)-> error.message.assert_Is '"a" != "a"'
    (-> assert.notEqual 1,1,'abc'    ).assert_Throws (error)-> error.message.assert_Is 'abc'
    (-> assert.notEqual 'a','a','abc').assert_Throws (error)-> error.message.assert_Is 'abc'
    assert.notEqual 1,2
    assert.notEqual 'a','b'

    #these are the ones that are not working as expected
    nan = NaN
    assert.notEqual NaN,NaN
    assert.notEqual nan,NaN
    assert.notEqual NaN,nan
    assert.notEqual Number('aaa'),Number('aaa')     # Number('aaa') is NaN
    assert.notEqual new Number('aaa').valueOf(),    # new Number('aaa') is NaN
                    new Number('aaa').valueOf()
    assert.notEqual Number('aaa'),NaN
    assert.notEqual NaN, null


    #confiming that multiple ways to get NaN are indeed 'NaN'
    assert.ok(Number('aaa').toString() is new Number('aaa').valueOf().toString())
    assert.ok(Number('aaa').toString() is NaN.toString())
    assert.ok(Number('aaa').toString() is 'NaN')
    assert.ok(NaN.toString()           is 'NaN')
```

**Comment by othiym23** [comment]
By definition, NaN (which is a special value object, like all numbers, that came along for the ride with [the rest of IEEE754](http://en.wikipedia.org/wiki/IEEE_floating_point) when Brendan Eich implemented JavaScript's numeric stack -- it's IEEE754 that specifies that `typeof NaN === "number"`) is not equal to itself (or any other number).

It is basically the numeric form of an exception, and is defined in such a way that it will propagate itself through calculations -- `NaN * 2`, `Infinity / NaN`, `NaN + 1`, and `0 - NaN` all evaluate to `NaN`. In addition, `NaN < NaN`, `NaN > NaN`, and `NaN == NaN` all evaluate to `false`. This is why `isNaN()` is part of the standard definition of JavaScript. Aside from some clever tests (`val > 0 || val < 0 || val != val`), there is no other way to know for sure that a value is NaN (for a similarly fun time, try to figure out how to tell the difference between `0` and `-0` -- IEEE754 prescribes that a negative zero exist, but that the sign be discarded by most ordinary operations).

This is all pretty counterintuitive, but, like many surprising boundary conditions in IEEE754 (see also: `1 / 0 === Infinity && -1 / 0 === -Infinity && Infinity / -Infinity === NaN`) is the result of careful design by people who know way more about numerical methods than most of us. One might make the case that JavaScript really could have stood to have more than just one numeric type (and one would have a point), but this is what we've got, and `assert.notEqual()` and `assert.equal()` are just reporting the facts to you.

**Comment by cjihrig** [comment]
Well said @othiym23.

@DinisCruz for future reference, you are more likely to get help if you post your code samples in JavaScript.

**Comment by DinisCruz** [comment]
@othiym23 thanks for such a great answer 

@cjihrig point taken
