### ISSUE TITLE
Is anybody use shard mongodb in nodejs? Im in trouble, pls HELP!

### ISSUE THREAD

**Issue by wanzhou** [joyent/node#9135]
I want to save the data into mongodb by a nodejs web server.
It can work well before I deploy the mongodb as a distribution. After that, it can't insert data by storage process in nodejs, and also can't work by exec `db.eval("storage process")`. Insert data in cmd `mongo` by `db.collectionName.insert(obj)` do well!

**pls forgive me for my bad english**

**Comment by OrangeDog** [comment]
You probably should take this to the mailing list.
