### ISSUE TITLE
API Docs missing Date class

### ISSUE THREAD

**Issue by AnmAtAnm** [joyent/node#9136]
The API docs at http://nodejs.org/api/ do describe the included Date class and its methods. This is frustrating when it differentiates from the Date object available in/documented for browsers, such as the missing Date.UTC() function.

**Comment by micnic** [comment]
`Date.UTC()` is not part of the Node core, it's part of the EcmaScript Standard, and it is accessible in Node, what is the issue exactly?

**Comment by cjihrig** [comment]
Yes, the Node docs don't describe standard features of the language.
