### ISSUE TITLE
fs.write with string has missed position

### ISSUE THREAD

**Issue by pepagos** [joyent/node#9140]
In fs.write call to writeString is

return binding.writeString(fd, buffer, offset, length, req);

but I think it should be

return binding.writeString(fd, buffer, offset, length, position, req);

**Comment by cjihrig** [comment]
@pepagos Is there a specific bug that you can reproduce? The C++ layer seems to rely on the 5th argument being an object in the asynchronous case.

**Comment by pepagos** [comment]
Nope.
I was misled by the corresponding call at writeSync:
  binding.writeString(fd, buffer, offset, length, position);
I didn't realize that at that call position is always undefined because of the calling conventions for strings.
Sorry for the inconvenience caused.
