### ISSUE TITLE
Windows 7: Asynchronos callback (After_cb) gets NULL as parameter for uv_work_t* object

### ISSUE THREAD

**Issue by pvenkatraman** [joyent/node#9142]
uv_queue_work ( uv_default_loop(), &req, async_cb1, async_cb2)

the req is allocated and filled-in and when the control reaches async_cb1 () the value is good, and when it reaches async_cb2() the value is NULL.

I tried adding extra parameter "int status" and the status value is always non-zero and different value on each run.

This only happens on Windows + node.0.10.28 & node.0.10.35 environment.

Any suggestion or workaround?

Thanks,
-P. Venkatraman.

**Comment by trevnorris** [comment]
@pvenkatraman Could you provide a little more code context? Also, it might be helpful to file this in https://github.com/libuv/libuv/issues.

**Comment by pvenkatraman** [comment]
Trevor

Fixed my code bug.
async_after_cb() return type should be void, by mistake had it as Handle<Value>.
This breaks only on Windows and works good on all other platforms.
Thanks,
