### ISSUE TITLE
Add installation documentation.

### ISSUE THREAD

**Issue by barrystaes** [joyent/node#9143]
As a new and experimenting Node.JS user, i have installed Node on various ways on various platforms. And sadly found out that its easy to install it wrong.. (wrong permissions, locally, via npm)

Please add documentation to the nodejs release (and/or website) that tells me what i just downloaded from http://nodejs.org , and what to do with the .tar.gz file after i downloaded it. (in contrast, for Windows its a compiled binary) The least of documentation would help.

So far, i think this is what is required on my Debian derived Linux distribution: (CrunchBang #!)

```
$ # Install prerequisites:
$ sudo apt-get update
$ sudo apt-get install git-core curl build-essential openssl libssl-dev

$ # Download, unpack and move:
$ cd ~/downloads
$ curl -L http://nodejs.org/dist/v0.10.36/node-v0.10.36.tar.gz
$ tar xvfz node-v0.10.36.tar.gz
$ sudo mv node-v0.10.36 /opt/

$ # Build from source:
$ cd /opt/node-v0.10.36
$ ./configure
$ make
$ sudo make install

$ # Is it now available globally?
$ cd ~
$ node -v
```

I'm admittedly a novice, i think its installed in the /opt/ folder now and available globally but not sure.
I hope the least of install documentation is not out of the scope of this project.

**Comment by jasnell** [comment]
Deferring to the docs wg effort - https://github.com/nodejs/docs
