### ISSUE TITLE
segmentation fault  node --harmony-generators index.js

### ISSUE THREAD

**Issue by bolasblack** [joyent/node#9144]
I just installed node v0.11.16 by homebrew, and I'm using OS X 10.10.2.

When I use command `node --harmony-generators index.js` to execute my code, node will print an error like issue title.

The file content:

```javascript
// Generated by CoffeeScript 1.9.0
(function() {
  var app, cutWord, jieba, koa, rive;

  jieba = require('nodejieba');

  rive = require('rivescript');

  koa = require('koa');

  jieba.loadDict(
    "./node_modules/nodejieba/dict/jieba.dict.utf8",
    "./node_modules/nodejieba/dict/hmm_model.utf8",
    "./node_modules/nodejieba/dict/user.dict.utf8"
  );

  cutWord = function(input, callback) {
    return jieba.queryCut(input, (function(_this) {
      return function(wordList) {
        return callback(null, wordList.join(' '));
      };
    })(this));
  };

  app = koa();

  app.use(function*() {
    return this.body = (yield cutWord(this.request.query.input));
  });

  app.listen(3000);

}).call(this);
```

**Comment by cjihrig** [comment]
@bolasblack can you please add a test case that doesn't have any external dependencies, such as koa. It's also worth mentioning that since generators are hidden behind a flag, there is a chance that they might not be ready for use.

**Comment by bolasblack** [comment]
@cjihrig After test I found maybe it is a bug of package node-jieba, sorry for my precipitance.
