### ISSUE TITLE
install on rhel 5.5 not working

### ISSUE THREAD

**Issue by trevor-pierce** [joyent/node#9145]
I receive the following message when trying to install via "curl -kL https://rpm.nodesource.com/setup | bash -": "Your distribution, identified as "redhat-release-5Server-5.5.0.2", is not currently supported". What can be done to fix this? Is a newer version of rhel5 supported?
Thanks

**Comment by chorrell** [comment]
I think this issue should probably be raised here?

https://github.com/nodesource/distributions
