### ISSUE TITLE
nodejs program on mac works, fails on linux

### ISSUE THREAD

**Issue by flareofghast** [joyent/node#9150]
node version : v0.10.36
package.json : 
{
  "dependencies": {
    "async": "^0.9.0",
    "chokidar": "^1.0.0-rc3",
    "express": "^4.11.2",
    "fs-extra": "^0.16.3",
    "ini": "^1.3.2",
    "introspect": "0.0.3",
    "node-uuid": "^1.4.2",
    "socket.io": "^1.3.3",
    "tail": "^0.4.0"
  }
}

on OSX 10.10.2 works fine.
on Ubuntu 14.04.1 it fails with error

path.js:360
        throw new TypeError('Arguments to path.join must be strings');
              ^
TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    at Object.exports.join (path.js:358:36)
    at new mineos.mc (/home/peter/Dev/mineos-node/mineos.js:95:15)
    at track_server (/home/peter/Dev/mineos-node/server.js:39:20)
    at EventEmitter.<anonymous> (/home/peter/Dev/mineos-node/server.js:27:11)
    at EventEmitter.emit (events.js:98:17)
    at EventEmitter.<anonymous> (/home/peter/Dev/mineos-node/node_modules/chokidar/lib/index.js:132:15)
    at EventEmitter.FSWatcher._emit (/home/peter/Dev/mineos-node/node_modules/chokidar/lib/index.js:145:5)
    at EventEmitter.NodeFsHandler._handleDir (/home/peter/Dev/mineos-node/node_modules/chokidar/lib/nodefs-handler.js:331:10)

is there a format difference or something I should be aware of?

**Comment by gepatto** [comment]
I tried v0.10.36 on a raspberry pi 2 (armv7) using the latest raspbian, and it doesn't work either.
It only throws "Unhandled prefetch abort: ... " errors.
v0.11.16 does seem to work..

**Comment by cjihrig** [comment]
Can you please post some code that reproduces the issue and doesn't have any external dependencies.

**Comment by gepatto** [comment]
I had a fresh install of raspbian  2015-01-31 on the raspberry pi 2.
I grabbed the source code http://nodejs.org/dist/v0.10.36/node-v0.10.36.tar.gz
extracted, did configure , make, and sudo make install  (this all went just fine, just takes a while)
made a new dir and did
`npm install express --save`
this spits out a lot of lines, and ends with Unhandled prefetch abort: ...
If I remember correctly even
`npm init` 
fails

Just a simple
`Console.log("Hello World");`
does work.

I'm getting a new SD-card today so I can test the different versions along side..
Right now I'm testing 0.11.16

So I'll do some more testing on 10.36 in a couple of hours when I have the extra sd-card

**Comment by gepatto** [comment]
ok I'm sorry,
I'm trying 0.10.36 again and so far it's just
`npm install any_module`
that is throwing the errors.   
I have tried the modules: forever, underscore express [ see https://db.tt/bK9gMXvr for logs ]
I also tried:
`sudo npm -g install npm@latest`
but I still get the errors.

So scripts without any external modules run just fine.

**Comment by cjihrig** [comment]
If the install is the problem, you might want to try npm issue tracker.

**Comment by gepatto** [comment]
Ok, will try that. Thnx

**Comment by flareofghast** [comment]
Sorry I got side tracked  from this and I don't believe I need this any longer.
