### ISSUE TITLE
Module loaded corrupted when using same filenames

### ISSUE THREAD

**Issue by ladariha** [joyent/node#9166]
Please check the project [1] and extract it:

```
$ cd tripplanner-master/server
$ npm install
$ node server.js
```

now make HTTP DELETE request (using CURL or some other tool) to URL 

```
http://localhost:13131/api/tripDay/4124324/3121321
```

and you can see that the Node's output in console contains

```[TypeError: undefined is not a function]```

The problem is in file ```tripplanner-master/server/tripDay/controller.js``` on line 10:

```
console.log(typeof trrr.getEditorsId);
```

The ```trrr``` module is loaded via ```var trrr = require("../trip/controller");```. The problem seems to be caused by having the same filename for 2 modules: ```tripplanner-master/server/tripDay/controller.js``` and ```tripplanner-master/server/trip/controller.js```. If I rename ```tripplanner-master/server/tripDay/controller.js``` to e.g. ```tripplanner-master/server/tripDay/sample.js``` (and change the require() call in ```tripplanner-master/server/api/tripDay.js```, line 10) , it works just fine. 

Interesting (for me) is that in both cases, the ```trrr``` variable is object, so the module is somehow loaded, it is "just" missing any exported properties/methods.

Thanks

[1] https://drive.google.com/file/d/0B6Sd5ov8j7IUSEE4Q2ROaHNseFU/view?usp=sharing

Ubuntu 14.04 32b
Node.js v0.12.0

**Comment by misterdjules** [comment]
It seems that some of the modules in your application have circular dependencies. For instance, `trip/controller.js` requires `tripday/controllers.js`, which itself requires `trip/controller.js`. You can find more info on how to handle circular dependencies in [the documentation](http://nodejs.org/api/modules.html#modules_cycles).

Closing this issue for now, but please let me know if you need anything else.

**Comment by ladariha** [comment]
Mea culpa, I haven't realized that and it confused me that it "worked" with renamed file. You are right of course. I'm sorry for this false issue. Thank you
