### ISSUE TITLE
Debug option and express extremely slow to load - debugging unusable

### ISSUE THREAD

**Issue by askhogan** [joyent/node#9177]
I switched to .12 expecting speed gains, but what I have found is that my development workflow is not workable.  Each restart is taking 5-10 minutes.  On .10 it was slow, but maybe 20 seconds.

**Comment by askhogan** [comment]
#9125

**Comment by misterdjules** [comment]
Thank you for reporting this issue @askhogan :+1: , closing as a duplicate of #9125.
