### ISSUE TITLE
EventEmitter listenerCount undocumented

### ISSUE THREAD

**Issue by smfreegard** [joyent/node#9183]
Is there a reason that EventEmitter.listenerCount() is undocumented?

We have a SIGTERM handler that is added at start-up that cleans-up and runs process.exit() but we have plugins that are loaded after this signal handler is created that themselves need to run some clean-up when SIGTERM is received (in this case to kill some child_processes via child_process.kill() so they don't persist after the process terminates).

As there's no way to specify that you want the listener push()'ed or shift()'ed on to the listeners array, the only way to handle this that I could come up with was like this:

`````
process.on('SIGTERM', function () {
     // do clean-up

    if (process.EventEmitter.listenerCount(process, 'SIGTERM') === 1) {
        process.exit();
    }

    // We have other listeners registered, let them run before we exit
    process.on('SIGTERM', function () {
        process.exit();
    }
}
````

**Comment by cjihrig** [comment]
Unless I misunderstand the question, it is documented [here](http://nodejs.org/api/events.html#events_class_method_eventemitter_listenercount_emitter_event).
