### ISSUE TITLE
Docs for "Tracing" missing

### ISSUE THREAD

**Issue by bradisbell** [joyent/node#9186]
The link to "Tracing" on http://nodejs.org/api/ points to http://nodejs.org/api/tracing.html, which results in a 404.

**Comment by KenanY** [comment]
https://github.com/joyent/node/pull/9172?

**Comment by bradisbell** [comment]
Thanks @KenanY.  I searched for it but didn't find it for some reason.  Closing as this is a duplicate of https://github.com/joyent/node/pull/9172.
