### ISSUE TITLE
Requesting guidance on accepted unit test failures when building Node from source

### ISSUE THREAD

**Issue by unphased** [joyent/node#9189]
I have seen this for a long time now, where on Linux environments I always get a few of the tests failing. 

What I am having a difficult time with is determining the severity of this. I can't figure out if this is actually expected. Looks like most folks don't bother to compile node from source, and when they do, they pretty much never bother running the unit tests. Well, that makes me... not most folks. 

```
$ make test
make -C out BUILDTYPE=Release V=1
make[1]: Entering directory `/home/centos/build/node/out'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/centos/build/node/out'
ln -fs out/Release/node node
/usr/bin/python tools/test.py --mode=release simple message
=== release test-child-process-fork-dgram ===
Path: simple/test-child-process-fork-dgram
Command: out/Release/node /home/centos/build/node/test/simple/test-child-process-fork-dgram.js
--- TIMEOUT ---
=== release test-cluster-dgram-1 ===
Path: simple/test-cluster-dgram-1
master sent 40 packets
Command: out/Release/node /home/centos/build/node/test/simple/test-cluster-dgram-1.js
--- TIMEOUT ---
=== release test-debugger-client ===
Path: simple/test-debugger-client
got stderr data "debugger listening on port 13683\n"
>>> connecting...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect ECONNREFUSED
    at errnoException (net.js:905:11)
    at Object.afterConnect [as oncomplete] (net.js:896:19)
Command: out/Release/node /home/centos/build/node/test/simple/test-debugger-client.js
=== release test-http-many-keep-alive-connections ===
Path: simple/test-http-many-keep-alive-connections
Command: out/Release/node /home/centos/build/node/test/simple/test-http-many-keep-alive-connections.js
--- TIMEOUT ---
[04:25|% 100|+ 632|-   4]: Done
make: *** [test] Error 1
```

So I've seen this 4 failing tests result several times now and this latest one is on Centos 7 on a fresh and brand spankin' new t2.micro AWS instance. 

If these 4 tests are not actually important then can they just, oh i dunno, get removed from the test suite?

**Comment by mhdawson** [comment]
Which version of Node was this ?

**Comment by unphased** [comment]
Hmmm I should have included that. It was 0.10.36 I believe. But if these tests weren't removed, I'm sure they still fail.

**Comment by mhdawson** [comment]
Any chance you could see if they are failing in 0.12.2, there was a push to get all tests passing for the 0.12.0 release and there have been a number of changes contributed to fix tests since 0.12.0 as well.

**Comment by unphased** [comment]
Tell ya what, if you are pretty sure that this is resolved in 0.12, then I will close this (and if I encounter the issue again I will come back and re-open).

**Comment by mhdawson** [comment]
My understanding is that all tests passed for 0.12.0 at release (although that does not mean they are not intermittent).  In my internal build environment (at IBM) the tests are passing consistently on our linux machines (ubuntu 14, sles, rhel) were I checked about 30 runs and did not see instances of those specific failures.

**Comment by unphased** [comment]
Ok. I'll close...

Did you test 0.10.36? and get something similar to what I saw?
