### ISSUE TITLE
`fs.readlink` throw `EINVAL` error when file is not a symlink

### ISSUE THREAD

**Issue by zhiyelee** [joyent/node#9191]
Currently, `fs.readlink` will throw an `EINVAL` error when called with file which is not a symlink.

```  
var fs = require('fs');
fs.readlink(__filename, function(e, p) {
    console.log(e)
});
```

output

```
{ [Error: EINVAL, readlink '/home/lizhiye/dev/tmp/t.js']
  errno: -22,
  code: 'EINVAL',
  path: '/home/lizhiye/dev/tmp/t.js' }
```

I think return the file path itself or `-1` is much better. Or at least, we can declare in the docs that the function will throw an error when called with a file not a symlink.

```
✍ node -v
v0.11.14
```

**Comment by cjihrig** [comment]
This code does not throw. An error is passed to the callback function, specifying why the operation failed. This is standard operating procedure throughout Node. Returning -1 isn't really helpful, and you already have the file path since you passed it in.

**Comment by zhiyelee** [comment]
thanks @cjihrig
