### ISSUE TITLE
node module not loading after upgrade to v0.12

### ISSUE THREAD

**Issue by barrettr5** [joyent/node#9192]
I am trying to develop a .node addon module for zeromq.  It had been loading (but not working).  After upgrading the module "could not be found".  Uninstalled v0.12 and re-installed v.10.21.  At least now the module is found and will load again.

**Comment by CGavrila** [comment]
I am not familiar with zeromq, and this might sound like a silly question, but did you recompile for v0.12? There are breaking API changes in V8 which might make your add-on behave like you described. In case that's the problem, you could use [Nan](https://github.com/rvagg/nan).

Of course, I'm just guessing here. You have to provide more details for anyone to have a chance of helping.

**Comment by barrettr5** [comment]
Yes, I recompiled with v0.12.  The code I am using does use Nan, and I did get the latest update.  I also tried to get the latest version of V8 by updating node-gyp, but may not have.  I am using Windows 2008 R2 server, Visual C++ 2012, x64, and Unicode.  The code did compile and link to a .node module, but when I tried to require the module in js it failed to load.  It does load under v.10.21 (but still does not work).  I have posted a zeromq issue to try to resolve that problem.

**Comment by CGavrila** [comment]
Do you happen to have the add-on in a public repository? I could try compiling and running it.

Anyway, do you get any error when requiring it or does it fail silently? Did you try debugging it (at least some simple output messages)?

**Comment by barrettr5** [comment]
Sorry for the delay, problems getting started with github.  I now have a public repository with the code, zeromq-node.  The main program is binding.cc.  The js script stopped immediately on the require with the message "could not be found".  Re-installing v0.10.21 and using the same script allowed the node module to be loaded.  I got the same result using node-debug.

**Comment by jasnell** [comment]
Closing. Does not appear to be an issue in node. Can reopen if necessary
