### ISSUE TITLE
freebsd error resolved adres

### ISSUE THREAD

**Issue by coderxlsn** [joyent/node#9204]
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: getaddrinfo EAI_BADFLAGS
    at Object.exports._errnoException (util.js:746:11)
    at errnoException (dns.js:49:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)

node v.0.12
freebsd v.10

**Comment by cjihrig** [comment]
https://github.com/iojs/io.js/commit/04bea9f9c224d9f863f671a1ad52a3f392b292cb needs to be ported over.

**Comment by coderxlsn** [comment]
how to move?

**Comment by coderxlsn** [comment]
fix. install io.js 1.1.0

**Comment by misterdjules** [comment]
Reopening, as this issue hasn't been fixed in joyent/node.

**Comment by pct** [comment]
Hi, the io.js patch worked! Please see and try the patch on your freebsd ports https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=197539

**Comment by misterdjules** [comment]
Fixed by #18204.

**Comment by misterdjules** [comment]
Also downgrading to P-2 as I believe this is fixed in FreeBSD's ports.

**Comment by misterdjules** [comment]
Fixed by 0e392f3.
