### ISSUE TITLE
MDB ::jsstack doesn't work on Linux cores

### ISSUE THREAD

**Issue by yunong** [joyent/node#9214]
Hi,

I'm really enjoying the ability to post mortem Linux Node.JS cores. All of the features work as expected, except for ::jsstack.

Any chance this will be added in an upcoming release?

**Comment by bprodoehl** [comment]
@yunong I have a few questions.  What Linux distro are you running, how are you installing Node, how are you generating your core dumps, and how are you opening them with mdb? Are you feeding them into Manta?

**Comment by yunong** [comment]
@bprodoehl here's the version of linux we're using ```Linux shakti-prod-i-1548abe5 3.2.0-74-virtual #109-Ubuntu SMP Tue Dec 9 17:04:48 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux```

I am generating core dumps with gdb's gcore.

 I am running mdb like so
```bash
$ export LD_PRELOAD_64=~/libproc-update.so
[root@272d6f3f-0242-4ac6-ee09-81bd972f6ae2 ~]# mdb ./binaries/node core.7431
mdb: warning: librtld_db failed to initialize; shared library information will not be available
> ::load ./v8.so
V8 version: 3.14.5.9
Autoconfigured V8 support from target
C++ symbol demangling enabled
> ::jsprint
> ::jsstack
>
```

**Comment by bprodoehl** [comment]
Is this on Manta, or just your own Smart Machine?  If I run a default manta interactive compute session (mlogin with no args aside from my core tarball), I can read in Linux coredumps from the 0.12.0 binaries on nodejs.org without doing anything special with libproc or v8.so, and ::jsstack appears to work.  I agree that its confusing, though.  Where did you get your libproc-update.so and v8.so?

I think this blog post needs a refresh to strip out the bits about pulling the special libproc64.so: https://www.joyent.com/blog/mdb-and-linux

**Comment by yunong** [comment]
This is on a smartmachine in the Joyent Public Cloud. I got libproc-update.so from @tjfontaine sometime ago, and v8.so was from the v0.12 build of node. I will try and provision a new joyent smart machine and see if this is fixed in the new smartos platform.

**Comment by yunong** [comment]
Okay, I ran this on a later smartos platform and I can indeed see stacks. Thanks @bprodoehl

**Comment by bprodoehl** [comment]
Glad to hear it!  I'm seeing enough odd things that I think are worth a ticket or two here, but honestly I'm still sifting through what's to be expected, what's me misunderstanding things, and what is actually a bug in mdb grokking Linux coredumps.  For example, ::jsprint seems to have a lot of trouble with even simple objects, where it will get all the keys right, but the values, which are just strings, are all of "unknown type".  And I have yet to see it resolve a reference to anything.  Everything I look up seems to be referenced by nobody.

**Comment by yunong** [comment]
I've seen that a lot too. I have been able to find objects by reference,
but many javascript objects are not printable, which is annoying.

**Comment by ortegag** [comment]
Hi, I'm also trying to debug a linux dump generated using gcore (AWS linux) following https://www.joyent.com/blog/mdb-and-linux, and I think I'm missing something with the libproc lib...

I'm running my own SmartOS (I don't want to use Mantra)
SunOS 5.11 joyent_20150514T133314Z i86pc i386 i86pc

Where can I get a updated/patched libproc.so?

So far, I'm getting this output from mdb

mdb: warning: librtld_db failed to initialize; shared library information will not be available
Loading modules: [ ld.so.1 ]
> ::load v8
mdb: failed to determine V8 version: no mapping for address

**Comment by bprodoehl** [comment]
I would suggest compiling Node from source on your SmartOS (0.12.3, I guess) and use the resulting mdb_v8.so from there.  Then run ```::load /path/to/your/mdb_v8.so``` instead of ```::load v8```

Even if you're running Node 0.10.x, or whatever, I'd suggest using the latest mdb_v8.so.

**Comment by ortegag** [comment]
Tried, no luck :(

./node -v
v0.12.3

mdb core.19415 
mdb: warning: librtld_db failed to initialize; shared library information will not be available
Loading modules: [ ld.so.1 ]
> ::load ./mdb_v8.so
mdb: failed to determine V8 version: no mapping for address

**Comment by yunong** [comment]
@jclulow @davepacheco Maybe you can shed some light on why this is failing for @ortegag

**Comment by bprodoehl** [comment]
@ortegag are you definitely passing it the same node binary that generated the core file? You can use a newer mdb_v8.so, but you have to make sure that mdb is looking at the same binary that generated the core.

**Comment by kelapure** [comment]
I have tried multiple times to get the mdb debugger working with core dumps generated on linux to no avail. _The  tooling around reading linux Node.js cores are broken._

**root@ip-10-152-178-106.ec2.internal:/root/dmp# mdb node-v0.12.7-linux-x64/bin/node node.0.core**

```
mdb: warning: librtld_db failed to initialize; shared library information will not be available

> ::load /root/dmp/mdb_v8_amd64.so
mdb_v8 version: 1.1.1 (release, from 28cedf2)
mdb: failed to determine V8 version: no mapping for address

> ::jsstack
native: _ZN2v88internal7Isolate13IsErrorObjectENS0_6HandleINS0_6ObjectEE...
native: _ZN2v88internal2IC19UpdatePolymorphicICENS0_6HandleINS0_4NameEEE...
native: _ZN2v88internal16HStoreNamedField20HasOutOfBoundsAccessEi+0x21
        (1 internal frame elided)
```

What could i be doing wrong ? The latest mdb_V8 module released is 1.1.2 from November 2015. I even tried building from the master and loading it to no avail. Can someone please illustrate how to do this with a simple instructions.

**Comment by davepacheco** [comment]
@kelapure How was that core file generated?  Can you make it available for someone to take a look?

**Comment by kelapure** [comment]
@davepacheco  I am on vacation today. I will upload the cores, the node.js runtime and the mdb_v8.so tonight
