### ISSUE TITLE
how to get system locale?

### ISSUE THREAD

**Issue by luckydrq** [joyent/node#9221]
Is there an api in node for retrieving system(default) locale info? Other language such as `java` does have a way to do so which is something like `java.util.Locale.getDefault()`.  

According to issue [#4689](https://github.com/joyent/node/issues/4689), it seems that node needs to bundle [v8-i18n](https://code.google.com/p/v8-i18n/) to provide such a way. BUT that would make node [become too massive](https://github.com/joyent/node/issues/4689#issuecomment-12935544). Is it a reason or do i miss something?

**Comment by sindresorhus** [comment]
I made a module for this: https://github.com/sindresorhus/os-locale

**Comment by srl295** [comment]
v0.12 already includes `i18n` on by default in binaries. `v8-i18n` is obsolete (merged into v8). See #7676 or more importantly the wiki.

Will update more.

**Comment by luckydrq** [comment]
@sindresorhus i will use it, thanks!

**Comment by luckydrq** [comment]
@srl295 roger that, thanks!
