### ISSUE TITLE
 Node.js express project application terminated

### ISSUE THREAD

**Issue by hanifarahman5** [joyent/node#9226]
When i run my node.js express project application file, the file does not run and gets terminated.
![untitled](https://cloud.githubusercontent.com/assets/10931874/6210075/d878de04-b580-11e4-8f30-3080690bdf8f.png)

**Comment by hanifarahman5** [comment]
#console #5172

**Comment by xXxRazielxXx** [comment]
I have the same problem no matter what version of java or nodeclipse i got 
It works fine from Command line though

**Comment by misterdjules** [comment]
It is not clear from the screenshot and the description provided that it's a bug in Node.js. Is there a way to access some logs that show why and how node terminated? Also, what version of Node.js did you use? If you used node v0.12.0, did you try with node v0.10.36?

Thank you!

**Comment by jasnell** [comment]
closing for lack of detail and activity
