### ISSUE TITLE
pfiles against a linux node core file doesn't work

### ISSUE THREAD

**Issue by geek** [joyent/node#9230]
I am likely missing a required parameter... but if I run `pfiles corefilename` where the corefile was created on linux, I get `pfiles: cannot examine corefile`.  Please note that this same core file can be loaded in mdb.

/cc @davepacheco

**Comment by davepacheco** [comment]
Sorry for the issue.  It's not related to Node per se, though.  It should be filed against https://github.com/joyent/illumos-joyent/issues.  (Is there a way for me to move this issue?)

**Comment by davepacheco** [comment]
CC @tjfontaine @rmustacc

**Comment by rmustacc** [comment]
@geek would it be possible to provide your specific core file? Unfortunately, in this case all we can really do is improve the error message here. The Linux kernel core file format doesn't actually include information about open file descriptors so unfortunately, there will not be any information for pfiles to show.

**Comment by geek** [comment]
@rmustacc honestly, I would rather you all not fix this... knowing that it can't be fixed for linux core files is good enough for me.  

What about on FreeBSD, will the core be able to work with pfiles?

**Comment by rmustacc** [comment]
illumos doesn't have support for understanding FreeBSD core files. I don't have a FreeBSD system handy to look at its elf notes; however, it appears that it does have some kind of file descriptor section that gets included in gcore(), so it seems theoretically possible if the illumos work was done.

**Comment by misterdjules** [comment]
Closing this issue as it seems it is not related to node itself.

@davepacheco The closest thing to a GitHub issue mover I'm aware of is https://github-issue-mover.appspot.com.

**Comment by geek** [comment]
@rmustacc or @davepacheco do you all have a AppCrash script tailored for node.js on SmartOS?  http://www.oracle.com/technetwork/server-storage/solaris10/app-crash-142906.html
