### ISSUE TITLE
http.get() returning null on some fields on json request

### ISSUE THREAD

**Issue by onewithhammer** [joyent/node#9233]
Here is a simple node program to request data from a GET request.

On several of the fields, the data is returned as <b>'null'</b> but when I do the same using curl
the data is present.

The data is also present when calling from a browser.

Here is a small sample of the data from the program below.

Notice the <b>thumbnailURL</b> and <b>productCount</b> field are null.

Data:{"errorReference":null,"data":[{"sortOrder":1,<b>"thumbnailURL":null</b>,"subcategories":[{"sortOrder":1,"categoryId":1,"subcategoryId":3,"subcategoryName":"Balloon Rides"},{"sortOrder":2,"categoryId":1,"subcategoryId":121,"subcategoryName":"Inter-Island Flights"},{"sortOrder":3,"categoryId":1,"subcategoryId":2,"subcategoryName":"Helicopter Tours"},{"sortOrder":4,"categoryId":1,"subcategoryId":1,"subcategoryName":"Air Tours"}],<b>"productCount":null</b>,"groupName":"Air, Helicopter & Balloon Tours","id":1}

Here is a small sample of the data using curlL

Notice the <b>thumbnailURL</b> and <b>productCount</b> field are populated.

curl -i -X GET -H "Accept: application/json" "http://prelive.viatorapi.viator.com/service/taxonomy/categories?destId=671&apiKey=XXXXXXXXXX"
HTTP/1.1 200 OK
Date: Tue, 17 Feb 2015 00:58:45 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Server: Viator Secure Web Server 1.0

{"errorReference":null,"data":[{"sortOrder":1,<b>"thumbnailURL":"http://cache.graphicslib.viator.com/graphicslib-prelive/thumbs154x109/5069/SITours/west-maui-and-molokai-exclusive-45-minute-helicopter-tour-in-maui-39823.jpg"</b>,"subcategories":[{"sortOrder":1,"categoryId":1,"subcategoryId":2,"subcategoryName":"Helicopter Tours"},{"sortOrder":2,"categoryId":1,"subcategoryId":121,"subcategoryName":"Inter-Island Flights"}],<b>"productCount":10</b>,"groupName":"Air, Helicopter & Balloon Tours","id":1}

From Browser:

{"errorReference":null,"data":[{"sortOrder":1,<b>"thumbnailURL":"http://cache.graphicslib.viator.com/graphicslib-prelive/thumbs154x109/5069/SITours/west-maui-and-molokai-exclusive-45-minute-helicopter-tour-in-maui-39823.jpg"</b>,"subcategories":[{"sortOrder":1,"categoryId":1,"subcategoryId":2,"subcategoryName":"Helicopter Tours"},{"sortOrder":2,"categoryId":1,"subcategoryId":121,"subcategoryName":"Inter-Island Flights"}],<b>"productCount":10</b>,"groupName":"Air, Helicopter & Balloon Tours","id":1}

Is this a BUG?

#node -v
#v0.10.36

```
var http = require('http');
var options = {
    host: 'prelive.viatorapi.viator.com',
    port: 80,
    path: '/service/taxonomy/categories?apiKey=XXXXXXXXXX&destID=671',
    headers : { 'Accept': 'application/json' }
  };
var req = http.get(options, function(response) {
  // handle the response
  var res_data = '';
  response.on('data', function(chunk) {
    console.log("Chunk:" + chunk + "\n");
    res_data += chunk;
  });
  response.on('end', function() {
    console.log("Data:" + res_data);
  });
});
req.on('error', function(e) {
  console.log("Got error: " + e.message);
});
```

**Comment by meandmycode** [comment]
Can't see how this is anything to do with node, undefined maybe but not null. And you are only buffering a string not parsing it so it's hard to see how node would manage this.

I'm thing to guess that the requests actually aren't equivalent, could even be that the API is user agent sniffing.

Try running something like fiddler and watching your node request compared to the browsers and see where they differ.

Fiddler even let's you modify and replay requests so you could change headers etc until you find what triggers the behavior change.

**Comment by onewithhammer** [comment]
The company who provides the API also has a test web site where you can call the APIs.

I used the Web Developer tools in Firefox on this test web site to look at the request / response.

I tried to pass in the same headers but I could never get it to return the fields with data, this is when I tried to use <b>curl</b>.

When <b>curl</b> worked with only "Accept: application/json" set in the headers I was baffled and thought this might be a bug.

When using POST method on the same company's API - all data is returned correct with just "Accept: application/json" set in the header...

I will continue to play with the request headers and I will contact the company to see if they can help.
