### ISSUE TITLE
Backport SNICallback callback to v0.10.x

### ISSUE THREAD

**Issue by coolaj86** [joyent/node#9236]
## UPDATE: Partial Shim / Workaround

```javascript
  function addSniWorkaroundCallback() {
      //SNICallback is passed the domain name, see NodeJS docs on TLS
      secureOpts.SNICallback = function (domainname, cb) {
        console.log('[log] SNI:', domainname);

        var secureContext = secureContexts[domainname]
          || loadCerts(domainname)
          || secureContexts.dummy
          //|| createSecureContext(dummyCerts)
          //|| createSecureContext(loadDummyCerts())
          ;

        if (!secureContext) {
          secureContext = createSecureContext(loadDummyCerts());
        }

        console.log('[log]', secureContext);

        // workaround for v0.12 / v1.2 backwards compat bug
        if ('function' === typeof cb) {
          console.log('using sni callback callback');
          cb(null, secureContext);
        } else {
          console.log('NOT using sni callback callback');
          return secureContext;
        }
      };
  }

  secureContexts.dummy = createSecureContext(dummyCerts);
  addSniWorkaroundCallback();
```

Where **`createSecureContext`** and **`loadCerts`** are defined as:

```javascript
  //
  // abstract workaround for v0.10 / v0.12 / v1.2 backwards compat
  //
  function createSecureContext(certs) {
    try {
      return require('tls').createSecureContext(certs);
    } catch(e) {
      return require('crypto').createCredentials(certs).context;
    }
  }


  //
  // loading certs SYNChronously
  //
  function loadCerts(domainname) {
    // TODO make async
    // WARNING: This must be SYNC until we KNOW we're not going to be running on v0.10
    // Also, once we load Let's Encrypt, it's lights out for v0.10

    // assuming a directory structure where `certs` is in `/path/to/apps/<<appname>>/certs`
    var certsPath = path.join(vhostsdir, domainname, 'certs');

    // assuming server certs are in a subdir `server` and ca certs are in a subdir `ca`
    try {
      var nodes = fs.readdirSync(path.join(certsPath, 'server'));
      var keyNode = nodes.filter(function (node) { return /\.key\.pem$/.test(node); })[0];
      var crtNode = nodes.filter(function (node) { return /\.crt\.pem$/.test(node); })[0];
      var secOpts = {
        key:  fs.readFileSync(path.join(certsPath, 'server', keyNode))
      , cert: fs.readFileSync(path.join(certsPath, 'server', crtNode))
      }

      if (fs.existsSync(path.join(certsPath, 'ca'))) {
        secOpts.ca = fs.readdirSync(path.join(certsPath, 'ca')).filter(function (node) {
          console.log('[log ca]', node);
          // don't accidentally load a key file
          return /crt\.pem$/.test(node);
        }).map(function (node) {
          return fs.readFileSync(path.join(certsPath, 'ca', node));
        });
      }
    } catch(err) {
      // TODO Let's Encrypt / ACME HTTPS
      console.error("[ERROR] Couldn't READ HTTPS certs from '" + certsPath + "':");
      // this will be a simple file-read error
      console.error(err.message);
      return null;
    }

    try {
      secureContexts[domainname] = crypto.createCredentials(secOpts).context;
    } catch(err) {
      console.error("[ERROR] Certificates in '" + certsPath + "' could not be used:");
      console.error(err);
      return null;
    }

    return secureContexts[domainname];
  }
```

## Issue

There's a bug  in node.js v0.12 / io.js v1.2 on arm6 (see https://github.com/iojs/io.js/issues/869) that requires the use of the new optional SNICallback and since for the next little bit I'm going to have to use both versions of node / io.js (and I can't easily feature-detect which API style to use), so I'd like to see A) the bug fixed and B) the new API backported.

### was in v0.10.x

http://nodejs.org/docs/v0.10.36/api/tls.html#tls_tls_createserver_options_secureconnectionlistener

```javascript
SNICallback: function (domainname) {
  // ...
  return secureContext;
}
```

### is now in v0.12.x

http://nodejs.org/docs/v0.12.0/api/tls.html#tls_tls_createserver_options_secureconnectionlistener

```javascript
SNICallback: function (domainname, cb) {
  // ...
  if (secureContext) {
    return secureContext;
  }
  getSecureContext(function (ctx) {
      secureContext = ctx;
      cb(null, ctx);
  });
}
```

### psuedo-code for backwards/forwards compat

Since you can easily tell via duck typing whether or not a `secureContext` was returned as well as via `fn.arity` if a callback was passed, I see only benefit in backporting this change.

I haven't tested it yet, so perhaps you already did - but it isn't documented that the new way is backported nor is it documented that the old way works in v0.12 / v1.2

```javascript
if (2 >= snicb.arity) {
  if (!(result instanceOf SecureContext)) {
    // wait for callback
    return;
  }
}

cancelCallback();
doNextThing();
return;
```

**Comment by coolaj86** [comment]
## workaround

This should have been obvious, not enough sleep I guess:

```javascript
      //SNICallback is passed the domain name, see NodeJS docs on TLS
      secureOpts.SNICallback = function (domainname, cb) {
        console.log('[log] SNI:', domainname);

        var secureContext = secureContexts[domainname];

        if (!secureContext) {
          // testing with shared dummy
          //secureContext = secureContexts.dummy;
          // testing passing bad argument
          //secureContext = createSecureContext(loadDummyCerts);
          // testing with fresh dummy
          secureContext = createSecureContext(loadDummyCerts());
        }

        console.log('[log]', secureContext);

        // workaround for v0.12 / v1.2 backwards compat bug
        if ('function' === typeof cb) {
          console.log('using sni callback callback');
          cb(null, secureContext);
        } else {
          console.log('NOT using sni callback callback');
          return secureContext;
        }
      };
```

**Comment by indutny** [comment]
I'm afraid this can't be fixed. Please consider it as a breaking API change.

Arity check won't work because the specified callback could be of such form:

```javascript
function (servername) {
  console.log(servername);
  return otherFn.apply(this, arguments);
```

I also tried checking the return value of callback, but it won't work because v0.10 allowed returning `undefined` from it. See: https://github.com/indutny/io.js/tree/fix/gh-9236 .

I'm sorry for breaking this, but it is how it should have work in order to allow many beautiful things, like loading context asynchronously.

Should I close the issue?

**Comment by coolaj86** [comment]
Arity still works, actually. No v0.10 user will be be using the callback parameter, so in v0.10, if the arity is 2, we know they're using it. If they want to use callback with v0.10 and they aren't currently, you could explicitly state in the documentation that it's a transitional fix so they must pass the argument.

But how about also printing a deprecation notice or something?

I guess it's not that big of a deal because I must be one of about 10 people using this feature, but I'd really like a way to get this backported because I have to run on both v0.10 and v1.2 until I can sort through bugs / breaking changes between the two.

Another solution:

Add a transitional `SNICallbackAsync` with a deprecation warning when it's used.

**Comment by indutny** [comment]
@coolaj86 why not just check the presence of `cb` parameter?

**Comment by coolaj86** [comment]
That's what I'm doing now (see example above), but I'd actually like to be able to use the sync functionality because I'm hot-loading websites and using lets encrypt to dynamically get certificates.

—

**Comment by indutny** [comment]
Why not just invoke callback immediately? It'll have the same effect as old-style API

**Comment by coolaj86** [comment]
That's what I'm doing now, but I'll be loading the certificates dynamically so I'll have to make a request to the letsencrypt.org cert server for new (or expired) certs.


I can do some eager loading for certs already on the file system, but since I'm on an embedded platform I found that the slowdown can be significant as the number of files grows.




I can work around it with enough jiggery pokery, I'd just like to not have to do that.




Why not just add a SNICallbackAsync to v0.10?




If you're still against it feel free to close the issue. I'm probably only one of 5 people using it anyway considering that others haven't already brought up this concern since v0.12 has been released. It would be interesting to search npm to see if anyone else has code that will break because of this, but it's probably very very few.


—

**Comment by indutny** [comment]
@coolaj86 v0.10 API is frozen, we are not adding new features to it.

**Comment by indutny** [comment]
@coolaj86 this the point of major releases, they have new features and breaking changes. Old code should be working just fine on previous major version, but it isn't guaranteed to work without changes on a newer one.

**Comment by coolaj86** [comment]
I totally understand where you're coming from and I appreciate your concern and your help. :-)

**Comment by indutny** [comment]
@coolaj86 thank you! :)
