### ISSUE TITLE
Throwing on Failed File Access Check

### ISSUE THREAD

**Issue by atomantic** [joyent/node#9238]
It is not node's call whether the failure to access a file is an exception or a natural and intended part of the business logic within an application.

If an application allows the inclusion of dynamic configuration files, which may or may not exist depending on the parameters supplied, instead of doing this:
```
return fs.readFileSync(overrideConfig) || fs.readFileSync(defaultConfig);
```
(which would be really nice)
We have to wrap this code in a try/catch to handle Node.js assuming the failure to find/access the file is an exception to the app's well being (yuck)
```
var config;
try {
     // try to get the override configuration file if it exists
     config = fs.readFileSync(overrideConfig);
} catch(e){
     // otherwise, node.js barfed and we have to clean it up
     // use the default file
     config = fs.readFileSync(defaultConfig);
}
return config;
```

There needs to be a way to check if a file exists on the system without throwing an exception if it doesn't.

**Comment by blazedd** [comment]
It sounds like you'll need to write your own function to handle this logic, as the [file system library](http://nodejs.org/api/fs.html) does include a way to check if a file exists:

    fs.existsSync(overrideConfig)

You can read more about it here: http://nodejs.org/api/fs.html#fs_fs_existssync_path

I would recommend writing a quick method to combine the readFile and exists methods to do what you are trying to accomplish.

**Comment by cjihrig** [comment]
You can also use the async version which does not throw, although it does require a bit more code.

**Comment by atomantic** [comment]
fs.exists and fs.existsSync are scheduled for deprecation.
Yes. I got this working with a huge amount of extra code using the async version--this seems silly though. Node is making an assumption that this file check is a fatal error when it isn't necessarily one.

Ideally, I'd like to do a file.existsSync(overrideConfig) and then require(overrideConfig) on that condition. Or if `require` could be configured to not throw on failure, that would be even better.

I'm probably going to use https://github.com/jprichardson/node-jsonfile because I agree "Writing JSON.stringify() and then fs.writeFile() and JSON.parse() with fs.readFile() enclosed in try/catch blocks became annoying."

It still stands that if you have to write a try/catch block around this check, node is doing the wrong thing.

**Comment by atomantic** [comment]
`fs.existsSync` throwing an exception when the answer is `false`, is equivalent to asking someone if there's a file on his desk but instead of saying "no", he throws his arms in the air and says, "WTF, everything is wrong! You are a broken human being!" And then he sets you on fire and slams the door in your face.

`fs.existsSync` and `fs.accessSync` should return `true`/`false` in order to answer the question. If the consumer of this API thinks a `false` answer means an exception should be thrown, that's up to the implementor to decide.

**Comment by mikaturunen** [comment]
To confuse even more, you could potentially go with the promise wrapped ones. Q.ninvoke. I love it for this kind of stuff.

    Q.ninvoke(fs, "readFile", path)
       .then()
       .catch()
       .done() 

Chain the promises for easier reading and usage. But yeah, the way you are attempting to use them seems slightly un-node-like, which in no way is bad but probably should be avoided for sake of consistency and making sure it stays well maintained. The IO is async (in node) anyway so forcing it into sync seems tad off in more than one way.
