### ISSUE TITLE
net.listen's documentation should mention what type of socket it binds to

### ISSUE THREAD

**Issue by misterdjules** [joyent/node#9239]
After https://github.com/joyent/node/commit/57c56558858f8348f938194c7fe563574cc46fd6, `net.listen` binds to an IPv6 socket when possible. This is not in line with [the documentation](http://nodejs.org/api/net.html#net_server_listen_port_host_backlog_callback) that only mentions IPv4 addresses.

The documentation should be updated to describe what type of socket it binds to and in which cases, and include some code examples.

**Comment by cjihrig** [comment]
I think #9195 may also be relevant here.

**Comment by misterdjules** [comment]
@cjihrig Thanks! Closing as duplicate of #9195.
