### ISSUE TITLE
documentation sample needs to be improved for vm

### ISSUE THREAD

**Issue by smartmouse** [joyent/node#9240]
The following sample needs to be improved:
If we just execute it -- it will give an error -- 
C:\Users\IBM_ADMIN\VMTest\vmincr.js:28
  script.runInContext(sandbox);
         ^
TypeError: sandbox argument must have been converted to a context.
    at TypeError (native)
    at Object.<anonymous> (C:\Users\IBM_ADMIN\VMTest\vmincr.js:28:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

============================================
var util = require('util');
var vm = require('vm');

var sandbox = {
  animal: 'cat',
  count: 2
};

var script = new vm.Script('count += 1; name = "kitty"');

for (var i = 0; i < 10; ++i) {
  script.runInContext(sandbox);
}

console.log(util.inspect(sandbox));

// { animal: 'cat', count: 12, name: 'kitty' }

======================================================

Thanks. I can resolve this by adding
vm.runInNewContext('count += 1; name = "kitty"', sandbox);
console.log(util.inspect(sandbox));

**Comment by cjihrig** [comment]
The example is indeed broken, but I don't think that is the correct way to fix it. What about this:

```javascript
var util = require('util');
var vm = require('vm');

var sandbox = {
  animal: 'cat',
  count: 2
};

var context = vm.createContext(sandbox);
var script = new vm.Script('count += 1; name = "kitty"');

for (var i = 0; i < 10; ++i) {
  script.runInContext(context);
}

console.log(util.inspect(sandbox));

// { animal: 'cat', count: 12, name: 'kitty' }
```

**Comment by smartmouse** [comment]
Perfect! This works! Thank you so much for your prompt reply. Much appreciated!
