### ISSUE TITLE
v0.12: Poor choice of V8 version

### ISSUE THREAD

**Issue by jakobkummerow** [joyent/node#9241]
I just happened to notice that node v0.12 ships V8 3.28.73. That's a pretty bad choice, as 3.28.73 was just a random trunk snapshot that was briefly considered as the basis for the 3.28 branch, but was then discarded/abandoned because it was too unstable. The tip of the branch is 3.28.71.19: https://chromium.googlesource.com/v8/v8.git/+/branch-heads/3.28

While the 3.28 branch is generally outdated and hence unmaintained anyway, at least using its tip is very strongly preferable over using a random trunk commit from shortly after the branch point. To be very clear: **There are known crash and security bugs in 3.28.73 that are fixed in 3.28.71.19!**

**Comment by KenanY** [comment]
https://github.com/joyent/node/pull/9185?

**Comment by jakobkummerow** [comment]
Ah. Well, I would recommend to ship that ASAP.

**Comment by misterdjules** [comment]
Thanks @jakobkummerow for your input. Assigning to @trevnorris as he's already working on #9185.

**Comment by misterdjules** [comment]
Fixed by 32166a90cf126e4738b3ac81496ba1a46a23281d, beff91c44e7ba13035d1dbd05cf2bef7a7d65f82, ace398ed425e5b640fa4922697d317755ef8a652,  9a960c270c4ca48e05ccc915135845a1e2120e94 5b2bf92211278eba3ff1cc954cc42060b75b526f and 712cb4340b6c784779b986b0fcfe3564ee173ccf, thank you!
