### ISSUE TITLE
Is /usr/local/README.md a must file?

### ISSUE THREAD

**Issue by benpptung** [joyent/node#9254]
Couple months ago, I cannot `brew update` Homebrew and got the following error.

    error: Your local changes to the following files would be overwritten by merge:
	README.md
    Please, commit your changes or stash them before you can merge.
    Aborting
    Error: Failure while executing: git pull -q origin refs/heads/master:refs/remotes/origin/master

Then, based on the issue Homebrew/homebrew#35487 , I understand the /usr/local/README.md was modified by Node.js Mac package installer. It makes me confused and wondering if `/usr/local/README.md` a must file in Node.js?  Or, IMHO, Node.js Mac package installer( Or Homebrew ) should not put a README.md at /usr/local/README.md, which is an unique filename on an unique path in the system.

**Comment by gtomitsuka** [comment]
Nah, it isn't. Feel free to delete it. That's just a bug.
