### ISSUE TITLE
spawn doesn't properly handle shell script with "daemon" commands

### ISSUE THREAD

**Issue by p0deje** [joyent/node#9255]
I'm trying to start some simple shell script to expose current directory as web server. The shell script looks like this:

```bash
#!/bin/bash
python -m SimpleHTTPServer &
```

It works fine when I just run using bash:

```
$ ./simplehttpserver.sh
$ ps ax | grep python
61666 s000  S      0:00.06 /usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -m SimpleHTTPServer
```

I'm trying to run the same shell script using child process spawn, but that doesn't seem to work since the process never exits:

```javascript
var spawn = require('child_process').spawn;

var child = spawn('./stdout.sh');
child.on('close', function(code) {
  console.log('exited with ' + code);
});
```

```
$ node simplehttpserver.js
  ... never exits
```

It seems to me that the problem is somehow related to stdio, because everything works fine if I modify the script to this:

```bash
#!/bin/bash
python -m SimpleHTTPServer &> /dev/null &
```

```
$ node simplehttpserver.js
exited with 0
```

P.S. I've also checked Ruby implementation of [child_process](https://github.com/jarib/childprocess) and the following example (which in my opinion is similar to `simplehttpserver.js`) works just fine with original script:

```ruby
require 'childprocess'

child = ChildProcess.build('./simplehttpserver.sh')
child.start
child.wait
puts "exited with #{child.exit_code}"
```

```
$ ruby simplehttpserver.rb
exited with 0
```

**Comment by cjihrig** [comment]
Have you tried `spawn()`'s [`detached`](http://nodejs.org/api/child_process.html#child_process_options_detached) option? It allows the child process to continue running after Node exits.

**Comment by p0deje** [comment]
@cjihrig I tried, it behaves the same.

**Comment by cjihrig** [comment]
What if you also set `stdio` to `'ignore'` (or something not tied to the Node process), and `unref()` the child process?

**Comment by p0deje** [comment]
@cjihrig If I modify script it like that:

```javascript
var spawn = require('child_process').spawn;

var child = spawn('./stdout.sh', [], {detach: true, stdio: 'ignore'});
child.on('close', function(code) {
  console.log('exited with ' + code);
});
child.unref();
```

It doesn't hang, but close callback is not called as well.

**Comment by cjihrig** [comment]
Right. Because your child process isn't closing.

**Comment by p0deje** [comment]
I'm not sure how `detach` is related to event emitter, but I believe this is still a bug.

**Comment by cjihrig** [comment]
I disagree (although I could be wrong). `detach` allows Node to exit, while your child process continues to execute (which appears to be what you require). The `close` event is emitted ["when the stdio streams of a child process have all terminated."](http://nodejs.org/api/child_process.html#child_process_event_close)

**Comment by p0deje** [comment]
Oh, this makes more sense now, the file descriptors are not closed after process is sent to background with `&`. This seems correct to me, though it wasn't that obvious.

Thanks for a such a fast response!
