### ISSUE TITLE
dead link on website

### ISSUE THREAD

**Issue by adamzerner** [joyent/node#9267]
http://nodejs.org/api/tracing.html is dead

http://nodejs.org/api/ search for 'tracing'

**Comment by KenanY** [comment]
https://github.com/joyent/node-website/issues/77 https://github.com/joyent/node/pull/9172

**Comment by misterdjules** [comment]
@adamzerner Thank you very much for reporting this!

The fix landed in https://github.com/joyent/node/commit/08a1192478ed84422902d59a8bfe056ff88cc88d. See https://github.com/joyent/node-website/issues/77 for more info on when the fix will be deployed to the actual website.

In the future, the best place to report issues related to nodejs.org is https://github.com/joyent/node-website.

Thanks again!
