### ISSUE TITLE
Include OpenSSL headers with node distributions

### ISSUE THREAD

**Issue by swaj** [joyent/node#9269]
When node is installed (or a pre-built binary from nodejs.org is used), there are several header files that are packaged with Node which make native addon development possible.  Amongst them are headers for v8, c-ares, libuv, etc.  I've noticed that there's even an `openssl` subdirectory that contains a single header file:  `opensslconf.h`.

Well it turns out that OSX ships with OpenSSL 0.9.8 by default, and when Node is compiled using its own bundled version of OpenSSL, the verison is much more recent and includes some features that I'd like to use, specifically.

So this feature request is relatively simple:  When Node is built using it's bundled version of OpenSSL (no `--shared-openssl`), can the headers for the included version be shipped in that `include/node/openssl` subdirectory?

**Comment by tjfontaine** [comment]
A related issue is #5112

Keep in mind that in part because we don't have a well defined API/ABI it means that if you link against our compiled openssl you will be stuck using only the symbols we consume. So if there's a deficiency in our existing consumption of openssl, it's likely that just linking against ours won't be sufficient.

Some of this can be fixed with map files etc, but we have to decide what we want our public symbols for node to be. Or you can ship your own copy of openssl with your module, but you want to make sure it's scoped local to your binary addon such that our static openssl doesn't interfere with yours.

**Comment by swaj** [comment]
For me this is perfectly acceptable since I don't actually link statically to OpenSSL.  I always end up using whatever node bundles.

**Comment by misterdjules** [comment]
@swaj It seems to me https://github.com/joyent/node/pull/14089 fixes this issue, could you please confirm? Thanks!

**Comment by swaj** [comment]
Confirmed.  I was able to build 9d19dfbfdb2253e0bf42b55c7c1bbd618f40bf3c and the headers I'm looking for are now included.  Thanks Julien!  Feel free to close this one.

**Comment by misterdjules** [comment]
Thank you very much @swaj :+1: That fix and https://github.com/joyent/node/commit/4028669531bcd30d6082bf0dfdb8d73ddb0717c6 will be included in the upcoming v0.10.39 and v0.12.5 releases. When that will be depends on our progress on fixing recent issues with OpenSSL and logjam. More information here: github.com/joyent/node/issues/25509.

Closing then!

**Comment by swaj** [comment]
@misterdjules I think there may be some more headers missing, unfortunately.  It seems the OpenSSL headers rely on other headers, which aren't present.  A good example is `openssl/evp.h`:

```
In file included from ../src/crypto.c:4:
/usr/local/include/node/openssl/evp.h:1:10: fatal error: '../../crypto/evp/evp.h' file not found
#include "../../crypto/evp/evp.h"
         ^
1 error generated.
```

I'm not sure if this is something we can fix at the node layer or not.  When performing a compilation of OpenSSL manually, and subsequently doing a `make install`, `evp.h` never includes relative path references like this to other headers.  This makes me think the OpenSSL build process must generate the fully-constructed headers.

**Comment by misterdjules** [comment]
@swaj Thank you for the feedback :+1: Reopening and adding to the next milestone.

**Comment by shigeki** [comment]
This is to be fixed in https://github.com/nodejs/io.js/pull/2016 . I will submit a new PR after that.

**Comment by misterdjules** [comment]
@swaj This should be fixed by https://github.com/joyent/node/commit/82778223444d9717bcd2629443c93677035fc40f. Could you please give it a try and let us know if that fixes your issue?

Thank you :+1:

**Comment by misterdjules** [comment]
This issue had been moved to 0.10.41, but it was fixed by https://github.com/joyent/node/commit/82778223444d9717bcd2629443c93677035fc40f in v0.10.40. So moving it back again to the 0.10.40 milestone.
