### ISSUE TITLE
Cannot open special Windows device "NUL"

### ISSUE THREAD

**Issue by natevw** [joyent/node#9271]
I can't figure out a way to `fs.openSync("NUL")` (the Win32 equivalent of "/dev/null").

It seems that, since the open logic resolves to absolute path first, rather than just passing what I provide to the underlying call, that any [special files](https://technet.microsoft.com/library/Cc961816) like this will fail under Windows.

**Comment by natevw** [comment]
Figured it out via [this post](https://groups.google.com/forum/#!topic/nodejs/w21RPwaoTWI): `fs.open("\\\\.\\NUL", "r")` works.

Whether this is a workaround or the expected "right" way to accomplish this I don't know, but it works.

**Comment by OrangeDog** [comment]
That's the correct UNC path for a device file.

https://msdn.microsoft.com/en-gb/library/windows/desktop/aa365247.aspx#Win32_Device_Namespaces
