### ISSUE TITLE
npm WARN unmet dependency C:\Users\myusername\AppData\Roaming\npm\node_modules\r edis-commander requires ___@'~_._._' but will load

### ISSUE THREAD

**Issue by goodseller** [joyent/node#9283]
After installed the latest nodejs on windows, I get the follow message from the console, does anyone know why?

Microsoft Windows [版本 6.2.9200]
(c) 2012 Microsoft Corporation. 著作權所有，並保留一切權利。

C:\WINDOWS\system32>npm install -g bower
C:\Users\myusername\AppData\Roaming\npm\bower -> C:\Users\myusername\AppData\Roa
ming\npm\node_modules\bower\bin\bower
npm WARN unmet dependency C:\Users\myusername\AppData\Roaming\npm\node_modules\r
edis-commander requires redis@'~0.7.2' but will load
npm WARN unmet dependency C:\Users\myusername\AppData\Roaming\npm\node_modules\r
edis,
npm WARN unmet dependency which is version 0.12.1
npm WARN unmet dependency C:\Users\myusername\AppData\Roaming\npm\node_modules\b
ower-update\node_modules\bower requires chalk@'0.5.0' but will load
npm WARN unmet dependency C:\Users\myusername\AppData\Roaming\npm\node_modules\c
halk,
npm WARN unmet dependency which is version 0.5.1
npm WARN unmet dependency C:\Users\myusername\AppData\Roaming\npm\node_modules\b
ower-update\node_modules\nomnom requires chalk@'~0.4.0' but will load
npm WARN unmet dependency C:\Users\myusername\AppData\Roaming\npm\node_modules\c
halk,
npm WARN unmet dependency which is version 0.5.1
npm WARN unmet dependency C:\Users\myusername\AppData\Roaming\npm\node_modules\b
ower-update\node_modules\bower\node_modules\bower-config requires osenv@'0.0.3'
but will load
npm WARN unmet dependency C:\Users\myusername\AppData\Roaming\npm\node_modules\b
ower-update\node_modules\bower\node_modules\osenv,
npm WARN unmet dependency which is version 0.1.0
npm WARN unmet dependency C:\Users\myusername\AppData\Roaming\npm\node_modules\b
ower-update\node_modules\bower\node_modules\bower-registry-client requires async
@'~0.2.8' but will load
npm WARN unmet dependency C:\Users\myusername\AppData\Roaming\npm\node_modules\b
ower-update\node_modules\async,
npm WARN unmet dependency which is version 0.9.0
npm WARN unmet dependency C:\Users\myusername\AppData\Roaming\npm\node_modules\b
ower-update\node_modules\bower\node_modules\bower-registry-client requires lru-c
ache@'~2.3.0' but will load
npm WARN unmet dependency C:\Users\myusername\AppData\Roaming\npm\node_modules\b
ower-update\node_modules\bower\node_modules\lru-cache,
npm WARN unmet dependency which is version 2.5.0
npm WARN unmet dependency C:\Users\myusername\AppData\Roaming\npm\node_modules\n
pm\node_modules\node-gyp requires minimatch@'1' but will load
npm WARN unmet dependency C:\Users\myusername\AppData\Roaming\npm\node_modules\n
pm\node_modules\minimatch,
npm WARN unmet dependency which is version 2.0.1
npm WARN unmet dependency C:\Users\myusername\AppData\Roaming\npm\node_modules\n
pm\node_modules\npm-registry-client\node_modules\concat-stream requires readable
-stream@'~1.1.9' but will load
npm WARN unmet dependency C:\Users\myusername\AppData\Roaming\npm\node_modules\n
pm\node_modules\readable-stream,
npm WARN unmet dependency which is version 1.0.33
npm WARN unmet dependency C:\Users\myusername\AppData\Roaming\npm\node_modules\r
edis-commander\node_modules\node-redis-dump requires redis@'~0.8.4' but will loa
d
npm WARN unmet dependency C:\Users\myusername\AppData\Roaming\npm\node_modules\r
edis,
npm WARN unmet dependency which is version 0.12.1
bower@1.3.12 C:\Users\myusername\AppData\Roaming\npm\node_modules\bower
├── is-root@1.0.0
├── stringify-object@1.0.0
├── junk@1.0.1
├── abbrev@1.0.5
├── chmodr@0.1.0
├── which@1.0.8
├── osenv@0.1.0
├── archy@0.0.2
├── opn@1.0.1
├── lru-cache@2.5.0
├── bower-logger@0.2.2
├── graceful-fs@3.0.5
├── rimraf@2.2.8
├── bower-endpoint-parser@0.2.2
├── lockfile@1.0.0
├── retry@0.6.0
├── nopt@3.0.1
├── tmp@0.0.23
├── q@1.0.1
├── request-progress@0.3.0 (throttleit@0.0.2)
├── chalk@0.5.0 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-colo
r@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
├── shell-quote@1.4.2 (array-filter@0.0.1, array-map@0.0.0, array-reduce@0.0.
0, jsonify@0.0.0)
├── semver@2.3.2
├── fstream@1.0.4 (inherits@2.0.1)
├── bower-json@0.4.0 (intersect@0.0.3, deep-extend@0.2.11, graceful-fs@2.0.3)

├── p-throttler@0.1.0 (q@0.9.7)
├── promptly@0.2.0 (read@1.0.5)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── bower-config@0.5.2 (osenv@0.0.3, graceful-fs@2.0.3, optimist@0.6.1)
├── fstream-ignore@1.0.2 (inherits@2.0.1, minimatch@2.0.1)
├── tar-fs@0.5.2 (pump@0.3.5, tar-stream@0.4.7)
├── decompress-zip@0.0.8 (nopt@2.2.1, mkpath@0.1.0, touch@0.0.2, readable-str
eam@1.1.13, binary@0.3.0)
├── glob@4.0.6 (inherits@2.0.1, once@1.3.1, minimatch@1.0.0)
├── request@2.42.0 (caseless@0.6.0, json-stringify-safe@5.0.0, forever-agent@
0.5.2, aws-sign2@0.5.0, stringstream@0.0.4, tunnel-agent@0.4.0, oauth-sign@0.4.0
, qs@1.2.2, node-uuid@1.4.2, mime-types@1.0.2, form-data@0.1.4, bl@0.9.4, http-s
ignature@0.10.1, tough-cookie@0.12.1, hawk@1.1.1)
├── bower-registry-client@0.2.3 (graceful-fs@2.0.3, request-replay@0.2.0, lru
-cache@2.3.1, mkdirp@0.3.5, async@0.2.10, request@2.51.0)
├── cardinal@0.4.0 (redeyed@0.4.4)
├── mout@0.9.1
├── update-notifier@0.2.0 (semver-diff@0.1.0, string-length@0.1.2, latest-ver
sion@0.2.0, configstore@0.3.2)
├── handlebars@2.0.0 (optimist@0.3.7, uglify-js@2.3.6)
├── insight@0.4.3 (object-assign@1.0.0, chalk@0.5.1, async@0.9.0, lodash.debo
unce@2.4.1, os-name@1.0.3, tough-cookie@0.12.1, configstore@0.3.2, inquirer@0.6.
0)
└── inquirer@0.7.1 (figures@1.3.5, mute-stream@0.0.4, through@2.3.6, readline
2@0.1.1, lodash@2.4.1, cli-color@0.3.2, rx@2.4.1)

C:\WINDOWS\system32>

**Comment by KenanY** [comment]
@goodseller This looks like an `npm` issue, so you should've opened this at the [`npm` issue tracker](https://github.com/npm/npm/issues) (this tracker is for bugs in Node core). Regardless, there's no error in the log you've posted, just a bunch of warnings. We can continue this on the `npm` repo if you'd like.
