### ISSUE TITLE
socket.remoteAddress after close is undefined

### ISSUE THREAD

**Issue by fastest963** [joyent/node#9287]
`socket.remoteAddress` after `close` is undefined because `this._handle` is null. Since we're caching `this._peername` can we just change `_getpeername` to return `this._peername` if it already exists and not always look for a `this._handle`.

Related stackoverflow posts:
http://stackoverflow.com/questions/12444598/why-is-socket-remoteaddress-undefined-on-end-event
http://stackoverflow.com/questions/12126403/getting-the-ip-address-of-a-socket-inside-a-close-event-handler

**Comment by tjfontaine** [comment]
I would need to look back through some other issues, but in the past I've advocated for always caching the data, even though it could potentially result in a few more syscalls under the hood, it often leads to easier debugging experiences for everyone.

I would definitely entertain a PR that always caches the remote side for both inbound and outbound connections.

**Comment by fastest963** [comment]
@tjfontaine I just made a PR that hopefully does what you were looking for. It's caching the `_peername` once we get one. It's only removing it if `connect` is called again.

**Comment by cjihrig** [comment]
Closed in 8c38b07252d86f4eef91344f8df4f0c3e38bca35
