### ISSUE TITLE
Reconciliation with io.js

### ISSUE THREAD

**Issue by BenjaminProgram** [joyent/node#9295]
Over at iojs/io.js#978 we are discussing reconciliation. I hope that some of you are interested and open to participating in the discussion.

**Comment by ravi** [comment]
That task says:

> It is not an ultimatum to Joyent or The Node.js Foundation but rather a collaboration point for the io.js community to produce a proposal for merging.

I am not part of the io.js community nor do I understand the need for it in the first place. So I am not well suited to contribute in any productive way to the effort.

Additionally, participating in discussions is worthwhile only if all processes are and continue to be democratic: users of NodeJS (i.e., developers) have some sort of significant (non-symbolic) say.

**Comment by piscisaureus** [comment]
> I am not part of the io.js community nor do I understand the need for it in the first place. So I am not well suited to contribute in any productive way to the effort.

Io.js doesn't define community membership that narrowly. You're welcome to provide your input / ask what's the need for it if you want to.

**Comment by ravi** [comment]
@piscisaureus Thank you, but even by a loose definition, wouldn't it make sense that I be a contributor or user of io.js? I am a NodeJS user. I was and am happy with it. I know that some very significant contributors have chosen to fork Node to io.js (IIUC) which is certainly a matter of concern for me if, as a result, NodeJS loses their future contributions. But I also know/realise all that is really out of my control.

As I hinted at in my comment, it would be salutary, IMO, if any foundation/organisation/community had community members in an advisory (if not decision-making) role. Perhaps that is one comment I could contribute to the reconciliation thread, in more detail.

**Comment by nodejsrocks** [comment]
This is a place for node.js developers to discuss technical matters. I believe io.js issues can be discussed on it's own place.

I'm one of the silent crowd of developers and I believe I'm not alone on this. 
Briefly, I'm very disappointed with the whole io.js play. 

Please close this none node.js technical related item.

**Comment by victorhooi** [comment]
@nodejsrocks You joined *today* just to post that one comment? Lol. From your nickname, I can't tell if you're actually a NodeJS groupie, or whether you're taking the piss...

If it's the second, I applaud you - sometimes we take ourselves too seriously =).

And no, I don't have a horse in this race, but as a general principle, brushing things under the rug doesn't help. Anyhow, hopefully we can all get along.

**Comment by BenjaminProgram** [comment]
@nodejsrocks This is to notify you not discuss.

**Comment by tjfontaine** [comment]
@BenjaminProgram thank you for the ping, and we appreciate how much our community cares. I know I am excited to see the Node.js Foundation being created, and I am certain it will continue to foster a healthy and vibrant diverse community, but on a larger scale.

The process for creating the foundation will take time. In the mean time there are outstanding (in many senses of the word) contributions that need to be integrated into Node.js, and potentially vice versa. If users know about those changes please shepherd them through the process. We all want to continue to collaborate and innovate in our ecosystem, lets continue to do that for our community's sake.

For now though, I agree that this issue tracker is meant for discussing bugs, feature requests, and other topics related to the software project of Node.js and I will close this issue.

**Comment by runvnc** [comment]
@tjfontaine I am just an observer here but you basically just ignored the proposal.  It seemed like such a great proposal too, I actually assumed it would move forward.  Without a complete reversal on that non-response from Node/Joyent management then I will have to say that I overestimated the Node/Joyent team.  In my personal opinion this may have been the last opportunity Node/Joyent had to stay relevant from a technical perspective, and it looks like it went right over your head.  

I am sure it will take some time for the mainstream/business world to adapt to this, but there does not seem to be any relevant leadership from Node/Joyent, and again, barring a complete 180 from that non-response, I am moving on.

**Comment by themgt** [comment]
Wow guys, this really has been a sad spectacle. You seem quite set on finding out whether you can beat Larry Ellison's record for losing an open source community's hearts and minds with empty corporate pablum and actions that discredit your words.

io.js looks more and more like the future of Node with each passing day

**Comment by ravi** [comment]
@runvnc @themgt If io.js is the future of Node/JS and you are moving on, whence the need for such proposals and mergers? If you are the future, and the rest of us are sad spectacles, charity suggests you minimally leave us to our ways, to wither in peace :-).

**Comment by runvnc** [comment]
@ravi myself I have nothing against Node users, most of my projects still use Node. I started migrating to io.js though.  Was just giving my personal opinion about the leadership in the two camps.  But I personally think Node and io.js users are in the same community really and I certainly dont make comments to try to split them or disturb your peace or anything.  Anyway again the moving on thing is my personal opinion and I am not part of eithrr of these groups just another users..and I did qualify it in case Joyent reverses their response.  The reality is io.js has the core technical leadership and has now demonstrated they have the organizational leadership as well so I am just hoping other groups will be able to adjust to that.

**Comment by tjfontaine** [comment]
I understand that this is an important issue that people care deeply about, as I assure you I do as well. This is just not the appropriate venue to have these discussions, this issue tracker is for bugs, features, and other such topics related to the software project.

These discussions should happen in https://github.com/joyent/nodejs-advisory-board as that's the outlet and the mechanism that has been leading the foundation work. So conversations around the creation of the foundation and its related pieces will be held there. I've locked this discussion  to avoid confusion around where this discussion should take place.

We want all of this to be done in the open, in transparent, and understandable ways -- and of course with buy in from the community. We absolutely want to have open and frank conversations about the community concerns, but we also want those conversations to be civil, compassionate, and empathetic.

For now, all projects will be operating as they were before, and we shouldn't be hindering anyone from doing the work they are passionate about on whatever project they want to work on.

**Comment by isaacs** [comment]
Continuation: https://github.com/joyent/nodejs-advisory-board/issues/28
