### ISSUE TITLE
AssertionError: false == true at RoundRobinHandle.add (cluster.js:140:3)

### ISSUE THREAD

**Issue by adrai** [joyent/node#9296]
Is this a node issue? https://github.com/Unitech/PM2/issues/1049

**Comment by tjfontaine** [comment]
Would need to see more information about the test case, but in short that assertion fails when trying to re-add a worker that was already in the pool.

@cjihrig can you take a look at this?

**Comment by cjihrig** [comment]
@tjfontaine the solution to this is in https://github.com/joyent/node/pull/8643. It landed in master, but not 0.12.

**Comment by adrai** [comment]
In which release can I expect to be fixed? v0.12.1 ? v1.0.0 ? Or should I wait for io.js to be merged ;-) ?

**Comment by cjihrig** [comment]
It appears that I mixed up this issue with #9261 (similar issue titles and stack traces). My original comment applies to #9261, but @adrai can you tell me if your failure involves the use of UDP? If not, can you please provide code with no external dependencies that reproduces the issue.

**Comment by adrai** [comment]
ok, i tested on an other machine... and I can't reproduce it, so we can close this issue...

**Comment by suparngp** [comment]
I am still having this issue. I ran the following sample code for express app and it produces the same error

<pre>
<code>
var cluster = require("cluster");
var cpus = require("os").cpus().length - 1;

if (cluster.isMaster) {
    for (var i = 0; i < cpus; i++) {
        cluster.fork();
    }
    return;
}

else {
    var app = require('../app');
    var http = require('http');

    var port = 3000;
    app.set('port', port);

    /**
     * Create HTTP server.
     */

    var server = http.createServer(app);

    /**
     * Listen on provided port, on all network interfaces.
     */

    server.listen(port);
    server.on('error', onError);
    server.on('listening', onListening);
}

</code>
</pre>


<pre>
<code>
assert.js:86
  throw new assert.AssertionError({
        ^
AssertionError: false == true
    at RoundRobinHandle.add (cluster.js:140:3)
    at queryServer (cluster.js:480:12)
    at Worker.onmessage (cluster.js:438:7)
    at ChildProcess.<anonymous> (cluster.js:692:8)
    at ChildProcess.emit (events.js:129:20)
    at handleMessage (child_process.js:324:10)
    at Pipe.channel.onread (child_process.js:352:11)
</code>
</pre>

**Comment by solshark** [comment]
I have this issue as well

**Comment by jvt** [comment]
I also have this issue.

**Comment by blake-jennings** [comment]
I am having this issue as well. Are you guys using any workarounds for now?

**Comment by austinkelleher** [comment]
+1
