### ISSUE TITLE
Http2 support

### ISSUE THREAD

**Issue by mrlove** [joyent/node#9305]
Hi guys,

i know it s a little bit early for this feature request, but would it be possible to integrate **http2** in a simple way? It could help to migrate more users to the fantastic node.js world. 

Best, 
mrlove

**Comment by jasnell** [comment]
http2 support will likely be best pursued outside of the core for now. There's still a lot of work to be done on figuring out exactly the best way to support the new protocol.

**Comment by mrlove** [comment]
Thank you.
