### ISSUE TITLE
end not called on streams over 65K

### ISSUE THREAD

**Issue by bryanmacfarlane** [joyent/node#9306]
Open a readable stream on a file and pipe to another stream (sample uses PassThrough)
On files over 65K (data chunk is called more than once), I get two data events and no end event.
This worked on v0.10.28

bug.js @ gist
https://gist.github.com/bryanmacfarlane/cbf864336bc9b6ad6884

For a small file, it outputs (size on itself):
$ node bug.js bug.js 
.size: 889

For a larger file:
$ node bug.js node-v0.12.0.pkg 
..$

**Comment by smikes** [comment]
I am unable to get a size for a large file, even with `node@0.10.28`:

```
$ nvm use 0.10.28
Now using node v0.10.28
$ node --version
v0.10.28
$ node gist.js gist.js
.size: 899
$ node gist.js `which node`
..$ 
```

It looks like you're running OSX; did you verify with `node@0.10.28` on that platform?

**Comment by bryanmacfarlane** [comment]
Yes, I'm on OSX Yosemite.  

I believe the end event should still be called.

I created another gist that is closer to the actual code that hit this problem (I replace with PassThrough) that works on 10.29 and not on 12.0.  That code was working daily for months and started failing on 12.0.

https://gist.github.com/bryanmacfarlane/aa7541927aa05eab8fa2

$ node -v
v0.10.29
$ node test2.js node-v0.12.0.pkg 
............................................................................................................................................................................................................................................
size: 15445373
$ node -v
v0.12.0
$ node test2.js node-v0.12.0.pkg 
................$

Thanks!

**Comment by bryanmacfarlane** [comment]
I just made the second gist work even on v0.12.0.  
It's still interesting why it worked on v0.10.29

next() call missing in _write.

```
var NullStream = function () {
    stream.Writable.call(this, { objectMode: true });
    this._write = function (data, encoding, next) {
        next();  // need to call next()
    };
};
util.inherits(NullStream, stream.Writable);
```

**Comment by bryanmacfarlane** [comment]
I understand this now.  no need for a bug.
