### ISSUE TITLE
Change names of packages in dists?

### ISSUE THREAD

**Issue by maxrimue** [joyent/node#9308]
Since the Pi 2 came out with its new ARMv7 chip, I wonder if someone could rename the older `.tar.gzs`, preferably to `node-<version>-linux-armv6l.tar.gz`, so people won't get confused which ARM it is.

**Comment by misterdjules** [comment]
I don't know how these binary tarballs have been built, so I'm not sure what architecture they support. @tjfontaine Could you please provide us with more information on that?

**Comment by maxrimue** [comment]
They seem to only work on ARMv6

**Comment by jasnell** [comment]
@misterdjules ... were you ever able to get more information on this?

**Comment by fivdi** [comment]
If the `.tar.gz` files being referred to are those below http://nodejs.org/dist, for example, http://nodejs.org/dist/v0.10.28/node-v0.10.28-linux-arm-pi.tar.gz, then AFAIK, they were built by @TooTallNate whenever he had time. If I'm not mistaken, they were never "official" releases of Node.js.

**Comment by jasnell** [comment]
Ok, then I'm going to close this and mark it as a deferral to the converged stream.
