### ISSUE TITLE
test-vm-timeout failures on ubuntu 10 in 0.12.X

### ISSUE THREAD

**Issue by mdawsonibm** [joyent/node#9317]
As part of our internal 0.12.0 node testing we see intermittent failures of the test-vm-timeout test.  It fails in 1 in 5 or more runs.

We only see the failures on ubuntu 10 at this point, but I've not run lots of repeats to see if we can recreate on other OS versions.

In any case,  I found this issue in io.js https://github.com/iojs/io.js/pull/622 and it matches the problem that I'm seeing and I validated that it resolves the failure.  The explanation also explains why we'd only see it on ubuntu 10, the issue is related to timer precision on older kernels.
  
Seems like we should pull this patch over.

**Comment by jasnell** [comment]
+1

**Comment by orangemocha** [comment]
+1

**Comment by misterdjules** [comment]
It makes sense to me too, thank you @mdawsonibm! Do you want to take care of porting https://github.com/iojs/io.js/pull/622?

**Comment by mdawsonibm** [comment]
Pull request created https://github.com/joyent/node/pull/9410

**Comment by mdawsonibm** [comment]
Landed in 7e9d2f8de8194e5f4d950eb87288bf97b2f3e509
