### ISSUE TITLE
Process.stderr value changes when node js process runs in background.

### ISSUE THREAD

**Issue by mindfireon812** [joyent/node#9318]
Node js process.stderr >>>>>>>>>
{ domain: null,
  _events: {},
  _maxListeners: 10,
  fd: 2,
  writable: true,
  readable: false,
  autoClose: false,
  _type: 'fs',
  _isStdio: true,
  destroySoon: [Function],
  destroy: [Function] }

**Comment by jasnell** [comment]
Need a test case and additional information to be able to check this.

**Comment by mindfireon812** [comment]
When we run node js directly on terminal or redirect stdout  into a file  i.e 

developers@workspace1/$ > node test.js  

OR

developers@workspace1/$ > node test.js 2>&1 > test.log &

and if we print process.stderr value in console statement then  we get following

{ _connecting: false,
  _handle: 
   { fd: 2,
     writeQueueSize: 0,
     owner: [Circular],
     onread: [Function: onread] },
  _readableState: 
   { highWaterMark: 16384,
     buffer: [],
     length: 0,
     pipes: null,
     pipesCount: 0,
     flowing: false,
     ended: false,
     endEmitted: false,
     reading: false,
     calledRead: false,
     sync: true,
     needReadable: false,
     emittedReadable: false,
     readableListening: false,
     objectMode: false,
     defaultEncoding: 'utf8',
     ranOut: false,
     awaitDrain: 0,
     readingMore: false,
     decoder: null,
     encoding: null },
  readable: false,
  domain: null,
  _events: 
   { end: { [Function: g] listener: [Function: onend] },
     finish: [Function: onSocketFinish],
     _socketEnd: [Function: onSocketEnd] },
  _maxListeners: 10,
  _writableState: 
   { highWaterMark: 16384,
     objectMode: false,
     needDrain: false,
     ending: false,
     ended: false,
     finished: false,
     decodeStrings: false,
     defaultEncoding: 'utf8',
     length: 0,
     writing: false,
     sync: true,
     bufferProcessing: false,
     onwrite: [Function],
     writecb: null,
     writelen: 0,
     buffer: [],
     errorEmitted: false },
  writable: true,
  allowHalfOpen: false,
  onend: null,
  destroyed: false,
  bytesRead: 0,
  _bytesDispatched: 0,
  _pendingData: null,
  _pendingEncoding: '',
  columns: 80,
  rows: 24,
  _type: 'tty',
  fd: 2,
  _isStdio: true,
  destroySoon: [Function],
  destroy: [Function] }



but if I run node js in background and also print stderr in file i.e 

developers@workspace1/$ > node test.js  > test.log 2>&1 &

then value of process.stderr is
 
{ domain: null,
_events: {},
_maxListeners: 10,
fd: 2,
writable: true,
readable: false,
autoClose: false,
_type: 'fs',
_isStdio: true,
destroySoon: [Function],
destroy: [Function] }

**Comment by piscisaureus** [comment]
@mindfireon812 
You're right; process.stderr might be an instance of either `fs.WriteStream`, `net.Socket` or an internal TTY type. 
But is this actually a problem?

**Comment by mindfireon812** [comment]
In one npm progress module ,they are using the properties of process.stderr values tty type , columns ,rows for their processing ,So when node js is in background this module dont respond.

**Comment by cjihrig** [comment]
You should probably open an issue on the module in question. They need to handle the case where `stderr` is not a tty.

**Comment by mindfireon812** [comment]
Can Any one tell me why this process.stderr value changes this way ? or why it is not tty in baakcground ?
