### ISSUE TITLE
Cannot debug gulp with Node 12

### ISSUE THREAD

**Issue by JeffryBooher** [joyent/node#9322]
I installed Node 0.12.0 and I can no longer debug gulp tasks. Not sure if this affects other debugging tasks or not.

1) Install gulp 
2) Create a gulpfile.js
3) node-debug gulp 

That should launch a node inspector stopped at the first line of gulp.js.
Actual: node-inspector is launched but as soon as it launches execution continues, the task completes and node-inspector exits.

I've tried reinstalling  node-inspector:
```sh
node --version: v0.12.0
node-inspector --version: v0.9.1
gulp --version: CLI version 3.8.11, Local version 3.8.11
```

**Comment by JeffryBooher** [comment]
This works with `Node --version: 0.10.36`

**Comment by JeffryBooher** [comment]
I should also note that I found this on Windows and did not test Mac or Linux.  Chrome 41 (64 bit)

**Comment by jasnell** [comment]
Seems to be working alright on Mac

gulpfile.js:
```javascript
debugger;
var gulp = require('gulp');

gulp.task('default', function() {
  // place code for your default task here
});
```

Running `node-inspector` v0.9.1, `node` v0.12.0, `gulp` 3.8.11. Able to hit breakpoints in gulp with no problem.

**Comment by JeffryBooher** [comment]
@jasnell does it work without the `debugger;` statement from the command line?  `node-debug ...`?

**Comment by jasnell** [comment]
Without the `debugger;` statement, no, it does not appear so. Unable to hit any breakpoints in gulp. 

To contrast, running `node-debug` with another script works fine without the `debugger;` statement:

```javascript
function doit() {
  console.log('.');
  setTimeout(doit, 5*1000);
}
doit();
```
`node-debug test.js` works fine. A bit later this afternoon I'll test against node v0.10.x to see what result I get.

**Comment by jasnell** [comment]
Just another quick test on this... changing the gulpfile.js to add a short timeout seems to make it work. It appears that there may be a timing issue here when connecting to node-inspector. Will flag this an investigate further later.

**Comment by JeffryBooher** [comment]
@jasnell yep, I was able to debug other node js files; I can't think of what's special about gulp that would make it behave that way. Thanks for the quick tests!

**Comment by cjihrig** [comment]
FWIW, it might also be worth checking in with the Gulp and node inspector teams. I know there are a lot of changes in the debugger in 0.12, so something could need to be updated. I'm also not ruling out a node issue.

**Comment by contra** [comment]
Does this happen with gulp 4.0 as well?

**Comment by bajtos** [comment]
IMO this is a duplicate of https://github.com/node-inspector/node-inspector/issues/534.

**Comment by fcdwg** [comment]
This issue was moved to google/github-issue-mover#27

**Comment by fcdwg** [comment]
This issue was moved to google/github-issue-mover#28

**Comment by fcdwg** [comment]
This issue was moved to google/github-issue-mover#29

**Comment by fcdwg** [comment]
This issue was moved to google/github-issue-mover#30

**Comment by contra** [comment]
@fcdwg how do I opt-out of you, you pile of shit

![](https://gs1.wac.edgecastcdn.net/8019B6/data.tumblr.com/97c1c355fa35fb60ea8a797de6f83d6e/tumblr_mxoi7xGRA51rzffavo1_500.gif)

**Comment by jasnell** [comment]
@JeffryBooher ... as far as I can tell, @bajtos may be correct. This looks like it's a problem in node-inspector. I'm going to close this issue accordingly. If it does turn out to be a node issue, let me know and I'll reopen.

**Comment by fcdwg** [comment]
This issue was moved to google/github-issue-mover#31

**Comment by fcdwg** [comment]
This issue was moved to google/github-issue-mover#32

**Comment by JeffryBooher** [comment]
yep. Sounds good, thanks!

**Comment by fcdwg** [comment]
This issue was moved to google/github-issue-mover#33
