### ISSUE TITLE
http: delete method does not send `transfer-encoding: chunked` by default

### ISSUE THREAD

**Issue by davidgwking** [joyent/node#9324]
As of v0.12.0, it appears that the http request client no longer uses chunked encoding by default for DELETE. This is a departure from v0.10.36 behavior.

Given that this wasn't a documented change and it is not horribly uncommon to include entity bodies with DELETE, I am left wondering whether this was intended.

Implementation: https://github.com/joyent/node/blob/v0.12.0/lib/_http_client.js#L121

**Comment by BSteephenson** [comment]
From @lalitkapoor 's commit
https://github.com/joyent/node/commit/aef09601b4320648f4b6fac0baba3e5c54b0406a

**Comment by lalitkapoor** [comment]
@davidgwking please take a look at these:
https://github.com/joyent/node/issues/6185
https://github.com/joyent/node/pull/6564

**Comment by davidgwking** [comment]
@lalitkapoor @BSteephenson  Thanks, closing issue as there was considerable support behind this change.
