### ISSUE TITLE
Create UNIX socket without creating server

### ISSUE THREAD

**Issue by gobwas** [joyent/node#9329]
Hello!

I want my application to create UNIX socket on start, and then http.server to listen it.

How can I create socket file (pipe) in node without creating net server?

```js
var socketPath = "/tmp/my.sock"; // this is not existing file
net.connect({path: socketPath}); // produce ENOENT error
```

If I do something like this:

```js
fs.open(socketPath, "w+", function(err, fd) {
  new net.Socket({fd: fd}) // produce unsupported fd type FILE (need to be PIPE)
});
```

Can anybody help me? 

Thanks!

**Comment by jasnell** [comment]
The best place to ask would be stacktrace or one of the other user communities
