### ISSUE TITLE
add a `--suffix` to allow multiple versions of node to be installed

### ISSUE THREAD

**Issue by larkost** [joyent/node#9330]
I don't see a current method of having completely separate installs of node, and the current build system does not seem to allow for multiple installs without having separate prefix directories. Other systems such as Python or Ruby allow for a `--suffix` option to `./configure` that allow for multiple versions to be install simultaneously, including config information and packages. For example I have 7 versions of Python on my system for testing (e.g: python2.6, python2.7, python3.0, etc...).

An example of where this is very useful is in testing packages that run on Node.js. I work on the RethinkDB tests system and we can do a single testing run on 7 versions of Python, 3 versions of Ruby, but only a single version of Node. I would like to expand this so that I can have both 0.11 and 1.12.

For the moment I can get most of the way I need by building locally, then copying the binary into place with the suffix name I want. But that does not get me man pages or separate configs or packages.

**Comment by Freyert** [comment]
Would [Node Version Manager](https://github.com/creationix/nvm) not do the trick?

**Comment by larkost** [comment]
There are a couple of non-optimal parts to that:
1. It is using PATH manipulation to switch amongst versions. This troubles me both in that I have to re-architect my discovery methods to special case for Node rather than working like Python and Ruby already do, and in that I don't have an absolute path that I am working with.
2. It adds another dependency that I have to add to all of my systems. My current auto-discovery just works, so I can have different collections on different testing machines, and still have it work seamlessly on non-modified machines (this is for the RethinkDB testing system).

The latter is probably the bigger problem for me, since I need to be able to work a lot of places; namely as close to anywhere as possible.

**Comment by jasnell** [comment]
Closing this issue here. Would defer further discussion to the nodejs/build WG
