### ISSUE TITLE
simple testsuite does not tolerate being run in deep file paths. 

### ISSUE THREAD

**Issue by mdawsonibm** [joyent/node#9334]
We were seeing a number of strange failures in our test runs, mostly in tests related to pipes. 

We discovered that the problem was related  to the deep file paths used in our jenkins jobs.  When run in shallower paths the tests passed, when run in deeper paths we'd get various failures depending on how long the path was.

We ended up debugging this down to failures in the uv_pipe_connect call.  The documentation here http://docs.libuv.org/en/latest/pipe.html. identifies that path names as to uv_pipe_connect are truncated on unix to a length of sizeof(sockaddr_un.sun_path), typically between 92 and 108 bytes. Due to the truncation we'd get different error codes but none made it obvious that the path was being truncated.  I've opened this issue on libuv https://github.com/libuv/libuv/issues/244 to ass if returning  ENAMETOOLONG would be a better approach.

If the libuv behavior is not change we may want to add a check to PipeWrap:Connect/PipWrap::Bind (src/pipe_wrap.cc)  in order to ensure the end user gets a reasonable error.    If nothing else it would be good to document in net.createConnection that paths have a maximum length.

Regardless, I think we need to make it possible to run the tests in deep file paths as typical usage with Jenkins can easily result in this case.

The simplest/smallest change that I came up with that would let the tests run in our setup is to add an environment variable (NODE_PIPE_DIR) which is used as the directory in which to create pipes as opposed to the current base which is something off the directory in which the test is running.   The change based on this approach would be:
<pre>
diff --git a/test/common.js b/test/common.js
index a4825da..768ebd6 100644
--- a/test/common.js
+++ b/test/common.js
@@ -35,7 +35,11 @@ if (process.platform === 'win32') {
   exports.PIPE = '\\\\.\\pipe\\libuv-test';
   exports.opensslCli += '.exe';
 } else {
-  exports.PIPE = exports.tmpDir + '/test.sock';
+  if (typeof process.env.NODE_PIPE_DIR == 'undefined') {
+    exports.PIPE = exports.tmpDir + '/test.sock';
+  } else {
+    exports.PIPE = process.env.NODE_PIPE_DIR + '/test.sock';
+  }
 }
 if (!fs.existsSync(exports.opensslCli))
   exports.opensslCli = false;
diff --git a/test/simple/test-net-pipe-connect-errors.js b/test/simple/test-net-pipe-connect-errors.js
index 8200a16..fa15903 100644
--- a/test/simple/test-net-pipe-connect-errors.js
+++ b/test/simple/test-net-pipe-connect-errors.js
@@ -32,6 +32,11 @@ var accessErrorFired = false;
 // Test if ENOTSOCK is fired when trying to connect to a file which is not
 // a socket.
 var emptyTxt = path.join(common.fixturesDir, 'empty.txt');
+if (typeof process.env.NODE_PIPE_DIR !== 'undefined') {
+  emptyTxt = path.join(process.env.NODE_PIPE_DIR, 'empty.txt');
+  fs.closeSync(fs.openSync(emptyTxt, 'w'));
+}
+
 var notSocketClient = net.createConnection(emptyTxt, function() {
   assert.ok(false);
 });
</pre>

If this seems like a reasonable approach I can create a pull request for this change as a first step.   Then depending on the response to my question to libuv we could decide if we want to tighten up the doc and/or add a path length check in the createConnection call.

**Comment by jasnell** [comment]
I'm sure there's a joke about taking the long path hiding in there
somewhere. +1 to the documentation, env var and additional check in
pipe_wrap.

**Comment by mdawsonibm** [comment]
There are two additional changes beyond what I show above.  The first is to make test/testpy/__init__.py cleanup the directory specified by NODE_PIPE_DIR between test runs and a change to test/simple/test-cluster-eaccess.js to make it use NODE_PIPE_DIR as we later identified it was suffering from the same problem.  Once we have agreement on the approach I'll put together a pull request with the full set of changes

**Comment by mdawsonibm** [comment]
Create pull request https://github.com/joyent/node/pull/9381

**Comment by mdawsonibm** [comment]
landed as 5dd5ce75d7d9a1470f4e35b6b4046bc933714f2d
