### ISSUE TITLE
Missing documentation for util module methods

### ISSUE THREAD

**Issue by recidive** [joyent/node#9340]
Not sure if this is the correct place to post this, but there are many methods of `util` that are not documented in <a href="http://nodejs.org/api/util.html">nodejs.org</a>. Methods such as [`isString()`](https://github.com/joyent/node/blob/v0.12.0/lib/util.js#L534), [`isNumber()`](https://github.com/joyent/node/blob/v0.12.0/lib/util.js#L529), [`isBoolean()`](https://github.com/joyent/node/blob/v0.12.0/lib/util.js#L514) and so on are not documented there and they are very useful.

**Comment by jasnell** [comment]
Resolved in nodejs/node
