### ISSUE TITLE
Big Pipes on Child Process Spawn

### ISSUE THREAD

**Issue by thebergamo** [joyent/node#9343]
Today, I have a big problem on my app in production. :cry: 

My app call a command line written in Node.js too, using spawn instead on child process. Yeah, this is fine, but whats the problem?

My CLI output a lot of logs, in my tests on development mode, I don't have problem, because my script to processing not output much logs, but in one unique case on production my script can be much long and the logs too. In this case, the pipe used in Spawn can be clogged and I don't have any logs to say me it!

And is more complicated because I don't find anyone mention about this limit on the docs, my reference to solve this problem is the issue #6764. 

Please, is very useful say me if my Child Process pipe is obstructed to continue the application because I don't have any logs to say me it. Only my CLI is freeze and not continue. 

I'm glad very much if anyone can apply an error or any log when a problem like it occurs.

**Comment by jasnell** [comment]
@thebergamo ... I'm sorry, but this is not quite enough information to diagnose any particular problem.

**Comment by thebergamo** [comment]
On my oldest case, my problem is my Child Process send much logs to the terminal and this freeze my process, but I can't receive any logs.

In this case to fix, need to send logs to /dev/null

**Comment by jasnell** [comment]
@chrisdickinson @trevnorris ... any ideas?

**Comment by trevnorris** [comment]
This isn't my area of expertise in node. Would need a test case to reproduce locally.

@piscisaureus any ideas?

**Comment by piscisaureus** [comment]
The pipe size is inherently limited (the actual size differs greatly between OSes, I believe the size may be as small as 512 bytes but on windows for example its 64kb), but this shouldn't be an issue; the parent process should just read from it's end of the pipe and it should be all good.

In the particular case of logging, you could just make the child process inherit the parent's stdout by specifying `{ stdio: 'inherit' })`. In that scenario the parent process won't have anything to do anything, the child process would output straight to stdout.

I recommend closing this issue and reopen if the user comes up with a test case.

**Comment by jasnell** [comment]
SGTM
