### ISSUE TITLE
HTTPS, no warnings about 443 being used

### ISSUE THREAD

**Issue by AlicanC** [joyent/node#9344]
Using Node v0.12.0 on Windows 8.1, I did not get any warnings about port 443 being used in this script:
```javascript
var http = require('http');
var https = require('https');
var fs = require('fs');
var express = require('express');

//Configuration
var config = {
	httpPort: 80,
	httpsPort: 443,
	httpsOptions: {
		key: fs.readFileSync('127.0.0.1.key', 'utf-8'),
		cert: fs.readFileSync('127.0.0.1.cert', 'utf-8')
	}
};

//Express app
var app = express();

//Listen
http.createServer(app).listen(config.httpPort);
https.createServer(config.httpsOptions, app).listen(config.httpsPort);
```

It was being used by `vmware-hostd` and I could only notice that after I decided to switch to nginx and got `nginx: [emerg] bind() to 0.0.0.0:443 failed (10013: An attempt was made to access a socket in a way forbidden by its access permissions)`.

**Comment by Freyert** [comment]
Tried this out on Mac OS X Yosemite v.10.10.2 using Node v.0.12.0.

Here's the error you should see. 
```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1129:14)
    at listen (net.js:1155:10)
    at Server.listen (net.js:1240:5)
    at Object.<anonymous> (/Users/fultonbyrne/Desktop/learn/https_bug.js:20:24)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```
Solution might be somewhere in here:
```
    at Server._listen2 (net.js:1129:14)
    at listen (net.js:1155:10)
    at Server.listen (net.js:1240:5)
```

**Comment by AlicanC** [comment]
I do get the `EADDRINUSE` for 443 when I run two of "server.js", one with 80/443 and another one with 8080/443 port configuration.

This is what I get when VMware Workstation Server's "Shared VMs" feature is enabled and I run "server.js" with 80/443:
```
NET 1840: listen2 null 80 4 false
NET 1840: _listen2: create a handle
NET 1840: bind to anycast
NET 1840: listen2 null 443 4 false
NET 1840: _listen2: create a handle
NET 1840: bind to anycast
Listening on port 80...
Listening on port 443...
```
Of course, node is not really listening on 443. It is VMware that is listening on 443 and causing me to debug this mess for hours.

Intrestingly, nginx gave me `10013: An attempt was made to access a socket in a way forbidden by its access permissions` instead of `98: Address already in use`. I thought this could be a permission issue but running node in an Administrator cmd didn't help.

**Comment by Freyert** [comment]
That's very weird. And this happens every time `vmware-hostd` is running? I wonder if this occurs with any other *daemon*, or background processes listening on 443. I don't know too much about OS's in general, but perhaps `vmware-hostd` isn't actively listening until an actual connection happens and then the OS wakes it up and directs the traffic there. Perhaps this is why Windows doesn't prevent you from making a new, but impotent listener on that socket.

@AlicanC try creating a socket on 443 with Python or something else, or if you're able have a different daemon process listening on 443 and see if you still get the same issue. Best of luck and keep at it!
