### ISSUE TITLE
[proposal] show warning when require() packages not in package.json

### ISSUE THREAD

**Issue by piranna** [joyent/node#9354]
I don't know how related would be npm ```package.json``` with Node.js (or io.js), but since npm will be going to dedupe the packages diferentiating the phisical and logical packages, [we have thing](https://github.com/npm/npm/issues/6912#issuecomment-77683253) this could lead to problems by using ```require()``` of packages not defined in ```package.json```. That's why I've though that if there's a ```package.json``` file, ```require()``` would show an error message on the console when using it with a package not defined there, since it would lead to problems in the future if the dependencies change.

I know the behaviour of ```require()``` is frozen, but this could be a good improvement that don't break backwards compatibility and in fact it improves the packages quality, so I think it could be included...

**Comment by jasnell** [comment]
Given the transition of active development over to nodejs/node, that would be the right place to discuss this further. Closing this issue here.
