### ISSUE TITLE
Where is version?

### ISSUE THREAD

**Issue by r2d2Proton** [joyent/node#9357]

**Comment by r2d2Proton** [comment]
When I type in version why doesn't node report what version is running?

**Comment by KenanY** [comment]
@r2d2Proton `node --version`?

**Comment by r2d2Proton** [comment]
Does node have a version? If so, how do I tell?

**Comment by CGavrila** [comment]
@r2d2Proton: @KenanY described how you can find out above. If you have Node.js installed, then you can do `node --version` in the console.

**Comment by cjihrig** [comment]
From the command line use `node -v` or `node --version`. Inside of an application you can use `process.version` to get the node version, or `process.versions` to get the node version as well as the versions for the dependencies such as libuv, v8, etc.

**Comment by r2d2Proton** [comment]
Thank you guys for the help. I didn't think to try command line options. I found the .process.xxx from the Node.js Tools for Visual Studio (NTVS):  https://nodejstools.codeplex.com/

I just started using Node, and the tools, and actually working on debugging a problem. And the Node Tools for Visual Studio helped tremendously. Hopefully I can spread the word to others using a similar setup as mine.
