### ISSUE TITLE
What about help? How to get help?

### ISSUE THREAD

**Issue by r2d2Proton** [joyent/node#9358]
I hear how cool node is but type ? . . . what do you get?
type /help what do you get

Really, these are basic questions.

**Comment by cjihrig** [comment]
Use `node --help`

**Comment by r2d2Proton** [comment]
Thank you again.

I'm just catching up and commented on my other "issue". It would have been nice if these were readily discoverable from the online documentation. Do you know where they are? Looking at the Node.js site, there's nothing that jumps out at me as to where to find this.

Btw, and I am repeating myself just in case you didn't have a chance to read my other comment - there's a really nice Visual Studio Tool for Node.js that allows for editing, and debugging Node applications:  https://nodejstools.codeplex.com/

**Comment by cjihrig** [comment]
I don't think the command line arguments are documented. They probably should be.
