### ISSUE TITLE
Explicit String conversion on Symbol should not throw

### ISSUE THREAD

**Issue by dmail** [joyent/node#9363]
node v0.12.0
```javascript
String(Symbol('key')); // TypeError: Cannot convert a Symbol value to a string
```

firefox 36 or chrome 40
```javascript
String(Symbol('key')); // 'Symbol(key)'
```

See http://people.mozilla.org/~jorendorff/es6-draft.html#sec-symboldescriptivestring

**Comment by cjihrig** [comment]
This is an issue with the version of v8 that ships with 0.12. The bug appears to have been fixed in later versions, as this is not an issue in Chrome or io.js.

**Comment by mixonic** [comment]
@cjihrig wait, does this suggest that we should use node master or io.js instead of Node? Is this even fixed in node master?

**Comment by cjihrig** [comment]
This is not fixed in master, which is using the same version of V8. This particular bug has a very simple workaround. Instead of `String(Symbol('key'));`, just do `Symbol('key').toString();`.

**Comment by dmail** [comment]
Thanks for the reply, I use this workaround but it forces something like
```javascript
name = typeof name == 'symbol' ? name.toString() : String(name);
```
When I could write `name = String(name);`
