### ISSUE TITLE
Leap seconds

### ISSUE THREAD

**Issue by mhdawson** [joyent/node#9382]
In coordinated universal time (UTC) a day normally consists of 86400 seconds. However, every few years there is an extra second called a "leap second". The leap second is always added as the last second of the day, and always on December 31 or June 30. There will be a leap second on June 30 2015.

We've been asked about the possible effect on Node.  In many cases Node depends on either libuv or V8 for time related functions.

Issue opened in libuv repository to ask question: https://github.com/libuv/libuv/issues/261

Some hits searching on V8/leap second

https://esdiscuss.org/topic/leap-second-clarification
https://code.google.com/p/v8/issues/detail?id=1944
http://blog.synyx.de/2012/11/properly-calculating-time-differences-in-javascript/ - indicates ECMA-262 specification explicitly ignores leap seconds

This article discusses linux and leap seconds:
http://www.wired.com/2015/01/torvalds_leapsecond/

**Comment by srl295** [comment]
New FAQ added. https://github.com/joyent/node/wiki/FAQ#what-are-leap-seconds-what-impact-do-they-have-on-nodejs-applications

**Comment by mhdawson** [comment]
Going to close this now since FAQ has been added
