### ISSUE TITLE
Generator Functions Syntax Error with Node 0.12

### ISSUE THREAD

**Issue by asyncer** [joyent/node#9403]
I just download the latest NodeJS binary and running this simple code gives me error of "SyntaxError: Unexpected token *"

var main = function *(){
}
main()

Did I miss any configuration to enable Generator functions?

**Comment by skenqbx** [comment]
Node does not support ES6 by default, but `node --harmony-generators` should do the trick.

**Comment by cjihrig** [comment]
You can also use the `--harmony` flag.
