### ISSUE TITLE
Compilation errors regarding bson and kerberos modules during 'npm install mongoose'

### ISSUE THREAD

**Issue by theScratchLad** [joyent/node#9406]
Hi, I am trying to develop a mean stack web application on WIndows 7.

NodeJS is 0.12 v.

Every other module/package is working fine like express, bower, connect, ejs that I am using. But with mongoDB things, I need mongoose, which is failing with the following build errors.

gyp ERR! configure error 
gyp ERR! stack Error: spawn C:\Python27 ENOENT
gyp ERR! stack     at exports._errnoException (util.js:746:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1046:32)
gyp ERR! stack     at child_process.js:1137:20
gyp ERR! stack     at process._tickCallback (node.js:355:11)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "c:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd e:\git\gitTest\meanapp\node_modules\bson
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 

gyp ERR! configure error 
gyp ERR! stack Error: spawn C:\Python27 ENOENT
gyp ERR! stack     at exports._errnoException (util.js:746:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1046:32)
gyp ERR! stack     at child_process.js:1137:20
gyp ERR! stack     at process._tickCallback (node.js:355:11)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "c:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd e:\git\gitTest\meanapp\node_modules\kerberos
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 

Please help me resolve this error.

**Comment by cjihrig** [comment]
Do you have Python installed?

**Comment by theScratchLad** [comment]
Yup python is installed.

**Comment by misterdjules** [comment]
This seems to be an issue with your setup, not with Node.js itself. This issues tracker is used to track issues with Node.js' core, not general issues when using Node.js.

Could you please ask this question on the [Node.js Google group](https://groups.google.com/forum/#!forum/nodejs) and/or Stackoverflow and let us know if ever it turns out this is an issue with Node.js?

Thank you!
