### ISSUE TITLE
Exception thrown from http.js.

### ISSUE THREAD

**Issue by luosuiqian** [joyent/node#9407]
I am using the express 4 to build up a server.
When the homepage (There is 12 photos in the homepage) is visiting, the following exception is thrown.

http.js:1947
      socket.parser.pause();
                    
TypeError: Object # < HTTPParser > has no method 'pause'
    at Socket.socket.ondata (http.js:1947:21)
    at TCP.onread (net.js:510:27)

I am using Node 0.12.0
Why will the socket.parser have no method 'pause' ?

**Comment by JacksonTian** [comment]
Are you sure the version is 0.12.0?

**Comment by luosuiqian** [comment]
Yes, I am sure. I have used the command 'n ls' to check the version of Node. It is 0.12.0.

**Comment by cjihrig** [comment]
Can you please post a runnable piece of code that reproduces the problem with no external dependencies, such as Express.

**Comment by luosuiqian** [comment]
I am sorry that I can not reproduce this problem by myself.
In my website, it throws out this exception for more than 20 times per day.
But I have noticed that this problem only occurs when someone (exactly from the same IP address!) uses the 'get' method to visit the URL '/'.

My main code is in this page: https://github.com/luosuiqian/badminton/blob/master/tsba.js
I did not use the package 'socket' or 'socket.io' in my project and did not parse for 'socket'.
Will it be the reason to cause this problem?

**Comment by luosuiqian** [comment]
I have no ideas. And I don't know how to record the whole request so that I can post more details here. Can anyone give any suggestions?

**Comment by dayuoba** [comment]
did you use some module for logs?if not,'log4js' may be a nice module to write down all what you want!
```
sudo npm install log4js --save
```

**Comment by luosuiqian** [comment]
Ok. Thanks for the comments. I will learn and use the log module log4js in my website.

**Comment by jasnell** [comment]
Does not appear to be an issue with node. Please comment further if it does appear to be an issue and I'll reopen.
