### ISSUE TITLE
Does not listen to CTRL-C anymore when executing Java

### ISSUE THREAD

**Issue by binarykitchen** [joyent/node#9421]
I have a case here where I run an external Java process with `require('child_process').exec(...)` and when I want to abort node in the middle of that with CTRL-C, nothing happens.

Looks like the Java process is somehow taking over the node main process which shouldn't happen.

Not sure if this is a bug or something untested?

**Comment by OrangeDog** [comment]
Platform? Terminal?

**Comment by binarykitchen** [comment]
Ubuntu 14.10, using the latest Terminator as the terminal.

**Comment by jasnell** [comment]
@binarykitchen ... are you able to provide a test case that can reproduce the problem

**Comment by binarykitchen** [comment]
sorry no - i gave up a while ago
