### ISSUE TITLE
Buffer write documentation writeUIntLE does not exist

### ISSUE THREAD

**Issue by CraigLRussell** [joyent/node#9422]
The documentation at https://nodejs.org/api/buffer.html includes several functions for writing numbers to the buffer, but they don't exist. 
writeUIntBE
writeUIntLE
writeIntLE
writeIntBE

The functions that do exist have the number of bits encoded into the function name, e.g.
writeUInt8
writeUInt16
writeUInt32BE
writeUInt32LE
etc.

**Comment by CGavrila** [comment]
I think you might be using Node v0.10.x, while the documentation you point to is for v0.12.

**Comment by CraigLRussell** [comment]
You are so right.

Thanks,

Craig

> On Mar 17, 2015, at 4:02 AM, Cristian Gavrila <notifications@github.com> wrote:
> 
> I think you might be using Node v0.10.x, while the documentation you point to is for v0.12.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/joyent/node/issues/9422#issuecomment-82276907>.
> 

Craig L RussellArchitect, Oraclehttp://db.apache.org/jdo408 276-5638 mailto:Craig.Russell@oracle.comP.S. A good JDO? O, Gasp!
