### ISSUE TITLE
readableObjectMode in stream.Transform won't set readable to objectMode

### ISSUE THREAD

**Issue by stieizc** [joyent/node#9424]
After I run

      var x = new stream.Transform({readableObjectMode: true})

I can see that x._readableState.objectMode is false. Did I do it wrong?

**Comment by vkurchatkin** [comment]
which node version do you use?

**Comment by stieizc** [comment]
Yes……It turns out I was using node v0.10, and when I change to v0.12 just now it works. So thank you and sorry for being so careless.
