### ISSUE TITLE
Upgrade OpenSSL to 1.0.1m

### ISSUE THREAD

**Issue by misterdjules** [joyent/node#9433]
See the [announcement of the upcoming 1.0.1m release](https://mta.openssl.org/pipermail/openssl-announce/2015-March/000020.html).

**Comment by misterdjules** [comment]
@jasnell I assigned this to you, but feel free to reassign if you don't have time to take care of it. Thank you!

**Comment by flavorjones** [comment]
1.0.1m is now available:

> https://www.openssl.org/source/

Any thoughts around the timing of a release would be greatly appreciated! Thanks so much.

**Comment by misterdjules** [comment]
@flavorjones A new release will be done as soon as possible. We'll first do a node v0.10.38 release, and then a v0.12.1 release. We're aiming for both releases tomorrow, but it might slip to Monday.

**Comment by flavorjones** [comment]
Sweet, thank you for the update!

**Comment by misterdjules** [comment]
@flavorjones node v0.10.38 was released a few hours ago, and I'm currently doing the v0.12.1 release. It should be available tonight PDT. Thank you!

**Comment by misterdjules** [comment]
Fixed by 3b511a8ccdad299eae8ef4546fa51e87e48e42b5, 1aa510321ba73e8ad0e24294cbbf9eb1662186a0, 88744453120fa55b0f1634efc084a5e4c42b0927, 9fb6cf1ebb5f763ace710705fdc54213aaabcb1b, 8d10b8d6f7012d044a4d85f4c28c0f965dc70772, b5a37e560351497186ea219c1ff80ee69ccd723f and a43219bcd12552ac854164655ebe0c35607fbc2a.

**Comment by flavorjones** [comment]
Great, thanks again, everyone.
