### ISSUE TITLE
JSON.stringify transform objects into arrays when object has property "length" in node 0.12

### ISSUE THREAD

**Issue by norx85** [joyent/node#9437]
I'm using nodejs 0.12 on a linux server.

Calling JSON.stringify on an object with a property named "length" the JSON string represantation become an array with only values of the starting object.

For example, assuming that we have a variable named "rows" that is an array of documents returned from a query on mongodb, and a variable named count that is an integer representing the count of the query, if I create this object:
```javascript
    var resultObjFromDB = { 
        success: true, 
        rows : rows, 
        page: 0, 
        length: rows.length, 
        total: count 
    };
```
and then I call:
```javascript
var jsonstring = JSON.stringify(resultObjFromDB);
console.log(jsonstring);
```
the result is:
```javascript
[ "true", [{ "_id": "550a8611e288c0e2aeacfc24", "foo": "bar" }], 0, 1, 1 ]
```

if I rename "length" into "numrows" the stringify work as expected

**Comment by amir-s** [comment]
I don't see this problem on Mac.

**Comment by norx85** [comment]
The problem i'm getting is on a server on the openshift cloud.
the kernel is:
Linux 2.6.32-504.12.2.el6.x86_64 x86_64

**Comment by amir-s** [comment]
I also tested it against Ubuntu, I didn't see the problem there too. I used my DigitalOcean droplet.

```
amir@assp:~$ uname -r
3.2.0-24-virtual
amir@assp:~$ cat /proc/version
Linux version 3.2.0-24-virtual (buildd@vernadsky) (gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5) ) #37-Ubuntu SMP Wed Apr 25 12:51:49 UTC 2012
amir@assp:~$ node -v
v0.12.0
```

**Comment by cjihrig** [comment]
I'm not able to reproduce either. I think this is either some sort of application error, or an extremely unlikely V8 bug (Node doesn't provide the `JSON` object).
