### ISSUE TITLE
Issue in Buffer.toString()

### ISSUE THREAD

**Issue by ahmedshendy** [joyent/node#9438]
Dears'
I have issue in converting buffer of utf8 bytes to utf8 string
Please look at this example

var buffer = new Buffer([0xed, 0xa0, 0xbd, 0xed, 0xb8, 0x9a]);
console.log(buffer);
buffer = new Buffer(buffer.toString(), "utf-8");
console.log(buffer);
the out put is
<Buffer ed a0 bd ed b8 9a>
<Buffer f0 9f 98 9a>

**Comment by trevnorris** [comment]
Small test:
```javascript
var b = new Buffer([0xed, 0xa0, 0xbd, 0xed, 0xb8, 0x9a]);
assert.deepEqual(new Buffer(b.toString()), b);
```

**Comment by ahmedshendy** [comment]
the result is false

**Comment by trevnorris** [comment]
As it should be. Is just a simple test demonstrating the issue.

**Comment by ahmedshendy** [comment]
Dears'

Is there a solution for this issue

**Comment by trevnorris** [comment]
Doesn't seem there is a solution. From a conversation on IRC:
```
<Fishrock123> trevnorris: i.e. Iirc, higher-numbered unicode characters can be repesented as either \octal\octal or as \hex
<petka__>     decode encode on what is invalid utf8 in the first place doesn't return same value
<petka__>     depending on the decoding strategy
<petka__>     which is error, ignore or replacement character �
<petka__>     if replacement strategy was used then the result buffer is ["\xef", "\xbf", "\xbd", "\xef", "\xbf", "\xbd"]
<petka__>     also ["\xef", "\xbf", "\xbd"] is valid
<petka__>     open this is in different browsers http://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-test.txt, you see different amount of �
```

**Comment by petkaantonov** [comment]
Your buffer contains invalid utf-8 for which valid results include 0-6 replacement characters (chrome, firefox and bash give ������ i.e. 6 replacement characters, [my decoder](https://github.com/petkaantonov/unicode.js/blob/master/unicode.js) gives ��), an error or empty string.

**Comment by petkaantonov** [comment]
FWIW I think you have tried to encode the [U+1F61A: KISSING FACE WITH CLOSED EYES](http://www.charbase.com/1f61a-unicode-kissing-face-with-closed-eyes) but you are using [CESU encoding](http://en.wikipedia.org/wiki/CESU-8) instead of UTF-8.

The valid UTF-8 encoding for this character is: `[0xf0, 0x9f, 0x98, 0x9a]`
