### ISSUE TITLE
Upgrade OpenSSL to 1.0.1m

### ISSUE THREAD

**Issue by misterdjules** [joyent/node#9441]
See the [announcement of the upcoming 1.0.1m release](https://mta.openssl.org/pipermail/openssl-announce/2015-March/000020.html).

When the node v0.10.38 release that contains the OpenSSL upgrade is done, please merge into v0.12 and do the v0.12.1 release.

**Comment by misterdjules** [comment]
@jasnell As discussed this morning, the plan for now is to first upgrade OpenSSL in v0.10, then to merge  v0.10 into v0.12.1 branched off of v0.12.0, and finally to merge v0.12.1-release into v0.12.

@joyent/node-coreteam Please let us know if this is correct.

**Comment by jasnell** [comment]
Sounds good.

**Comment by jasnell** [comment]
@joyent/node-coreteam ...

For review:
Patch against: v0.10.37-release -  https://github.com/jasnell/node/commit/8a917ca403e8a9e9c0b167018b17b628217a65a2 (my branch: https://github.com/jasnell/node/tree/v0.10.37-opensslm)

Patch against: v0.12.0-release - https://github.com/jasnell/node/commit/5cc430fb94392bbb50da8069900bb2f1b1c4ba25 (my branch: https://github.com/jasnell/node/tree/v0.12.0-opensslm)

The patch followed the process documented in the io.js openssl-m update (https://github.com/iojs/io.js/pull/1206) by @shigeki

Builds on Mac OSx 10.10 and Ubuntu 14.10. Tests pass. Needs additional review and verification.

**Comment by shigeki** [comment]
I've just reviewed the v0.10.37-opensslm branch and verified there is no difference from my patch. It can work on Node-v0.10.x. LGTM.

**Comment by jasnell** [comment]
@shigeki ... I appreciate your work. You made it significantly easier for
me :+1:

**Comment by misterdjules** [comment]
@shigeki @jasnell Looking at the changes, I think it would be better to make changes to `deps/openssl/openssl.gyp` instead of changes to the OpenSSL source itself to work around the symlinked headers. That makes us have to maintain one less floating patch.

I would also like to keep at least these commits:
* https://github.com/shigeki/io.js/commit/a3e0da2e0c4ffcb7272a8a3f41d8772b0969e706.
* https://github.com/shigeki/io.js/commit/ac89f8ac5b036b857afb27d9d0e7bc78a8a732cd.

as separate commits so that we can track them separately from the rest of the changes.

How does that sound?

**Comment by piscisaureus** [comment]
The problem with symlinked headers is that they're a pain on windows.

**Comment by jasnell** [comment]
See alternate PR: https://github.com/joyent/node/pull/9451

**Comment by shigeki** [comment]
@misterdjules It would be possible to move all headers to the directory out of  OpenSSL source such as  `deps/openssl/config/openssl/include/` and change `include_dirs` in openssl.gyp. But I wonder if there are some addons to use openssl library which refers `deps/openssl/openssl/include` in their gyp and they are all affected.

**Comment by shigeki** [comment]
On openssl git repository,  the include directory is empty and written in `.gitignore`. `Makefile` generates symlinks by using util/mklink.pl. But the distributed tar.gz file includes symlinks and it causes issues on Windows as pointed out by @piscisaureus . So we need to modify the original source so as to make  the include directory  be empty even when we change to use gyp.

**Comment by misterdjules** [comment]
@piscisaureus @shigeki Thank you for the clarification, I didn't realize that [the symlinks shim has been present for quite a while now](https://github.com/joyent/node/commit/c4b9be7c5a97b9cac99cd599dbd995da556a5a17).

**Comment by misterdjules** [comment]
Fixed by c6e8a2c920e0cecebfb8fe62d5bcfc19edb850ae, 10717f659b1d8db86cc7fce6f6a64e4c0ba22062, 2b21c45f75043f8e5728650e24a4e972ade18cf1, 63377ec3c3ed52d7dec04515854a760787b9893f, 15cdeb7d990d278f569ba0733bf6feec97916cc6,  1fc3fdf8925d4bfd2aaead48885a5f0b77607f77 and 4b69c72b8b1725fe98539da1274bc85d3661d3a5.
